#!/bin/sh

URL="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
arch=$(uname -m)
currentuser=$(who | awk '{print $1}')

cd /opt/am
case "$1" in
  ''|'-h'|'help') echo '
 ------------------------------------------------------------------------
                    _____                    _____                                                                           
                   /\    \                  /\    \         
                  /::\    \                /::\____\        
                 /::::\    \              /::::|   |        
                /::::::\    \            /:::::|   |        
               /:::/\:::\    \          /::::::|   |        
              /:::/__\:::\    \        /:::/|::|   |        
             /::::\   \:::\    \      /:::/ |::|   |        
            /::::::\   \:::\    \    /:::/  |::|___|______  
           /:::/\:::\   \:::\    \  /:::/   |::::::::\    \ 
          /:::/  \:::\   \:::\____\/:::/    |:::::::::\____\
          \::/    \:::\  /:::/    /\::/    / ~~~~~/:::/    /
           \/____/ \:::\/:::/    /  \/____/      /:::/    / 
                    \::::::/    /               /:::/    /  
                     \::::/    /               /:::/    /   
                     /:::/    /               /:::/    /    
                    /:::/    /               /:::/    /     
                   /:::/    /               /:::/    /      
                  /:::/    /               /:::/    /       
                  \::/    /                \::/    /        
                   \/____/                  \/____/         


 ▄▀█ █▀█ █▀█ █░░ █ █▀▀ ▄▀█ ▀█▀ █ █▀█ █▄░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▀ █▀█
 █▀█ █▀▀ █▀▀ █▄▄ █ █▄▄ █▀█ ░█░ █ █▄█ █░▀█   █░▀░█ █▀█ █░▀█ █▀█ █▄█ ██▄ █▀▄

                             by Ivan Alex HC

 ------------------------------------------------------------------------

  >>  Enjoy your applications without thinking about anything else   <<   
  
 ------------------------------------------------------------------------
      
  Usage:		am [option] [argument]
  
  where option include:
  
  -i, install 	Install a program. This will be taken directly from the
  		repository of the developer (always the latest version):
  		- the installer is stored in /opt/am/.cache;
  		- the command is linked into a $PATH or launched from a 
		custom script (created in a $PATH) which automates updates
		at program startup;
		- the program is stored in /opt/<program> with a script to
	    	remove this and all the files listed above.
		The icon and the launcher are optional for no-ui programs.
  		"AM" uses both AppImages and other standalone programs.
  		
  -r, remove	Removes the program and all the other files listed above
  		using the instructions in /opt/<program>/remove.
  		Confirmation is required (Y or N, default is N).
  		
  -t, template	This option allows you to generate a custom script to
  		manipulate on your PC in your $HOME directory. Please,
  		consider submitting your app to the AM application manager,
  		at https://github.com/ivan-hc/AM-application-manager
  		
  -----------------------------------------------------------------------

  Usage:		am [option] [keywords]
  
  where option include:  

  -q, query	Use one or more keywords to search for in the list of
  		available applications.

  -----------------------------------------------------------------------

  Usage:		am [option]
  
  where option include:
  
  -h, help	Prints this message.
  
  -c, clean	Removes all the unnecessary files.

  -f, files	Shows the installed programs managed by "AM".
  
  -l, list	Shows the list of apps available in the repository.

  -s, sync	Updates "AM" to a more recent version.

  -----------------------------------------------------------------------
   
  SITE: https://github.com/ivan-hc/AM-application-manager
  
  ' ;;
  '-c'|'clean') echo ""; rm -R -f /opt/am/.cache/*;
	echo "All unnecessary files are removed, exiting."; echo "" ;;
  '-f'|'files') echo ""; echo $(echo "YOU HAVE INSTALLED "; cd /opt && find -name 'remove' -printf "%h\n" | sort -u | wc -l;
  	echo " STANDALONE PROGRAMS MANAGED BY THE 'AM' COMMAND:"); echo "";
  	cd /opt && find -name 'remove' -printf "%h\n" | sort -u | xargs -n 1 basename; echo "" ;;
  '-i'|'install')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do cd /opt/am/.cache; mkdir tmp; cd tmp; wget $URL/programs/$arch/$2; cd ..; mv ./tmp/$2 ./$2; rmdir ./tmp;
	chmod a+x /opt/am/.cache/$2 && exec /opt/am/.cache/$2; done
	esac
	shift
	done;;
  '-l'|'list') echo ""; echo "  LIST OF APPLICATIONS AVAILABLE IN THE 'AM' REPOSITORY:";
  	rm -R -f /opt/am/.cache/$arch-apps; cd /opt/am/.cache;
	am -q ◆ | nawk -vORS='\n' 1 ;
  	echo $(echo "ALL:"; grep -e "$" -c /opt/am/.cache/$arch-apps);
  	echo $(echo "INSTALLED:"; cd /opt && find -name 'remove' -printf "%h\n" | sort -u | wc -l); echo "";;
  '-q'|'query')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do rm -R -f /opt/am/.cache/$arch-apps; cd /opt/am/.cache;
	wget -q $URL/programs/$arch-apps;
	echo "" && grep -i -E $2 /opt/am/.cache/$arch-apps | nawk -vORS='\n\n' 1 ; echo ""; done
	esac
	shift
	done;;
  '-r'|'remove')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do read -p "Do you wish to REMOVE this program (y,N)?" yn
		case $yn in
		[Yy]* ) exec /opt/$2/remove; echo ""; echo "Application removed!"; echo ""; break;;
		[Nn]*|* ) echo "Aborted"; exit;; esac done;;
	esac
	shift
	done;;
  '-s'|'sync') echo ""; echo " Updating the Application Manager, please wait..."; sleep 1;
  	cd /opt/am/.cache; wget -q $URL/APP-MANAGER && chmod a+x ./APP-MANAGER; cd ..;
  	mv /opt/am/.cache/APP-MANAGER /opt/am; chown -R $currentuser /opt/am; echo "...done!";;
  '-t'|'template')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2
	do cd /home/$currentuser/
	echo ""
	echo " WHAT KIND OF PROGRAM DO YOU WANT TO WRITE A SCRIPT FOR?"
	echo ""
	echo ""
	echo " 1) I have an AppImage that uses Appimageupdate"
	echo ""
	echo " 2) I have an AppImage that uses a separated zsync file"
	echo ""
	echo " 3) I have a package or a non-updatable AppImage from a repository"
	echo ""
	echo " 4) I have a package or a non-updatable AppImage from a main site"
	echo ""
	echo ""
	read -r -p " Please only choose one option between 1, 2, 3 and 4 : " response
	case "$response" in
    	1) mkdir $2-script-for-AM && cd $2-script-for-AM; wget $URL/templates/AM-SAMPLE-for-appimageupdate;;
    	2) mkdir $2-script-for-AM && cd $2-script-for-AM; wget $URL/templates/AM-SAMPLE-for-zsync;;
    	3) mkdir $2-script-for-AM && cd $2-script-for-AM; wget $URL/templates/AM-SAMPLE-from-a-repository;;
    	4) mkdir $2-script-for-AM && cd $2-script-for-AM; wget $URL/templates/AM-SAMPLE-from-a-main-site;;
    	*) echo ""; echo " No valid argument was chosen: process aborted! "; echo ""; exit;;
	esac
	mv AM-SAMPLE* $2
	sed -i s/SAMPLE/$2/g $2
	done
	esac
	shift
	done;;
  *) exec /opt/am/APP-MANAGER ;;
esac
