#!/bin/sh

URL="https://raw.githubusercontent.com/ivan-hc/EYA-App-Manager/main"

cd /opt/eya
case "$1" in
  ''|'-h'|'help') echo '
 ------------------------------------------------------------------------
            _____                _____                    _____          
           /\    \              |\    \                  /\    \         
          /::\    \             |:\____\                /::\    \        
         /::::\    \            |::|   |               /::::\    \       
        /::::::\    \           |::|   |              /::::::\    \      
       /:::/\:::\    \          |::|   |             /:::/\:::\    \     
      /:::/__\:::\    \         |::|   |            /:::/__\:::\    \    
     /::::\   \:::\    \        |::|   |           /::::\   \:::\    \   
    /::::::\   \:::\    \       |::|___|______    /::::::\   \:::\    \  
   /:::/\:::\   \:::\    \      /::::::::\    \  /:::/\:::\   \:::\    \ 
  /:::/__\:::\   \:::\____\    /::::::::::\____\/:::/  \:::\   \:::\____\
  \:::\   \:::\   \::/    /   /:::/~~~~/~~      \::/    \:::\  /:::/    /
   \:::\   \:::\   \/____/   /:::/    /          \/____/ \:::\/:::/    / 
    \:::\   \:::\    \      /:::/    /                    \::::::/    /  
     \:::\   \:::\____\    /:::/    /                      \::::/    /   
      \:::\   \::/    /    \::/    /                       /:::/    /    
       \:::\   \/____/      \/____/                       /:::/    /     
        \:::\    \                                       /:::/    /      
         \:::\____\                                     /:::/    /       
          \::/    /                                     \::/    /        
           \/____/                                       \/____/         
                                                                         
     >>  Enjoy Your Apps... without thinking about anything else   <<     

 ------------------------------------------------------------------------

  Usage:		eya [option]
  
  where option include:
  
  -h, help	Print this message.

  -f, files	Show the programs installed.

  -s, sync	Updates EYA to a more recent version.

  -----------------------------------------------------------------------
      
  Usage:		eya [option] [argument]
  
  where option include:
  
  -a, about	Show basic info on each application installed.
  		  
  -i, install 	Install a program. This will be taken directly from the
  		repository of the developer (always the latest version):
  		- the installer is stored in /opt/eya/programs;
  		- the program is stored in /opt/<program>;
  		- the icon is pushed in /usr/share/pixmaps;
  		- the launcher is created /usr/share/applications;
  		- the command is linked to /usr/bin;
  		- the uninstaller is created in /opt/eya/remove;
  		- other files can be stored in /opt/<program>.
  		The icon and launcher are not needed for no-ui programs.
  		EYA uses both AppImages and other standalone programs.
  		
  -r, remove	Removes the program and all the other files listed above
  		using the instructions in /opt/eya/remove/<program>.
  		Confirmation is required (Y or N, default is N).		 

  -----------------------------------------------------------------------
   
  SITE: https://github.com/ivan-hc/EYA-App-Manager
  
  ' ;;
  '-a'|'about')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do cat /opt/$2/about; echo ""; done
	esac
	shift
	done;;
  '-f'|'files') echo ""; echo $(echo "  Applications installed on the system:"; ls /opt/eya/remove/ | wc -l); echo ""; ls /opt/eya/remove; echo "" ;;
  '-i'|'install')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do cd /opt/eya/programs; mkdir tmp; cd tmp; wget $URL/programs/$2; cd ..; mv ./tmp/$2 ./$2; rmdir ./tmp;
	chmod a+x /opt/eya/programs/$2 && exec /opt/eya/programs/$2; done
	esac
	shift
	done;;
  '-r'|'remove')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do read -p "Do you wish to REMOVE this program (y,N)?" yn
		case $yn in
		[Yy]* ) exec /opt/eya/remove/$2; echo ""; echo "Application removed!"; echo ""; break;;
		[Nn]*|* ) echo "Aborted"; exit;; esac done;;
	esac
	shift
	done;;
  '-s'|'sync') echo ""; echo " Updating EYA, please wait..."; sleep 1;
  	cd /opt/eya; mkdir tmp; cd ./tmp; wget -q $URL/eya && chmod a+x ./eya; cd ..;
  	mv /opt/eya/tmp/eya /opt/eya; rmdir /opt/eya/tmp; echo "...done!";;
  *) exec /opt/eya/eya ;;
esac
