#!/bin/sh

APP=appman

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP /etc/bash_completion.d/appman-completion.sh" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
wget -q https://raw.githubusercontent.com/ivan-hc/AppMan/main/appman-portable -O appman && chmod a+x ./appman

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
appman -s' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo '

       ___      .______   .______   .___  ___.      ___      .__   __. 
      /   \     |   _  \  |   _  \  |   \/   |     /   \     |  \ |  | 
     /  ^  \    |  |_)  | |  |_)  | |  \  /  |    /  ^  \    |   \|  | 
    /  /_\  \   |   ___/  |   ___/  |  |\/|  |   /  /_\  \   |  . `  | 
   /  _____  \  |  |      |  |      |  |  |  |  /  _____  \  |  |\   | 
  /__/     \__\ | _|      | _|      |__|  |__| /__/     \__\ |__| \__| 


   >>  App Manager for GNU/Linux that uses and creates AppImages  <<

   SITE: https://github.com/ivan-hc/AppMan
  
 Run "appman -h" to start, "appman -l" to get the list of applications
';
