#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=firefox-esr
SITE="https://www.firefox.com" SITE2="ivan-hc/Firefox-appimage"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP
read -r -p "
 Choose a package format:

 1. Official portable package, with automatic updates (~300 MB).

    Source: https://www.firefox.com

 2. AppImage created from the official package mentioned above (~100 MB).

    Source: https://github.com/ivan-hc/Firefox-appimage

 Which version you choose (type a number and press ENTER)?" response
RELEASE=""

if echo "$response" | grep -q "^1"; then
	RELEASE="PORTABLE"
	LANGUAGE=$(curl -Ls https://raw.githubusercontent.com/linuxmint/mdm/master/config/locale.alias | grep -i "$LANG" | grep -o '^\S*')
	CODE=$(curl -Ls https://releases.mozilla.org/pub/firefox/releases/latest/README.txt | cut -d ':' -f2 | grep -i "$LANGUAGE" | cut -d '=' -f2)
	wget "https://download.mozilla.org/?product=$APP-latest&os=linux64-aarch64&lang=$CODE" --trust-server-names || exit 1
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	cd ..
	mv ./tmp/firefox/* ./
	rm -R ./tmp || exit 1
elif echo "$response" | grep -q "^2"; then
	RELEASE="APPIMAGE"
	version=$(curl -Ls https://api.github.com/repos/ivan-hc/Firefox-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|x86_64\|amd64\|armv7l" | grep -i "esr" | head -1)
	wget "$version" || exit 1
	cd ..
	mv ./tmp/*mage ./"$APP"
	rm -R -f ./tmp || exit 1
	echo "$version" > ./version
	chmod a+x ./"$APP" || exit 1
fi
[ -z "$RELEASE" ] && exit 0

if [ "$RELEASE" = APPIMAGE ]; then
	# LINK TO PATH
	ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

	# SCRIPT TO UPDATE THE PROGRAM (APPIMAGE ONLY)
	cat <<-'HEREDOC' >> ./AM-updater
	#!/bin/sh
	set -u
	APP=firefox-esr
	SITE="ivan-hc/Firefox-appimage"
	version0=$(cat "/opt/$APP/version")
	version=$(curl -Ls https://api.github.com/repos/ivan-hc/Firefox-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|x86_64\|amd64\|armv7l" | grep -i "esr" | head -1)
	[ -n "$version" ] || { echo "Error getting link"; exit 1; }
	if command -v appimageupdatetool >/dev/null 2>&1; then
	   cd "/opt/$APP" || exit 1
	   appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
	fi
	if [ "$version" != "$version0" ]; then
	   mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	   notify-send "A new version of $APP is available, please wait"
	   wget "$version" || exit 1
	   # Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	   cd ..
	   mv --backup=t ./tmp/*mage ./"$APP"
	   chmod a+x ./"$APP" || exit 1
	   echo "$version" > ./version
	   rm -R -f ./*zs-old ./*.part ./tmp ./*~
	   notify-send "$APP is updated!"
	else
	   echo "Update not needed!"
	fi
	HEREDOC
	sed -i 's/   /	/g' ./AM-updater
	chmod a+x ./AM-updater || exit 1

	# LAUNCHER & ICON
	./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
	./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
	COUNT=0
	while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
		if [ -L ./"$APP".desktop ]; then
			LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
		fi
		if [ -L ./DirIcon ]; then
			LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
		fi
		[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
		COUNT=$((COUNT + 1))
	done
	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
	mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
	rm -R -f ./squashfs-root
else
	# LINK TO PATH
	ln -s "/opt/$APP/firefox" "/usr/local/bin/$APP"

	# LAUNCHER
	rm -f /usr/local/share/applications/"$APP"-AM.desktop
	cat <<-HEREDOC >> /usr/local/share/applications/"$APP"-AM.desktop
	[Desktop Entry]
	Name=Firefox ESR
	Comment=Web Browser
	Exec=/opt/$APP/firefox %u
	Terminal=false
	Type=Application
	Icon=/opt/$APP/browser/chrome/icons/default/default128.png
	Categories=Network;WebBrowser;
	MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
	StartupNotify=true
	Actions=Private;

	[Desktop Action Private]
	Exec=/opt/$APP/firefox --private-window %u
	Name=Open in private mode
	HEREDOC
fi