#!/bin/sh

APP=github2am

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
wget https://raw.githubusercontent.com/ivan-hc/github2AM/main/github2am
chmod a+x /opt/$APP/$APP

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
mkdir /opt/'$APP'/tmp
cd /opt/'$APP'/tmp
wget https://raw.githubusercontent.com/ivan-hc/github2AM/main/github2am
cd ..
mv ./tmp/'$APP' ./'$APP'
chmod a+x /opt/'$APP'/'$APP'
rmdir ./tmp' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 $APP is provided by https://github.com/ivan-hc
  
";
