#!/bin/sh

APP=supertuxkart

mkdir /opt/$APP
cd /opt/$APP

echo "#!/bin/sh
rm -R -f /opt/supertuxkart /usr/share/applications/supertuxkart.desktop /usr/share/pixmaps/supertuxkart.svg /usr/games/supertuxkart" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/supertuxkart/stk-code/releases/latest -O - | egrep '/.*/.*/.*linux-arm64.tar.xz' -o)

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

tar xf ./*.tar.xz
cd ..
mv ./tmp/SuperTuxKart-*-linux-64bit/* ./
rm -R ./tmp

ln -s /opt/$APP/run_game.sh /usr/games/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)
url=https://github.com/supertuxkart/stk-code/releases/latest' >> /opt/$APP/AM-updater

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
echo 'else' >> /opt/$APP/AM-updater
echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater

########################################################################################

function1='$(wget https://github.com/supertuxkart/stk-code/releases/latest -O -'
function2="egrep '/.*/.*/.*linux-arm64.tar.xz' -o)"
function3='$(ls /opt/$APP/tmp)'

echo "  wget https://github.com/$function1 | $function2
  version=$function3" >> /opt/$APP/AM-updater

########################################################################################

echo '  cd ..
  if test -f ./tmp/*tar.xz; then rm ./version
  fi
  echo "$version" >> ./version' >> /opt/$APP/AM-updater
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER

rm -R -f /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=SuperTuxKart
Icon=supertuxkart
GenericName=A kart racing game
GenericName[da]=Et kart racerspil
GenericName[de]=Ein Kart-Rennspiel
GenericName[fr]=Un jeu de karting
GenericName[gl]=Xogo de carreiras con karts
GenericName[pl]=Wyścigi gokartów
GenericName[ro]=Un joc de curse cu carturi
Exec=supertuxkart
Terminal=false
StartupNotify=false
Type=Application
Categories=Game;ArcadeGame;
Keywords=tux;game;race;" >> /usr/share/applications/$APP.desktop

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg
mv ./$APP.svg /usr/share/pixmaps/

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "";
echo "   SuperTuxKart has been installed!";
echo "";
