#!/bin/sh

APP=ventoy

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD VENTOY
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/ventoy/Ventoy/releases/latest -O - | egrep '/.*/.*/.*linux.tar.gz' -o)
tar xf ./*.tar.gz
cd ..
mv ./tmp/ventoy-*/* ./
rm -R -f ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh
cd /opt/$APP;
sudo ./VentoyGUI.aarch64' >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=Ventoy
Comment=Open source tool to create bootable USB drive for ISO/WIM/IMG/VHD(x)/EFI files. 
Exec=/opt/$APP/VentoyGUI.aarch64
Icon=/opt/$APP/$APP.svg
Type=Application
Categories=System;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg;

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

	Ventoy is provided by https://www.ventoy.net
	
"
