#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.6
set -u
APP=zalo
SITE="VN-Linux-Family/zalo-for-linux"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# CHOOSE A VERSION, DOWNLOAD AND PREPARE THE APP, $version is also used for updates
read -r -p "
 Choose which variant of Zalo AppImage to use:

 1. With ZaDark (helps you experience Zalo more privately and more personalized)

    Filename: Zalo-<ver>+ZaDark-<zadark_ver>-<commit_hash>-aarch64.AppImage

 2. Original variant

	Filename: Zalo-<ver>-Original-<commit_hash>-aarch64.AppImage

 Which variant you choose (type a number and press ENTER)?" response

case "$response" in
	1) rm -f /opt/"$APP"/version
	UPDATER=1
	version=$(curl -Ls https://api.github.com/repos/VN-Linux-Family/zalo-for-linux/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*download.*ZaDark.*mage$" | grep -i "aarch64\|arm64" | head -1)
	wget "$version"
	echo "$version" >> /opt/$APP/version;;
	2) rm -f /opt/"$APP"/version
	version=$(curl -Ls https://api.github.com/repos/VN-Linux-Family/zalo-for-linux/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*download.*mage$" | grep -i "aarch64\|arm64" | grep -vi "%2BZaDark" | head -1)
	UPDATER=2
	wget "$version"
	echo "$version" >> /opt/$APP/version;;
	*) /opt/"$APP"/remove && exit;;
esac

# Keep this space in sync with other installation scripts
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
# Keep this space in sync with other installation scripts
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=zalo
SITE="VN-Linux-Family/zalo-for-linux"
version0=$(cat "/opt/$APP/version")
version=$($LINK)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv --backup=t ./tmp/*mage ./"$APP"
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
if [ "$UPDATER" = "1" ]; then
    sed -i 's#$LINK#curl -Ls https://api.github.com/repos/VN-Linux-Family/zalo-for-linux/releases/latest | sed '"'"'s/[()",{} ]/\\n/g'"'"' | grep -oi "https.*download.*ZaDark.*mage$" | grep -i "aarch64\\|arm64" | head -1#g' /opt/"$APP"/AM-updater
elif [ "$UPDATER" = "2" ]; then
    sed -i 's#$LINK#curl -Ls https://api.github.com/repos/VN-Linux-Family/zalo-for-linux/releases/latest | sed '"'"'s/[()",{} ]/\\n/g'"'"' | grep -oi "https.*download.*mage$" | grep -i "aarch64\\|arm64" | grep -vi "%2BZaDark" | head -1#g' /opt/"$APP"/AM-updater
fi
chmod a+x ./AM-updater || exit 1

# LAUNCHER & ICON
./"$APP" --appimage-extract *.desktop 1>/dev/null
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	for f in squashfs-root/*.desktop; do
		FILE="$f"
		if [ -L "$f" ]; then
			LINKPATH="$(readlink "$f" | sed 's|^\./||' 2>/dev/null)"
			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null
			FILE="./squashfs-root/$LINKPATH"
		fi
		if grep -qi '^NoDisplay=true$' "$FILE" 2>/dev/null; then mv "$FILE" ./"$APP"-handler-AM.desktop && printf '\n%s' "rm -f /usr/local/share/applications/$APP-handler-AM.desktop" >> ./remove
		else [ ! -f ./"$APP"-AM.desktop ] && mv "$FILE" ./"$APP"-AM.desktop || mv "$FILE" ./"$APP"-"$COUNT"-AM.desktop && printf '\n%s' "rm -f /usr/local/share/applications/$APP-$COUNT-AM.desktop" >> ./remove
		fi
	done
	if [ -L ./DirIcon ]; then
		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./"$APP"-AM.desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
for f in ./*-AM.desktop; do [ "$f" != ./"$APP"-AM.desktop ] && [ -f "$f" ] && [ "$(sort ./"$APP"-AM.desktop)" = "$(sort "$f")" ] && rm -f "$f"; done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" ./*-AM.desktop
mv ./*-AM.desktop /usr/local/share/applications/ && mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root
