#!/bin/sh

# Creating a dedicated folder for wine-staging
mkdir /opt/wine-staging
cd /opt/wine-staging
mkdir tmp
cd ./tmp

# Downloading the AppImage
wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-staging
cd ..
mv ./tmp/wine*AppImage ./wine-staging
chmod a+x ./wine-staging

ln -s /opt/wine-staging/wine-staging /usr/bin/wine
ln -s /opt/wine-staging/wine-staging /usr/bin/wineserver

# Creating an updater script
echo "#!/bin/sh
cd /opt/wine-staging
appimageupdate -O wine-staging
rm *zs-old" >> /opt/wine-staging/wine-update

# Creating a launcher for a process that starts on login to check for updates
mkdir /home/$USER/.config/autostart
echo "[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=wine-staging-update
Comment=Automatic update for WINE
Exec=/opt/wine-staging/wine-update
OnlyShowIn=XFCE;
RunHook=0
StartupNotify=true
Terminal=false
Hidden=false" >> /home/$USER/.config/autostart/wine-staging-update.desktop

# Creating a script that removes all the files listed above
echo '#!/bin/sh
rm -R /usr/bin/wine /usr/bin/wineserver /usr/wine-staging/wine-update /home/$USER/.config/autostart/wine-staging-update.desktop /opt/wine-staging /opt/want/remove/wine-staging /opt/want/programs/wine-staging' >> /opt/want/remove/wine-staging
chmod a+x /opt/want/remove/wine-staging

# Message
# Message
echo ""
echo " Wine staging has been installed!"
echo ""
echo ' Please run the command "sudo chown -R $USER /opt/wine-staging" to made it updatable'
echo ""

