#!/bin/sh

# Creating a dedicated folder for wine-staging
mkdir /opt/wine-staging
cd /opt/wine-staging
mkdir tmp
cd ./tmp

# Downloading the AppImage
wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-staging
cd ..
mv ./tmp/wine*AppImage ./wine-staging
chmod a+x ./wine-staging

ln -s /opt/wine-staging/wine-staging /usr/bin/wine
ln -s /opt/wine-staging/wine-staging /usr/bin/wineserver

# Creating an updater script
echo "#!/bin/sh
cd /opt/wine-staging
appimageupdate -O wine-staging
rm *zs-old" >> /opt/wine-staging/wine-update

# Creating a script that removes all the files listed above
echo '#!/bin/sh
rm -R /usr/bin/wine /usr/bin/wineserver /usr/wine-staging/wine-update /home/$USER/.config/autostart/wine-staging-update.desktop /opt/wine-staging /opt/want/remove/wine-staging /opt/want/programs/wine-staging' >> /opt/want/remove/wine-staging
chmod a+x /opt/want/remove/wine-staging

# Message
echo ""
echo " Wine staging has been installed!"
echo ""
echo '  Please run the command "sudo chown -R $USER /opt/wine-staging" to'
echo "  made it updatable, and add /opt/wine-staging/wine-update among the"
echo "  startup processes or session login."

