#!/bin/sh

cd /opt/want
case "$1" in
  '-i'|'install')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do cd /opt/want/install && wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$2-installer &&
	chmod a+x /opt/want/install/$2-installer && exec /opt/want/install/$2-installer; done
	esac
	shift
	done;;
  '-r'|'remove')
	while [ -n "$1" ]
	do
	case $2 in
	*) for var in $2;
	do read -p "Do you wish to REMOVE this program (y,N)?" yn
		case $yn in
		[Yy]* ) exec /opt/want/remove/$2-remove; echo ""; echo "Application removed!"; echo ""; break;;
		[Nn]*|* ) echo "Aborted"; exit;; esac done;;
	esac
	shift
	done;;
  *) exec /opt/want/want ;;
esac
