name: "Add portable apps (NOT AppImages)"
description: "Suggest applications for this database that are NOT AppImages"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        To help us make adding applications quicker and easier, please follow the syntax below (**NOTE that if point 2 is a github repository, you can remove points 3 and 4**, and **if the program is a CLI you can remove points 5 and 6**). Also consider learning how to create, test and finally add scripts yourself. Follow the guide https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/template.md

  - type: input
    id: app_name
    attributes:
      label: "1. Name"
      description: "Lowercase, this will be the command to use"
      placeholder: "e.g., my-awesome-app"
    validations:
      required: true

  - type: input
    id: main_site
    attributes:
      label: "2. Main site, repository or reference web page"
      description: "URL, DO NOT use direct download link"
      placeholder: "e.g., https://github.com/user/repo"
    validations:
      required: true

  - type: input
    id: download_page
    attributes:
      label: "3. Download page"
      description: "Optional if point 2 is a GitHub repository"
      placeholder: "e.g., https://example.com/downloads"
    validations:
      required: false

  - type: textarea
    id: app_description
    attributes:
      label: "4. Description of the application"
      description: "Optional if point 2 is a GitHub repository"
      placeholder: "A brief description of what the application does."
    validations:
      required: false

  - type: input
    id: icon_url
    attributes:
      label: "5. URL to the application icon"
      description: "Optional if the program is a CLI"
      placeholder: "e.g., https://example.com/icon.png"
    validations:
      required: false

  - type: textarea
    id: desktop_file
    attributes:
      label: "6. The .desktop* file"
      description: "Optional if the program is a CLI. Choose whether to add a URL, to paste the content of the file, to drag a text file into your comment, or to provide only the following 3 desktop entries: `Name=`, `Exec=` and `Categories=`"
      placeholder: "Name=My App\nExec=my-app\nCategories=Utility;"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        We encourage contributors to follow the [GNU Kind Communications Guidelines (GNU KCG)](https://gnu.support/philosophy/GNU-Kind-Communications-Guidelines.html)
