name: "Bug report (generic)"
description: "Create a report to help us improve"
title: ""
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Premise
        By opening this issue, I certify:
        - that I have updated "AM"/"AppMan" to the latest version
        - that I have read the README https://github.com/ivan-hc/AM/blob/main/README.md
        - that I have read the documentation https://github.com/ivan-hc/AM/tree/main/docs
        - that I have searched for an option or flag in `-h` that covers my use case
        - that I have searched for an issue that covers my use case https://github.com/ivan-hc/AM/issues

        We encourage contributors to follow the [GNU Kind Communications Guidelines (GNU KCG)](https://gnu.support/philosophy/GNU-Kind-Communications-Guidelines.html)

  - type: dropdown
    id: tool_selection
    attributes:
      label: "Are you using \"AM\" or \"AppMan\"?"
      options:
        - "AM"
        - "AppMan"
    validations:
      required: true

  - type: input
    id: distribution
    attributes:
      label: "What GNU/Linux distribution are you using it on?"
      placeholder: "e.g., Ubuntu 24.04, Fedora 40, Arch Linux"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Please, describe the bug"
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "What are the steps/commands to perform?"
      placeholder: "1. Run command...\n2. See error..."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "What is the expected behavior?"
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: true
