name: "Feature request"
description: "Suggest an idea for this project"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Premise
        By opening this issue, I certify:
        - that I have updated "AM"/"AppMan" to the latest version
        - that I have read the README https://github.com/ivan-hc/AM/blob/main/README.md
        - that I have read the documentation https://github.com/ivan-hc/AM/tree/main/docs
        - that I have searched for an option or flag in `-h` that covers my use case
        - that I have searched for an issue that covers my use case https://github.com/ivan-hc/AM/issues

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: related_problem
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      placeholder: "Write here"
    validations:
      required: true

  - type: textarea
    id: desired_solution
    attributes:
      label: "Describe the solution you'd like"
      placeholder: "Write here"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      placeholder: "Write here"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        We encourage contributors to follow the [GNU Kind Communications Guidelines (GNU KCG)](https://gnu.support/philosophy/GNU-Kind-Communications-Guidelines.html)
