name: "Questions and answers (free speech)"
description: "Are you insecure? Ask whatever you want."
labels: ["question"]
assignees: []
body:
  - type: textarea
    id: question
    attributes:
      label: "Your question"
      description: "Ask whatever you want."
      placeholder: "Write here..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        We encourage contributors to follow the [GNU Kind Communications Guidelines (GNU KCG)](https://gnu.support/philosophy/GNU-Kind-Communications-Guidelines.html)
