#!/bin/sh

APP=handbrake

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: handbrake
binpatch: true

ingredients:
  dist: sid
  sources:
    - deb http://ftp.debian.org/debian/ sid main contrib non-free

script:
  - cp usr/share/applications/*desktop .
  - cp usr/share/icons/hicolor/scalable/apps/fr.handbrake.ghb.svg ." >> recipe.yml;

cp ./recipe.yml /opt/$APP/

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

mkdir version
cp /opt/$APP/tmp/$APP/handbrake_*_amd64.deb /opt/$APP/tmp/version/
version=$(ls /opt/$APP/tmp/version)
echo "$version" >> /opt/$APP/version

cd ..;
mv ./tmp/HandBrake-x86_64.AppImage ./$APP;
chmod a+x ./$APP
cp ./tmp/$APP/$APP.AppDir/fr.handbrake.ghb.svg /opt/$APP/$APP.svg

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
version0=$(cat /opt/'$APP'/version)
url="http://ftp.debian.org/debian/pool/main/h/handbrake/"
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed, exit!"
 else
  notify-send "A new version of '$APP' is available, please wait!"
  mkdir /opt/'$APP'/tmp
  cd /opt/'$APP'/tmp
  wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
  wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
  chmod a+x ./appimagetool ./pkg2appimage
  cp /opt/'$APP'/recipe.yml /opt/'$APP'/tmp/recipe.yml
  ./pkg2appimage ./recipe.yml
  ARCH=x86_64 ./appimagetool -n /opt/'$APP'/tmp/'$APP'/'$APP'.AppDir
  mkdir version
  cp /opt/'$APP'/tmp/'$APP'/handbrake_*_amd64.deb /opt/'$APP'/tmp/version/
  version=$(ls /opt/'$APP'/tmp/version)
  cd ..
  if test -f ./tmp/HandBrake-x86_64.AppImage; then rm -R -f ./version
  fi
  echo $version >> ./version
  mv ./tmp/HandBrake-x86_64.AppImage ./'$APP'
  chmod a+x ./'$APP'
  rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Name=HandBrake
GenericName=Media Transcoder
Comment=Transcodes DVD, Bluray, and other media
Exec=$APP %f
Icon=/opt/$APP/$APP.svg
Terminal=false
Type=Application
Categories=GTK;AudioVideo;Video;
MimeType=application/ogg;application/x-extension-mp4;application/x-flac;application/x-matroska;application/x-ogg;audio/ac3;audio/mp4;audio/mpeg;audio/ogg;audio/x-flac;audio/x-matroska;audio/x-mp2;audio/x-mp3;audio/x-mpeg;audio/x-vorbis;video/mp4;video/mp4v-es;video/mpeg;video/msvideo;video/quicktime;video/vnd.divx;video/x-avi;video/x-m4v;video/x-matroska;video/x-mpeg;video/ogg;video/x-ogm+ogg;video/x-theora+ogg;x-content/video-dvd;x-content/video-vcd;x-content/video-svcd;" >> /usr/share/applications/$APP.desktop;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

     HandBrake is provided by https://handbrake.fr

 This is the unofficial AppImage built from Debian Unstable
  
";
