#!/bin/sh

APP=obs-studio

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove
APP=obs-studio
mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE: APPDIR FROM A RECIPE...
echo "app: obs-studio
binpatch: true

ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu bionic-security main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main universe restricted multiverse
  ppas:
    - obsproject/obs-studio
  packages:
    - obs-studio
    - v4l2loopback-dkms" >> recipe.yml;

cp /opt/$APP/tmp/recipe.yml /opt/$APP/recipe.yml

./pkg2appimage ./recipe.yml;

# ...DOWNLOADING LIBUNIONPRELOAD...
wget https://github.com/project-portable/libunionpreload/releases/download/amd64/libunionpreload.so
chmod a+x libunionpreload.so
mv ./libunionpreload.so ./$APP/$APP.AppDir/

# ...REPLACING THE EXISTING APPRUN WITH A CUSTOM ONE...
rm -R -f ./$APP/$APP.AppDir/AppRun
function1="'^Exec=.*'"
function2="'s|%.||g'"
echo '#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so":/usr/lib/x86_64-linux-gnu/libpangox-1.0.so.0:/lib/x86_64-linux-gnu/libselinux.so.1:/lib/x86_64-linux-gnu/libpango-1.0.so.0:/usr/lib/x86_64-linux-gnu/libfribidi.so.0:/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
export PATH=/usr/bin/:"${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/opt/obs-studio/:"${HERE}"/sbin/:"${PATH}"
export LD_LIBRARY_PATH=/usr/lib/:/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/obs-studio/:"${HERE}"/usr/lib64/obs-studio/:"${HERE}"/usr/lib32/obs-studio/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/usr/lib/x86_64-linux-gnu/obs-scripting/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib/udev/:"${HERE}"/usr/lib/x86_64-linux-gnu/obs-plugins/:"${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${HERE}"/usr/lib/python*/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/:"${HERE}"/usr/lib/python*/
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${HERE}"/usr/share/obs/:"${HERE}"/usr/share/obs/obs-studio/:"${XDG_DATA_DIRS}"
export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/'$APP'/:"${HERE}"/usr/lib64/'$APP'/:"${HERE}"/usr/lib32/'$APP'/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
EXEC=$(grep -e '$function1' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e '$function2')
exec ${EXEC} "$@"' >> AppRun
chmod a+x AppRun
cp ./AppRun /opt/$APP/
mv ./AppRun ./$APP/$APP.AppDir

# ...IMPORT THE LAUNCHER AND THE ICON TO THE APPDIR (uncomment if not available)...
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/22x22/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/24x24/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/32x32/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/48x48/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/64x64/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/128x128/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/256x256/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/512x512/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
#cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/scalable/apps/* ./$APP/$APP.AppDir/ 2>/dev/null
cp ./$APP/$APP.AppDir/usr/share/applications/* ./$APP/$APP.AppDir/ 2>/dev/null

# ...EXPORT THE APPDIR TO AN APPIMAGE!
ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;
underscore=_
mkdir version
mv ./$APP/$APP$underscore*.deb ./version/
version=$(ls /opt/$APP/tmp/version)
echo "$version" >> /opt/$APP/version

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
initial=$(echo $APP | head -c 1)
echo '#!/bin/sh
version0=$(cat /opt/'$APP'/version)
url="https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/pool/main/'$initial'/'$APP'/$version0"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
else
  notify-send "A new version of '$APP' is available, please wait!"
  mkdir /opt/'$APP'/tmp
  cd /opt/'$APP'/tmp
  wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
  wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
  chmod a+x ./appimagetool ./pkg2appimage
  cp /opt/'$APP'/recipe.yml /opt/'$APP'/tmp/recipe.yml
  ./pkg2appimage ./recipe.yml;
  cp ./'$APP'/'$APP'.AppDir/usr/share/applications/AM-com.obsproject.Studio.desktop ./'$APP'/'$APP'.AppDir;
  cp ./'$APP'/'$APP'.AppDir/usr/share/icons/hicolor/256x256/apps/*png ./'$APP'/'$APP'.AppDir
  wget https://github.com/project-portable/libunionpreload/releases/download/amd64/libunionpreload.so
  chmod a+x libunionpreload.so
  mv ./libunionpreload.so ./'$APP'/'$APP'.AppDir/
  rm -R -f ./'$APP'/'$APP'.AppDir/AppRun
  cp /opt/'$APP'/AppRun ./'$APP'/'$APP'.AppDir/
  ARCH=x86_64 ./appimagetool -n ./'$APP'/'$APP'.AppDir
  mkdir version
  mv ./'$APP'/'$APP''$underscore'*.deb ./version/
  cd ..
  version=$(ls /opt/'$APP'/tmp/version)
  if test -f ./tmp/version/$version; then rm -R -f ./version
  fi
  echo "$version" >> /opt/'$APP'/version
  mv ./tmp/*.AppImage ./'$APP';
  chmod a+x ./'$APP'
  rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Version=1.0
Name=OBS Studio
GenericName=Streaming/Recording Software
Comment=Free and Open Source Streaming/Recording Software
Exec=obs-studio
Icon=/opt/$APP/$APP.png
Terminal=false
Type=Application
Categories=AudioVideo;Recorder;
StartupNotify=true
StartupWMClass=obs-studio
GenericName[an_ES]=Programa de retransmisión/gravación
Comment[an_ES]=Program de retransmisión/gravación libre y de codigo ubierto
GenericName[ar_SA]=برامج البث / التسجيل
Comment[ar_SA]=برنامج بث / تسجيل مجاني ومفتوح المصدر
GenericName[bn_BD]=স্ট্রিমিং/রেকর্ডিং সফটওয়্যার
Comment[bn_BD]=ফ্রি এবং মুক্ত সোর্স স্ট্রিমিং/রেকর্ডিং সফ্টওয়্যার
GenericName[ca_ES]=Programa de retransmissió/enregistrament
Comment[ca_ES]=Programa de retransmissió/enregistrament de codi lliure i gratuït
GenericName[cs_CZ]=Software pro vysílání a nahrávání
Comment[cs_CZ]=Svobodný software pro vysílání a nahrávání
GenericName[da_DK]=Streaming-/optagelsessoftware
Comment[da_DK]=Gratis og open-source streaming-/optagelsessoftware
GenericName[de_DE]=Streaming-/Aufnahme-Software
Comment[de_DE]=Freie und Open-Source-Streaming-/Aufnahme-Software
GenericName[el_GR]=Λογισμικό Ροής/Καταγραφής
Comment[el_GR]=Δωρεαν Λογισμικό Streaming/Kαταγραφή ανοιχτου κωδικα
GenericName[en_GB]=Streaming/Recording Software
Comment[en_GB]=Free and Open Source Streaming/Recording Software
GenericName[es_ES]=Disfusion digital/ Software de grabacion
Comment[es_ES]=Difusion Digital/Software de grabacion Gratis y con Fuentes Abiertas
GenericName[et_EE]=Video voogesituse ja salvestuse tarkvara
Comment[et_EE]=Tasuta ja avatud lähtekoodiga video voogesituse ja salvestuse tarkvara
GenericName[fa_IR]=نرم افزار جریان/ضبط
Comment[fa_IR]=نرم افزار منبع باز و رایگان جریان/ضبط
GenericName[fi_FI]=Striimaus-/tallennusohjelmisto
Comment[fi_FI]=Ilmainen ja avoimen lähdekoodin striimaus-/tallennusohjelmisto
GenericName[fil_PH]=Software para sa Streaming/Recording
Comment[fil_PH]=Libre at Open Source na Streaming/Recording Software
GenericName[fr_FR]=Logiciel de diffusion/enregistrement
Comment[fr_FR]=Logiciel de diffusion/enregistrement gratuit et Open Source
GenericName[gd_GB]=Bathar-bog sruthaidh/clàraidh
Comment[gd_GB]=Bathar-bog sruthaidh/clàraidh saor le bun-tùs fosgailte
GenericName[he_IL]=תוכנה לשידורים חיים והקלטה
Comment[he_IL]=תכנה חינמית בקוד פתוח לשידורים חיים ולהקלטה
GenericName[hi_IN]=स्ट्रीमिंग/रिकॉर्डिंग सॉफ्टवेयर
Comment[hi_IN]=स्वतंत्र एवं खुले स्रोत वाला स्ट्रीमिंग/रिकॉर्डिंग सॉफ्टवेयर
GenericName[hr_HR]=Softver za emitiranje/snimanje
Comment[hr_HR]=Slobodan softver otvorenog koda za emitiranje/snimanje
GenericName[hu_HU]=Közvetítő/rögzítő szoftver
Comment[hu_HU]=Szabad és nyílt forráskódú közvetítő/rögzítő szoftver
GenericName[id_ID]=Perangkat Lunak Streaming/Perekaman
Comment[id_ID]=Perangkat Lunak Streaming/Perekaman Gratis dan Sumber Terbuka
GenericName[it_IT]=Software per dirette e registrazione schermo
Comment[it_IT]=Software Libero e Open Source Streaming/Registrazione
GenericName[ja_JP]=配信/録画ソフトウェア
Comment[ja_JP]=無料のオープンソース配信/録画ソフトウェア
GenericName[ka_GE]=ვიდეოს ეთერში გამშვები/ჩამწერი პროგრამა
Comment[ka_GE]=თავისუფალი და ღია წყაროს მქონე, ვიდეოს ეთერში გამშვები/ჩამწერი პროგრამა
GenericName[kmr_TR]=Nermalava weşandin/tomarkirin-ê
Comment[kmr_TR]=Nermalava weşandin/tomarkirin-ê belaş û çavkaniya azad
GenericName[ko_KR]=방송 및 녹화 프로그램
Comment[ko_KR]=무료 오픈소스 방송 및 녹화 프로그램
GenericName[ms_MY]=Perisian Penstriman/Rakaman
Comment[ms_MY]=Perisian Penstriman/Rakaman Bersumber Terbuka dan Bebas
GenericName[nb_NO]=Strømming- og Opptaksprogramvare
Comment[nb_NO]=Gratis Strømming- og Opptaksprogramvare med Åpen Kildekode
GenericName[nl_NL]=Streaming/Opname Software
Comment[nl_NL]=Vrij en Open Source Streaming/Opname Sofware
GenericName[pl_PL]=Oprogramowanie do transmisji strumieniowej/nagrywania
Comment[pl_PL]=Darmowe i otwarte oprogramowanie do transmisji strumieniowej/nagrywania
GenericName[pt_BR]=Software de Streaming/Gravação
Comment[pt_BR]=Software de Streaming/Gravação de Código Aberto e Livre
GenericName[pt_PT]=Programa de transmissão/gravação
Comment[pt_PT]=Programa de transmissão/gravação livre e de código aberto
GenericName[ro_RO]=Program de Streaming/Înregistrare
Comment[ro_RO]=Program de streaming / înregistrare gratuit și open source
GenericName[ru_RU]=Программа для видеостриминга и видеозаписи
Comment[ru_RU]=Свободное и открытое ПО для видеостриминга и видеозаписи
GenericName[sk_SK]=Streamovací/Nahrávací Software
Comment[sk_SK]=Bezplatný a otvorený streamovací/nahrávací software
GenericName[sl_SI]=Pretočna/snemalna programska oprema
Comment[sl_SI]=Brezplačni in odprtokodna programska oprema za pretakanje/snemanje
GenericName[sv_SE]=Programvara för strömning/inspelning
Comment[sv_SE]=Fri programvara för strömning/inspelning med öppen källkod
GenericName[tr_TR]=Yayın/Kayıt Yazılımı
Comment[tr_TR]=Ücretsiz ve Açık Kaynaklı Yayın/Kayıt Yazılımı
GenericName[uk_UA]=Програма для трансляцій/запису
Comment[uk_UA]=Вільне та відкрите програмне забезпечення для трансляцій/запису
GenericName[vi_VN]=Phần mềm ghi hình/phát luồng
Comment[vi_VN]=Phần mềm ghi hình / phát luồng mở và miễn phí
GenericName[zh_CN]=直播/录像软件
Comment[zh_CN]=自由且开源的用于直播串流以及视频录制的软件
GenericName[zh_TW]=串流與錄影軟體
Comment[zh_TW]=免費，開源的串流與錄影軟體" >> /usr/share/applications/AM-$APP.desktop;

# ICON
wget https://obsproject.com/favicon-96x96.png
mv ./favicon-96x96.png ./$APP.png

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 OBS Studio is provided by https://obsproject.com
  
";
