#!/bin/sh

mkdir /opt/celestia
cd /opt/celestia
mkdir tmp
cd tmp
wget https://download.opensuse.org/repositories/home:/munix9/AppImage/celestia-latest-x86_64.AppImage
cd ..
mv ./tmp/celestia*AppImage ./celestia
rmdir ./tmp
chmod a+x ./celestia
echo "#!/bin/sh
cd /opt/celestia
appimageupdate -O celestia
rm *zs-old
/opt/celestia/celestia" >> /usr/bin/celestia
chmod a+x /usr/bin/celestia
echo "[Desktop Entry]
Version=1.0
Name=Celestia (GTK)
GenericName=Space Simulator (AppImage-1.6.2.2)
GenericName[de]=Weltraum-Simulator (AppImage-1.6.2.2)
Comment=Explore the Universe in this detailed space simulation
Comment[de]=Erkunde das Universum in dieser detaillierten Weltraumsimulation
Type=Application
Categories=Astronomy;Education;Science;GTK;
Icon=celestia
Exec=celestia %f
Terminal=false
MimeType=application/x-celestia-script;" >> /usr/share/applications/celestia.desktop
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/celestia/celestia.svg
mv ./celestia.svg /usr/share/pixmaps/
echo "#!/bin/sh
rm -R /usr/share/applications/celestia.desktop /usr/share/pixmaps/celestia.svg /usr/bin/celestia /opt/celesti /opt/want/remove/celestia /opt/want/install/celestia" >> /opt/want/remove/celestia
chmod a+x /opt/want/remove/celestia
chown -R $USER /opt/celestia/

echo ""
echo "Celestia is installed!"
echo ""
