#!/bin/sh

APP=appimagetool

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget https://github.com/$(wget https://github.com/AppImage/AppImageKit/releases/latest | grep -E '/.*/.*/.*i686.AppImage' -o);
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP

cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-i386.AppImage
cd ..
mv ./tmp/appimageupdatetool-i386.AppImage ./updater
chmod a+x ./updater

rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM

echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo 'cd /opt/$APP
./updater -O ./$APP
chmod a+x /opt/$APP/$APP
rm -R -f /opt/$APP/*zs-old && rm -R -f /opt/$APP/*.part' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 AppImageTool is provided by https://github.com/AppImage/AppImageKit

"
