#!/bin/sh

APP=appman

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# LOCAL APPS INTEGRATION
echo '
  -----------------------------------------------------------------------
       ___      .______   .______   .___  ___.      ___      .__   __. 
      /   \     |   _  \  |   _  \  |   \/   |     /   \     |  \ |  | 
     /  ^  \    |  |_)  | |  |_)  | |  \  /  |    /  ^  \    |   \|  | 
    /  /_\  \   |   ___/  |   ___/  |  |\/|  |   /  /_\  \   |  . `  | 
   /  _____  \  |  |      |  |      |  |  |  |  /  _____  \  |  |\   | 
  /__/     \__\ | _|      | _|      |__|  |__| /__/     \__\ |__| \__| 

   >>  App Manager for GNU/Linux that uses and creates AppImages  <<

                             by Ivan Alex HC
  
  -----------------------------------------------------------------------

  AppMan is a fork of "AM" and takes all sources from the "AM" repository, 
  all it does is to convert all the installation scripts for "AM" that 
  normally must be executed with ROOT privileges in normal scripts that can
  manage applications in the local folder of the current user.
  To learn more about "AM" and all its scripts, visit the official repository
  on GitHub.

  SITE: https://github.com/IVAN-HC/AM-APPLICATION-MANAGER

  -----------------------------------------------------------------------

  To made the applications working locally, AppMan requires the following 
  string in your ~/.bashrc:
  
  "export PATH=$PATH:$(xdg-user-dir USER)/.local/bin"

'
read -r -p " Do you wish to add this line using this current script (Y/n)?" response
case "$response" in
	[Nn]*) echo ""; echo " INSTALLATION ABORTED"; rm -R -f /opt/$APP; echo ""; exit;;
	[Yy]*|*) currentuser=$(who | awk '{print $1}')
	cd /home/$currentuser && echo 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' >> ./.bashrc
	chown -R $currentuser $(xdg-user-dir USER)/.bashrc; break;;
esac
  


# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir /opt/$APP/tmp
cd /opt/$APP/tmp

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/appman

cd ..
mv ./tmp/$APP ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

clear
# MESSAGE
echo '

       ___      .______   .______   .___  ___.      ___      .__   __. 
      /   \     |   _  \  |   _  \  |   \/   |     /   \     |  \ |  | 
     /  ^  \    |  |_)  | |  |_)  | |  \  /  |    /  ^  \    |   \|  | 
    /  /_\  \   |   ___/  |   ___/  |  |\/|  |   /  /_\  \   |  . `  | 
   /  _____  \  |  |      |  |      |  |  |  |  /  _____  \  |  |\   | 
  /__/     \__\ | _|      | _|      |__|  |__| /__/     \__\ |__| \__| 


   >>  App Manager for GNU/Linux that uses and creates AppImages  <<

   SITE: https://github.com/ivan-hc/AppMan
  
 Run "appman -h" to start, "appman -l" to get the list of applications
';
