#!/bin/sh

APP=armagetronad

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir tmp
cd ./tmp

tag=$(curl -Ls https://api.github.com/repos/ArmagetronAd/armagetronad/releases/latest | jq '.' | grep -E tag_name | awk -F '[""]' '{print $4}')
v=$(echo $tag | cut -c 2-)
wget https://github.com/ArmagetronAd/armagetronad/releases/download/$tag/ArmagetronAdvanced-32bit-$v.AppImage

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)
url=https://api.github.com/repos/ArmagetronAd/armagetronad/releases/latest' >> /opt/$APP/AM-updater

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
echo 'else' >> /opt/$APP/AM-updater
echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater

########################################################################################

function1='$(curl -Ls https://api.github.com/repos/ArmagetronAd/armagetronad/releases/latest | jq '.''
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget https://github.com/ArmagetronAd/armagetronad/releases/download/$tag/ArmagetronAdvanced-32bit-$v.AppImage'
function5='$(echo $tag | cut -c 2-)'

echo "  tag=$function1 | $function2
  v=$function5
  $function4
  version=$function3" >> /opt/$APP/AM-updater

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /opt/$APP/AM-updater
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm -f /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Type=Application
Name=Armagetron Advanced
Exec=armagetronad %f
Comment=3d light cycle game
Comment[de]=dreidimensionales Lichtradspiel
Icon=/opt/$APP/Armagetron_Advanced.png
Terminal=false
Categories=Game;ActionGame;
StartupNotify=false
MimeType=application/x-armagetronad;
Keywords=tron-like;light;cycle;3D;multiplayer;networked;server;" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://upload.wikimedia.org/wikipedia/commons/1/10/Armagetron_Advanced.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 ArmagetronAd is providev by https://github.com/ArmagetronAd
  
";
