#!/bin/sh

APP=kdegames
REPO="ivan-hc/32-bit-AppImage-packages-database"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP*.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(curl -Ls https://api.github.com/repos/$REPO/releases | jq '.' | grep browser_download_url | grep -i $APP | grep -i appimage | cut -d '"' -f 4 | head -1)
wget $version
echo "$version" >> /opt/$APP/version
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
cat >> /usr/local/bin/$APP << 'EOF'
#!/bin/sh
APP=kdegames
export QT_QPA_PLATFORMTHEME=$QT_QPA_PLATFORMTHEME
export QT_FONT_DPI=96
$APP "$*"
EOF
chmod a+x /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=kdegames
REPO="ivan-hc/32-bit-AppImage-packages-database"
version0=$(cat /opt/$APP/version)
version=$(curl -Ls https://api.github.com/repos/$REPO/releases | jq '.' | grep browser_download_url | grep -i $APP | grep -i appimage | cut -d '"' -f 4 | head -1)
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget $version
  if ls . | grep mage; then
	cd ..
  	if test -f ./tmp/*mage; then rm ./version
  	fi
  	echo $version >> ./version
  	mv --backup=t ./tmp/*mage ./$APP
  	chmod a+x /opt/$APP/$APP
  	rm -R -f ./tmp ./*~
  fi
  notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHERS AND ICONS
mkdir icons
./kdegames --appimage-extract > /dev/null
cp ./squashfs-root/usr/share/icons/hicolor/22x22/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/24x24/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/32x32/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/48x48/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/64x64/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/128x128/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/256x256/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/512x512/apps/* /opt/$APP/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/scalable/apps/* /opt/$APP/icons/ 2>/dev/null
cd /opt/$APP/icons
for file in *.png; do mv -- "$file" "${file%%.png}"; done
cd ..

mkdir /opt/$APP/launchers
cp ./squashfs-root/usr/share/applications/* /opt/$APP/launchers/ 2>/dev/null
cd /opt/$APP/launchers
for file in *; do mv ./$file ./AM-$APP-$file
done
sed -i "s#Exec=#Exec=/opt/kdegames/kdegames #g" /opt/$APP/launchers/*.desktop
sed -i "s#Icon=#Icon=/opt/kdegames/icons/#g" /opt/$APP/launchers/*.desktop
cp /opt/$APP/launchers/*.desktop /usr/share/applications/

rm -R -f /opt/$APP/launchers
rm -R -f /opt/$APP/squashfs-root

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
 $APP is provided by https://github.com/$(echo $REPO | sed 's:/[^/]*$::')
"
