#!/bin/sh

APP=bovo

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Type=Application
Exec=bovo -qwindowtitle %c
Icon=/opt/$APP/$APP.svg
Terminal=false
StartupNotify=true
X-DBUS-StartupType=Multi
X-DBUS-ServiceName=org.kde.bovo
X-DocPath=bovo/index.html
Categories=Qt;KDE;Game;BoardGame;
Name=Bovo
Name[ar]=بوڤو
Name[bs]=Bovo
Name[ca]=Bovo
Name[ca@valencia]=Bovo
Name[cs]=Bovo
Name[da]=Bovo
Name[de]=Bovo
Name[el]=Bovo
Name[en_GB]=Bovo
Name[eo]=Bovo
Name[es]=Bovo
Name[et]=Bovo
Name[eu]=Bovo
Name[fa]=بُوُ
Name[fi]=Bovo
Name[fr]=Bovo
Name[ga]=Bovo
Name[gl]=Bovo
Name[hne]=बोवो
Name[hr]=Bovo
Name[hu]=Bovo
Name[id]=Bovo
Name[it]=Bovo
Name[ja]=Bovo
Name[kk]=Бово
Name[km]=Bovo
Name[ko]=Bovo
Name[lt]=Bovo
Name[lv]=Bovo
Name[mai]=Bovo
Name[mr]=बोव्हो
Name[ms]=Bovo
Name[nb]=Bovo
Name[nds]=Bovo
Name[ne]=बोभो
Name[nl]=Bovo
Name[nn]=Bovo
Name[pa]=ਬੋਵੋ
Name[pl]=Bovo
Name[pt]=Bovo
Name[pt_BR]=Bovo
Name[ro]=Bovo
Name[ru]=Bovo
Name[sk]=Bovo
Name[sl]=Bovo
Name[sq]=Bovo
Name[sr]=Бово
Name[sr@ijekavian]=Бово
Name[sr@ijekavianlatin]=Bovo
Name[sr@latin]=Bovo
Name[sv]=Bovo
Name[te]=బొవొ
Name[tr]=Bovo
Name[ug]=Bovo
Name[uk]=Бово
Name[wa]=Bovo
Name[zh_CN]=Bovo
Name[zh_TW]=Bovo
GenericName=Five-in-a-row Board Game
GenericName[ar]=لعبة خمسة في صفّ
GenericName[bs]=Pet-u-redu Igra na ploči
GenericName[ca]=Joc de cinc en fila
GenericName[ca@valencia]=Joc de cinc en fila
GenericName[da]=Fem-på-række-brætspil
GenericName[de]=Fünf-Gewinnt-Brettspiel
GenericName[el]=Επιτραπέζιο παιχνίδι Πέντε στη σειρά
GenericName[en_GB]=Five-in-a-row Board Game
GenericName[eo]=Gobanga bretludo
GenericName[es]=Juego de tablero de cinco en línea
GenericName[et]=Viis ritta lauamäng
GenericName[eu]=Bosteko artzain-jokoa
GenericName[fa]=بازی تخته پنج در یک سطر
GenericName[fi]=Viiden suora
GenericName[fr]=Jeu de plateau « Cinq-en-ligne »
GenericName[ga]=Cluiche cláir cúig-cinn-as-a-chéile
GenericName[gl]=Xogo de taboleiro «pai, fillo e nai»
GenericName[hne]=बोर्ड मं एक लकीर मं पांच वाले खेल
GenericName[hu]=Ötöt egy sorba táblajáték
GenericName[id]=Permainan Papan lima dalam sebaris
GenericName[is]=Fimm-í-röð borðleikur
GenericName[it]=Forza 5, gioco da tavolo
GenericName[ja]=五目並べ
GenericName[km]=ល្បែង​ក្ដារ ប្រាំ​ក្នុង​មួយ​ជួរ
GenericName[ko]=오목 게임
GenericName[lt]=Penki-vienoje-eilutėje stalo žaidimas
GenericName[lv]=Galda spēle pieci-rindā
GenericName[mr]=एका-ओळीत-पाच बोर्ड खेळ
GenericName[nb]=Brettspill fem på rad
GenericName[ne]=एक पङ्क्तिमा पाँच बोर्ड खेल
GenericName[nl]=Vijf-op-een-rij bordspel
GenericName[nn]=Fem på rad
GenericName[pt]=Jogo de Tabuleiro Cinco-em-Linha
GenericName[pt_BR]=Jogo de tabuleiro como Reversi
GenericName[ro]=Joc de table Cinci-în-linie
GenericName[ru]=Японские крестики-нолики
GenericName[sk]=Stolová hra Piškvorky
GenericName[sl]=Namizna igra Pet v vrsto
GenericName[sr]=Игра на табли „пет у низу“
GenericName[sr@ijekavian]=Игра на табли „пет у низу“
GenericName[sr@ijekavianlatin]=Igra na tabli „pet u nizu“
GenericName[sr@latin]=Igra na tabli „pet u nizu“
GenericName[sv]=Fem-i-rad brädspel
GenericName[tr]=Bir-satırda-beş Tahta Oyunu
GenericName[ug]=بىر-قۇردا-بەش تاختا ئويۇنى
GenericName[uk]=Гра на дошці (п'ять-в-рядку)
GenericName[wa]=Djeu «cénk e roye»
GenericName[zh_CN]=五子棋游戏
GenericName[zh_TW]=五子棋棋盤遊戲" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
