#!/bin/sh

APP=btop

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-i686.AppImage -O appimagetool
chmod a+x ./appimagetool

# CREATING THE APPIMAGE
mkdir $APP.AppDir
cd ./$APP.AppDir

v=$(curl -Ls https://api.github.com/repos/aristocratos/btop/releases/latest | jq '.' | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/aristocratos/btop/releases/download/$v/btop-i686-linux-musl.tbz
tar xf ./*.tbz;
rm -f ./*.tbz;
cd ..;
touch ./$APP.AppDir/$APP.png;
echo "[Desktop Entry]
Name=btop
Exec=btop
Icon=btop
Type=Application
Categories=Utility;" >> ./$APP.AppDir/$APP.desktop;

echo '#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/bin/:${HERE}/themes/${PATH:+:$PATH}"
EXEC="${HERE}/bin/btop"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
exec "${EXEC}" "$@"' >> ./$APP.AppDir/AppRun;
chmod a+x ./$APP.AppDir/AppRun;
cp ./$APP.AppDir/AppRun /opt/$APP/AppRun

ARCH=i686 ./appimagetool -n ./$APP.AppDir;

echo "$v" >> /opt/$APP/version

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
APP='$APP'
version0=$(cat /opt/$APP/version)
url=https://api.github.com/repos/aristocratos/btop/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!".
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-i686.AppImage -O appimagetool
chmod a+x ./appimagetool
mkdir $APP.AppDir
cd ./$APP.AppDir' >> /opt/$APP/AM-updater
########################################################################################

function1='$(curl -Ls https://api.github.com/repos/aristocratos/btop/releases/latest | jq '.''
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget https://github.com/aristocratos/btop/releases/download/$v/btop-i686-linux-musl.tbz'

echo "  v=$function1 | $function2
  $function4" >> /opt/$APP/AM-updater

########################################################################################
echo 'tar xf ./*.tbz;
rm -f ./*.tbz;
cd ..;
touch ./$APP.AppDir/$APP.png;
echo "[Desktop Entry]
Name=btop
Exec=btop
Icon=btop
Type=Application
Categories=Utility;" >> ./$APP.AppDir/$APP.desktop;
cp /opt/$APP/AppRun ./$APP.AppDir/AppRun
ARCH=i686 ./appimagetool -n ./$APP.AppDir;
if test -f ./*mage; then rm -R -f /opt/$APP/version
  fi
echo "$v" >> /opt/$APP/version
cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP
rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 Btop is provided by https://github.com/aristocratos/btop
  
";
