#!/bin/sh

APP=firefox-esr

# CREATE THE DIRECTORY
mkdir -p /opt/"$APP"
cd /opt/"$APP"

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/"$APP"/remove
echo "rm -R -f /opt/$APP /usr/local/share/applications/$APP-AM.desktop /usr/local/bin/$APP" >> /opt/"$APP"/remove
chmod a+x /opt/"$APP"/remove

# DOWNLOAD THE ARCHIVE
mkdir -p tmp
cd ./tmp

LANGUAGE=$(echo "${LANG%%.*}" | sed -- 's/_/-/g')
CODES=$(curl -Ls https://releases.mozilla.org/pub/firefox/releases/latest/README.txt | tr ' ' '\n' | grep "^lang=")
if echo "$CODES" | grep -q "^lang=$LANGUAGE"; then
	CODE="$LANGUAGE"
elif echo "$CODES" | grep -q "^lang=$(echo "$LANGUAGE" | tr '-' '\n' | head -1)"; then
	CODE="$(echo "$LANGUAGE" | tr '-' '\n' | head -1)"
else
	CODE=""
fi
download=$(curl -I "https://download.mozilla.org/?product=$APP-latest-ssl&os=linux&lang=$CODE" 2>/dev/null | grep -Eoi "http.*xz" | head -1)
wget "$download" || exit 1

[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
cd ..
mv ./tmp/firefox/* ./
rm -R ./tmp

# LINK TO PATH
ln -s "/opt/$APP/firefox" "/usr/local/bin/$APP"

# LAUNCHER
echo "[Desktop Entry]
Name=Firefox ESR
Comment=Web Browser
Exec=/opt/$APP/firefox %u
Terminal=false
Type=Application
Icon=/opt/$APP/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Actions=Private;

[Desktop Action Private]
Exec=/opt/$APP/firefox --private-window %u
Name=Open in private mode" > /usr/local/share/applications/"$APP"-AM.desktop
