#!/bin/sh

APP=kblackbox

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
GenericName=Blackbox Logic Game
GenericName[be]=Лагічная гульня з чорнай скрыняй
GenericName[bn]=যুক্তির খেলা ব্ল্যাকবক্স
GenericName[bs]=Logička igra crna kutija
GenericName[ca]=Joc de lògica Blackbox
GenericName[ca@valencia]=Joc de lògica Blackbox
GenericName[cs]=Logická hra s černou skříňkou
GenericName[cy]=Gêm Resymeg Blackbox
GenericName[da]=Blackbox logikspil
GenericName[de]=„Blackbox“-Spiel
GenericName[el]=Παιχνίδι λογικής Blackbox
GenericName[en_GB]=Blackbox Logic Game
GenericName[eo]=Divenlogika ludo
GenericName[es]=Juego de lógica Blackbox
GenericName[et]=Blackboxi loogikamäng
GenericName[eu]=Blackbox logika-jokoa
GenericName[fa]=بازی منطقی جعبه‌سیاه
GenericName[fi]=Logiikkapeli
GenericName[fr]=Jeu de logique Blackbox
GenericName[ga]=Cluiche Loighce Blackbox
GenericName[gl]=Xogo de lóxica Blackbox
GenericName[he]=משחק לוגיקה
GenericName[hi]=ब्लैक बॉक्स तर्क का खेल
GenericName[hne]=ब्लैक डब्बा तर्क वाले खेल
GenericName[hr]=Blackbox logička igra
GenericName[hu]=Blackbox logikai játék
GenericName[id]=Permainan Logika Blackbox
GenericName[is]=Blackbox kænskuleikur
GenericName[it]=Gioco di logica Blackbox
GenericName[ja]=ブラックボックス論理ゲーム
GenericName[kk]=Қара жәшік
GenericName[km]=ល្បែង​តក្ក​វិទ្យា Blackbox
GenericName[ko]=블랙박스 논리 게임
GenericName[lt]=Blackbox loginis žaidimas
GenericName[lv]=Melnās kastes loģikas spēle
GenericName[mk]=Логичка игра Blackbox
GenericName[mr]=ब्लॅकबॉक्स तर्क खेळ
GenericName[nb]=Logikkspillet Blackbox
GenericName[nds]=Blackbox Logikspeel
GenericName[ne]=कालोबाकस तार्किक खेल
GenericName[nl]=Blackbox: Logisch spel
GenericName[nn]=Blackbox logikkspel
GenericName[pl]=KCzarnaSkrzynka - Gra logiczna
GenericName[pt]=Jogo de Lógica Caixa Preta
GenericName[pt_BR]=Jogo lógico de Caixa Preta
GenericName[ro]=Joc de logică Blackbox
GenericName[ru]=Чёрный ящик
GenericName[se]=Logihkkaspeallu Blackbox
GenericName[sk]=Logická hra - čierna skrinka
GenericName[sl]=Logična igra KBlackBox
GenericName[sq]=Lojë Logjike Kutia e zezë
GenericName[sr]=Логичка игра „црна кутија“
GenericName[sr@ijekavian]=Логичка игра „црна кутија“
GenericName[sr@ijekavianlatin]=Logička igra „crna kutija“
GenericName[sr@latin]=Logička igra „crna kutija“
GenericName[sv]=Svart låda logiskt spel
GenericName[ta]=கறுப்புபெட்டி லாஜிக் விளையாட்டு
GenericName[tr]=Karakutu Mantık Oyunu
GenericName[ug]=قارا قۇتا لوگىكىلىق ئويۇنى
GenericName[uk]=Гра на логіку (чорна скринька)
GenericName[wa]=Djeu d' lodjike noere boesse
GenericName[x-test]=xxBlackbox Logic Gamexx
GenericName[zh_CN]=黑箱逻辑游戏
GenericName[zh_TW]=黑盒子智力遊戲
Exec=kblackbox -qwindowtitle %c
Name=KBlackBox
Name[af]=Kblackbox
Name[be]=Чорная скрыня
Name[bn]=কে-ব্ল্যাকবক্স
Name[br]=KBlackBox
Name[bs]=KBlackBox
Name[ca]=KBlackBox
Name[ca@valencia]=KBlackBox
Name[cs]=KBlackBox
Name[cy]=KBlackBox
Name[da]=KBlackBox
Name[de]=KBlackBox
Name[el]=KBlackBox
Name[en_GB]=KBlackBox
Name[eo]=KBlackBox
Name[es]=KBlackBox
Name[et]=KBlackBox
Name[eu]=KBlackBox
Name[fa]=جعبه‌سیاه
Name[fi]=KBlackBox
Name[fr]=KBlackBox
Name[ga]=KBlackBox
Name[gl]=KBlackBox
Name[he]=KBlackBox
Name[hi]=के-ब्लेकबॉक्स
Name[hne]=के-ब्लेकबाक्स
Name[hr]=KBlackBox
Name[hu]=KBlackBox
Name[id]=KBlackBox
Name[is]=Svarti Kassinn
Name[it]=KBlackBox
Name[ja]=KBlackBox
Name[kk]=KBlackBox
Name[km]=KBlackBox
Name[ko]=KBlackBox
Name[lt]=KBlackBox
Name[lv]=KBlackBox
Name[mk]=KBlackBox
Name[mr]=के-ब्लॅकबॉक्स
Name[nb]=KBlackBox
Name[nds]=KBlackBox
Name[ne]=केडीई कालोबाकस
Name[nl]=KBlackBox
Name[nn]=KBlackBox
Name[pa]=ਕੇ-ਬਲੈਕ ਬਾਕਸ
Name[pl]=KCzarnaSkrzynka
Name[pt]=KBlackBox
Name[pt_BR]=KBlackBox
Name[ro]=KBlackBox
Name[ru]=KBlackBox
Name[se]=KBlackBox
Name[sk]=KBlackBox
Name[sl]=KBlackBox
Name[sq]=KBlackBox
Name[sr]=К‑црна‑кутија
Name[sr@ijekavian]=К‑црна‑кутија
Name[sr@ijekavianlatin]=K‑crna‑kutija
Name[sr@latin]=K‑crna‑kutija
Name[sv]=Svarta lådan
Name[ta]=கேகருப்பு பெட்டி
Name[tg]=KҚуттии Сиёҳ
Name[tr]=KBlackBox
Name[ug]=KBlackBox
Name[uk]=Чорна скринька
Name[vi]=KBlackBox
Name[wa]=KBlackBox
Name[xh]=KBlackBox
Name[x-test]=xxKBlackBoxxx
Name[zh_CN]=KBlackBox
Name[zh_TW]=KBlackBox 黑盒子
Icon=/opt/$APP/$APP.svg
X-DocPath=kblackbox/index.html
Type=Application
Terminal=false
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;BoardGame;" >> /usr/share/applications/AM-$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
