#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=kdegames
SITE="ivan-hc/32-bit-AppImage-packages-database"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP*-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/ivan-hc/32-bit-AppImage-packages-database/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*kdegames.*mage$" | head -1)
wget "$version" || exit 1
# Keep this space in sync with other installation scripts
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
# Keep this space in sync with other installation scripts
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=kdegames
SITE="ivan-hc/32-bit-AppImage-packages-database"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/ivan-hc/32-bit-AppImage-packages-database/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*kdegames.*mage$" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	wget "$version" || exit 1
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv --backup=t ./tmp/*mage ./"$APP"
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHER & ICON
./kdegames --appimage-extract > /dev/null
cp ./squashfs-root/usr/share/icons/hicolor/22x22/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/24x24/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/32x32/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/48x48/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/64x64/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/128x128/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/256x256/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/512x512/apps/* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/scalable/apps/* /opt/"$APP"/icons/ 2>/dev/null
cd /opt/"$APP"/icons || exit 1
for file in *.png; do mv -- "$file" "${file%%.png}"; done
cd ..

mkdir /opt/"$APP"/launchers
cp ./squashfs-root/usr/share/applications/* /opt/"$APP"/launchers/ 2>/dev/null
cd /opt/"$APP"/launchers
for f in *; do mv "$f" "$APP-${f%.desktop}-AM.desktop"; done
sed -i "s#Exec=#Exec=/opt/kdegames/kdegames #g" /opt/"$APP"/launchers/*.desktop
sed -i "s#Icon=#Icon=/opt/kdegames/icons/#g" /opt/"$APP"/launchers/*.desktop
cp /opt/"$APP"/launchers/*.desktop /usr/local/share/applications/

rm -R -f /opt/"$APP"/launchers
rm -R -f ./squashfs-root
