#!/bin/sh

APP=kdiamond

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Type=Application
Exec=kdiamond -qwindowtitle %c
Name=KDiamond
Name[bs]=KDiamond
Name[ca]=KDiamond
Name[ca@valencia]=KDiamond
Name[cs]=KDiamond
Name[da]=KDiamond
Name[de]=KDiamond
Name[el]=KDiamond
Name[en_GB]=KDiamond
Name[es]=KDiamond
Name[et]=KDiamond
Name[eu]=KDiamond
Name[fa]=جواهرات
Name[fi]=KDiamond
Name[fr]=KDiamond
Name[ga]=KDiamond
Name[gl]=KDiamond
Name[hne]=केडायमंड
Name[hr]=KDiamond
Name[hu]=KDiamond
Name[id]=KDiamond
Name[it]=KDiamond
Name[ja]=KDiamond
Name[kk]=KDiamond
Name[km]=KDiamond
Name[ko]=KDiamond
Name[lt]=KDiamond
Name[lv]=KDiamond
Name[mr]=के-डायमंड
Name[nb]=KDiamond
Name[nds]=KDiamant
Name[nl]=KDiamond
Name[nn]=KDiamantar
Name[pl]=KDiament
Name[pt]=KDiamond
Name[pt_BR]=KDiamond
Name[ro]=KDiamant
Name[ru]=KDiamond
Name[sk]=KDiamond
Name[sl]=KDiamond
Name[sq]=KDiamond
Name[sr]=К‑дијамант
Name[sr@ijekavian]=К‑дијамант
Name[sr@ijekavianlatin]=K‑dijamant
Name[sr@latin]=K‑dijamant
Name[sv]=Kdiamant
Name[tr]=KDiamond
Name[ug]=KDiamond
Name[uk]=КДіамант
Name[x-test]=xxKDiamondxx
Name[zh_CN]=KDiamond
Name[zh_TW]=KDiamond 寶石方塊
GenericName=Three-in-a-row game
GenericName[bs]=Tri-u-nizu igra
GenericName[ca]=Joc de tres en fila
GenericName[ca@valencia]=Joc de tres en fila
GenericName[da]=Tre på række-spil
GenericName[de]=Drei gewinnt
GenericName[el]=Παιχνίδι τριάδων
GenericName[en_GB]=Three-in-a-row game
GenericName[es]=Juego de tablero de tres en raya
GenericName[et]=Kolm ritta mäng
GenericName[eu]=Hiruko artzain-jokoa
GenericName[fa]=بازی «سه در یک سطر»
GenericName[fi]=Kolmen suora
GenericName[fr]=Jeu « Trois-en-ligne »
GenericName[ga]=Cluiche boird trí-cinn-as-a-chéile
GenericName[gl]=Xogo de tres en raia
GenericName[hne]=एक लकीर मं तीन वाले खेल
GenericName[hu]=Táblás játék
GenericName[id]=Permainan tiga dalam sebaris
GenericName[it]=Gioco del tris
GenericName[ja]=三目並べ
GenericName[km]=ល្បែង​ បី​​ក្នុង​មួយ​ជួរ
GenericName[ko]=삼목 게임
GenericName[lv]=Galda spēle trīs-rindā
GenericName[mr]=एका-ओळीत-तीन खेळ
GenericName[nb]=Tre-på-rad-spilll
GenericName[nl]=Drie-op-een-rij bordspel
GenericName[nn]=Tre-på-rad-spel
GenericName[pt]=Jogo de três-em-linha
GenericName[pt_BR]=Jogo de lógica três em linha
GenericName[ro]=Un joc Trei-în-rând
GenericName[ru]=Убийца вашего времени
GenericName[sl]=Namizna igra tri v vrsto
GenericName[sq]=Lojë tre në rresht
GenericName[sr]=Игра „три у низу“
GenericName[sr@ijekavian]=Игра „три у низу“
GenericName[sr@ijekavianlatin]=Igra „tri u nizu“
GenericName[sr@latin]=Igra „tri u nizu“
GenericName[sv]=Tre-i-rad spel
GenericName[tr]=Bir-satırda-üç oyunu
GenericName[ug]=بىر-قۇردا-ئۈچ ئويۇن
GenericName[uk]=Гра у три в рядок
GenericName[wa]=Djeu «troes e roye»
GenericName[x-test]=xxThree-in-a-row gamexx
GenericName[zh_CN]=三子连线棋游戏
GenericName[zh_TW]=把三個相同的寶石連成一線
Comment=Logic game
Comment[ca]=Joc de lògica
Comment[ca@valencia]=Joc de lògica
Comment[cs]=Logická hra
Comment[da]=Logikspil
Comment[de]=Logikspiel
Comment[el]=Παιχνίδι λογικής
Comment[en_GB]=Logic game
Comment[es]=Juego de lógica
Comment[et]=Loogikamäng
Comment[eu]=Logika jokoa
Comment[fi]=Logiikkapeli
Comment[fr]=Jeu de logique
Comment[gl]=Xogo de lóxica.
Comment[id]=Permainan logika
Comment[it]=Gioco di logica
Comment[ko]=논리 게임
Comment[nl]=Logisch spel
Comment[nn]=Hjernetrim
Comment[pl]=Gra logiczna
Comment[pt]=Jogo de lógica
Comment[pt_BR]=Jogo de lógica
Comment[ru]=Логическая игра
Comment[sk]=Logická hra
Comment[sl]=Logična igra
Comment[sr]=Логичка игра
Comment[sr@ijekavian]=Логичка игра
Comment[sr@ijekavianlatin]=Logička igra
Comment[sr@latin]=Logička igra
Comment[sv]=Logikspel
Comment[tr]=Mantık oyunu
Comment[uk]=Гра на логіку
Comment[x-test]=xxLogic gamexx
Comment[zh_CN]=逻辑游戏
Comment[zh_TW]=智力遊戲
Terminal=false
Icon=/opt/$APP/$APP.svg
StartupNotify=true
Categories=Qt;KDE;Game;LogicGame;
X-DocPath=kdiamond/index.html
X-DBUS-ServiceName=org.kde.kdiamond" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
