#!/bin/sh

APP=klickety

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=Klickety
Name[bs]=Kliketi
Name[ca]=Klickety
Name[ca@valencia]=Klickety
Name[cs]=Klickety
Name[da]=Klickety
Name[de]=Klickety
Name[el]=Klickety
Name[en_GB]=Klickety
Name[es]=Klickety
Name[et]=Klickety
Name[fi]=Klickety
Name[fr]=Klickety
Name[ga]=Klickety
Name[gl]=Klickety
Name[hi]=क्लिकेटी
Name[hu]=Klickety
Name[id]=Klickety
Name[it]=Klickety
Name[kk]=Klickety
Name[km]=Klickety
Name[ko]=Klickety
Name[lv]=Klickety
Name[mr]=क्लिकेटी
Name[nb]=Klickety
Name[nds]=Klickety
Name[nl]=Klickety
Name[nn]=Klickety
Name[pl]=Klickety
Name[pt]=Klickety
Name[pt_BR]=Klickety
Name[ru]=Klickety
Name[sk]=Klickety
Name[sl]=Klickety
Name[sr]=Кликети
Name[sr@ijekavian]=Кликети
Name[sr@ijekavianlatin]=Kliketi
Name[sr@latin]=Kliketi
Name[sv]=Klickety
Name[tr]=Klickety
Name[ug]=Klickety
Name[uk]=Klickety
Name[x-test]=xxKlicketyxx
Name[zh_CN]=Klickety
Name[zh_TW]=Klickety
GenericName=Board Game
GenericName[af]=Bord Speletjie
GenericName[be]=Настольная гульня
GenericName[bn]=ছককেন্দ্রিক খেলা
GenericName[br]=Ur c'hoari taolenn
GenericName[bs]=Igra na ploči
GenericName[ca]=Joc de taula
GenericName[ca@valencia]=Joc de taula
GenericName[cs]=Desková hra
GenericName[cy]=Gêm Fwrdd
GenericName[da]=Brætspil
GenericName[de]=Brettspiel
GenericName[el]=Επιτραπέζιο παιχνίδι
GenericName[en_GB]=Board Game
GenericName[eo]=Bretludo
GenericName[es]=Juego de tablero
GenericName[et]=Lauamäng
GenericName[eu]=Mahai-jokoa
GenericName[fa]=بازی تخته
GenericName[fi]=Lautapeli
GenericName[fr]=Jeu de plateau
GenericName[ga]=Cluiche Cláir
GenericName[gl]=Xogo de taboleiro
GenericName[he]=משחק לוח
GenericName[hi]=बिसात के खेल
GenericName[hne]=बिसात वाले खेल
GenericName[hr]=Igra na ploči
GenericName[hu]=Táblajáték
GenericName[id]=Permainan Papan
GenericName[is]=Borðleikur
GenericName[it]=Gioco da tavolo
GenericName[ja]=ボードゲーム
GenericName[kk]=Тақта ойыны
GenericName[km]=ល្បែង​ក្ដារ
GenericName[ko]=보드 게임
GenericName[lt]=Stalo žaidimas
GenericName[lv]=Galda spēle
GenericName[mai]=बिसात केर खेल
GenericName[mk]=Игра на табла
GenericName[mr]=बोर्ड खेळ
GenericName[nb]=Brettspill
GenericName[nds]=Brettspeel
GenericName[ne]=बोर्ड खेल
GenericName[nl]=Bordspel
GenericName[nn]=Brettspel
GenericName[pa]=ਬੋਰਡ ਖੇਡ
GenericName[pl]=Gra planszowa
GenericName[pt]=Jogo de Tabuleiro
GenericName[pt_BR]=Jogo de Tabuleiro
GenericName[ro]=Un joc de table
GenericName[ru]=Настольная игра
GenericName[se]=Duolbbášspeallu
GenericName[sk]=Stolová hra
GenericName[sl]=Namizna igra
GenericName[sr]=Игра на табли „исто‑исто“
GenericName[sr@ijekavian]=Игра на табли „исто‑исто“
GenericName[sr@ijekavianlatin]=Igra na tabli „isto‑isto“
GenericName[sr@latin]=Igra na tabli „isto‑isto“
GenericName[sv]=Brädspel
GenericName[ta]=பலகை விளையாட்டு
GenericName[te]=పలక ఆట
GenericName[tg]=Бозии Рӯи Мизӣ
GenericName[tr]=Tahta Oyunu
GenericName[ug]=تاختا ئويۇنى
GenericName[uk]=Гра на дошці
GenericName[uz]=Stol oʻyini
GenericName[uz@cyrillic]=Стол ўйини
GenericName[vi]=Game bàn 
GenericName[wa]=Djeu d' platea
GenericName[xh]=Umdlalo Webhodi
GenericName[x-test]=xxBoard Gamexx
GenericName[zh_CN]=色块消去游戏
GenericName[zh_TW]=棋盤遊戲
Icon=/opt/$APP/$APP.svg
Exec=klickety -qwindowtitle %c
Type=Application
Comment=
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DocPath=klickety/index.html
X-DBUS-ServiceName=org.kde.klickety" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
