#!/bin/sh

APP=kreversi

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Exec=kreversi -qwindowtitle %c
Name=KReversi
Name[af]=Kreversi
Name[be]=Рэверсі
Name[bn]=কে-রিভার্সি
Name[br]=KReversi
Name[bs]=KReversi
Name[ca]=KReversi
Name[ca@valencia]=KReversi
Name[cs]=KReversi
Name[cy]=KReversi
Name[da]=KReversi
Name[de]=KReversi
Name[el]=KReversi
Name[en_GB]=KReversi
Name[eo]=Renverso
Name[es]=KReversi
Name[et]=KReversi
Name[eu]=KReversi
Name[fi]=KReversi
Name[fr]=KReversi
Name[ga]=KReversi
Name[gl]=KReversi
Name[he]=KReversi
Name[hi]=के-रिवर्सी
Name[hne]=के-रिवर्सी
Name[hr]=KReversi
Name[hu]=KReversi
Name[id]=KReversi
Name[is]=KViðsnúningur
Name[it]=KReversi
Name[ja]=KReversi
Name[kk]=KReversi
Name[km]=KReversi
Name[ko]=KReversi
Name[lt]=KReversi
Name[lv]=KReversi
Name[mk]=KReversi
Name[mr]=के-रिवर्सी
Name[nb]=KReversi
Name[nds]=KReversi
Name[ne]=केडीई रिभर्सी
Name[nl]=KReversi
Name[nn]=KReversi
Name[pa]=ਕੇ-ਰੀਵਰਸੀ
Name[pl]=KReversi
Name[pt]=KReversi
Name[pt_BR]=KReversi
Name[ro]=KReversi
Name[ru]=KReversi
Name[se]=KReversi
Name[sk]=KReversi
Name[sl]=KReversi
Name[sr]=К‑реверси
Name[sr@ijekavian]=К‑реверси
Name[sr@ijekavianlatin]=K‑reversi
Name[sr@latin]=K‑reversi
Name[sv]=Othello
Name[ta]=Kரிவர்ஸி
Name[tg]=KРеверси
Name[tr]=KReversi
Name[ug]=KReversi
Name[uk]=Реверсі
Name[uz]=KReversi
Name[uz@cyrillic]=KReversi
Name[vi]=KReversi
Name[wa]=KReversi
Name[xh]=KReversi
Name[x-test]=xxKReversixx
Name[zh_CN]=KReversi
Name[zh_TW]=KReversi 黑白棋
Type=Application
X-DocPath=kreversi/index.html
GenericName=Reversi Board Game
GenericName[be]=Настольная гульня ў рэверсі
GenericName[bn]=ছককেন্দ্রিক খেলা রিভার্সি
GenericName[br]=Ur c'hoari taolenn Reversi
GenericName[bs]=Reversi igra na ploči
GenericName[ca]=Joc de taula Reversi
GenericName[ca@valencia]=Joc de taula Reversi
GenericName[cs]=Desková hra Reversi
GenericName[cy]=Gêm Fwrdd Reversi
GenericName[da]=Reversi brætspil
GenericName[de]=„Reversi“-Brettspiel
GenericName[el]=Επιτραπέζιο παιχνίδι Reversi
GenericName[en_GB]=Reversi Board Game
GenericName[es]=Juego de tablero Reversi
GenericName[et]=Lauamäng Reversi
GenericName[fa]=بازی Reversi Board
GenericName[fi]=Othello
GenericName[fr]=Jeu de plateau Reversi
GenericName[ga]=Cluiche Cláir Reversi
GenericName[gl]=Xogo de taboleiro similar ao Reversi
GenericName[he]=רברסי, משחק לוח
GenericName[hi]=रिवर्सी बोर्ड खेल
GenericName[hne]=रिवर्सी बोर्ड खेल
GenericName[hr]=Reversi igra na ploči
GenericName[hu]=Reversi táblajáték
GenericName[id]=Permainan Papan Membalik-balik
GenericName[is]=Reversi borðleikur
GenericName[it]=Reversi, gioco da tavolo
GenericName[ja]=リバーシゲーム
GenericName[kk]=Реверси тақта ойыны
GenericName[km]=ល្បែង​ក្ដារ Reversi
GenericName[ko]=리버시 보드 게임
GenericName[lt]=Reversi stalo žaidimas
GenericName[lv]=Reversi galda spēle
GenericName[mk]=Игра на табла Reversi
GenericName[mr]=रिवर्सी बोर्ड खेळ
GenericName[nb]=Brettspillet reversi
GenericName[nds]=Reversi-Brettspeel
GenericName[ne]=रिभर्सी बोर्ड खेल
GenericName[nl]=Reversi-bordspel
GenericName[nn]=Brettspelet reversi
GenericName[pl]=Gra planszowa Reversi
GenericName[pt]=Jogo de Tabuleiro Reversi
GenericName[pt_BR]=Jogo de tabuleiro como Reversi
GenericName[ro]=Joc de table Reversi
GenericName[ru]=Настольная игра в реверси
GenericName[se]=Duolbbášspeallu reversi
GenericName[sk]=Stolová hra Reversi
GenericName[sl]=Namizna igra Reversi
GenericName[sr]=Игра на табли „реверси“
GenericName[sr@ijekavian]=Игра на табли „реверси“
GenericName[sr@ijekavianlatin]=Igra na tabli „reversi“
GenericName[sr@latin]=Igra na tabli „reversi“
GenericName[sv]=Othello brädspel
GenericName[ta]=ரிவர்சி பலகை விளையாட்டு
GenericName[te]=రివర్సి పలక ఆట
GenericName[tr]=Reversi Tahta Oyunu
GenericName[ug]=Reversi تاختا ئويۇنى
GenericName[uk]=Гра на дошці (реверсі)
GenericName[wa]=Djeu d' platea Reversi
GenericName[x-test]=xxReversi Board Gamexx
GenericName[zh_CN]=黑白棋游戏
GenericName[zh_TW]=黑白棋棋盤遊戲
Terminal=false
Icon=/opt/$APP/$APP.svg
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;BoardGame;
X-DBUS-ServiceName=org.kde.kreversi" >> /usr/share/applications/AM-$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
