#!/bin/sh

APP=kspaceduel

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KSpaceDuel
Name[af]=K-ruimte-uitdaging
Name[be]=Касмічная дуэль
Name[bn]=কে-স্পেসডুয়েল
Name[br]=KSpaceDuel
Name[bs]=KSpaceDuel
Name[ca]=KSpaceDuel
Name[ca@valencia]=KSpaceDuel
Name[cs]=KSpaceDuel
Name[cy]=KSpaceDuel
Name[da]=KSpaceDuel
Name[de]=KSpaceDuel
Name[el]=KSpaceDuel
Name[en_GB]=KSpaceDuel
Name[eo]=KSpaceDuel
Name[es]=KSpaceDuel
Name[et]=KSpaceDuel
Name[eu]=KSpaceDuel
Name[fa]=دوئل فضایی
Name[fi]=KSpaceDuel
Name[fr]=KSpaceDuel
Name[ga]=KSpaceDuel
Name[gl]=KSpaceDuel
Name[he]=KSpaceDuel
Name[hne]=के-स्पेसड्यूएल
Name[hr]=KSvemirski dvoboj
Name[hu]=Űrpárbaj
Name[is]=Geimeinvígi
Name[it]=KSpaceDuel
Name[ja]=KSpaceDuel
Name[kk]=KSpaceDuel
Name[km]=KSpaceDuel
Name[ko]=KSpaceDuel
Name[lt]=KSpaceDuel
Name[lv]=KSpaceDuel
Name[mk]=KSpaceDuel
Name[mr]=के-स्पेस-ड्युएल
Name[nb]=Rom-duell
Name[nds]=KSpaceDuel
Name[ne]=केडीई स्पेसड्युल
Name[nl]=KSpaceDuel
Name[nn]=Romduell
Name[pl]=Kosmiczny pojedynek
Name[pt]=KSpaceDuel
Name[pt_BR]=KSpaceDuel
Name[ro]=Duel spațial
Name[ru]=KSpaceDuel
Name[sk]=KSpaceDuel
Name[sl]=KSpaceDuel
Name[sr]=К‑свемирски-двобој
Name[sr@ijekavian]=К‑свемирски-двобој
Name[sr@ijekavianlatin]=K‑svemirski-dvoboj
Name[sr@latin]=K‑svemirski-dvoboj
Name[sv]=Kspaceduel
Name[ta]=Kஸ்பேஸ்டுயல்
Name[tg]=KМуҳорибаи Кайҳонӣ
Name[tr]=Uzay Düellosu
Name[ug]=KSpaceDuel
Name[uk]=Космічна дуель
Name[vi]=KSpaceDuel
Name[wa]=KSpaceDuel
Name[xh]=KSpaceDuel
Name[x-test]=xxKSpaceDuelxx
Name[zh_CN]=KSpaceDuel
Name[zh_TW]=KSpaceDuel 決戰星空
Exec=kspaceduel -qwindowtitle %c
GenericName=Space Arcade Game
GenericName[be]=Касмічная аркадная гульня
GenericName[bn]=মহাশূন্য নিয়ে একটি আর্কেড (Arcade) খেলা
GenericName[bs]=Svemir arkadna igra
GenericName[ca]=Joc arcade de l'espai
GenericName[ca@valencia]=Joc arcade de l'espai
GenericName[cs]=Vesmírná arkádová hra
GenericName[cy]=Gêm Arcêd Ofod
GenericName[da]=Rum arkadespil
GenericName[de]=Weltraum-Spiel
GenericName[el]=Διαστημικό Arcade παιχνίδι
GenericName[en_GB]=Space Arcade Game
GenericName[eo]=Kosma arkadoludo
GenericName[es]=Juego arcade espacial
GenericName[et]=Põnevusmäng kosmoses
GenericName[eu]=Espazioko arcade jokoa
GenericName[fa]=بازی گذرگاه فضایی
GenericName[fi]=Arcade-peli
GenericName[fr]=Jeu d'arcade dans l'espace
GenericName[ga]=Cluiche Stuara Spáis
GenericName[gl]=Xogo arcade espacial
GenericName[he]=משחק ארקייד חללי
GenericName[hne]=स्पेस आर्केड खेल
GenericName[hr]=Arkadna igra u Svemiru
GenericName[hu]=Űrbeli ügyességi játék
GenericName[is]=Skotgeimleikur
GenericName[it]=Gioco arcade nello spazio
GenericName[ja]=宇宙アーケードゲーム
GenericName[kk]=Ғарыштағы атылыс ойны
GenericName[km]=ល្បែង​ទូ​លំហ
GenericName[ko]=우주 아케이드 게임
GenericName[lv]=Kosmiskā dueļa spēle
GenericName[mk]=Вселенска аркадна игра
GenericName[mr]=अंतरिक्ष ऑर्केड खेळ
GenericName[nb]=Arkade-romspill
GenericName[nds]=Speelhall-Weltruumspeel
GenericName[ne]=स्पेस आर्केड खेल
GenericName[nl]=Ruimte-arcadespel
GenericName[nn]=Arkade-romspel
GenericName[pl]=Kosmiczna gra zręcznościowa
GenericName[pt]=Jogo de Arcada Espacial
GenericName[pt_BR]=Jogo de Arcade espacial
GenericName[ro]=Un joc de aventuri spațiale
GenericName[ru]=Космическая аркадная игра
GenericName[sk]=Vesmírna arkádová hra
GenericName[sl]=Vesoljska arkadna igra
GenericName[sr]=Свемирска аркадна игра
GenericName[sr@ijekavian]=Свемирска аркадна игра
GenericName[sr@ijekavianlatin]=Svemirska arkadna igra
GenericName[sr@latin]=Svemirska arkadna igra
GenericName[sv]=Rymdspel
GenericName[ta]=விண்வெளி ஆர்கேட் விளையாட்டு
GenericName[tr]=Uzay Macera Oyunu
GenericName[ug]=بوشلۇق ئويۇنى
GenericName[uk]=Космічна аркадна гра — дуель
GenericName[wa]=Djeu d' årcåde di l' espåce
GenericName[x-test]=xxSpace Arcade Gamexx
GenericName[zh_CN]=空间型街机游戏
GenericName[zh_TW]=大型遊戲機遊戲
Icon=/opt/$APP/$APP.svg
X-DocPath=kspaceduel/index.html
Type=Application
Terminal=false
X-KDE-StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;ArcadeGame;
X-DBUS-ServiceName=org.kde.kspaceduel" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
