#!/bin/sh

APP=ksudoku

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KSudoku
Name[bs]=KSudoku
Name[ca]=KSudoku
Name[ca@valencia]=KSudoku
Name[cs]=KSudoku
Name[da]=KSudoku
Name[de]=KSudoku
Name[el]=KSudoku
Name[en_GB]=KSudoku
Name[es]=KSudoku
Name[et]=KSudoku
Name[eu]=KSudoku
Name[fi]=KSudoku
Name[fr]=KSudoku
Name[ga]=KSudoku
Name[gl]=KSudoku
Name[hi]=के-सुडोकु
Name[hne]=के-सुडोकु
Name[hu]=KSudoku
Name[it]=KSudoku
Name[ja]=KSudoku
Name[kk]=KSudoku
Name[km]=KSudoku
Name[ko]=KSudoku
Name[lt]=KSudoku
Name[lv]=KSudoku
Name[ml]=കെസുഡോക്കു
Name[mr]=के-सुडोकु
Name[nb]=KSudoku
Name[nds]=KSudoku
Name[nl]=KSudoku
Name[nn]=KSudoku
Name[pa]=ਕੇਸੁਡੂਕੂ
Name[pl]=KSudoku
Name[pt]=KSudoku
Name[pt_BR]=KSudoku
Name[ro]=KSudoku
Name[ru]=KSudoku
Name[sk]=KSudoku
Name[sl]=KSudoku
Name[sr]=К‑судоку
Name[sr@ijekavian]=К‑судоку
Name[sr@ijekavianlatin]=K‑sudoku
Name[sr@latin]=K‑sudoku
Name[sv]=Ksudoku
Name[tr]=KSudoku
Name[ug]=KSudoku
Name[uk]=KSudoku
Name[wa]=KSudoku
Name[x-test]=xxKSudokuxx
Name[zh_CN]=KSudoku
Name[zh_TW]=KSudoku
Exec=ksudoku -qwindowicon ksudoku -qwindowtitle %c
Icon=/opt/$APP/$APP.svg
Type=Application
X-DocPath=ksudoku/index.html
GenericName=Sudoku Game
GenericName[bs]=Sudoku igra
GenericName[ca]=Joc de Sudoku
GenericName[ca@valencia]=Joc de Sudoku
GenericName[cs]=Sudoku hra
GenericName[da]=Sudoku-spil
GenericName[de]=„Sudoku“-Spiel
GenericName[el]=Παιχνίδι Sudoku
GenericName[en_GB]=Sudoku Game
GenericName[eo]=Ludo de sudoko
GenericName[es]=Juego de Sudoku
GenericName[et]=Sudoku mäng
GenericName[eu]=Sudoku jokoa
GenericName[fa]=بازی سودوکو
GenericName[fi]=Sudoku-peli
GenericName[fr]=Jeu de Sudoku
GenericName[ga]=Cluiche Sudoku
GenericName[gl]=Xogo de Sudoku
GenericName[hi]=सुडोकु खेल
GenericName[hne]=सुडोकु खेल
GenericName[hu]=Sudoku játék
GenericName[it]=Gioco del Sudoku
GenericName[ja]=数字パズルゲーム
GenericName[kk]=Судоку ойны
GenericName[km]=ល្បែង Sudoku
GenericName[ko]=스도쿠 게임
GenericName[lt]=Sudoku žaidimas
GenericName[lv]=Sudoku spēle
GenericName[ml]=സുഡോകു കളി
GenericName[mr]=सुडोकु खेळ
GenericName[nb]=Sudoku-spill
GenericName[nds]=Sudoku-Speel
GenericName[nl]=Sudoku-spel
GenericName[nn]=Sudoku-spel
GenericName[pa]=ਸੁਡੂਕੁ ਖੇਡ
GenericName[pl]=Sudoku
GenericName[pt]=Jogo do Sudoku
GenericName[pt_BR]=Jogo Lógico Sudoku
GenericName[ro]=Joc sudoku
GenericName[ru]=Игра судоку
GenericName[sk]=Sudoku hra
GenericName[sl]=Igra Sudokuja
GenericName[sr]=Игра „судоку“
GenericName[sr@ijekavian]=Игра „судоку“
GenericName[sr@ijekavianlatin]=Igra „sudoku“
GenericName[sr@latin]=Igra „sudoku“
GenericName[sv]=Sudoku-spel
GenericName[tr]=Sudoku Oyunu
GenericName[uk]=Гра у судоку
GenericName[wa]=Djeu di Sudoku
GenericName[x-test]=xxSudoku Gamexx
GenericName[zh_CN]=数独游戏
GenericName[zh_TW]=Sudoku 數獨遊戲
Comment=KSudoku, Sudoku game & more by KDE
Comment[ca]=KSudoku, joc de Sudoku i més, creat per la comunitat KDE
Comment[ca@valencia]=KSudoku, joc de Sudoku i més, creat per la comunitat KDE
Comment[cs]=KSudoku, Sudoku hra od KDE
Comment[da]=KSudoku, sudoku-spil med mere af KDE
Comment[de]=KSudoku, Sudoku-Spiel & mehr von KDE
Comment[en_GB]=KSudoku, Sudoku game & more by KDE
Comment[es]=KSudoku, juego Sudoku y más creado por KDE
Comment[et]=KSudoku, KDE sudoku mäng ja palju enam
Comment[eu]=KSudoku, Sudoku jokoa eta gehiago KDEk egina
Comment[fi]=KDE:n KSudoku, Sudoku-peli ja jotain muutakin
Comment[fr]=KSudoku, jeu de Sodoku et plus par KDE
Comment[gl]=KSudoku, o xogo do Sudoku e outros por KDE
Comment[hi]=के-सुडोकु, सुडोकु खेल तथा केडीई द्वारा अधिक
Comment[it]=KSudoku, gioco del Sudoku ed altri da KDE
Comment[ko]=KSudoku, KDE의 스도쿠 게임과 그 이상
Comment[ml]=കെഡിഇ യുടെ കെസുഡോകു,സുഡോകു കളിയും കൂടുതലും
Comment[nl]=KSudoku, sudoku-spel en meer door KDE
Comment[nn]=KSudoku – omfattande sudoku-spel frå KDE
Comment[pl]=KSudoku, gra Sudoku i więcej w ramach KDE
Comment[pt]=KSudoku, um jogo de Sudoku & mais do KDE
Comment[pt_BR]=KSudoku, Jogo Sudoku e mais do KDE
Comment[ro]=KSudoku, joc KDE de sudoku și altele
Comment[ru]=KSudoku — судоку и другие игры от KDE
Comment[sk]=KSudoku, Sudoku hra a ďalšie pre KDE
Comment[sl]=KSudoku - Sudoku in več s strani KDE
Comment[sr]=К‑судоку, судоку и још штошта из КДЕ‑а
Comment[sr@ijekavian]=К‑судоку, судоку и још штошта из КДЕ‑а
Comment[sr@ijekavianlatin]=K‑sudoku, sudoku i još štošta iz KDE‑a
Comment[sr@latin]=K‑sudoku, sudoku i još štošta iz KDE‑a
Comment[sv]=Ksudoku, Sudoku-spel med mera av KDE
Comment[tr]=KSudoku, KDE için sudoku oyunu & fazlası
Comment[uk]=KSudoku, гра у судоку і інше від KDE
Comment[x-test]=xxKSudoku, Sudoku game & more by KDExx
Comment[zh_CN]=KSudoku，KDE 的增强型数独游戏
Comment[zh_TW]=KSudoku，數獨遊戲與更多由 KDE 製作
Terminal=false
Categories=Qt;KDE;Game;LogicGame;
X-DBUS-ServiceName=org.kde.ksudoku" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
