#!/bin/sh

APP=ktuberling

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Exec=ktuberling -qwindowtitle %c %u
Name=Potato Guy
Name[af]=Aartappel Man
Name[be]=Бульбяш
Name[bn]=পটেটো গাই
Name[br]=Paotr ar patatez
Name[bs]=Krompirko
Name[ca]=Home Patata
Name[ca@valencia]=Home Patata
Name[cs]=Bramborový chlapík
Name[cy]=Potato Guy
Name[da]=Kartoffelfyren
Name[de]=Kartoffelknülch
Name[el]=Πατατάνθρωπος
Name[en_GB]=Potato Guy
Name[eo]=Terpomulo
Name[es]=Señor Patata
Name[et]=Kartulimees
Name[eu]=Patata jauna
Name[fa]=مرد سیب زمینی
Name[fi]=Perunamies
Name[fr]=Monsieur Patate
Name[ga]=Potato Guy
Name[gl]=O home pataca
Name[he]=מר תפוח אדמה
Name[hne]=आलू परसाद
Name[hr]=Krumpirko
Name[hu]=Krumpli bácsi
Name[id]=Potato Guy
Name[is]=Kartöflukall
Name[it]=Uomo patata
Name[ja]=ポテトマン
Name[kk]=Картопбай
Name[km]=មនុស្ស​ដំឡូង
Name[ko]=감자돌이
Name[lt]=Bulvinis Vyrukas
Name[lv]=Kartupeļu vīrs
Name[mk]=Компирко
Name[mr]=बटाटा व्यक्ति
Name[nb]=Potetfyren
Name[nds]=Kantüffelfips
Name[ne]=पोट्याटो गाइ
Name[nl]=Aardappelmannetje
Name[nn]=Potetfyren
Name[pa]=ਆਲੂ ਮੁੰਡਾ
Name[pl]=Ziemniaczany facet
Name[pt]=Homem Batata
Name[pt_BR]=Homem-Batata
Name[ro]=Domnul Cartof
Name[ru]=Картофельный парень
Name[se]=Buđetolmmái
Name[sk]=Zemiakový chlapec
Name[sl]=Krompirček
Name[sr]=Кромпирко
Name[sr@ijekavian]=Кромпирко
Name[sr@ijekavianlatin]=Krompirko
Name[sr@latin]=Krompirko
Name[sv]=Potatismannen
Name[ta]=உருளைகிழங்கு வீரர்
Name[tg]=Писараки Картошкагин
Name[tr]=Patates Adam
Name[ug]=Potato Guy
Name[uk]=Картопляний хлопець
Name[vi]=Potato Guy
Name[wa]=Monsieu Crompire
Name[xh]=Umfana wetapile 
Name[x-test]=xxPotato Guyxx
Name[zh_CN]=土豆小子
Name[zh_TW]=馬鈴薯小子
GenericName=Picture Game for Children
GenericName[bs]=Igra slika za djecu
GenericName[ca]=Joc d'imatges per a la canalla
GenericName[ca@valencia]=Joc d'imatges per a la canalla
GenericName[cs]=Obrázková hra pro děti
GenericName[da]=Billedspil til børn
GenericName[de]=Bastelspiel für Kinder
GenericName[el]=Παιχνίδι με εικόνες για παιδιά
GenericName[en_GB]=Picture Game for Children
GenericName[eo]=Bildludo por infanoj
GenericName[es]=Juego de dibujo para niños
GenericName[et]=Laste pildimäng
GenericName[eu]=Umeentzako irudien jokoa
GenericName[fa]=بازی تصویری برای بچه‌‌‌ها
GenericName[fi]=Peli lapsille
GenericName[fr]=Jeu d'image pour les enfants
GenericName[ga]=Cluiche Pictiúir do Phaistí
GenericName[gl]=Xogo de imaxes para nenos
GenericName[hne]=लइका मन बर फोटू वाले खेल
GenericName[hu]=Képes játék gyermekeknek
GenericName[id]=Permainan Gambar untuk Anak-anak
GenericName[is]=Myndaleikur fyrir börn
GenericName[it]=Gioco di immagini per bambini
GenericName[ja]=子供のための福笑いゲーム
GenericName[kk]=Сурет салу балалар ойны
GenericName[km]=ល្បែង​រូបភាព​សម្រាប់​ក្មេងៗ
GenericName[ko]=어린이용 그림 게임
GenericName[lv]=Bilžu spēle bērniem
GenericName[mr]=मुलांकरिता प्रतिमा खेळ
GenericName[nb]=Bildespill for unger
GenericName[nds]=Billerspeel för Kinners
GenericName[nl]=Plaatjesspel voor kinderen
GenericName[nn]=Biletspel for ungar
GenericName[pl]=Gra obrazkowa dla dzieci
GenericName[pt]=Jogo de Imagens para Crianças
GenericName[pt_BR]=Jogo de figuras para Crianças
GenericName[ro]=Joc cu imagini pentru copii
GenericName[ru]=Игра с картинками для детей
GenericName[sk]=Obrázková hra pre deti
GenericName[sl]=Slikovna igra za otroke
GenericName[sr]=Игра за децу
GenericName[sr@ijekavian]=Игра за дјецу
GenericName[sr@ijekavianlatin]=Igra za djecu
GenericName[sr@latin]=Igra za decu
GenericName[sv]=Bildspel för barn
GenericName[te]=పిల్లల చిత్రాల ఆట
GenericName[tr]=Çocuklar için Resim Oyunu
GenericName[ug]=بالىلار ئۈچۈن سۈرەت ئويۇنى
GenericName[uk]=Гра у картинки для дітей
GenericName[wa]=Djeu d' dessin po ls efants
GenericName[x-test]=xxPicture Game for Childrenxx
GenericName[zh_CN]=孩子们的游戏
GenericName[zh_TW]=小孩的圖畫遊戲
Comment=A simple constructor game suitable for children and adults alike
Comment[ca]=Un joc de construcció senzill, adequat per a infants i també per a adults
Comment[ca@valencia]=Un joc de construcció senzill, adequat per a infants i també per a adults
Comment[da]=En simpelt byggeprogram til børn i alle aldre
Comment[de]=Ein einfaches Aufbauspiel für Kinder und Erwachsene
Comment[el]=Ένα απλό παιχνίδι κατασκευών κατάλληλο για παιδιά και μεγάλους
Comment[en_GB]=A simple constructor game suitable for children and adults alike
Comment[es]=Un sencillo juego de construcción adecuado para niños y para adultos
Comment[et]=Lihtne konstrueerimismäng, mis sobib nii lastele kui ka täiskasvanutele
Comment[eu]=Eraikitzeko joko erraz bat ume eta helduentzako egokia
Comment[fi]=Yksinkertainen rakennuspeli, joka sopii niin lapsille kuin aikuisille
Comment[fr]=Un jeu d'assemblage simple qui convient aussi bien aux enfants qu'aux adultes
Comment[gl]=Un construtor de xogos sinxelo axeitado tanto para nenos como para adultos.
Comment[hu]=Egyszerű építőjátéknak gyerekeknek és felnőtteknek egyaránt
Comment[id]=Sebuah permainan konstruktor yang sederhana cocok untuk anak-anak dan dewasa juga
Comment[it]=Un semplice gioco di costruzioni adatto sia ai bambini, sia agli adulti
Comment[ko]=어린이와 어른 모두가 좋아하는 그림 그리기 게임
Comment[nl]=Een eenvoudig aannemerspel geschikt voor zowel kinderen als volwassenen
Comment[nn]=Eit enkelt biletbyggjespel for både store og små
Comment[pl]=Prosta gra twórcza kierowana dla dzieci i dorosłych
Comment[pt]=Um jogo de construção simples, adequado tanto para crianças como adultos
Comment[pt_BR]=Um jogo de construção simples, adequado para crianças e adultos
Comment[ru]=Игра-конструктор для детей, а также взрослых, впадающих в детство
Comment[sk]=Jednoduchá výstavbová hra vhodná pre deti a dospelých
Comment[sl]=Preprosta igra sestavljanja primerna za mlajše in starejše otroke
Comment[sr]=Једноставна игра конструисања погодна и за децу и за одрасле
Comment[sr@ijekavian]=Једноставна игра конструисања погодна и за децу и за одрасле
Comment[sr@ijekavianlatin]=Jednostavna igra konstruisanja pogodna i za decu i za odrasle
Comment[sr@latin]=Jednostavna igra konstruisanja pogodna i za decu i za odrasle
Comment[sv]=Ett enkelt byggspel lika lämpligt för barn som vuxna
Comment[tr]=Çocukların ve yetişkinlerin hoşlanacağı basit bir inşaat oyunu
Comment[uk]=Проста гра-складанка для дітей та дорослих.
Comment[x-test]=xxA simple constructor game suitable for children and adults alikexx
Comment[zh_CN]=一个简单的建造游戏，适合儿童和成人
Comment[zh_TW]=適合小孩與童心未泯的大人們的簡單遊戲
Type=Application
X-DocPath=ktuberling/index.html
Terminal=false
Icon=/opt/$APP/$APP.svg
MimeType=application/x-tuberling;
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;KidsGame;
X-DBUS-ServiceName=org.kde.ktuberling" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
