#!/bin/sh

APP=picmi

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=picmi
Name[bs]=picmi
Name[ca]=picmi
Name[ca@valencia]=picmi
Name[cs]=picmi
Name[da]=picmi
Name[de]=picmi
Name[el]=picmi
Name[en_GB]=picmi
Name[es]=picmi
Name[et]=picmi
Name[eu]=picmi
Name[fi]=picmi
Name[fr]=picmi
Name[ga]=picmi
Name[gl]=picmi
Name[hi]=picmi
Name[hu]=picmi
Name[it]=picmi
Name[kk]=picmi
Name[ko]=picmi
Name[lv]=picmi
Name[mr]=पिक्मि
Name[nb]=picmi
Name[nds]=Picmi
Name[nl]=picmi
Name[nn]=picmi
Name[pl]=picmi
Name[pt]=picmi
Name[pt_BR]=picmi
Name[ro]=picmi
Name[ru]=picmi
Name[sk]=picmi
Name[sl]=picmi
Name[sr]=Пикми
Name[sr@ijekavian]=Пикми
Name[sr@ijekavianlatin]=Picmi
Name[sr@latin]=Picmi
Name[sv]=picmi
Name[tr]=picmi
Name[uk]=picmi
Name[x-test]=xxpicmixx
Name[zh_CN]=picmi
Name[zh_TW]=picmi
GenericName=Logic Game
GenericName[bs]=Logička igra
GenericName[ca]=Joc de lògica
GenericName[ca@valencia]=Joc de lògica
GenericName[cs]=Logická hra
GenericName[da]=Logikspil
GenericName[de]=Logikspiel
GenericName[el]=Παιχνίδι λογικής
GenericName[en_GB]=Logic Game
GenericName[es]=Un juego de lógica
GenericName[et]=Loogikamäng
GenericName[eu]=Logika jokoa
GenericName[fi]=Logiikkapeli
GenericName[fr]=Jeu de logique
GenericName[ga]=Cluiche Loighce
GenericName[gl]=Xogo de lóxica
GenericName[hi]=तर्क खेल
GenericName[hu]=Logikai játék
GenericName[it]=Gioco di logica
GenericName[kk]=Логикалық ойын
GenericName[ko]=논리 게임
GenericName[lv]=Loģikas spēle
GenericName[mr]=तर्क खेळ
GenericName[nb]=Logikkspill
GenericName[nds]=Logikspeel
GenericName[nl]=Logisch spel
GenericName[nn]=Hjernetrim
GenericName[pl]=Gra logiczna
GenericName[pt]=Jogo de Lógica
GenericName[pt_BR]=Jogo de lógica
GenericName[ro]=Joc de logică
GenericName[ru]=Логическая игра
GenericName[sk]=Logická hra
GenericName[sl]=Logična igra
GenericName[sr]=Логичка игра
GenericName[sr@ijekavian]=Логичка игра
GenericName[sr@ijekavianlatin]=Logička igra
GenericName[sr@latin]=Logička igra
GenericName[sv]=Logikspel
GenericName[tr]=Mantık Oyunu
GenericName[ug]=لوگىكىلىق ئويۇن
GenericName[uk]=Гра на логіку
GenericName[x-test]=xxLogic Gamexx
GenericName[zh_CN]=逻辑游戏
GenericName[zh_TW]=智力遊戲
Comment=A number logic game
Comment[bs]=Logička igra s brojevima
Comment[ca]=Un joc de lògica de nombres
Comment[ca@valencia]=Un joc de lògica de nombres
Comment[cs]=Logická hra s čísly
Comment[da]=Et spil med tallogik
Comment[de]=Ein Logikspiel mit Zahlen
Comment[el]=Παιχνίδι λογικής με αριθμούς
Comment[en_GB]=A number logic game
Comment[es]=Un juego de lógica con números
Comment[et]=Arvuloogikamäng
Comment[eu]=Zenbakizko logika joka
Comment[fi]=Lukulogiikkapeli
Comment[fr]=Un jeu de logique avec des chiffres
Comment[gl]=Un xogo de lóxica numérica.
Comment[hi]=अंको का तर्क खेल
Comment[hu]=Egy számos logikai játék
Comment[it]=Un gioco di logica con i numeri
Comment[kk]=Сандық логика ойны
Comment[ko]=숫자 논리 게임
Comment[lv]=Skaitļu loģikas spēle
Comment[mr]=संख्या तर्क खेळ
Comment[nb]=Et spill med tall-logikk
Comment[nds]=En Tallen-Logikspeel
Comment[nl]=Een logisch spel met nummers
Comment[nn]=Talbasert hjernetrim
Comment[pl]=Liczbowa gra logiczna
Comment[pt]=Um jogo lógico com números
Comment[pt_BR]=Jogo de lógica com números
Comment[ro]=Joc de logică cu numere
Comment[ru]=Логическая игра с числами
Comment[sk]=Číselná logická hra
Comment[sl]=Logična igra s številkami
Comment[sr]=Логичка игра с бројевима
Comment[sr@ijekavian]=Логичка игра с бројевима
Comment[sr@ijekavianlatin]=Logička igra s brojevima
Comment[sr@latin]=Logička igra s brojevima
Comment[sv]=Ett logikspel med siffror
Comment[tr]=Bir sayı mantığı oyunu
Comment[uk]=Гра з числами на логіку
Comment[x-test]=xxA number logic gamexx
Comment[zh_CN]=数字逻辑游戏
Comment[zh_TW]=數字邏輯遊戲
Exec=picmi
Icon=/opt/$APP/$APP.svg
Terminal=false
Type=Application
StartupNotify=true
Categories=Qt;KDE;Game;LogicGame;
X-DBUS-ServiceName=org.kde.picmi" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
