#!/bin/sh

APP=pkg2appimage

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP

rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/bin/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

  pkg2appimage is provided by https://github.com/AppImage/pkg2appimage

        this fork for the 32 bit architecture is providev by

          https://github.com/ivan-hc/pkg2appimage-32bit

"