#!/bin/sh

APP=supertuxkart

mkdir /opt/$APP
cd /opt/$APP

echo "#!/bin/sh
rm -R -f /opt/supertuxkart /usr/share/applications/supertuxkart.desktop /usr/share/pixmaps/supertuxkart.svg /usr/games/supertuxkart" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/supertuxkart/stk-code/releases/latest -O - | egrep '/.*/.*/.*linux-32bit.tar.xz' -o)

tar xf ./*.tar.xz
cd ..
mv ./tmp/SuperTuxKart-*-linux-32bit/* ./
rm -R ./tmp

ln -s /opt/$APP/run_game.sh /usr/games/$APP

rm -R -f /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=SuperTuxKart
Icon=supertuxkart
GenericName=A kart racing game
GenericName[da]=Et kart racerspil
GenericName[de]=Ein Kart-Rennspiel
GenericName[fr]=Un jeu de karting
GenericName[gl]=Xogo de carreiras con karts
GenericName[pl]=Wyścigi gokartów
GenericName[ro]=Un joc de curse cu carturi
Exec=supertuxkart
Terminal=false
StartupNotify=false
Type=Application
Categories=Game;ArcadeGame;
Keywords=tux;game;race;" >> /usr/share/applications/$APP.desktop

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg
mv ./$APP.svg /usr/share/pixmaps/

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "";
echo "   SuperTuxKart has been installed!";
echo "";
