#!/bin/sh

APP=windows2usb
APPNAME=windows2usb
USER=ValdikSS
REPO=windows2usb
URL=https://github.com/$USER/$REPO/releases/latest
COMMENT=$(curl https://api.github.com/repos/$USER/$REPO  2>/dev/null | grep description | sed 's/"description": "//' | sed 's/",//')

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

version=$(curl -Ls https://api.github.com/repos/$USER/$REPO/releases/latest | jq '.' | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/$USER/$REPO/releases/download/$version/windows2usb-$version-i686.AppImage
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=windows2usb
version0=$(cat /opt/$APP/version)
url=https://github.com/FUNCTION1/FUNCTION2/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  URL=https://github.com/FUNCTION1/FUNCTION2/releases/latest
  version=$(curl -Ls https://api.github.com/repos/FUNCTION1/FUNCTION2/releases/latest | jq '.' | grep -E tag_name | awk -F '[""]' '{print $4}')
  wget https://github.com/FUNCTION1/FUNCTION2/releases/download/$version/windows2usb-$version-i686.AppImage
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo $version >> ./version
  mv --backup=t ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
fi
EOF
sed -i s/FUNCTION1/$USER/g /opt/$APP/AM-updater
sed -i s/FUNCTION2/$REPO/g /opt/$APP/AM-updater
sed -i s/FUNCTION3/$FILENAMEBEGIN/g /opt/$APP/AM-updater
sed -i s/FUNCTION4/$FILENAMEEXTENTION/g /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo '

 '$APPNAME' is provided by https://github.com/'$USER'/'$REPO'

'
