#!/bin/sh

APP=SAMPLE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

WGET-THE-PROGRAM-OR-THE-APPIMAGE

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
# THIS IS JUST AN EXAMPLE ON HOW TO COMPARE THE VERSION WITH THE ONE WROTE IN THE SOURCE
# THIS IS FOR CHROMIUM WEB BROWSER FROM THE SLAKWARE'S REPOSITORY, FOR YOUR APPLICATION MAY BE DIFFERENT
echo '#!/bin/sh
version=$(exec /opt/chromium/chromium --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
url="http://www.slackware.com/~alien/slackbuilds/chromium/pkg64/current/chromium-$version-x86_64-1alien.txz"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
  exec /opt/chromium/chromium
else
  mkdir /opt/chromium/tmp
  cd /opt/chromium/tmp
  wget -r -erobots=off -l1 -np -A chromium-*-x86_64-1alien.txz -nd http://www.slackware.com/~alien/slackbuilds/chromium/pkg64/current/
  tar xf ./*.txz
  cd ..
  mv ./tmp/usr/lib64/chromium/* ./
  rm -R -f ./tmp
  exec /opt/chromium/chromium
fi' >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "LAUNCHER" >> /usr/share/applications/$APP.desktop

# ICON
WGET-THE-ICON

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
	
"
