#!/usr/bin/env bash

for name in "firefox"
do
  [[ $(which $name 2>/dev/null) ]] || { echo "" && echo -e 'ERROR: "'$name'" not found in $PATH, exiting.';deps=1; }
done
[[ $deps -ne 1 ]] || { echo -e "\nInstall the above and try again\n";exit 1; }

APP=SAMPLE-webapp
APPNAME="GIVEMEANAME"
ICONURL="YOURICONURL"

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# LINK
cat >> /usr/local/bin/$APP << 'EOF'
#!/bin/sh
sh -c 'XAPP_FORCE_GTKWINDOW_ICON=/opt/SAMPLE-webapp/icons/SAMPLE-webapp firefox --class WebApp-SAMPLE --profile /opt/SAMPLE-webapp --no-remote -url 'MYWEBSITE''
EOF
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=$APPNAME
Exec=$APP
Icon=/opt/$APP/icons/$APP
Type=Application
Terminal=false
Categories=YOURCATEGORY;
Comment=Web Application based on Firefox" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir /opt/$APP/icons
wget $ICONURL -O /opt/$APP/icons/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 WebApp for MYWEBSITE
 
"
