#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=SAMPLE
SITE="REPLACETHIS"; GHRC_REF="ITEM"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
#printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(FUNCTION)
curl -Ls "https://raw.githubusercontent.com/ivan-hc/AM/main/tools/ghcr_dl.sh" | sh -s -- "$GHRC_REF" "$APP" || exit 1



cd ..
mv ./tmp/* ./
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./$APP || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=SAMPLE
SITE="REPLACETHIS"; GHRC_REF="ITEM"
version0=$(cat "/opt/$APP/version")
version=$(FUNCTION)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	curl -Ls "https://raw.githubusercontent.com/ivan-hc/AM/main/tools/ghcr_dl.sh" | sh -s -- "$GHRC_REF" "$APP" || exit 1
	cd ..
	mv --backup=t ./tmp/* ./
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1
