#!/bin/sh

APP=SAMPLE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

WGET-THE-APPIMAGE

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP

cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
chmod a+x ./updater

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE
echo '#!/bin/sh
APP='$APP'
cd /opt/$APP
./updater -O ./$APP
chmod a+x /opt/$APP/$APP
rm -R -f /opt/$APP/*zs-old && rm -R -f /opt/$APP/*.part' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER & ICON
cd /opt/$APP
./$APP --appimage-extract *.desktop
mv squashfs-root/*.desktop ./$APP.desktop
if desktop-file-validate --no-hints ./$APP.desktop | grep error; then 
	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$APP*.desktop 
	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
fi
if cat ./$APP.desktop | grep Exec | grep AppRun; then sed -i "s#AppRun#$APP#g" ./$APP.desktop; fi
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$APP*.desktop 
	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
fi
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract share/applications/*$APP*.desktop 
	mv squashfs-root/share/applications/*.desktop ./$APP.desktop
fi
CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $APP | head -1)
sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | grep $APP | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop

mkdir icons
mv $(./$APP --appimage-extract *.png) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract *.svg) ./icons/$APP 2>/dev/null
./$APP --appimage-extract share/icons/*/*/*/*
./$APP --appimage-extract usr/share/icons/*/*/*/*
cp ./squashfs-root/share/icons/hicolor/22x22/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/24x24/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/32x32/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/48x48/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/64x64/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/128x128/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/256x256/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/512x512/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/share/icons/hicolor/scalable/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/22x22/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/24x24/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/32x32/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/48x48/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/64x64/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/128x128/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/256x256/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/512x512/apps/*$APP* ./icons/$APP 2>/dev/null
cp ./squashfs-root/usr/share/icons/hicolor/scalable/apps/*$APP* ./icons/$APP 2>/dev/null

rm -R -f /opt/$APP/squashfs-root
mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

	MESSAGE

"
