#!/bin/sh

APP=SAMPLE
URL=APPIMAGE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp;
cd ./tmp;
wget $URL;
wget $URL.asc;
wget $URL.zsync;
wget $URL.zsync.asc;
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*mage.zsync ./$APP.zsync
#mv ./tmp/*mage.asc ./$APP.asc
#mv ./tmp/*zsync.asc ./$APP.zsync.asc
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "cd /opt/$APP
mkdir tmp
cd ./tmp
wget $URL.asc;
wget $URL.zsync;
wget $URL.zsync.asc
cd ..
mv ./tmp/*mage.zsync ./$APP.zsync
#mv ./tmp/*mage.asc ./$APP.asc
#mv ./tmp/*zsync.asc ./$APP.zsync.asc
rmdir ./tmp
zsync /opt/$APP/$APP.zsync
rm -R -f /opt/$APP/*zs-old /opt/$APP/*.part
chmod a+x /opt/$APP/$APP" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER & ICON
cd /opt/$APP
mv $(./$APP --appimage-extract *.desktop) ./$APP.desktop
if [ ! -e ./$APP.desktop ]; then rm ./$APP.desktop; mv $(/opt/$APP/$APP --appimage-extract usr/share/applications/*.desktop) ./$APP.desktop; fi
if [ ! -e ./$APP.desktop ]; then rm ./$APP.desktop; mv $(/opt/$APP/$APP --appimage-extract share/applications/*.desktop) ./$APP.desktop; fi
if cat ./$APP.desktop | grep Exec | grep AppRun; then rm ./$APP.desktop; mv $(./$APP --appimage-extract usr/share/applications/*$APP*.desktop) ./$APP.desktop; fi
CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $APP | head -1)
sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | grep $APP | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop

mkdir icons
mv $(./$APP --appimage-extract *.png) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract *.svg) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/22x22/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/24x24/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/32x32/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/48x48/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/64x64/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/128x128/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/256x256/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/512x512/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract share/icons/hicolor/scalable/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/22x22/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/24x24/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/32x32/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/48x48/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/64x64/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/128x128/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/256x256/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/512x512/apps/*$APP*) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract usr/share/icons/hicolor/scalable/apps/*$APP*) ./icons/$APP 2>/dev/null

rm -R -f /opt/$APP/squashfs-root
mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

	MESSAGE
	
"
