#!/bin/sh

APP=SAMPLE
URL=APPIMAGE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp;
cd ./tmp;
wget $URL;
wget $URL.asc;
wget $URL.zsync;
wget $URL.zsync.asc;
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*mage.zsync ./$APP.zsync
mv ./tmp/*mage.asc ./$APP.asc
mv ./tmp/*zsync.asc ./$APP.zsync.asc
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "cd /opt/$APP
mkdir tmp
cd ./tmp
wget $URL.asc;
wget $URL.zsync;
wget $URL.zsync.asc
cd ..
mv ./tmp/*mage.zsync ./$APP.zsync
mv ./tmp/*mage.asc ./$APP.asc
mv ./tmp/*zsync.asc ./$APP.zsync.asc
rmdir ./tmp
zsync /opt/$APP/$APP.zsync && rm -R -f /opt/$APP/*zs-old /opt/$APP/*.part
chmod a+x /opt/$APP/$APP" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "LAUNCHER" >> /usr/share/applications/AM-$APP.desktop

# ICON
WGET

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

	MESSAGE
	
"
