#!/bin/sh

APP=SAMPLE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

WGET-THE-APPIMAGE

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP

echo "cd /opt/$APP
appimageupdate -O $APP
rm *zs-old" >> /usr/local/bin/$APP
echo 'case "$1" in' >> /usr/local/bin/$APP

symbol='"$@"'

echo "  'wine') exec /opt/$APP/$APP ;;
  *) exec /opt/$APP/$APP $symbol ;;
esac" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "LAUNCHER" >> /usr/share/applications/$APP.desktop

# ICON
WGET-THE-ICON

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
	YOUR-MESSAGE
"
