#!/bin/sh

APP=SAMPLE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

WGET-THE-PROGRAM-OR-THE-APPIMAGE

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
# THIS IS JUST AN EXAMPLE ON HOW TO COMPARE THE VERSION WITH THE ONE WROTE ON THE MAIN PAGE OF THE WEBSITE
# THIS IS FOR THE APPIMAGE VERSION OF KDENLIVE VIDEO EDITOR, FOR YOUR APPLICATION MAY BE DIFFERENT
echo '#!/bin/sh
version=$(exec /opt/kdenlive/kdenlive --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
if curl -L -s https://kdenlive.org/en/download/ | grep -ioF "AppImage $version"; then
  echo "Update not needed, exit!"
  exec /opt/kdenlive/kdenlive
else
  mkdir /opt/kdenlive/tmp
  cd /opt/kdenlive/tmp' >> /usr/local/bin/$APP

echo '  wget https://download.kde.org/$(wget https://kdenlive.org/en/download/ -O - | grep "/stable/kdenlive/.*/linux/.*appimage" -o)' >> /usr/local/bin/$APP

echo '  cd ..
  mv ./tmp/*mage ./kdenlive
  chmod a+x /opt/kdenlive/kdenlive
  rmdir ./tmp
  exec /opt/kdenlive/kdenlive
fi' >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "LAUNCHER" >> /usr/share/applications/$APP.desktop

# ICON
WGET-THE-ICON

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
	
"
