#!/bin/sh

APP=SAMPLE

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

WGET-THE-APPIMAGE
WGET-THE-ZSYNC

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*zsync ./$APP.zsync
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "cd /opt/$APP " >> /usr/local/bin/$APP

echo "WGET-THE-ZSYNC" >> /usr/local/bin/$APP

echo "mv ./*AppImage.zsync ./$APP.zsync
zsync /opt/$APP/$APP.zsync && rm -R -f /opt/$APP/*zs-old
chmod a+x /opt/$APP/$APP
exec /opt/$APP/$APP" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "LAUNCHER" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
	
"
