#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=SAMPLE
SITE="REPLACETHIS"; ARGUMENT="ITEM"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" && export DBIN_INSTALL_DIR="$PWD" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
#printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(FUNCTION)
if command -v dbin >/dev/null 2>&1; then dbin install "$ARGUMENT" 2>/dev/null || exit 1
else curl -Ls "https://raw.githubusercontent.com/xplshn/dbin/master/stubdl" | sh -s -- install "$ARGUMENT" 2>/dev/null || exit 1
fi
cd ..
mv ./tmp/* ./"$APP"

rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./$APP || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=SAMPLE
SITE="REPLACETHIS"; ARGUMENT="ITEM"
version0=$(cat "/opt/$APP/version")
version=$(FUNCTION)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" && export DBIN_INSTALL_DIR="$PWD" || exit 1
	notify-send "A new version of $APP is available, please wait"
	if command -v dbin >/dev/null 2>&1; then dbin install "$ARGUMENT" 2>/dev/null || exit 1
	else curl -Ls "https://raw.githubusercontent.com/xplshn/dbin/master/stubdl" | sh -s -- install "$ARGUMENT" 2>/dev/null || exit 1
	fi
	cd ..
	mv --backup=t ./tmp/* ./"$APP"
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1
