#!/usr/bin/env bash

# this url must point to an online directory containing the installation scripts (for the -i and -d options)
APPSDB="$AMREPO/programs/$arch"

# this url must point to an online $arch-apps file (for example "x86_64-apps", "$arch" is the architecture name)
# this is the list of all available programs (for the -l, -q and -s options)
APPSLISTDB="$AMREPO/programs/$arch-apps"

# this url is the main page of the catalog you want to use
AMCATALOGUE="https://PORTABLE-LINUX-APPS.GITHUB.IO"

# this url points to an online directory containing .md files containing the application description (for the -a option)
AMCATALOGUEMARKDOWNS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/apps"

# uncomment the following line to disable the "Source: ..." message about using a third-party repository
#NEODBFLAG=nowarn
