#!/usr/bin/env bash

# This script is an example of how you can use third-party databases instead of the one used in AM/AppMan, without having to change the CLI repository.
# It should be placed in $AMPATH (for "AM" it is always /opt/am, for it is the "appman" folder located in the path chosen to install the applications).
# The purpose of each assigned value is explained on each variable.
# ------------------------------------------------------
# this url must point to an online directory containing the installation scripts (for the -i and -d options)
#
# SYNTAX: https://yoursite.org/path/to/directory
#
# NAME OF THE FILE THAT WILL BE MANAGED AS AN ARGUMENT BY THE MODULES: "$arg"
APPSDB="$AMREPO/programs/$arch"

# ------------------------------------------------------
# this url must point to an online $arch-apps file (for example "x86_64-apps", "$arch" is the architecture name)
# this is the list of all available programs (for the -l, -q and -s options)
#
# SYNTAX: https://yoursite.org/path/to/file/named/x86_64-apps
#
# NAME OF THE FILE THAT WILL BE MANAGED AS AN ARGUMENT BY THE MODULES: it's already in the url, it's "$arch-apps"
APPSLISTDB="$AMREPO/programs/$arch-apps"

# ------------------------------------------------------
# this url is the main page of the catalog you want to use
#
# SYNTAX: https://yoursite.org
#
# NAME OF THE FILE THAT WILL BE MANAGED AS AN ARGUMENT BY THE MODULES: none
AMCATALOGUE="https://PORTABLE-LINUX-APPS.GITHUB.IO"

# ------------------------------------------------------
# this url points to an online directory containing .md files containing the application description (for the -a option)
#
# SYNTAX: https://yoursite.org/path/to/markdown/files/
#
# NAME OF THE FILE THAT WILL BE MANAGED AS AN ARGUMENT BY THE MODULES: "$arg.md"
AMCATALOGUEMARKDOWNS="https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/apps"

# ------------------------------------------------------
# uncomment the following line to disable the "Source: ..." message about using a third-party repository
#NEODBFLAG=nowarn
