#!/bin/sh

echo ""
echo " 0 A.D. is an epic game provided by https://play0ad.com"
echo ""
echo ' "AM" provides two different versions built from Debian Unstable:'
echo ""
echo " 1) '0ad-appimage', this is compressed and takes at least 1.7 GB of disk space"
echo ""
echo " 2) '0ad-bundle', this takes 3.5 GB, useful for debugging and mods"
echo ""
read -r -p " What do you choose between 1 and 2? " response
case "$response" in
    1) rm /opt/am/.cache/0ad && sudo am install 0ad-appimage;;
    2) rm /opt/am/.cache/0ad && sudo am install 0ad-bundle;;
    *) echo ""; echo " No valid argument was chosen: installation aborted! "; rm -f /opt/am/.cache/0ad; echo "";;
esac