#!/bin/sh

APP=altus

mkdir /opt/$APP
cd /opt/$APP

echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp
cd ./tmp
download=$(wget -q https://api.github.com/repos/amanharwara/altus/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | egrep '/.*/.*/.*AppImage' | head -1)
wget $download
download=$(wget -q https://api.github.com/repos/amanharwara/altus/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | egrep '/.*/.*/.*AppImage.zsync' | head -1)
wget $download
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*zsync ./$APP.zsync
rmdir ./tmp
# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo 'cd /opt/altus
download=$(wget -q https://api.github.com/repos/amanharwara/altus/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | egrep "/.*/.*/.*AppImage.zsync"-o | head -1)
wget $download
mv ./*AppImage.zsync ./altus.zsync
zsync /opt/altus/altus.zsync && rm -R -f /opt/altus/*zs-old
chmod a+x /opt/altus/altus' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=Altus
Exec=altus
Terminal=false
Type=Application
Icon=/opt/altus/altus.svg
StartupWMClass=Altus
StartupNotify=true
Comment=Desktop client for WhatsApp Web with themes & multiple account support.
MimeType=x-scheme-handler/whatsapp;
Categories=Chat;Network;" >> /usr/share/applications/AM-$APP.desktop

wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP
# MESSAGE
echo ""
echo " Altus WhatsApp Web Client is provided by";
echo "";
echo "   https://github.com/amanharwara/altus";
echo ""
