#!/bin/sh

APP=altus

mkdir /opt/$APP
cd /opt/$APP

echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp
cd ./tmp
wget https://github.com/$(wget https://github.com/amanharwara/altus/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)
wget https://github.com/$(wget https://github.com/amanharwara/altus/releases/latest -O - | egrep '/.*/.*/.*AppImage.zsync' -o)
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*zsync ./$APP.zsync
rmdir ./tmp

echo '#!/bin/sh' >> /usr/local/bin/$APP
echo 'cd /opt/altus
wget https://github.com/$(wget https://github.com/amanharwara/altus/releases/latest -O - | egrep "/.*/.*/.*AppImage.zsync" -o)
mv ./*AppImage.zsync ./altus.zsync
zsync /opt/altus/altus.zsync && rm -R -f /opt/altus/*zs-old
chmod a+x /opt/altus/altus
exec /opt/altus/altus --no-sandbox %U' >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=Altus
Exec=altus
Terminal=false
Type=Application
Icon=/opt/altus/altus.svg
StartupWMClass=Altus
StartupNotify=true
Comment=Desktop client for WhatsApp Web with themes & multiple account support.
MimeType=x-scheme-handler/whatsapp;
Categories=Chat;Network;" >> /usr/share/applications/$APP.desktop

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo ""
echo " Altus WhatsApp Web Client is provided by";
echo "";
echo "   https://github.com/amanharwara/altus";
echo ""
