#!/bin/sh

APP=amusiz

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/mirkobrombin/Amusiz/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)
wget https://github.com/$(wget https://github.com/mirkobrombin/Amusiz/releases/latest -O - | egrep '/.*/.*/.*AppImage.zsync' -o)

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*zsync ./$APP.zsync
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "cd /opt/$APP " >> /opt/$APP/AM-updater

echo 'wget https://github.com/$(wget https://github.com/mirkobrombin/Amusiz/releases/latest -O - | egrep "/.*/.*/.*AppImage.zsync" -o)' >> /opt/$APP/AM-updater

echo "mv ./*AppImage.zsync ./$APP.zsync
zsync /opt/$APP/$APP.zsync && rm -R -f /opt/$APP/*zs-old
chmod a+x /opt/$APP/$APP" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=Amusiz
Exec=amusiz
Comment=An unofficial and unpretentious Amazon Music client for Linux.
Icon=/opt/amusiz/amusiz.svg
Type=Application
Categories=Audio;" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
	Amusiz is provided by https://github.com/mirkobrombin/Amusiz
"
