#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=antigravity
SITE="https://antigravity.google"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop /usr/local/share/applications/$APP-url-handler-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://raw.githubusercontent.com/BOTOOM/google-antigravity-bin-arch/main/package/PKGBUILD | grep -oP 'https://[^"]+\.deb' | head -1)
download="$version"
wget "$download" || exit 1
# Add custom AppRun here
# Add custom launcher here
# Add custom icon here
curl -Ls "https://raw.githubusercontent.com/ivan-hc/portable2appimage/refs/heads/main/portable2appimage" | sh -s -- ./* "$APP" || exit 1
cd .. && mv ./tmp/*mage ./"$APP" && rm -R -f ./tmp || exit 1; rm -f AppRun *.desktop *.png *.svg *.xpm
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=antigravity
SITE="https://antigravity.google"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://raw.githubusercontent.com/BOTOOM/google-antigravity-bin-arch/main/package/PKGBUILD | grep -oP 'https://[^"]+\.deb' | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	download="$version"
	wget "$download" || exit 1
	# Add custom AppRun here
	# Add custom launcher here
	# Add custom icon here
	curl -Ls "https://raw.githubusercontent.com/ivan-hc/portable2appimage/refs/heads/main/portable2appimage" | sh -s -- ./* "$APP" || exit 1
	cd .. && mv --backup=t ./tmp/*mage ./"$APP" && chmod a+x ./"$APP" || exit 1; rm -f AppRun *.desktop *.png *.svg *.xpm
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHER & ICON
./"$APP" --appimage-extract usr/share/applications/*.desktop 1>/dev/null
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./DirIcon ]; then
		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
desktop_main=$(find ./squashfs-root -name "$APP.desktop" | head -1)
desktop_url=$(grep -rl "NoDisplay=true" ./squashfs-root --include="*.desktop" | head -1)
if [ -n "$desktop_main" ]; then
	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" "$desktop_main"
	cp "$desktop_main" /usr/local/share/applications/"$APP"-AM.desktop
fi
if [ -n "$desktop_url" ]; then
	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" "$desktop_url"
	cp "$desktop_url" /usr/local/share/applications/"$APP"-url-handler-AM.desktop
fi
mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root
