#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=antigravity
SITE="https://antigravity.google"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop /usr/local/share/applications/$APP-url-handler-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://raw.githubusercontent.com/BOTOOM/google-antigravity-bin-arch/main/package/PKGBUILD | grep -Eoi "http.*tar.gz" | head -1)
download="$version"
wget "$download" || exit 1
# Add custom AppRun here
curl -Ls "https://raw.githubusercontent.com/ivan-hc/portable2appimage/refs/heads/main/portable2appimage" | sh -s -- ./* "$APP-ide" || exit 1
cd .. && mv ./tmp/*mage ./"$APP" && rm -R -f ./tmp || exit 1; rm -f AppRun *.desktop *.png *.svg *.xpm
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=antigravity
SITE="https://antigravity.google"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://raw.githubusercontent.com/BOTOOM/google-antigravity-bin-arch/main/package/PKGBUILD | grep -Eoi "http.*tar.gz" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	download="$version"
	wget "$download" || exit 1
	# Add custom AppRun here
	curl -s -Lo ../"$APP".png "https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/icons/antigravity.png" || exit 1
	curl -Ls "https://raw.githubusercontent.com/ivan-hc/portable2appimage/refs/heads/main/portable2appimage" | sh -s -- ./* "$APP-ide" || exit 1
	cd .. && mv --backup=t ./tmp/*mage ./"$APP" && chmod a+x ./"$APP" || exit 1; rm -f AppRun *.desktop *.png *.svg *.xpm
	curl -s -Lo /usr/local/share/applications/"$APP"-AM.desktop "https://raw.githubusercontent.com/archlinux/aur/refs/heads/antigravity-ide/antigravity-ide.desktop" || exit 1
	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" /usr/local/share/applications/"$APP"-AM.desktop
	curl -s -Lo /usr/local/share/applications/"$APP"-url-handler-AM.desktop "https://raw.githubusercontent.com/archlinux/aur/refs/heads/antigravity-ide/antigravity-ide-url-handler.desktop" || exit 1
	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" /usr/local/share/applications/"$APP"-url-handler-AM.desktop
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHER & ICON
curl -s -Lo ./icons/"$APP" "https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/icons/antigravity.png" || exit 1
curl -s -Lo /usr/local/share/applications/"$APP"-AM.desktop "https://raw.githubusercontent.com/archlinux/aur/refs/heads/antigravity-ide/antigravity-ide.desktop" || exit 1
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" /usr/local/share/applications/"$APP"-AM.desktop
curl -s -Lo /usr/local/share/applications/"$APP"-url-handler-AM.desktop "https://raw.githubusercontent.com/archlinux/aur/refs/heads/antigravity-ide/antigravity-ide-url-handler.desktop" || exit 1
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" /usr/local/share/applications/"$APP"-url-handler-AM.desktop
