#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=antigravity
SITE="BOTOOM/google-antigravity-bin-arch"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://raw.githubusercontent.com/BOTOOM/google-antigravity-bin-arch/main/package/PKGBUILD | grep -oP 'https://[^"]+\.deb' | head -1)
wget "$version" -O antigravity.deb || exit 1
[ -e ./*deb ] && ar x ./*deb && tar fx ./data.tar.* && rm -f ./*tar* ./*deb
cd ..
mv ./tmp/usr/share/antigravity/* ./
cp ./resources/app/resources/linux/code.png ./icons/"$APP".png 2>/dev/null
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1
chmod 4755 ./chrome-sandbox 2>/dev/null || true

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=antigravity
SITE="BOTOOM/google-antigravity-bin-arch"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://raw.githubusercontent.com/BOTOOM/google-antigravity-bin-arch/main/package/PKGBUILD | grep -oP 'https://[^"]+\.deb' | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" -O antigravity.deb || exit 1
	[ -e ./*deb ] && ar x ./*deb && tar fx ./data.tar.* && rm -f ./*tar* ./*deb
	cd ..
	mv --backup=t ./tmp/usr/share/antigravity/* ./
	chmod a+x ./"$APP" || exit 1
	chmod 4755 ./chrome-sandbox 2>/dev/null || true
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHER
echo "[Desktop Entry]
Name=Antigravity
Exec=$APP
Icon=/opt/$APP/icons/$APP.png
Terminal=false
Type=Application
Comment=Google Antigravity IDE.
Categories=Development;" > /usr/local/share/applications/"$APP"-AM.desktop
