#!/bin/sh

APP=anydesk

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/anydesk/Anydesk.yml;
sed -i s/bullseye/unstable/g ./Anydesk.yml

./pkg2appimage ./Anydesk.yml;

ARCH=x86_64 ./appimagetool -n ./AnyDesk/AnyDesk.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
version=$(exec /opt/'$APP'/'$APP' --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
url="https://anydesk.com/en/downloads/linux"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
 else
  notify-send "A new version of '$APP' is available, please wait!"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimagetool/appimagetool
  wget https://github.com/ivan-hc/AppMan/raw/main/applications/pkg2appimage/pkg2appimage
  chmod a+x ./appimagetool ./pkg2appimage
  wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/anydesk/Anydesk.yml
  sed -i s/bullseye/unstable/g ./Anydesk.yml
  ./pkg2appimage ./Anydesk.yml
  ARCH=x86_64 ./appimagetool -n -n ./AnyDesk/AnyDesk.AppDir
  cd ..
  mv ./tmp/*.AppImage ./'$APP'
  chmod a+x ./'$APP'
  rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Type=Application
Name=AnyDesk
GenericName=AnyDesk
X-GNOME-FullName=AnyDesk
Exec=anydesk %u
Icon=/opt/$APP/$APP.svg
Terminal=false
Categories=Network;GTK;
MimeType=x-scheme-handler/anydesk;
Name[de_DE]=AnyDesk" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 Anydesk (unofficial AppImage) is provided by https://anydesk.com
  
";
