#!/bin/sh

APP=aphelion-wallet

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/aphtoken/aph-wallet-gui/releases/download/4.1.0/Aphelion_Wallet-4.1.0-lin.AppImage;

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=Aphelion Desktop Wallet
Exec=aphelion-wallet
Comment=The Aphelion desktop wallet application built with Electron
Icon=/opt/$APP/$APP.svg
Type=Application
Categories=Utility;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
   Aphelion Desktop Wallet is provided by https://github.com/aphtoken        
"
