#!/bin/sh

# CREATE THE FOLDER
mkdir /opt/appimagetool
cd /opt/appimagetool

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/appimagetool/remove
echo "rm -R -f /opt/appimagetool /usr/bin/appimagetool" >> /opt/appimagetool/remove
chmod a+x /opt/appimagetool/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
cd ..
mv ./tmp/*mage ./appimagetool
chmod a+x /opt/appimagetool/appimagetool

cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
chmod a+x ./updater

rmdir ./tmp

# LINK
ln -s /opt/appimagetool/appimagetool /usr/bin/appimagetool

# SCRIPT TO UPDATE THE PROGRAM

echo '#!/bin/sh' >> /opt/appimagetool/AM-updater
echo "APP=appimagetool" >> /opt/appimagetool/AM-updater
echo 'cd /opt/appimagetool
./updater -O ./appimagetool
chmod a+x /opt/appimagetool/appimagetool
rm -R -f /opt/appimagetool/*zs-old && rm -R -f /opt/appimagetool/*.part' >> /opt/appimagetool/AM-updater
chmod a+x /opt/appimagetool/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimagetool

# MESSAGE
echo "

 AppImageTool is provided by https://github.com/AppImage/AppImageKit

"

# CREATE THE FOLDER
mkdir /opt/appimageupdate
cd /opt/appimageupdate

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/appimageupdate/remove
echo "rm -R -f /opt/appimageupdate /usr/bin/appimageupdate" >> /opt/appimageupdate/remove
chmod a+x /opt/appimageupdate/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/*mage ./appimageupdate
chmod a+x /opt/appimageupdate/appimageupdate
rmdir ./tmp

# LINK
ln -s /opt/appimageupdate/appimageupdate /usr/bin/appimageupdate

# SCRIPT TO UPDATE THE PROGRAM

echo '#!/bin/sh' >> /opt/appimageupdate/AM-updater
echo "APP=appimageupdate" >> /opt/appimageupdate/AM-updater
echo 'cd /opt/appimageupdate
./appimageupdate -O ./appimageupdate
chmod a+x /opt/appimageupdate/appimageupdate
rm -R -f /opt/appimageupdate/*zs-old && rm -R -f /opt/appimageupdate/*.part' >> /opt/appimageupdate/AM-updater
chmod a+x /opt/appimageupdate/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimageupdate

# MESSAGE
echo "

         AppImageUpdate is provided by
         
    https://github.com/AppImage/AppImageUpdate

"

# CREATE THE FOLDER
mkdir /opt/pkg2appimage
cd /opt/pkg2appimage

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/pkg2appimage/remove
echo "rm -R -f /opt/pkg2appimage /usr/bin/pkg2appimage" >> /opt/pkg2appimage/remove
chmod a+x /opt/pkg2appimage/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous
cd ..
mv ./tmp/*mage ./pkg2appimage
chmod a+x /opt/pkg2appimage/pkg2appimage

cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
chmod a+x ./updater

rmdir ./tmp

# LINK
ln -s /opt/pkg2appimage/pkg2appimage /usr/bin/pkg2appimage

# SCRIPT TO UPDATE THE PROGRAM

echo '#!/bin/sh' >> /opt/pkg2appimage/AM-updater
echo "APP=pkg2appimage" >> /opt/pkg2appimage/AM-updater
echo 'cd /opt/pkg2appimage
./updater -O ./pkg2appimage
chmod a+x /opt/pkg2appimage/pkg2appimage
rm -R -f /opt/pkg2appimage/*zs-old && rm -R -f /opt/pkg2appimage/*.part' >> /opt/pkg2appimage/AM-updater
chmod a+x /opt/pkg2appimage/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/pkg2appimage

# MESSAGE
echo "

 pkg2appimage is provided by https://github.com/AppImage/pkg2appimage

"