#!/bin/sh

mkdir /opt/appimagetool
cd /opt/appimagetool

# Creating a script that removes all the files listed above
echo '#!/bin/sh
rm -R -f  /usr/bin/appimagetool /opt/appimagetool' >> /opt/appimagetool/remove
chmod a+x /opt/appimagetool/remove

mkdir tmp
cd tmp
wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
cd ..
mv ./tmp/*AppImage ./appimagetool
rmdir ./tmp
chmod a+x ./appimagetool

echo '#!/bin/sh
cd /opt/appimagetool
appimageupdate -O appimagetool
rm *zs-old
case "$1" in' >> /usr/bin/appimagetool
echo "  'appimagetool') exec /opt/appimagetool/appimagetool ;;" >> /usr/bin/appimagetool
echo '  *) exec /opt/appimagetool/appimagetool "$@" ;;
esac' >> /usr/bin/appimagetool
chmod a+x /usr/bin/appimagetool

# Changing privileges in /opt/appimagetool to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimagetool

# Message
echo ""
echo " AppImageTool has been installed!"
echo ""
