#!/bin/sh

APP=appimagedl

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
wget https://raw.githubusercontent.com/ivan-hc/appimagedl/master/appimagedl
chmod a+x /opt/$APP/$APP

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP




