#!/bin/sh

mkdir /opt/appimageupdate
cd /opt/appimageupdate

rm -R -f  /opt/appimageupdate/remove
echo '#!/bin/sh
rm -R -f  /usr/bin/appimageupdate /opt/appimageupdate' >> /opt/appimageupdate/remove
chmod a+x /opt/appimageupdate/remove

wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
mv ./appimageupdatetool-x86_64.AppImage ./appimageupdate
chmod a+x ./appimageupdate

ln -s /opt/appimageupdate/appimageupdate /usr/bin/appimageupdate

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimageupdate


echo "
      AppImageUpdate has been installed!

 SITE: https://github.com/AppImage/AppImageUpdate

"
