#!/bin/sh

APP=appimagepool

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp;
cd ./tmp;
v=$(wget -q https://api.github.com/repos/prateekmedia/appimagepool/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/prateekmedia/appimagepool/releases/download/$v/appimagepool-x86_64.AppImage
echo $v >> /opt/$APP/version
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*mage.zsync ./$APP.zsync
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat > /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=appimagepool
version=$(cat /opt/$APP/version)
url="https://github.com/prateekmedia/appimagepool/releases/download/$version/appimagepool-x86_64.AppImage"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
 else
  cd /opt/$APP
  mkdir tmp
  cd ./tmp
  v=$(wget -q https://api.github.com/repos/prateekmedia/appimagepool/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
  wget https://github.com/prateekmedia/appimagepool/releases/download/$v/appimagepool-x86_64.AppImage
  rm -R -f /opt/$APP/version
  echo $v >> /opt/$APP/version
  cd ..
  mv ./tmp/*mage ./
  rm -R -f ./tmp
  chmod a+x /opt/$APP/$APP
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=AppImage Pool
Icon=/opt/$APP/appimagepool.svg
Exec=appimagepool %u
StartupWMClass=appimagepool
Categories=Utility;
Keywords=AppImage;Store;AppImageHub;Flutter;Gtk;" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://raw.githubusercontent.com/prateekmedia/appimagepool/main/assets/appimagepool.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

       AppImage Pool is provided by

 https://github.com/prateekmedia/appimagepool
	
"
