#!/bin/sh

mkdir /opt/appimagetool
cd /opt/appimagetool

# Creating a script that removes all the files listed above
echo '#!/bin/sh
rm -R -f  /usr/bin/appimagetool /opt/appimagetool' >> /opt/appimagetool/remove
chmod a+x /opt/appimagetool/remove

mkdir tmp
cd tmp
wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimagetool/appimagetool
cd ..
mv ./tmp/* ./
rmdir ./tmp
chmod a+x ./appimagetool

ln -s /opt/appimagetool/appimagetool /usr/bin/appimagetool

# Changing privileges in /opt/appimagetool to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimagetool

# Message
echo ""
echo " AppImageTool has been installed!"
echo ""
