#!/bin/sh

mkdir /opt/appimageupdate
cd /opt/appimageupdate

# Creating a script that removes all the files listed above
rm -R -f  /opt/appimageupdate/remove
echo '#!/bin/sh
rm -R -f  /usr/bin/appimageupdate /opt/appimageupdate' >> /opt/appimageupdate/remove
chmod a+x /opt/appimageupdate/remove

wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
mv ./appimageupdatetool-x86_64.AppImage ./appimageupdate
chmod a+x ./appimageupdate

# Creating an /opt/bin/appimageupdate script that updates appimageupdate itself and all the AppImages that are using it
echo '#!/bin/sh
appimageupdate="/opt/appimageupdate/appimageupdate"
exec $appimageupdate -O $appimageupdate && rm /opt/appimageupdate/*zs-old
exec $appimageupdate -O %f' >> /usr/bin/appimageupdate
chmod a+x /usr/bin/appimageupdate

# Changing privileges in /opt/appimageupdate to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimageupdate

# Message
echo "
      AppImageUpdate has been installed!"

 SITE: https://github.com/AppImage/AppImageUpdate
"
