#!/bin/sh

APP=appman

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/appman && chmod a+x ./appman

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
cd /opt/appman
mkdir tmp
cd tmp
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/appman && chmod a+x ./appman
cd ..
mv ./tmp/appman ./appman
rmdir tmp' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater




