#!/bin/sh

APP=assaultcube

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/assaultcube/AC/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/assaultcube/AC/releases/download/$v/AssaultCube_$v.tar.bz2;

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

tar xf ./*.tar.bz2
rm ./*.tar.bz2
cd ..
mv ./tmp/AssaultCube*/* ./

rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=assaultcube
version0=$(cat /opt/$APP/version)

url=https://api.github.com/repos/assaultcube/AC/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!".
else
  notify-send 'A new version of assaultcube is available, please wait'
  mkdir /opt/assaultcube/tmp
  cd /opt/assaultcube/tmp
  v=$(wget -q https://api.github.com/repos/assaultcube/AC/releases/latest -O - | grep -E tag_name | awk -F '[]' '{print $4}')
  wget https://github.com/assaultcube/AC/releases/download/$v/AssaultCube_$v.tar.bz2
  version=$(ls /opt/$APP/tmp)
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version
  tar xf ./*.tar.bz2
  rm ./*.tar.bz2
  cd ..
  mv ./tmp/AssaultCube*/* ./
  rmdir ./tmp
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=AssaultCube
Exec=assaultcube
Comment=AssaultCube is a FREE, multiplayer, first-person shooter game, based on the CUBE engine.
Icon=/opt/$APP/icons/$APP
Type=Application
Categories=Game;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir icons
wget https://avatars.githubusercontent.com/u/5957666 -O ./icons/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
	AssaultCube is provided by https://assault.cubers.net        
"
