#!/bin/sh

APP=audacity

mkdir /opt/audacity
cd /opt/audacity

echo '#!/bin/sh
rm -R -f /opt/audacity /usr/local/bin/audacity /usr/share/applications/audacity.desktop' >> /opt/audacity/remove
chmod a+x /opt/audacity/remove

mkdir tmp;
cd tmp;
wget https://github.com/$(wget https://github.com/audacity/audacity/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/audacity*AppImage ./audacity;
chmod a+x /opt/audacity/audacity;
cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
chmod a+x ./updater
rmdir ./tmp

echo "[Desktop Entry]
Name=Audacity
GenericName=Sound Editor
GenericName[ar]=محرر أصوات
GenericName[ca]=Editor d'àudio
GenericName[co]=Editore audio
GenericName[da]=Lydredigeringsprogram
GenericName[de]=Audio-Editor
GenericName[el]=Επεξεργαστής ήχου
GenericName[es]=Editor de audio
GenericName[fr]=Éditeur audio
GenericName[hi]=ध्वनि संपादक
GenericName[ja]=音声編集ソフト
GenericName[ko]=오디오 편집기
GenericName[lt]=Garsų rengyklė
GenericName[nl]=Geluidseditor
GenericName[pt_BR]=Editor de áudio
GenericName[pt_PT]=Editor de áudio
GenericName[ru]=Редактор звуковых файлов
GenericName[sk]=Zvukový Editor
GenericName[tr]=Ses Düzenleyici
GenericName[uk]=Редактор звукових файлів
GenericName[zh_CN]=音频编辑器
GenericName[zh_TW]=音訊編輯器
Comment=Record and edit audio files
Comment[ar]=سجل و حرر ملفات صوت
Comment[ca]=Enregistreu i editeu els fitxers d'àudio
Comment[co]=Arregistrà è mudificà schedarii audio
Comment[da]=Optag og rediger lydfiler
Comment[de]=Audio-Dateien aufnehmen und bearbeiten
Comment[el]=Ηχογράφηση και επεξεργασία αρχείων ήχου
Comment[es]=Grabar y editar archivos de audio
Comment[fr]=Enregistrer et éditer des fichiers audio
Comment[hi]=ऑडियो फ़ाइल अंकित व संपादित करता है
Comment[ja]=音声ファイルの録音と編集
Comment[ko]=오디오 파일 녹음과 편집
Comment[lt]=Įrašyti ir montuoti garso failus
Comment[nl]=Audiobestanden opnemen en bewerken
Comment[pt_BR]=Gravar e editar arquivos de áudio
Comment[pt_PT]=Gravar e editar ficheiros de áudio
Comment[ru]=Запись и редактирование звуковых файлов
Comment[sk]=Nahráva a upravuje audio súbory.
Comment[tr]=Ses dosyalarını kaydetme ve düzenleme
Comment[uk]=Запис і редагування звукових файлів
Comment[zh_CN]=录音和编辑音频文件
Comment[zh_TW]=錄音和編輯音訊檔案

Icon=/opt/audacity/audacity.svg

Type=Application
Categories=AudioVideo;Audio;AudioVideoEditing;

Exec=env UBUNTU_MENUPROXY=0 audacity %F
StartupNotify=false
Terminal=false
MimeType=application/x-audacity-project;audio/aac;audio/ac3;audio/mp4;audio/x-ms-wma;video/mpeg;audio/flac;audio/x-flac;audio/mpeg;audio/basic;audio/x-aiff;audio/x-wav;application/ogg;audio/x-vorbis+ogg;" >> /usr/share/applications/audacity.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/audacity/audacity.svg;

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh ' >> /opt/$APP/AM-updater
echo 'cd /opt/audacity
./updater -O ./audacity
chmod a+x /opt/audacity/audacity
rm -R -f /opt/audacity/*zs-old && rm -R -f /opt/audacity/*.part' >> /opt/$APP/AM-updater

chmod a+x /opt/$APP/AM-updater

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/audacity

echo "";
echo " Audacity AppImage is provided by https://github.com/audacity ";
echo "";
