#!/bin/sh

APP=audacious

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove
APP=audacious
mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: audacious
binpatch: true

ingredients:
  dist: sid
  sources:
    - deb http://ftp.debian.org/debian/ sid main contrib non-free
  packages:
    - audacious" >> recipe.yml;

cp /opt/$APP/tmp/recipe.yml /opt/$APP/recipe.yml

./pkg2appimage ./recipe.yml;
cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/scalable/apps/$APP.svg ./$APP/$APP.AppDir
cp ./$APP/$APP.AppDir/usr/share/icons/hicolor/scalable/apps/$APP.svg /opt/$APP/

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;
underscore=_
mkdir version
mv ./$APP/$APP$underscore*.deb ./version/
version=$(ls /opt/$APP/tmp/version)
echo "$version" >> /opt/$APP/version

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
initial=$(echo $APP | head -c 1)
echo '#!/bin/sh
version0=$(cat /opt/'$APP'/version)
url="http://http.us.debian.org/debian/pool/main/'$initial'/'$APP'/$version0"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
else
  notify-send "A new version of '$APP' is available, please wait!"
  mkdir /opt/'$APP'/tmp
  cd /opt/'$APP'/tmp
  wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
  wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
  chmod a+x ./appimagetool ./pkg2appimage
  cp /opt/'$APP'/recipe.yml /opt/'$APP'/tmp/recipe.yml
  ./pkg2appimage ./recipe.yml;
  rm -R -f ./'$APP'/'$APP'.AppDir/'$APP'.desktop
  ARCH=x86_64 ./appimagetool -n ./'$APP'/'$APP'.AppDir
  mkdir version
  mv ./'$APP'/'$APP''$underscore'*.deb ./version/
  cd ..
  version=$(ls /opt/'$APP'/tmp/version)
  if test -f ./tmp/version/$version; then rm -R -f ./version
  fi
  echo "$version" >> /opt/'$APP'/version
  mv ./tmp/*.AppImage ./'$APP';
  chmod a+x ./'$APP'
  rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Audacious
GenericName=Music Player
Comment=Listen to music
Icon=/opt/$APP/$APP.svg
Keywords=audio;player;audacious;music;gtk;
Categories=AudioVideo;Audio;Player;GTK;
Exec=audacious %U
TryExec=audacious
StartupNotify=false
Terminal=false
MimeType=application/ogg;application/x-cue;application/x-ogg;application/xspf+xml;audio/aac;audio/flac;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpegurl;audio/ogg;audio/prs.sid;audio/wav;audio/x-flac;audio/x-it;audio/x-mod;audio/x-mp3;audio/x-mpeg;audio/x-mpegurl;audio/x-ms-asx;audio/x-ms-wma;audio/x-musepack;audio/x-s3m;audio/x-scpls;audio/x-stm;audio/x-vorbis+ogg;audio/x-wav;audio/x-wavpack;audio/x-xm;x-content/audio-cdda;

Comment[ar]=استمع إلى الموسيقى
Comment[be]=Слухайце музыку
Comment[bg]=Слушане на музика
Comment[ca]=Escolteu música
Comment[cs]=Poslouchat hudbu
Comment[da]=Lyt til musik
Comment[de]=Musik hören
Comment[el]=Ακρόαση μουσικής
Comment[eo]=Aŭskulti muzikon
Comment[es_AR]=Escuchar música
Comment[es_CL]=Listado de musica
Comment[es_MX]=Escuchar la música
Comment[es]=Escuchar música
Comment[et]=Kuula muusikat
Comment[fa_IR]=به موسیقی گوش کنید
Comment[fi]=Kuuntele musiikkia
Comment[fr]=Écouter de la musique
Comment[gl]=Escoitar música
Comment[hr]=Slušanje glazbe
Comment[hu]=Zenehallgatás
Comment[id_ID]=Dengarkan musik
Comment[it]=Ascolta la musica
Comment[ja]=音楽を聴きます
Comment[ko]=음악을 들어요
Comment[lt]=Klausyti muzikos
Comment[lv]=Klausīties mūziku
Comment[ms]=Dengar muzik
Comment[nl]=Luister naar muziek
Comment[pl]=Słuchaj muzyki
Comment[pt_BR]=Ouça música
Comment[pt_PT]=Reprodução de músicas
Comment[pt]=Escuta musica
Comment[ro]=Ascultă muzică
Comment[ru]=Слушать музыку
Comment[sk]=Počúvajte hudbu
Comment[sl]=Poslušaj glasbo
Comment[sq]=Dëgjoni muzikë
Comment[sr]=Слушајте музику
Comment[sv]=Lyssna på musik
Comment[ta]=இசையைக் கேளுங்கள்
Comment[tr]=Müzik dinleyin
Comment[uk]=Слухати музику
Comment[vi]=Nghe nhạc
Comment[zh_CN]=聆听音乐
Comment[zh_TW]=音樂鑑賞

GenericName[ar]=مشغل الموسيقى
GenericName[be]=Музычны прайгравальнік
GenericName[bg]=Музикален плейър
GenericName[ca]=Reproductor de música
GenericName[cs]=Hudební přehrávač
GenericName[da]=Musikafspiller
GenericName[de]=Musikspieler
GenericName[el]=Πρόγραμμα αναπαραγωγής μουσικής
GenericName[eo]=Muzik-ludilo
GenericName[es_AR]=Reproductor de Música
GenericName[es_CL]=Reproductor de musica
GenericName[es_MX]=Reproductor de Música
GenericName[es]=Reproductor de música
GenericName[et]=Muusikaesitaja
GenericName[fa_IR]=پخش کننده موسیقی
GenericName[fi]=Musiikkisoitin
GenericName[fr]=Lecteur audio
GenericName[gl]=Reprodutor de música
GenericName[hr]=Svirač glazbe
GenericName[hu]=Zenelejátszó
GenericName[id_ID]=Pemutar musik
GenericName[it]=Lettore musicale
GenericName[ja]=音楽プレイヤー
GenericName[ko]=음악 재생기
GenericName[lt]=Muzikos grotuvas
GenericName[lv]=Mūzikas atskaņotājs
GenericName[ms]=Pemain Muzik
GenericName[nl]=Muziekspeler
GenericName[pl]=Odtwarzacz muzyczny
GenericName[pt_BR]=Reprodutor de Música
GenericName[pt_PT]=Reprodutor áudio
GenericName[pt]=Reprodutor de musica
GenericName[ro]=Player de muzică
GenericName[ru]=Музыкальный проигрыватель
GenericName[sk]=Hudobný prehrávač
GenericName[sl]=Glasbeni predvajalnik
GenericName[sq]=Lojtës Muzike
GenericName[sr]=Програм за слушање музике
GenericName[sv]=Musikspelare
GenericName[ta]=இசைப்பான்
GenericName[tr]=Müzik Çalar
GenericName[uk]=Музичний програвач
GenericName[vi]=Trình chơi nhạc
GenericName[zh_CN]=音乐播放器
GenericName[zh_TW]=音樂播放器" >> /usr/share/applications/$APP.desktop;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 Audacious is provided by https://audacious-media-player.org
  
";
