#!/bin/sh

APP=audmonkey

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/AudMonkey/AudMonkey/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/AudMonkey/AudMonkey/releases/latest' >> /opt/$APP/AM-updater

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
echo 'else' >> /opt/$APP/AM-updater
echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater

########################################################################################

function1='$(wget https://github.com/AudMonkey/AudMonkey/releases/latest -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'

echo "  wget https://github.com/$function1 | $function2
  version=$function3" >> /opt/$APP/AM-updater

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /opt/$APP/AM-updater
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=AudMonkey
GenericName=Sound Editor
GenericName[ar]=محرر أصوات
GenericName[ca]=Editor d'àudio
GenericName[co]=Editore audio
GenericName[da]=Lydredigeringsprogram
GenericName[de]=Audio-Editor
GenericName[el]=Επεξεργαστής ήχου
GenericName[es]=Editor de audio
GenericName[fr]=Éditeur audio
GenericName[hi]=ध्वनि संपादक
GenericName[ja]=音声編集ソフト
GenericName[ko]=오디오 편집기
GenericName[lt]=Garsų rengyklė
GenericName[nl]=Geluidseditor
GenericName[pt_BR]=Editor de áudio
GenericName[pt_PT]=Editor de áudio
GenericName[ru]=Редактор звуковых файлов
GenericName[sk]=Zvukový Editor
GenericName[tr]=Ses Düzenleyici
GenericName[uk]=Редактор звукових файлів
GenericName[zh_CN]=音频编辑器
GenericName[zh_TW]=音訊編輯器
Comment=Record and edit audio files
Comment[ar]=سجل و حرر ملفات صوت
Comment[ca]=Enregistreu i editeu els fitxers d'àudio
Comment[co]=Arregistrà è mudificà schedarii audio
Comment[da]=Optag og rediger lydfiler
Comment[de]=Audio-Dateien aufnehmen und bearbeiten
Comment[el]=Ηχογράφηση και επεξεργασία αρχείων ήχου
Comment[es]=Grabar y editar archivos de audio
Comment[fr]=Enregistrer et éditer des fichiers audio
Comment[hi]=ऑडियो फ़ाइल अंकित व संपादित करता है
Comment[ja]=音声ファイルの録音と編集
Comment[ko]=오디오 파일 녹음과 편집
Comment[lt]=Įrašyti ir montuoti garso failus
Comment[nl]=Audiobestanden opnemen en bewerken
Comment[pt_BR]=Gravar e editar arquivos de áudio
Comment[pt_PT]=Gravar e editar ficheiros de áudio
Comment[ru]=Запись и редактирование звуковых файлов
Comment[sk]=Nahráva a upravuje audio súbory.
Comment[tr]=Ses dosyalarını kaydetme ve düzenleme
Comment[uk]=Запис і редагування звукових файлів
Comment[zh_CN]=录音和编辑音频文件
Comment[zh_TW]=錄音和編輯音訊檔案

Icon=/opt/$APP/$APP.svg

Type=Application
Categories=AudioVideo;Audio;AudioVideoEditing;

Exec=env UBUNTU_MENUPROXY=0 audmonkey %F
StartupNotify=false
Terminal=false
MimeType=application/x-audmonkey-project;audio/aac;audio/ac3;audio/mp4;audio/x-ms-wma;video/mpeg;audio/flac;audio/x-flac;audio/mpeg;audio/basic;audio/x-aiff;audio/x-wav;application/ogg;audio/x-vorbis+ogg;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " This AppImage is provided by https://github.com/AudMonkey ";
echo "";
