#!/bin/sh

mkdir /opt/avidemux
cd /opt/avidemux
mkdir tmp
cd ./tmp
wget --user-agent="X11; Linux x86_64;" https://sourceforge.net/projects/avidemux/files/latest/download
cd ..
mv ./tmp/download ./avidemux 
chmod a+x /opt/avidemux/avidemux
rmdir ./tmp

ln -s /opt/avidemux/avidemux /usr/local/bin/avidemux

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/avidemux/avidemux.svg;

rm -R -f /usr/share/applications/avidemux.desktop
echo "[Desktop Entry]
Name=Avidemux
GenericName=Video Editor
Comment=Multiplatform video editor
Exec=/opt/avidemux/avidemux %U
Icon=/opt/avidemux/avidemux.svg
Terminal=false
Type=Application
Categories=AudioVideo;AudioVideoEditing;Video;
MimeType=video/mpeg;video/x-mpeg;video/mp4;video/x-m4v;video/quicktime;video/3gp;video/mkv;video/x-matroska;video/webm;video/flv;video/x-flv;video/dv;video/x-msvideo;video/x-ms-wmv;video/x-ms-asf;video/x-anim;" >> /usr/share/applications/avidemux.desktop

echo '#!/bin/sh
rm -R -f /usr/share/applications/avidemux.desktop /opt/avidemux /usr/local/bin/avidemux' >> /opt/avidemux/remove
chmod a+x /opt/avidemux/remove

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/avidemux

echo "";
echo "   Avidemux AppImage has been installed!";
echo "";
