#!/bin/sh

APP=billard-gl

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove
APP=billard-gl
mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: billard-gl
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.debian.org/debian/ stable main contrib non-free
  packages:
    - billard-gl" >> recipe.yml;

cp /opt/$APP/tmp/recipe.yml /opt/$APP/recipe.yml

./pkg2appimage ./recipe.yml;
cp ./$APP/$APP.AppDir/usr/share/pixmaps/* ./$APP/$APP.AppDir/
cp ./$APP/$APP.AppDir/usr/share/pixmaps/billard-gl.xpm /opt/$APP/
ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;
underscore=_
mkdir version
mv ./$APP/$APP$underscore*.deb ./version/
version=$(ls /opt/$APP/tmp/version)
echo "$version" >> /opt/$APP/version

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# SCRIPT TO UPDATE THE PROGRAM
initial=$(echo $APP | head -c 1)
echo '#!/bin/sh
version0=$(cat /opt/'$APP'/version)
url="http://http.us.debian.org/debian/pool/main/'$initial'/'$APP'/$version0"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
else
  notify-send "A new version of '$APP' is available, please wait!"
  mkdir /opt/'$APP'/tmp
  cd /opt/'$APP'/tmp
  wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
  wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
  chmod a+x ./appimagetool ./pkg2appimage
  cp /opt/'$APP'/recipe.yml /opt/'$APP'/tmp/recipe.yml
  ./pkg2appimage ./recipe.yml;
  ARCH=x86_64 ./appimagetool -n ./'$APP'/'$APP'.AppDir
  mkdir version
  mv ./'$APP'/'$APP''$underscore'*.deb ./version/
  cd ..
  version=$(ls /opt/'$APP'/tmp/version)
  if test -f ./tmp/version/$version; then rm -R -f ./version
  fi
  echo "$version" >> /opt/'$APP'/version
  mv ./tmp/*.AppImage ./'$APP';
  chmod a+x ./'$APP'
  rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Type=Application
Name=Billard-GL
GenericName=billard-gl
Comment=Play Billard Game
Comment[de]=Spiele eine Partie Billard
Icon=/opt/$APP/billard-gl.xpm
Exec=billard-gl
Terminal=false
Categories=Game;Simulation;
Keywords=billard;3D;opengl;game;" >> /usr/share/applications/$APP.desktop;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

           BillardGL is provided by 

  https://sourceforge.net/projects/billardgl
  
";
