#!/bin/sh

APP=bottles
REPO="bottlesdevs/Bottles"
ICONURL="https://raw.githubusercontent.com/bottlesdevs/Bottles/master/data/icons/hicolor/scalable/apps/com.usebottles.bottles.svg"
FILENAMEEXTENTION="/.*/.*x86_64.AppImage"
URL=https://github.com/$REPO/releases/latest

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(wget -q https://api.github.com/repos/$REPO/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
echo "$version" >> /opt/$APP/version
if wget -q https://github.com/$REPO/releases | grep "x86_64.AppImage"; then
	download=$(wget -q https://api.github.com/repos/$REPO/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | grep -w -v i386 | grep -w -v i686 | grep -w -v arm64 | grep -w -v armv7l | egrep ''$FILENAMEEXTENTION'' -o | head -1);
wget https:$download
else
	wget https://github.com/bottlesdevs/Bottles/releases/download/2021.7.14-treviso/Bottles-2021.7.14-treviso-x86_64.AppImage
fi
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rm -R -f /opt/$APP/tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=bottles
REPO="bottlesdevs/Bottles"
FILENAMEEXTENTION="/.*/.*x86_64.AppImage"
version0=$(cat /opt/$APP/version)
url=https://github.com/$REPO/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  version=$(wget -q https://api.github.com/repos/$REPO/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
  if wget -q https://github.com/$REPO/releases/latest | grep "x86_64.AppImage"; then
	download=$(wget -q https://api.github.com/repos/$REPO/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | grep -w -v i386 | grep -w -v i686 | grep -w -v arm64 | grep -w -v armv7l | egrep ''$FILENAMEEXTENTION'' -o | head -1);
wget https:$download
	cd ..
  	if test -f ./tmp/*mage; then rm ./version
  	fi
  	echo $version >> ./version
  	mv --backup=t ./tmp/*mage ./$APP
  	chmod a+x /opt/$APP/$APP
  	rm -R -f /opt/$APP/tmp /opt/$APP/*~
  else
  	echo " No AppImage package available for $APP $version"
  	notify-send "No AppImage package available for $version"
  	rm -R -f /opt/$APP/version
  	echo $version >> /opt/$APP/version
	rm -R -f /opt/$APP/tmp /opt/$APP/*~
  fi
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
# LAUNCHER
echo "[Desktop Entry]
X-AppImage-Arch=x86_64
X-AppImage-Name=Bottles
Name[it]=Bottles
Name[fr]=Bouteilles
Name[de]=Bottles
Name[pt]=Bottles
Name[es]=Bottles
Name[nb_NO]=Flasker
Name[pt_BR]=Bottles
Name[id]=Bottles
Name[da]=Flasker
Name[nl]=Bottles
Name[tr]=Şişeler
Name[sv]=Bottles
Name[ru]=Бутылка
Name[eo]=Boteloj
Name[zh_Hans]=Bottles
Name[ar]=باتلز
Name[fil]=Bottles
Name[fi]=Pullot
Name[ja]=Bottles
Name[hr]=Butelje
Name[yi]=Bottles
Name[cs]=Láhve
Name[uk]=Пляшки
Name[hu]=Tárolók
Name[pl]=Bottles
Name=Bottles
Comment[it]=Gestisci con facilità i prefissi wine
Comment[fr]=Gérer facilement vos wineprefix
Comment[de]=Wineprefixes einfach verwalten
Comment[pt]=Define um wineprefix
Comment[es]=Gestione los prefijos de Wine fácilmente
Comment[nb_NO]=Håndter wineprefiks enkelt
Comment[pt_BR]=Gerencie o wineprefix facilmente
Comment[id]=Kelola wineprefix dengan mudah
Comment[da]=Administrer nemt wine-præfiks
Comment[nl]=Makkelijk beheer van wineprefix
Comment[tr]=Wineprefix'leri kolayca yönetin
Comment[sv]=Enkel hantering av Wine-prefix
Comment[ru]=Простое управление wine префиксами
Comment[eo]=Facile administru Wine-prefiksojn
Comment[zh_Hans]=轻松地管理 wineprefix
Comment[ar]=إدارة wineprefix بسهولة
Comment[fil]=Madaliang pagayos ng wineprefix
Comment[fi]=Hallitse helposti wine-etuliitettä
Comment[ja]=wineprefixを簡単に管理
Comment[hr]=Jednostavno upravljaj Wine mapama
Comment[yi]=גרינגע פאַרוואַלטונג פון "װײַנפּרעפֿיקסן"
Comment[cs]=Snadně spravujte wine prefixy
Comment[uk]=Легке керування wine префіксами
Comment[hu]=Könnyen kezelheti a wineprefix-et
Comment[pl]=Łatwo zarządzaj wineprefix
Comment=Easily manage wineprefix
Icon=/opt/$APP/icons/$APP
Exec=$APP %f
Terminal=false
Type=Application
Categories=Utility;GNOME;GTK;
StartupNotify=true
MimeType=application/x-ms-dos-executable;application/x-msi;application/x-ms-shortcut;application/x-wine-extension-msp;
Keywords[it]=wine;windows;
Keywords[fr]=wine;windows;
Keywords[es]=wine;windows;
Keywords[pt_BR]=wine;windows;
Keywords[id]=wine;windows;
Keywords[sv]=wine;windows;
Keywords[zh_Hans]=wine;windows;
Keywords[ja]=wine;windows;
Keywords[hr]=wine;windows;
Keywords[hu]=tároló;windows;wine;
Keywords=wine;windows;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir /opt/$APP/icons
wget $ICONURL -O /opt/$APP/icons/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 Bottles is provided by https://usebottles.com

"
