#!/bin/sh

mkdir /opt/bottles
cd /opt/bottles;

echo '#!/bin/sh
rm -R -f /opt/bottles /usr/share/applications/bottles.desktop /usr/local/bin/bottles' >> /opt/bottles/remove
chmod a+x /opt/bottles/remove

mkdir tmp;
cd tmp;
wget https://github.com/$(wget https://github.com/bottlesdevs/Bottles/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/Bottles*AppImage ./bottles;
chmod a+x /opt/bottles/bottles;
rmdir ./tmp

rm -R -f /usr/share/applications/bottles.desktop
echo "[Desktop Entry]
X-AppImage-Arch=x86_64
X-AppImage-Version=2021.8.28-treviso
X-AppImage-Name=Bottles
Name[it]=Bottles
Name[fr]=Bouteilles
Name[de]=Bottles
Name[pt]=Bottles
Name[es]=Bottles
Name[nb_NO]=Flasker
Name[pt_BR]=Bottles
Name[id]=Bottles
Name[da]=Flasker
Name[nl]=Bottles
Name[tr]=Şişeler
Name[sv]=Bottles
Name[ru]=Бутылка
Name[eo]=Boteloj
Name[zh_Hans]=Bottles
Name[ar]=باتلز
Name[fil]=Bottles
Name[fi]=Pullot
Name[ja]=Bottles
Name[hr]=Butelje
Name[yi]=Bottles
Name[cs]=Láhve
Name[uk]=Пляшки
Name[hu]=Tárolók
Name[pl]=Bottles
Name=Bottles
Comment[it]=Gestisci con facilità i prefissi wine
Comment[fr]=Gérer facilement vos wineprefix
Comment[de]=Wineprefixes einfach verwalten
Comment[pt]=Define um wineprefix
Comment[es]=Gestione los prefijos de Wine fácilmente
Comment[nb_NO]=Håndter wineprefiks enkelt
Comment[pt_BR]=Gerencie o wineprefix facilmente
Comment[id]=Kelola wineprefix dengan mudah
Comment[da]=Administrer nemt wine-præfiks
Comment[nl]=Makkelijk beheer van wineprefix
Comment[tr]=Wineprefix'leri kolayca yönetin
Comment[sv]=Enkel hantering av Wine-prefix
Comment[ru]=Простое управление wine префиксами
Comment[eo]=Facile administru Wine-prefiksojn
Comment[zh_Hans]=轻松地管理 wineprefix
Comment[ar]=إدارة wineprefix بسهولة
Comment[fil]=Madaliang pagayos ng wineprefix
Comment[fi]=Hallitse helposti wine-etuliitettä
Comment[ja]=wineprefixを簡単に管理
Comment[hr]=Jednostavno upravljaj Wine mapama
Comment[yi]=גרינגע פאַרוואַלטונג פון "װײַנפּרעפֿיקסן"
Comment[cs]=Snadně spravujte wine prefixy
Comment[uk]=Легке керування wine префіксами
Comment[hu]=Könnyen kezelheti a wineprefix-et
Comment[pl]=Łatwo zarządzaj wineprefix
Comment=Easily manage wineprefix
Icon=/opt/bottles/wine-bottles.svg
Exec=bottles %f
Terminal=false
Type=Application
Categories=Utility;GNOME;GTK;
StartupNotify=true
MimeType=application/x-ms-dos-executable;application/x-msi;application/x-ms-shortcut;application/x-wine-extension-msp;
Keywords[it]=wine;windows;
Keywords[fr]=wine;windows;
Keywords[es]=wine;windows;
Keywords[pt_BR]=wine;windows;
Keywords[id]=wine;windows;
Keywords[sv]=wine;windows;
Keywords[zh_Hans]=wine;windows;
Keywords[ja]=wine;windows;
Keywords[hr]=wine;windows;
Keywords[hu]=tároló;windows;wine;
Keywords=wine;windows;" >> /usr/share/applications/bottles.desktop

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/wine-bottles/wine-bottles.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/bottles

echo '#!/bin/sh
cd /opt/bottles
appimageupdate -O bottles
rm *zs-old
exec /opt/bottles/bottles' >> /usr/local/bin/bottles
chmod a+x /usr/local/bin/bottles

echo "";
echo " WINE Bottles AppImage is provided by https://github.com/bottlesdevs ";
echo "";
