#!/bin/sh

APP=btop
REPO="aristocratos/btop"

# CREATE DIRECTORIES
if [ -z "$APP" ]; then exit 1; fi
mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1

# ADD THE REMOVER
echo "#!/bin/sh
rm -f /usr/share/applications/AM-$APP.desktop /usr/local/bin/$APP
rm -R -f /opt/$APP" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP
# $version is also used for updates

version=$(wget -q https://api.github.com/repos/"$REPO"/releases/latest -O - | grep browser_download_url | grep x86_64 | cut -d '"' -f 4 | head -1)
wget "$version"
tar xf ./*.tbz
cd ..
echo "$version" >> ./version
mv ./tmp/*/* ./
ln -s ./bin/btop ./"$APP"

rm -R -f ./tmp

# LINK
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=btop
version0=$(cat /opt/$APP/version)
url=https://api.github.com/repos/aristocratos/btop/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!".
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  v=$(wget -q https://api.github.com/repos/aristocratos/btop/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
  wget https://github.com/aristocratos/btop/releases/download/$v/btop-x86_64-linux-musl.tbz
  tar xf ./*.tbz;
  cd ..;
  if test -f ./tmp/*.tbz; then rm -R -f /opt/$APP/version
  fi
  echo "$v" >> /opt/$APP/version
  rm ./tmp/*.tbz;
  mv --backup=t ./tmp/$(echo $dir)/* ./
  rm -R -f ./tmp ./*~
  notify-send "$APP is updated!"
fi
EOF
chmod a+x "/opt/$APP/AM-updater"

# LAUNCHER & ICON
mv ./*.desktop /usr/share/applications/AM-"$APP".desktop && mv ./*mg/*.svg ./icons/btop 2>/dev/null #btop already ships the files

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R "$currentuser" "/opt/$APP"

# MESSAGE
echo "
 $APP is provided by https://github.com/$(echo $REPO | sed 's:/[^/]*$::')
"
