#!/bin/sh

APP=castersoundboard

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/covarianttensor/CasterSoundboard/releases/tag/continuous -O - | egrep '/.*/.*/.*AppImage' -o);

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "APP=$APP" >> /usr/local/bin/$APP
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/covarianttensor/CasterSoundboard/releases/tag/continuous' >> /usr/local/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/local/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/local/bin/$APP
echo "  exec /opt/$APP/$APP" >> /usr/local/bin/$APP
echo 'else' >> /usr/local/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/local/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/local/bin/$APP

########################################################################################

function1='$(wget https://github.com/covarianttensor/CasterSoundboard/releases/tag/continuous -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'

echo "  wget https://github.com/$function1 | $function2
  version=$function3" >> /usr/local/bin/$APP

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /usr/local/bin/$APP
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
  exec /opt/$APP/$APP
fi" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=CasterSoundboard
Comment=A soundboard for hot-keying and playing back sounds
Icon=/opt/$APP/$APP
Exec=castersoundboard
NoDisplay=false
Categories=AudioVideo;
StartupNotify=false
Terminal=false" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo "          CasterSoundboard is provided by";
echo "";
echo " https://github.com/covarianttensor/CasterSoundboard ";
echo "";
