#!/bin/sh

APP=celeste64
REPO="ExOK/Celeste64"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i "linux-x64.zip" | cut -d '"' -f 4 | head -1)
wget $version
echo "$version" >> /opt/$APP/version
unzip ./*zip; rm -R -f ./*.zip
cd ..
mv ./tmp/* ./
rm -R -f ./tmp

# LINK
ln -s /opt/$APP/Celeste64 /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=celeste64
REPO="ExOK/Celeste64"
version0=$(cat /opt/$APP/version)
version=$(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i "linux-x64.zip" | cut -d '"' -f 4 | head -1)
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget $version
  unzip ./*zip; rm -R -f ./*.zip
  cd ..
  mv --backup=t ./tmp/*
  rm ./version
  echo $version >> ./version
  rm -R -f ./tmp ./*~
  notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Celeste64
Comment=A game made by the Celeste developers in a week(ish, closer to 2) 
Exec=$APP
Icon=/opt/$APP/icons/$APP
Categories=Game;
Terminal=true
StartupNotify=true" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir icons
wget -q "https://avatars.githubusercontent.com/u/40015064" -O /opt/$APP/icons/$APP




