#!/bin/sh

# Creating a dedicated folder in /opt
mkdir /opt/celestia
cd /opt/celestia

# Creating a script to remove all the files listed above
rm -R -f  /opt/celestia/remove
echo "#!/bin/sh
rm -R -f  /usr/share/applications/celestia.desktop /usr/share/pixmaps/celestia.svg /usr/bin/celestia /opt/celestia" >> /opt/celestia/remove
chmod a+x /opt/celestia/remove

mkdir tmp
cd tmp

# Downloading the AppImage of Celestia to /opt/celestia
wget https://download.opensuse.org/repositories/home:/munix9/AppImage/celestia-latest-x86_64.AppImage
cd ..
mv ./tmp/celestia*AppImage ./celestia
rmdir ./tmp
chmod a+x ./celestia

# Creating a command for "celestia" in /usr/bin with support for "appimageupdate"
rm -R -f  /usr/bin/celestia
echo "#!/bin/sh
cd /opt/celestia
appimageupdate -O celestia
rm *zs-old
exec /opt/celestia/celestia" >> /usr/bin/celestia
chmod a+x /usr/bin/celestia

# Creating the launcher in /usr/share/applications
rm -R -f  /usr/share/applications/celestia.desktop
echo "[Desktop Entry]
Version=1.0
Name=Celestia (GTK)
GenericName=Space Simulator (AppImage-1.6.2.2)
GenericName[de]=Weltraum-Simulator (AppImage-1.6.2.2)
Comment=Explore the Universe in this detailed space simulation
Comment[de]=Erkunde das Universum in dieser detaillierten Weltraumsimulation
Type=Application
Categories=Astronomy;Education;Science;GTK;
Icon=celestia
Exec=celestia %f
Terminal=false
MimeType=application/x-celestia-script;" >> /usr/share/applications/celestia.desktop

# Adding the icon to /usr/share/pixmaps
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/celestia/celestia.svg
mv ./celestia.svg /usr/share/pixmaps/

# Changing privileges in /opt/celestia to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/celestia

# Message
echo ""
echo " Celestia has been installed!"
echo ""
