#!/bin/sh

APP=celestia

# Creating a dedicated folder in /opt
mkdir /opt/celestia
cd /opt/celestia

# Creating a script to remove all the files listed above
rm -R -f  /opt/celestia/remove
echo "#!/bin/sh
rm -R -f  /usr/share/applications/AM-celestia.desktop /usr/bin/celestia /opt/celestia" >> /opt/celestia/remove
chmod a+x /opt/celestia/remove

mkdir tmp
cd tmp

# Downloading the AppImage of Celestia to /opt/celestia
wget https://download.opensuse.org/repositories/home:/munix9/AppImage/celestia-latest-x86_64.AppImage
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/celestia*AppImage ./celestia
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
rmdir ./tmp
chmod a+x ./celestia
chmod a+x ./updater

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh ' >> /opt/$APP/AM-updater
echo 'cd /opt/celestia
./updater -O ./celestia
chmod a+x /opt/celestia/celestia
rm -R -f /opt/celestia/*zs-old && rm -R -f /opt/celestia/*.part' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# Creating the launcher in /usr/share/applications
rm -R -f  /usr/share/applications/AM-celestia.desktop
echo "[Desktop Entry]
Version=1.0
Name=Celestia (GTK)
GenericName=Space Simulator (AppImage-1.6.2.2)
GenericName[de]=Weltraum-Simulator (AppImage-1.6.2.2)
Comment=Explore the Universe in this detailed space simulation
Comment[de]=Erkunde das Universum in dieser detaillierten Weltraumsimulation
Type=Application
Categories=Astronomy;Education;Science;GTK;
Icon=/opt/celestia/celestia.svg
Exec=celestia %f
Terminal=false
MimeType=application/x-celestia-script;" >> /usr/share/applications/AM-celestia.desktop

# Adding the icon to /usr/share/pixmaps
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/celestia.svg

# Changing privileges in /opt/celestia to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/celestia

# Message
echo "";
echo "           Celestia is provided by https://celestia.space";
echo "";
echo " AppImage at https://download.opensuse.org/repositories/home:/munix9/AppImage";
echo "";
