#!/bin/sh

APP=celestia

# Creating a dedicated folder in /opt
mkdir /opt/celestia
cd /opt/celestia

# Creating a script to remove all the files listed above
rm -R -f  /opt/celestia/remove
echo "#!/bin/sh
rm -R -f  /usr/share/applications/AM-celestia.desktop /usr/local/bin/celestia /opt/celestia" >> /opt/celestia/remove
chmod a+x /opt/celestia/remove

mkdir tmp
cd tmp

# Downloading the AppImage of Celestia to /opt/celestia
wget https://download.opensuse.org/repositories/home:/munix9/AppImage/celestia-latest-x86_64.AppImage
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage 2> /dev/null
cd ..
mv ./tmp/celestia*AppImage ./celestia
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
rmdir ./tmp
chmod a+x ./celestia
chmod a+x ./updater
echo "appimage" >> /opt/$APP/version

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh ' >> /opt/$APP/AM-updater
echo 'cd /opt/celestia
./updater -O ./celestia
chmod a+x /opt/celestia/celestia
rm -R -f /opt/celestia/*zs-old && rm -R -f /opt/celestia/*.part' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./$APP --appimage-extract *.desktop 1>/dev/null
./$APP --appimage-extract share/applications/*.desktop 1>/dev/null
./$APP --appimage-extract usr/share/applications/*.desktop 1>/dev/null
mv squashfs-root/*.desktop ./$APP.desktop 2>/dev/null
mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2>/dev/null
mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2>/dev/null
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$app*.desktop 1>/dev/null 
	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2>/dev/null
fi
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract share/applications/*$app*.desktop 1>/dev/null 
	mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2>/dev/null
fi
CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $app | head -1)
sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop
sed -i "s#AppRun#$APP#g" ./$APP.desktop
sed -i "s#Exec=/bin/#Exec=#g" ./$APP.desktop
sed -i "s#Exec=/usr/bin/#Exec=#g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop

mkdir icons
wget https://raw.githubusercontent.com/GottfriedSp/celestia-code/master/celestia/src/celestia/gtk/data/celestia-logo.png -O ./icons/$APP 2>/dev/null

rm -R -f /opt/$APP/squashfs-root
mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop 2> /dev/null

# Changing privileges in /opt/celestia to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/celestia

# MESSAGE
echo "";
echo "           Celestia is provided by https://celestia.space";
echo "";
echo " AppImage at https://download.opensuse.org/repositories/home:/munix9/AppImage";
echo "";
