#!/bin/sh

APP=chromium

mkdir /opt/$APP
cd /opt/$APP
mkdir tmp
cd ./tmp
wget -r -erobots=off -l1 -np -A chromium-*-x86_64-1alien.txz -nd http://www.slackware.com/~alien/slackbuilds/chromium/pkg64/current/;
tar xf ./*.txz
cd ..
mv ./tmp/usr/lib64/$APP/* ./
cp ./tmp/usr/share/applications/*desktop /usr/share/applications/$APP.desktop
cp ./tmp/usr/share/icons/hicolor/256x256/apps/*png /usr/share/pixmaps/$APP.png
rm -R -f ./tmp

echo '#!/bin/sh
/opt/chromium/chromium
version=$(exec /opt/chromium/chromium --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
url="http://www.slackware.com/~alien/slackbuilds/chromium/pkg64/current/chromium-$version-x86_64-1alien.txz"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
else
  mkdir /opt/chromium/tmp
  cd /opt/chromium/tmp
  wget -r -erobots=off -l1 -np -A chromium-*-x86_64-1alien.txz -nd http://www.slackware.com/~alien/slackbuilds/chromium/pkg64/current/
  tar xf ./*.txz
  cd ..
  mv ./tmp/usr/lib64/chromium/* ./
  rm -R -f ./tmp
fi' >> /usr/bin/$APP
chmod a+x /usr/bin/$APP

echo '#!/bin/sh
rm -R -f /opt/chromium /usr/share/pixmaps/chromium.png /usr/share/applications/chromium.desktop /usr/bin/chromium' >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo ""
echo " 

	    Chromium Browser has been installed!
	
	This version come from http://www.slackware.com

   This is the first standalone version that updates itself!

"
