#!/bin/sh

APP=citra
REPO="citra-emu/citra-nightly"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/${APP}/remove
echo "rm -R -f /usr/share/applications/AM-${APP}.desktop /usr/share/applications/AM-${APP}-qt.desktop /usr/share/applications/AM-${APP}-room.desktop /opt/${APP} /usr/local/bin/${APP}" /usr/local/bin/${APP}-qt" /usr/local/bin/${APP}-room"  >> /opt/${APP}/remove
chmod a+x /opt/${APP}/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i tar  | grep -i appimage | cut -d '"' -f 4 | head -1)
wget $version
echo "$version" >> /opt/$APP/version
tmpTarPkg=$(echo $version | sed 's:.*/\(.*\).tar.gz:\1:')  
tar fx ${tmpTarPkg}.tar.gz

cd ..

mv ./tmp/${tmpTarPkg}/${APP}.AppImage ./${APP}
mv ./tmp/${tmpTarPkg}/${APP}-qt.AppImage ./${APP}-qt
mv ./tmp/${tmpTarPkg}/${APP}-room.AppImage ./${APP}-room
chmod a+x /opt/$APP/${APP}*
rm -R -f ./tmp

# LINK
ln -s /opt/${APP}/${APP} /usr/local/bin/${APP}
ln -s /opt/${APP}/${APP}-qt /usr/local/bin/${APP}-qt
ln -s /opt/${APP}/${APP}-room /usr/local/bin/${APP}-room

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=citra
REPO="citra-emu/citra-nightly"
version0=$(cat /opt/$APP/version)
version=$(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i tar  | grep -i appimage | cut -d '"' -f 4 | head -1)
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget $version
  tmpTarPkg=$(echo $version | sed 's:.*/\(.*\).tar.gz:\1:')  
  tar fx ${tmpTarPkg}.tar.gz

  if ls ./${tmpTarPkg} | grep mage; then
	cd ..
  	rm ./version
  	echo $version >> ./version

    mv --backup=t ./tmp/${tmpTarPkg}/${APP}.AppImage ./${APP}
    mv --backup=t ./tmp/${tmpTarPkg}/${APP}-qt.AppImage ./${APP}-qt
    mv --backup=t ./tmp/${tmpTarPkg}/${APP}-room.AppImage ./${APP}-room
    chmod a+x /opt/$APP/${APP}*
  	rm -R -f ./tmp ./*~
  fi
  notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./${APP}-qt --appimage-extract usr/share/applications/citra-qt.desktop 1> /dev/null
./${APP}-room --appimage-extract usr/share/applications/citra-room.desktop 1> /dev/null
mv squashfs-root/usr/share/applications/${APP}-qt.desktop ./$APP-qt.desktop
mv squashfs-root/usr/share/applications/${APP}-room.desktop ./$APP-room.desktop

CHANGEICON=$(cat ./$APP-qt.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP-qt.desktop
CHANGEICON=$(cat ./$APP-room.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP-room.desktop

mkdir icons
mv $(./$APP --appimage-extract *.png) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract *.svg) ./icons/$APP 2>/dev/null
./$APP --appimage-extract share/icons/*/*/* 1>/dev/null
./$APP --appimage-extract usr/share/icons/*/*/* 1>/dev/null
./$APP --appimage-extract share/icons/*/*/*/* 1>/dev/null
./$APP --appimage-extract usr/share/icons/*/*/*/* 1>/dev/null
mv ./squashfs-root/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null

rm -R -f /opt/$APP/squashfs-root
mv ./$APP-qt.desktop /usr/share/applications/AM-$APP-qt.desktop
mv ./$APP-room.desktop /usr/share/applications/AM-$APP-room.desktop



