#!/bin/sh

APP=conky
URL=https://github.com/brndnmtthws/conky/releases/latest

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/brndnmtthws/conky/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Type=Application
Name=conky
Exec=conky --daemonize --pause=1
StartupNotify=false
Terminal=false
Icon=/opt/$APP/$APP.png
Categories=System;Monitor;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://d4.alternativeto.net/dKOGFqH9bJpus5EKzexMy7lvETTN8azD5REV_wQNgJo/rs:fill:140:140:0/g:ce:0:0/YWJzOi8vZGlzdC9pY29ucy9jb25reV8xODg5ODQucG5n.png -O $APP.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo '

   Conky is provided by https://github.com/brndnmtthws/conky

'
