#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=conty
SITE="Kron4ek/Conty"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
#printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
read -r -p "
 Choose which version of Conty to use:

 1. WINE (or BASE), it includes only WINE and its dependencies

 2. LITE, same as WINE, plus Wine-GE, Steam, Lutris, PlayOnLinux,
    GameHub, Minigalaxy, Legendary, Bottles, MultiMC, MangoHud,
    Gamescope, RetroArch, PPSSPP, PCSX2, DuckStation, OBS Studio
    and OpenJDK

 3. FULL, same as LITE, plus base-devel, gcc, mingw-w64-gcc, meson,
    cmake, jre-openjdk, multimc5, Firefox and qBittorrent

 Learn more at https://github.com/Kron4ek/Conty

 Which version you choose (type a number and press ENTER)?" response
RELEASE=""
if echo "$response" | grep -q "^1"; then
	RELEASE="conty_wine"
elif echo "$response" | grep -q "^2"; then
	RELEASE="conty_lite"
elif echo "$response" | grep -q "^3"; then
	RELEASE="conty"
fi
[ -z "$RELEASE" ] && exit 0

version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -io "https.*download.*$RELEASE.sh$" | head -1)
if [ -z "$version" ]; then
	printf "\n 💀 ERROR: it seems that upstream removed %b, please retry\n" "$RELEASE" && exit 1
else
	wget "$version" || exit 1
fi
cd ..
mv ./tmp/*sh ./"$APP"
mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
rm -R -f ./tmp || exit 1
echo "$version" > ./version
wget "$version.zsync" 2> /dev/null
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=conty
SITE="Kron4ek/Conty"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/Kron4ek/Conty/releases | sed 's/[()",{} ]/\n/g' | grep -io "https.*download.*REPLACETHIS.sh$" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*sh ./"$APP"
	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1
sed -i "s#REPLACETHIS#$RELEASE#g" /opt/"$APP"/AM-updater
