#!/bin/sh

APP=conty-wine
REPO="Kron4ek/Conty"
URL=$($(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v zsync | grep browser_download_url | grep -i "conty_wine.sh" | cut -d '"' -f 4 | head -1))

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget $URL
wget $URL.asc 2> /dev/null
wget $URL.zsync 2> /dev/null
wget $URL.zsync.asc 2> /dev/null
cd ..
mv ./tmp/* ./$APP 2> /dev/null
chmod a+x /opt/$APP/$APP
mv ./tmp/*.zsync ./$APP.zsync 2> /dev/null
#mv ./tmp/*.asc ./$APP.asc 2> /dev/null
#mv ./tmp/*zsync.asc ./$APP.zsync.asc 2> /dev/null
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=conty-wine
REPO="Kron4ek/Conty"
URL=$($(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v zsync | grep browser_download_url | grep -i "conty_wine.sh" | cut -d '"' -f 4 | head -1))
cd /opt/$APP
mkdir tmp
cd ./tmp
wget $URL.asc 2> /dev/null
wget $URL.zsync 2> /dev/null
wget $URL.zsync.asc 2> /dev/null
cd ..
mv ./tmp/*.zsync ./$APP.zsync
#mv ./tmp/*.asc ./$APP.asc
#mv ./tmp/*zsync.asc ./$APP.zsync.asc
rmdir ./tmp
zsync /opt/$APP/$APP.zsync
rm -R -f /opt/$APP/*zs-old /opt/$APP/*.part
chmod a+x /opt/$APP/$APP
EOF
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

	$APP is provided by 
	
"
