#!/bin/sh

APP=deadbeef-devel
SITE="https://deadbeef.sourceforge.io"

# CREATE DIRECTORIES
if [ -z "$APP" ]; then exit 1; fi
mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1

# ADD THE REMOVER
echo "#!/bin/sh
rm -f /usr/share/applications/AM-$APP.desktop /usr/local/bin/$APP
rm -R -f /opt/$APP" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP
# $version is also used for updates

version=$(wget -q https://sourceforge.net/projects/deadbeef/files/travis/linux/master/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | sort -u | grep "x86_64.tar.bz2")
wget $version -O download.tar.bz2
echo "$version" >> /opt/$APP/version
tar fx ./*tar*
cd ..
mv --backup=t ./tmp/*/* ./
chmod a+x "/opt/$APP/deadbeef"
ln -s "/opt/$APP/deadbeef" "/opt/$APP/$APP"
rm -R -f ./tmp

# LINK
ln -s "/opt/$APP/deadbeef" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=deadbeef-devel
version0=$(cat /opt/$APP/version)
version=$(wget -q https://sourceforge.net/projects/deadbeef/files/travis/linux/master/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | sort -u | grep "x86_64.tar.bz2")
if [ $version = $version0 ]; then
	echo "deadbeef-devel is up to date!"
else
	notify-send "A new version of $APP is available, please wait"
	mkdir /opt/$APP/tmp
	cd /opt/$APP/tmp
	wget $version -O download.tar.bz2
  tar fx ./*tar*; rm -f -R ./*tar*
	cd ..
  mv --backup=t ./tmp/*/* ./
	rm ./version
	echo $version >> ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# DESKTOP & ICON
DESKTOP="https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/master/deadbeef.desktop.in"
ICON="https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/master/icons/scalable/deadbeef.svg"
wget "$DESKTOP" -O ./"$APP".desktop && wget "$ICON" -O ./deadbeef.svg
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Name=DeaDBeeF#Name=DeaDBeeF Nightly#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/share/applications/AM-"$APP".desktop && mv ./deadbeef.svg ./icons/"$APP" 2>/dev/null
rm -R -f ./squashfs-root

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP
