#!/bin/sh

APP=digikam

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir tmp
cd ./tmp

version=$(curl -L -s https://www.digikam.org | grep -Eo "digiKam [+-]?[0-9]+([.][0-9]+)+([.][0-9]+)" | grep -Eo "[+-]?[0-9]+([.][0-9]+)+([.][0-9]+)")
wget https://download.kde.org/stable/digikam/$version/digiKam-$version-x86-64.appimage
echo $version >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh
version0=$(cat /opt/digikam/version)
if curl -L -s https://www.digikam.org | grep -o "$version0"; then
  echo "Update not needed, exit!"
else
  notify-send "A new version of digikam is available, please wait!"
  mkdir /opt/digikam/tmp
  cd /opt/digikam/tmp
  version=$(curl -L -s https://www.digikam.org | grep -Eo "digiKam [+-]?[0-9]+([.][0-9]+)+([.][0-9]+)" | grep -Eo "[+-]?[0-9]+([.][0-9]+)+([.][0-9]+)")
  wget https://download.kde.org/stable/digikam/$version/digiKam-$version-x86-64.appimage
  rm -R -f /opt/digikam/version
  echo $version >> /opt/digikam/version
  cd ..
  mv ./tmp/*mage ./digikam
  chmod a+x /opt/digikam/digikam
  rm -R -f ./tmp
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./$APP --appimage-extract *.desktop 2>/dev/null
./$APP --appimage-extract share/applications/*.desktop 2>/dev/null
./$APP --appimage-extract usr/share/applications/*.desktop 2>/dev/null
mv squashfs-root/*.desktop ./$APP.desktop 2>/dev/null
mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2>/dev/null
mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2>/dev/null
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$app*.desktop 2>/dev/null 
	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop 2>/dev/null
fi
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract share/applications/*$app*.desktop 2>/dev/null 
	mv squashfs-root/share/applications/*.desktop ./$APP.desktop 2>/dev/null
fi
CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $app | head -1)
sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop
sed -i "s#AppRun#$APP#g" ./$APP.desktop
sed -i "s#Exec=/bin/#Exec=#g" ./$APP.desktop
sed -i "s#Exec=/usr/bin/#Exec=#g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop

mkdir icons
mv $(./$APP --appimage-extract *.png) ./icons/$APP 2>/dev/null
mv $(./$APP --appimage-extract *.svg) ./icons/$APP 2>/dev/null
./$APP --appimage-extract share/icons/*/*/*/* 2>/dev/null
./$APP --appimage-extract usr/share/icons/*/*/*/* 2>/dev/null
./$APP --appimage-extract share/icons/*/*/*/* 2>/dev/null
./$APP --appimage-extract usr/share/icons/*/*/*/* 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/22x22/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/24x24/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/32x32/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/48x48/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/64x64/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/128x128/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/256x256/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/512x512/apps/*$app* ./icons/$APP 2>/dev/null
mv ./squashfs-root/usr/share/icons/hicolor/scalable/apps/*$app* ./icons/$APP 2>/dev/null

rm -R -f /opt/$APP/squashfs-root
mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 digiKam is provided by https://www.digikam.org
  
";
