#!/bin/sh

APP=discord

mkdir /opt/$APP
cd /opt/$APP
mkdir tmp
cd ./tmp
wget -r -A .AppImage -nd https://github.com/srevinsaju/discord-appimage/releases/tag/stable
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rm -R /opt/discord/tmp

echo '#!/bin/sh
cd /opt/discord
appimageupdate -O discord
rm *zs-old
exec /opt/discord/discord' >> /usr/local/bin/discord
chmod a+x /usr/local/bin/discord

echo "[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=discord
Icon=/opt/discord/discord.svg
Type=Application
Categories=Network;InstantMessaging;" >> /usr/share/applications/$APP.desktop

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

echo '#!/bin/sh
rm -R -f /opt/discord /usr/share/applications/discord.desktop /usr/local/bin/discord' >> /opt/discord/remove
chmod a+x /opt/discord/remove

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 Discord AppImage has been installed!

"
