#!/bin/sh

APP=discord

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/bin/$APP /usr/share/applications/$APP.desktop" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
wget -r -A .AppImage -nd https://github.com/srevinsaju/discord-appimage/releases/tag/stable
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP

cd ./tmp
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
chmod a+x ./updater

rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM

val1='"$1"'
val2='"$@"'

echo '#!/bin/sh' >> /usr/bin/$APP
echo "APP=$APP" >> /usr/bin/$APP
echo 'cd /opt/$APP
./updater -O ./$APP
chmod a+x /opt/$APP/$APP
rm -R -f /opt/$APP/*zs-old && rm -R -f /opt/$APP/*.part' >> /usr/bin/$APP
echo "
  case "$val1" in
  $APP) exec /opt/$APP/$APP ;;
  *) exec /opt/$APP/$APP "$val2" ;;
esac
fi" >> /usr/bin/$APP
chmod a+x /usr/bin/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=discord
Icon=/opt/discord/discord.svg
Type=Application
Categories=Network;InstantMessaging;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " Discord AppImage is provided by https://github.com/srevinsaju ";
echo "";
