#!/bin/sh

echo ""
echo " 
 Double Commander is a free cross platform open source file manager
 with two panels side by side. It is inspired by Total Commander and
 features some new ideas. 
  
  1) Double Commander GTK version

  2) Double Commander QT version
"
read -r -p " What do you choose between 1 and 2? " response
case "$response" in
    1) APP=doublecmd-gtk
URL=https://rsync.opensuse.org/repositories/home:/Alexx2000/AppImage/doublecmd-gtk-latest-x86_64.AppImage

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp;
cd ./tmp;
wget $URL;
wget $URL.zsync;
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*mage.zsync ./$APP.zsync
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "cd /opt/$APP
mkdir tmp
cd ./tmp
wget $URL.zsync;
cd ..
mv ./tmp/*mage.zsync ./$APP.zsync
rmdir ./tmp
zsync /opt/$APP/$APP.zsync
rm -R -f /opt/$APP/*zs-old /opt/$APP/*.part
chmod a+x /opt/$APP/$APP" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Name=Double Commander (GTK)
Comment=Double Commander is a cross platform open source file manager with two panels side by side.
Terminal=false
Icon=/opt/$APP/$APP.png
Exec=$APP %F
Type=Application
MimeType=inode/directory;
Categories=Utility;FileTools;FileManager;
Keywords=folder;manager;explore;disk;filesystem;orthodox;copy;queue;queuing;operations;
Comment[ru]=Double Commander — это кроссплатформенный двухпанельный файловый менеджер с открытым кодом." >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://doublecmd.sourceforge.io/site/images/logo.png -O $APP.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP;;

    2) APP=doublecmd-qt
URL=https://rsync.opensuse.org/repositories/home:/Alexx2000/AppImage/doublecmd-qt-latest-x86_64.AppImage

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp;
cd ./tmp;
wget $URL;
wget $URL.zsync;
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
mv ./tmp/*mage.zsync ./$APP.zsync
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "cd /opt/$APP
mkdir tmp
cd ./tmp
wget $URL.zsync;
cd ..
mv ./tmp/*mage.zsync ./$APP.zsync
rmdir ./tmp
zsync /opt/$APP/$APP.zsync
rm -R -f /opt/$APP/*zs-old /opt/$APP/*.part
chmod a+x /opt/$APP/$APP" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
echo "[Desktop Entry]
Name=Double Commander (QT)
Comment=Double Commander is a cross platform open source file manager with two panels side by side.
Terminal=false
Icon=/opt/$APP/$APP.png
Exec=$APP %F
Type=Application
MimeType=inode/directory;
Categories=Utility;FileTools;FileManager;
Keywords=folder;manager;explore;disk;filesystem;orthodox;copy;queue;queuing;operations;
Comment[ru]=Double Commander — это кроссплатформенный двухпанельный файловый менеджер с открытым кодом." >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://doublecmd.sourceforge.io/site/images/logo.png -O $APP.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP;;
    *) echo ""; echo " No valid argument was chosen: installation aborted! "; rm -f /opt/am/.cache/double-commander; echo "";;
esac


echo "

 Double Commander is provided by https://doublecmd.sourceforge.io
  
";