#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 

set -u
APP=dunst
SITE="Samueru-sama/dunst-AppImage"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
echo "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
echo "rm -f /usr/local/bin/dunstctl" >> "/opt/$APP/remove"
echo "rm -f /usr/local/bin/dunstify" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP
# $version is also used for updates

version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*continuous.*dunst.*86_64.*mage$' | head -1)
wget "$version" && echo "$version" > "/opt/$APP/version" || exit 1
cd ..
mv --backup=t ./tmp/*"$APP"* ./"$APP"
rm -R -f ./tmp || exit 1

# Wrappers for dunstctl and dunstify
echo '#!/bin/sh\ndunst ctl "$@"' > "/opt/$APP/dunstctl"
echo '#!/bin/sh\ndunst notify "$@"' > "/opt/$APP/dunstify"
chmod a+x "/opt/$APP/$APP"* || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
ln -s "/opt/$APP/dunstctl" /usr/local/bin/dunstctl
ln -s "/opt/$APP/dunstify" /usr/local/bin/dunstify

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
APP=dunst
SITE="Samueru-sama/dunst-AppImage"
if [ -z "$APP" ]; then exit 1; fi
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*continuous.*dunst.*86_64.*mage$' | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	notify-send "A new version of $APP is available, please wait"
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	wget "$version" || exit 1
	cd ..
	mv --backup=t ./tmp/*"$APP"* ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	chmod a+x "/opt/$APP/$APP" || exit 1
	notify-send "$APP is updated!"
	exit 0
fi
echo "Update not needed!"
EOF
chmod a+x "/opt/$APP/AM-updater"
