#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=eden
SITE="eden-emulator/Releases"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
read -r -p "
 Choose which version of $APP AppImage to use:

 1) AMD64 (PGO)
 2) AMD64 (STANDARD)
 3) LEGACY (PGO)
 4) LEGACY (STANDARD)
 5) ROG-ALLY (PGO)
 6) ROG-ALLY (STANDARD)
 7) STEAMDECK (PGO)
 8) STEAMDECK (STANDARD)

 Which version you choose (type a number and press ENTER)?" response
RELEASE=""
case "$response" in
	1) RELEASE="amd64"; CLASS="pgo";;
	2) RELEASE="amd64"; CLASS="standard";;
	3) RELEASE="legacy"; CLASS="pgo";;
	4) RELEASE="legacy"; CLASS="standard";;
	5) RELEASE="rog"; CLASS="pgo";;
	6) RELEASE="rog"; CLASS="standard";;
	7) RELEASE="steamdeck"; CLASS="pgo";;
	8) RELEASE="steamdeck"; CLASS="standard";;
esac
[ -z "$RELEASE" ] && exit 1

version=$(curl -Ls https://api.github.com/repos/eden-emulator/Releases/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l\|alpha\|beta\|rc[0-9]\|candidate\|backup\|dev" | grep -i "$RELEASE.*$CLASS" | head -1)
if [ -z "$version" ]; then
	printf "\n 💀 ERROR: it seems that upstream removed %b, please retry\n" "$RELEASE" && exit 1
else
	wget "$version" || exit 1
fi
cd ..
mv ./tmp/*mage ./"$APP"
# Keep this space in sync with other installation scripts
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=eden
SITE="eden-emulator/Releases"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/eden-emulator/Releases/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l\|alpha\|beta\|rc[0-9]\|candidate\|backup\|dev" | grep -i "TYPE.*CLASS" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv --backup=t ./tmp/*mage ./"$APP"
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1
sed -i "s/TYPE/$RELEASE/g; s/CLASS/$CLASS/g" /opt/"$APP"/AM-updater

# LAUNCHER & ICON
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./"$APP".desktop ]; then
		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
	fi
	if [ -L ./DirIcon ]; then
		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root
