#!/bin/sh

APP=ember

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://download.opensuse.org/repositories/games:/WorldForge/AppImage/ember-latest-x86_64.AppImage;

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Type=Application
Name=Ember
GenericName=3d client for Worldforge MMORPGs
GenericName[sv]=3d klient för Worldforge MMORPGs
GenericName[tr]=Worldforge MMORPG için 3B İstemci
Icon=/opt/$APP/$APP.svg
Exec=ember
Terminal=false
Categories=Game;RolePlaying;
Keywords=Game;Role Playing;Role-Playing;3D;3-D;Massively;Multiplayer;Online;MMO;MMORPG;Fantasy;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " Ember is provided by https://worldforge.gg ";
echo "";
