#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 
set -u
APP=exodus
SITE="https://exodus.com"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
printf '\n%s' "rm -f /usr/share/applications/AM-$APP.desktop" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(wget -q https://aur.archlinux.org/packages/exodus -O - | tr '"' '\n' | grep "http" | grep ".zip$" | head -1)
if wget --version | head -1 | grep -q ' 1.'; then
	wget --user-agent="Mozilla/5.0" "$version" || exit 1
else
	wget "$version" || exit 1
fi
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x "/opt/$APP/Exodus" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/Exodus" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
set -u
APP=exodus
SITE="https://exodus.com"
version0=$(cat "/opt/$APP/version")
version=$(wget -q https://aur.archlinux.org/packages/exodus -O - | tr '"' '\n' | grep "http" | grep ".zip$" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	if wget --version | head -1 | grep -q ' 1.'; then
		wget --user-agent="Mozilla/5.0" "$version" || exit 1
	else
		wget "$version" || exit 1
	fi
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x "/opt/$APP/Exodus || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
	exit 0
fi
echo "Update not needed!"
EOF
chmod a+x "/opt/$APP/AM-updater"

# ICON
mkdir -p icons
cp ./bin/*.png -O ./icons/"$APP" 2> /dev/null

# LAUNCHER
rm -f /usr/share/applications/AM-"$APP".desktop
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Exodus
Exec=exodus %f
Icon=/opt/$APP/icons/$APP
Comment=All-in-one app to secure, manage and exchange blockchain assets
Categories=Utility;
Terminal=false
StartupNotify=true" >> /usr/share/applications/AM-"$APP".desktop
