#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=fastfetch
SITE="fastfetch-cli/fastfetch"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/fastfetch\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/bin/flashfetch" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi 'https.*linux-amd64.tar.gz$' | head -1)
wget "$version" || exit 1
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
cd ..
mv ./tmp/*/usr/* ./ || exit 1
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x /opt/"$APP"/bin/* || exit 1

# LINK TO PATH
ln -s /opt/"$APP"/bin/* /usr/local/bin

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=fastfetch
SITE="fastfetch-cli/fastfetch"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi 'https.*linux-amd64.tar.gz$' | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	cd ..
	mv --backup=t ./tmp/*/usr/* ./ || exit 1
	chmod a+x /opt/"$APP"/bin/* || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1
