#!/bin/sh

APP=filezilla
SITE="https://filezilla-project.org"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(wget -q https://filezilla-project.org/download.php?platform=linux64 -O - | grep https://dl | cut -d '"' -f 4)
wget $version
echo "$version" >> /opt/$APP/version
tar fx ./*; rm -R -f ./*tar*
cd ..
mv --backup=t ./tmp/FileZilla3/* ./
rm -R -f ./tmp

# LINK
echo '#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}"/bin/:"${PATH}"
export LD_LIBRARY_PATH="${HERE}"/lib/:"${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${HERE}"/usr/share/filezilla/:"${XDG_DATA_DIRS}"
exec "${HERE}"/bin/filezilla' >> /opt/$APP/$APP
chmod a+x /opt/$APP/$APP
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=filezilla
version0=$(cat /opt/$APP/version)
version=$(wget -q https://filezilla-project.org/download.php?platform=linux64 -O - | grep https://dl | cut -d '"' -f 4)
if [ $version = $version0 ]; then
	echo "Update not needed!"
else
	notify-send "A new version of $APP is available, please wait"
	mkdir /opt/$APP/tmp
	cd /opt/$APP/tmp
	wget $version
	tar fx ./*; rm -R -f ./*tar*
	cd ..
	mv --backup=t ./tmp/FileZilla3/* ./
	rm ./version
	echo $version >> ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# ICON
mkdir icons
wget https://portable-linux-apps.github.io/icons/filezilla.png -O ./icons/$APP 2> /dev/null

# LAUNCHER
rm -f /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=FileZilla
GenericName=FTP client
GenericName[da]=FTP-klient
GenericName[de]=FTP-Client
GenericName[fr]=Client FTP
Comment=Download and upload files via FTP, FTPS and SFTP
Comment[da]=Download og upload filer via FTP, FTPS og SFTP
Comment[de]=Dateien über FTP, FTPS und SFTP übertragen
Comment[fr]=Transférer des fichiers via FTP, FTPS et SFTP
Exec=filezilla
Terminal=false
Icon=/opt/$APP/icons/$APP
Type=Application
Categories=Network;FileTransfer;
Version=1.0" >> /usr/share/applications/AM-$APP.desktop
