#!/bin/sh

mkdir /opt/firefox-beta
cd /opt/firefox-beta

echo "#!/bin/sh
rm -R -f /opt/firefox-beta /usr/share/applications/AM-firefox-beta.desktop /usr/local/bin/firefox-beta" >> /opt/firefox-beta/remove
chmod a+x /opt/firefox-beta/remove

mkdir tmp;
cd ./tmp;

LANGUAGE=$(wget -q https://raw.githubusercontent.com/linuxmint/mdm/master/config/locale.alias -O - | grep -i "$LANG" | grep -o '^\S*')
CODE=$(wget -q https://releases.mozilla.org/pub/firefox/releases/latest/README.txt -O - | cut -d ':' -f2 | grep -i $LANGUAGE | cut -d '=' -f2)
wget "https://download.mozilla.org/?product=firefox-beta-latest&os=linux64&lang=$CODE" --trust-server-names

tar fx firefox-*.tar.bz2
cd ..
mv ./tmp/firefox/* ./
rm -R ./tmp



ln -s /opt/firefox-beta/firefox /usr/local/bin/firefox-beta

rm -R -f /usr/share/applications/AM-firefox-beta.desktop
echo "[Desktop Entry]
Name=Firefox Beta
Comment=Web Browser
Exec=/opt/firefox-beta/firefox %u
Terminal=false
Type=Application
Icon=/opt/firefox-beta/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Actions=Private;

[Desktop Action Private]
Exec=/opt/firefox-beta/firefox --private-window %u
Name=Open in private mode"  >> /usr/share/applications/AM-firefox-beta.desktop
