#!/bin/sh

mkdir /opt/firefox-esr
cd /opt/firefox-esr
mkdir tmp;
cd ./tmp;
wget "https://download.mozilla.org/?product=firefox-esr-latest&os=linux64&lang=en-US" --trust-server-names
tar fx firefox-*.tar.bz2
cd ..
mv ./tmp/firefox/* ./
rm -R ./tmp

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/firefox-esr

ln -s /opt/firefox-esr/firefox /usr/local/bin/firefox-esr

rm -R -f /usr/share/applications/firefox-esr.desktop
echo "[Desktop Entry]
Name=Firefox ESR
Comment=Web Browser
Exec=/opt/firefox-esr/firefox %u
Terminal=false
Type=Application
Icon=/opt/firefox-esr/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Actions=Private;

[Desktop Action Private]
Exec=/opt/firefox-esr/firefox --private-window %u
Name=Open in private mode"  >> /usr/share/applications/firefox-esr.desktop

echo "#!/bin/sh
rm -R -f /opt/firefox-esr /usr/share/applications/firefox-esr.desktop /usr/local/bin/firefox-esr" >> /opt/firefox-esr/remove
chmod a+x /opt/firefox-esr/remove

echo "";
echo " Firefox ESR has been installed! ";
echo "";
