#!/bin/sh

APP=flameshot
URL=https://github.com/flameshot-org/flameshot/releases/latest

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget $URL -O - | egrep '/.*/.*/.*AppImage' -o)

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
function1='$(wget '$URL' -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'
echo '#!/bin/sh
APP='$APP'
version0=$(cat /opt/$APP/version)
url='$URL'
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!"
else
  notify-send "A new version of '$APP' is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://github.com/'$function1' | '$function2'
  version='$function3'
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo $version >> ./version
  mv --backup=t ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=Flameshot
Name[zh_CN]=火焰截图
GenericName=Screenshot tool
GenericName[zh_CN]=屏幕截图工具
GenericName[pl]=Zrzuty ekranu
GenericName[fr]=Outil de capture d'écran
GenericName[nl]=Schermfotoprogramma
GenericName[nl_NL]=Schermfotoprogramma
GenericName[ja]=スクリーンショットツール
GenericName[ru]=Создание скриншотов
GenericName[sk]=Nástroj na zachytávanie obrazovky
GenericName[sr]=Снимач екрана
GenericName[uk]=Інструмент скриншотів
GenericName[es]=Herramienta de captura de pantalla
GenericName[pt_BR]=Ferramenta de captura de tela
Comment=Powerful yet simple to use screenshot software.
Comment[zh_CN]=强大又易用的屏幕截图软件
Comment[pl]=Proste w użyciu narzędzie do zrzutów ekranu
Comment[fr]=Logiciel de capture d'écran puissant et simple d'utilisation.
Comment[nl]=Een eenvoudig doch krachtig schermfotoprogramma.
Comment[nl_NL]=Een eenvoudig doch krachtig schermfotoprogramma.
Comment[ja]=パワフルで使いやすいスクリーンショットソフトウェア。
Comment[ru]=Простой и функциональный инструмент для создания скриншотов
Comment[sk]=Mocný, no zároveň jednoduchý softvér na zachytávanie obrazovky.
Comment[sr]=Једноставан, а моћан алат за снимање екрана
Comment[uk]=Потужний простий у використанні додаток для створення знімків екрану.
Comment[es]=Software de captura de pantalla potente y fácil de usar.
Comment[de]=Schlichte, leistungsstarke Screenshot-Software
Comment[pt_BR]=Software de captura de tela poderoso, mas simples de usar.
Keywords=flameshot;screenshot;capture;shutter;
Keywords[zh_CN]=flameshot;screenshot;capture;shutter;截图;屏幕;
Keywords[fr]=flameshot;capture d'écran;capter;shutter;
Keywords[ja]=flameshot;screenshot;capture;shutter;スクリーンショット;キャプチャー;
Keywords[nl]=flameshot;schermfoto;screenshot;schermafdruk;vastleggen;schermopname;
Keywords[nl_NL]=flameshot;schermfoto;screenshot;schermafdruk;vastleggen;schermopname;
Keywords[es]=flameshot;screenshot;capture;shutter;captura;
Keywords[de]=flameshot;screenshot;Bildschirmfoto;Aufnahme;
Keywords[pt_BR]=flameshot;screenshot;captura de tela;captura;shutter;
Exec=flameshot
Icon=/opt/$APP/apple-touch-icon.png
Terminal=false
Type=Application
Categories=Graphics;
StartupNotify=false
StartupWMClass=flameshot
Actions=Configure;Capture;Launcher;
X-DBUS-StartupType=Unique
X-DBUS-ServiceName=org.flameshot.Flameshot
X-KDE-DBUS-Restricted-Interfaces=org.kde.kwin.Screenshot,org.kde.KWin.ScreenShot2

[Desktop Action Configure]
Name=Configure
Name[zh_CN]=配置
Name[pl]=Konfiguruj
Name[fr]=Configurer
Name[ja]=設定
Name[ru]=Настройки
Name[sk]=Nastaviť
Name[nl]=Instellen
Name[nl_NL]=Instellen
Name[sr]=Подешавања
Name[uk]=Налаштувати
Name[es]=Configurar
Name[de]=Einstellungen
Name[pt_BR]=Configurar
Exec=flameshot config

[Desktop Action Capture]
Name=Take screenshot
Name[zh_CN]=进行截图
Name[pl]=Zrzut ekranu
Name[fr]=Prendre une capture d'écran
Name[ja]=スクリーンショットを撮る
Name[ru]=Сделать скриншот
Name[sk]=Zachytiť obrazovku
Name[sr]=Сними екран
Name[uk]=Зробити знімок
Name[nl]=Schermfoto maken
Name[nl_NL]=Schermfoto maken
Name[es]=Tomar captura de pantalla
Name[de]=Bildschirmfoto aufnehmen
Name[pt_BR]=Capturar tela
Exec=flameshot gui --delay 500

[Desktop Action Launcher]
Name=Open launcher
Name[de]=Starter öffnen
Name[nl]=Starter openen
Name[nl_NL]=Starter openen
Name[sk]=Otvoriť spúšťač
Name[zh_CN]=打开启动器
Name[pt_BR]=Abrir lançador
Exec=flameshot launcher" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://flameshot.org/apple-touch-icon.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo '

	FlameShot is provided by https://flameshot.org

'
