#!/bin/sh

APP=freecad

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

version=$(wget -q https://www.freecadweb.org/downloads.php -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*.x86_64.AppImage")
wget $version
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=freecad
version0=$(cat /opt/$APP/version)
version=$(wget -q https://www.freecadweb.org/downloads.php -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*.x86_64.AppImage")
if [ $version0 = $version ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  version=$(wget -q https://www.freecadweb.org/downloads.php -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*.x86_64.AppImage")
  wget $version
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo $version >> ./version
  mv --backup=t ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Version=1.0
Name=FreeCAD
Exec=freecad
Icon=/opt/$APP/icons/$APP
Type=Application
Categories=Engineering;
Comment=Feature based Parametric Modeler
Terminal=false
StartupNotify=true
NoDisplay=false
MimeType=application/x-extension-fcstd;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir ./icons
wget https://raw.githubusercontent.com/FreeCAD/FreeCAD/master/src/Gui/Icons/freecad-icon-64.png -O /opt/$APP/icons/$APP


# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " FreeCAD is provided by https://www.freecadweb.org ";
echo "";
