#!/bin/sh

APP=gamehub

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/tkashkin/GameHub/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "APP=$APP" >> /usr/local/bin/$APP
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/tkashkin/GameHub/releases/latest' >> /usr/local/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/local/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/local/bin/$APP
echo "  exec /opt/$APP/$APP" >> /usr/local/bin/$APP
echo 'else' >> /usr/local/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/local/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/local/bin/$APP

########################################################################################

function1='$(wget https://github.com/tkashkin/GameHub/releases/latest -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'

echo "  wget https://github.com/$function1 | $function2
  version=$function3" >> /usr/local/bin/$APP

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /usr/local/bin/$APP
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
  exec /opt/$APP/$APP
fi" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=GameHub
GenericName=GameHub
Comment[ru]=Все игры в одном месте
Comment[pt_BR]=Todos os seus jogos em um só lugar
Comment[pt_PT]=Todos os seus jogos num só lugar
Comment[id]=Semua permainan Anda di satu tempat
Comment[nb_NO]=Alle dine spill på ett sted
Comment[nl]=Al je spellen op één plek
Comment[de]=Alle Ihre Spiele an einem Ort
Comment[fr]=Tous vos jeux en un endroit
Comment[pl]=Wszystkie twoje gry w jednym miejscu
Comment[tr]=Tüm oyunlarınızı tek bir yerde
Comment[fa]=همه بازی های شما در یک مکان
Comment[ar]=كل ألعابك في مكان واحد
Comment[ca]=Tots els teus jocs en un lloc
Comment[fi]=Kaikki pelisi yhdessä paikassa
Comment[es_MX]=Todos tus juegos en un solo lugar
Comment[it]=Tutti i tuoi giochi in un unico posto
Comment[zh_CN]=将您所有的游戏都整合到同一个地方
Comment[hr]=Sve vaše igre na jednom mjestu
Comment[es]=Todos sus juegos en un solo lugar
Comment[pt]=Todos os seus jogos num só lugar
Comment[eo]=Ĉiuj viaj ludoj en unu loko
Comment[sv]=Alla dina spel på ett ställe
Comment=All your games in one place
Categories=Game;Amusement;
Keywords=Game;Hub;Steam;GOG;Humble;HumbleBundle;
Exec=gamehub
X-GNOME-Gettext-Domain=com.github.tkashkin.gamehub
Icon=/opt/$APP/$APP.svg
Terminal=false
Type=Application" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " GameHub is provided by https://tkashkin.tk ";
echo "";
