#!/bin/sh

APP=gifcurry

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

REPO=lettier/gifcurry
version=$(curl -s https://api.github.com/repos/$REPO/releases | grep browser_download_url | cut -d '"' -f 4 | head -1)
wget $version

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=gifcurry
version0=$(cat /opt/$APP/version)

url=https://github.com/lettier/gifcurry/releases
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!".
else
  notify-send 'A new version of gifcurry is available, please wait'
  mkdir /opt/gifcurry/tmp
  cd /opt/gifcurry/tmp
  REPO=lettier/gifcurry
  version=$(curl -s https://api.github.com/repos/$REPO/releases | grep browser_download_url | cut -d '"' -f 4 | head -1)
  wget $version
  version=$(ls /opt/$APP/tmp)
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version
  mv ./tmp/*mage ./gifcurry
  chmod a+x /opt/gifcurry/gifcurry
  rmdir ./tmp
fi
EOF
chmod a+x ./AM-updater

# LAUNCHER
echo "[Desktop Entry]
Type=Application
Name=Gifcurry
Comment=The open-source, Haskell-built video editor for GIF makers.
Icon=/opt/$APP/$APP.svg
Categories=AudioVideo;Video;Graphics;Utility;
Terminal=false
Exec=gifcurry" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " Gifcurry is provided by https://github.com/lettier/gifcurry ";
echo "";
