#!/bin/sh

APP=godot
SITE="godotengine/godot"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(wget -q https://api.github.com/repos/godotengine/godot/releases -O - | grep browser_download_url | grep -i linux.x86_64.zip  | cut -d '"' -f 4 | head -1)
wget $version
echo "$version" >> /opt/$APP/version
unzip -qq ./*; rm -R -f ./*.zip
cd ..
mv --backup=t ./tmp/* ./$APP
rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=godot
version0=$(cat /opt/$APP/version)
version=$(wget -q https://api.github.com/repos/godotengine/godot/releases -O - | grep browser_download_url | grep -i linux.x86_64.zip  | cut -d '"' -f 4 | head -1)
if [ $version = $version0 ]; then
	echo "Update not needed!"
else
	notify-send "A new version of $APP is available, please wait"
	mkdir /opt/$APP/tmp
	cd /opt/$APP/tmp
	wget $version
	unzip -qq ./*; rm -R -f ./*.zip
	cd ..
	mv --backup=t ./tmp/* ./$APP
	rm ./version
	echo $version >> ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# ICON
mkdir icons
wget https://portable-linux-apps.github.io/icons/godot.png -O ./icons/$APP 2> /dev/null

# LAUNCHER
rm -f /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=Godot Engine
Exec=$APP
Icon=/opt/$APP/icons/$APP
Type=Application
Terminal=false
Categories=Development;" >> /usr/share/applications/AM-$APP.desktop



