#!/bin/sh

APP=goglauncher

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://gitlab.com/Aztorius/GOGLauncher/-/jobs/75423350/artifacts/raw/GOGLauncher-x86_64.AppImage;

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]

Type=Application
Version=1.0
Name=GOGLauncher
Comment=GOG Games Launcher
Exec=goglauncher
Icon=/opt/$APP/$APP.svg
Terminal=false
Categories=Game;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " GOGLauncher is provided by https://gitlab.com/Aztorius ";
echo "";
