#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=jellyfin
SITE="https://jellyfin.org"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(echo "https://repo.jellyfin.org/files/server/linux/latest-stable/amd64/$(curl -Ls https://repo.jellyfin.org/files/server/linux/latest-stable/amd64/ | tr '"' '\n' | grep -i "tar.gz$" | head -1)")
wget "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./$APP || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=jellyfin
SITE="https://jellyfin.org"
version0=$(cat "/opt/$APP/version")
version=$(echo "https://repo.jellyfin.org/files/server/linux/latest-stable/amd64/$(curl -Ls https://repo.jellyfin.org/files/server/linux/latest-stable/amd64/ | tr '"' '\n' | grep -i "tar.gz$" | head -1)")
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://raw.githubusercontent.com/jellyfin/jellyfin-media-player/master/resources/images/icon.png -O ./icons/"$APP" 2> /dev/null

# LAUNCHER
echo "[Desktop Entry]
Version=1.0
Name=Jellyfin Media Player
Comment=Desktop client for Jellyfin
Exec=$APP
Icon=/opt/$APP/icons/$APP
Terminal=false
Type=Application
StartupWMClass=com.github.iwalton3.jellyfin-media-player
Categories=AudioVideo;Video;Player;TV;

Actions=DesktopF;DesktopW;TVF;TVW

[Desktop Action DesktopF]
Name=Desktop [Fullscreen]
Exec=$APP --fullscreen --desktop

[Desktop Action DesktopW]
Name=Desktop [Windowed]
Exec=$APP --windowed --desktop

[Desktop Action TVF]
Name=TV [Fullscreen]
Exec=$APP --fullscreen --tv

[Desktop Action TVW]
Name=TV [Windowed]
Exec=$APP --windowed --tv" > /usr/local/share/applications/"$APP"-AM.desktop
