#!/bin/sh

APP=junest
REPO="fsquillace/junest"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP /usr/local/bin/sudoj" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

wget https://github.com/fsquillace/junest/archive/refs/heads/master.zip
cd ..
unzip -qq ./tmp/master.zip -d ./tmp/ && mv ./tmp/junest-master/*/ . && ln -s ./bin/* . && ln -s /opt/$APP/sudoj /usr/local/bin/sudoj
rm -R -f ./tmp
echo "latest" ./version

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP




