#!/bin/sh

APP=katomic

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimagetool/appimagetool
wget https://github.com/ivan-hc/AppMan/raw/main/applications/pkg2appimage/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: unstable
  sources:
    - deb http://ftp.us.debian.org/debian/ unstable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KAtomic
Name[af]=Katomic
Name[be]=KAtomic
Name[bn]=কে-অ্যাটমিক
Name[br]=KAtomic
Name[bs]=KAtomic
Name[ca]=KAtomic
Name[ca@valencia]=KAtomic
Name[cs]=KAtomic
Name[cy]=KAtomic
Name[da]=KAtomic
Name[de]=KAtomic
Name[el]=KAtomic
Name[en_GB]=KAtomic
Name[eo]=KAtomic
Name[es]=KAtomic
Name[et]=KAtomic
Name[eu]=KAtomic
Name[fa]=اتمی
Name[fi]=KAtomic
Name[fr]=KAtomic
Name[ga]=KAtomic
Name[gl]=KAtomic
Name[he]=KAtomic
Name[hne]=के-एटामिक
Name[hr]=KAtomic
Name[hu]=KAtomic
Name[id]=KAtomic
Name[is]=KAtomic
Name[it]=KAtomic
Name[ja]=KAtomic
Name[kk]=KAtomic
Name[km]=KAtomic
Name[ko]=KAtomic
Name[lt]=KAtomic
Name[lv]=KAtomic
Name[mk]=KAtomic
Name[mr]=के-एटॉमिक
Name[nb]=KAtomic
Name[nds]=KAtomic
Name[ne]=केडीई एटोमिक
Name[nl]=KAtomic
Name[nn]=KAtomic
Name[pa]=ਕੇ-ਪਰਮਾਣੂ
Name[pl]=Atomy
Name[pt]=KAtomic
Name[pt_BR]=KAtomic
Name[ro]=KAtomic
Name[ru]=KAtomic
Name[se]=KAtomic
Name[sk]=KAtomic
Name[sl]=KAtomic
Name[sq]=KAtomic
Name[sr]=К‑атомика
Name[sr@ijekavian]=К‑атомика
Name[sr@ijekavianlatin]=K‑atomika
Name[sr@latin]=K‑atomika
Name[sv]=Katom
Name[ta]=கேஅடாமிக்
Name[te]=కెఎటామిక్
Name[tg]=KАтомҳо
Name[tr]=KAtomic
Name[ug]=KAtomic
Name[uk]=Веселі атоми
Name[vi]=KAtomic
Name[wa]=KAtomic
Name[xh]=KAtomic
Name[x-test]=xxKAtomicxx
Name[zh_CN]=KAtomic
Name[zh_TW]=KAtomic 原子
Icon=/opt/$APP/$APP.svg
Type=Application
Exec=katomic -qwindowtitle %c
X-DocPath=katomic/index.html
GenericName=Sokoban-like Logic Game
GenericName[be]=Лагічная гульня тыпу Sokoban
GenericName[bn]=সোকোবান-এর মত যুক্তির খেলা
GenericName[bs]=Logička igra poput Sokoban-a
GenericName[ca]=Joc de lògica similar al Sokoban
GenericName[ca@valencia]=Joc de lògica similar al Sokoban
GenericName[cs]=Logická hra jako Sokoban
GenericName[cy]=Gêm Resymeg sy'n debyg i Sokoban
GenericName[da]=Sokoban-lignende logisk spil
GenericName[de]=„Sokoban“-Spiel
GenericName[el]=Παιχνίδι λογικής παρόμοιο με το Sokoban
GenericName[en_GB]=Sokoban-like Logic Game
GenericName[eo]=Logikludo simila al Sokoban
GenericName[es]=Juego de lógica similar al Sokoban
GenericName[et]=Sokobani moodi loogikamäng
GenericName[eu]=Sokoban-en antzeko joko logikoa
GenericName[fa]=بازی منطق شبیه Sokoban
GenericName[fi]=Sokoban-tyylinen logiikkapeli
GenericName[fr]=Jeu de logique dans le style de Sokoban
GenericName[ga]=Cluiche Loighce Cosúil le Sokoban
GenericName[gl]=Xogo de lóxica ao estilo do Sokoban
GenericName[he]=חיקוי Sokoban, משחק לוגי
GenericName[hne]=सोकोबान जइसन तर्क वाले खेल
GenericName[hr]=Logička igra poput Sokobana
GenericName[hu]=Sokoban-szerű logikai játék
GenericName[id]=Permainan Logika Seperti Sokoban
GenericName[is]=Leikur sem líkist Sokoban
GenericName[it]=Gioco di logica simile a Sokoban
GenericName[ja]=倉庫番のような論理ゲーム
GenericName[kk]=Сокобан-секілді логикалық ойын
GenericName[km]=ល្បែង​តក្ក​ដូច Sokoban
GenericName[ko]=소코반 같은 전략 게임
GenericName[lt]=Sokoban tipo loginis žaidimas
GenericName[lv]=Sokoban līdzīga loģiskā spēle
GenericName[mk]=Логичка игра слична на Сокобан
GenericName[nb]=Sokoban-lignende logikkspill
GenericName[nds]=Sokoban-liek Logikspeel
GenericName[ne]=सोकोबान जस्तै तार्किक खेल
GenericName[nl]=Sokoban-achtig logisch spel
GenericName[nn]=Sokoban-liknande logikkspel
GenericName[pl]=Gra logiczna typu Sokoban
GenericName[pt]=Jogo de Lógica tipo Sokoban
GenericName[pt_BR]=Jogo Lógico parecido com Sokoban
GenericName[ro]=Un joc de logică ca Sokoban
GenericName[ru]=Составление молекул, клон Sokoban
GenericName[se]=Sokoban-lágan logihkkaspeallu
GenericName[sk]=Logická hra ako Sokoban
GenericName[sl]=Logična igra podobna Sokobanu
GenericName[sq]=Lojë logjike e ngjajshme me Sokoban
GenericName[sr]=Логичка игра налик на Сокобан
GenericName[sr@ijekavian]=Логичка игра налик на Сокобан
GenericName[sr@ijekavianlatin]=Logička igra nalik na Sokoban
GenericName[sr@latin]=Logička igra nalik na Sokoban
GenericName[sv]=Sokoban-liknande logiskt spel
GenericName[ta]=சோகோபான் போன்ற லாஜிக் விளையாட்டு
GenericName[tr]=Sokoban-benzeri Mantık Oyunu
GenericName[ug]=Sokoban غا ئوخشايدىغان لوگىكىلىق ئويۇن
GenericName[uk]=Гра на логіку подібна до Сокобану
GenericName[wa]=Djeu di lodjike rishonnant a sokoban
GenericName[x-test]=xxSokoban-like Logic Gamexx
GenericName[zh_CN]=类似推箱子的逻辑游戏
GenericName[zh_TW]=倉庫番(sokoban)式的智力遊戲
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.katomic" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
