#!/bin/sh

APP=kbounce

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KBounce
Name[af]=K-hop
Name[be]=Несуцішныя шарыкі
Name[bn]=কে-বাউন্স
Name[br]=KBounce
Name[bs]=KBounce
Name[ca]=KBounce
Name[ca@valencia]=KBounce
Name[cs]=KBounce
Name[cy]=KBounce
Name[da]=KBounce
Name[de]=KBounce
Name[el]=KBounce
Name[en_GB]=KBounce
Name[eo]=KBounce
Name[es]=KBounce
Name[et]=KBounce
Name[eu]=KBounce
Name[fa]=پرش
Name[fi]=KBounce
Name[fr]=KBounce
Name[ga]=KBounce
Name[gl]=KBounce
Name[he]=KBounce
Name[hi]=के-बाउंस
Name[hne]=के-बाउंस
Name[hr]=KBounce
Name[hu]=KBounce
Name[id]=KBounce
Name[is]=KBounce
Name[it]=KBounce
Name[ja]=KBounce
Name[kk]=KBounce
Name[km]=KBounce
Name[ko]=KBounce
Name[lt]=KBounce
Name[lv]=KBounce
Name[mk]=KBounce
Name[mr]=के-बाउंस
Name[nb]=KBounce
Name[nds]=KBounce
Name[ne]=केडीई उफ्रिने
Name[nl]=KBounce
Name[nn]=KBounce
Name[pa]=ਕੇ-ਬਾਊਂਸ
Name[pl]=KOdbij
Name[pt]=KBounce
Name[pt_BR]=KBounce
Name[ro]=Bilă săritoare
Name[ru]=KBounce
Name[se]=KBounce
Name[sk]=KBounce
Name[sl]=KBounce
Name[sq]=KBounce
Name[sr]=К‑одбој
Name[sr@ijekavian]=К‑одбој
Name[sr@ijekavianlatin]=K‑odboj
Name[sr@latin]=K‑odboj
Name[sv]=Kstuds
Name[ta]=கேபவுன்ஸ்
Name[tg]=KТӯби ҷаҳанда
Name[tr]=KBounce
Name[ug]=KBounce
Name[uk]=KBounce
Name[vi]=KBounce
Name[wa]=KBounce
Name[xh]=KBounce
Name[x-test]=xxKBouncexx
Name[zh_CN]=KBounce
Name[zh_TW]=KBounce 彈力球

Type=Application
Exec=kbounce -qwindowtitle %c
X-DocPath=kbounce/index.html
Icon=/opt/$APP/$APP.svg

GenericName=Ball Bouncing Game
GenericName[bs]=Igra lopta koja odskače
GenericName[ca]=Un joc de pilotes que reboten
GenericName[ca@valencia]=Un joc de pilotes que reboten
GenericName[cs]=Hra s poskakujícími míčky
GenericName[da]=Et spil med hoppende bolde
GenericName[de]=Bälle einfangen
GenericName[el]=Παιχνίδι αναπήδησης μπάλας
GenericName[en_GB]=Ball Bouncing Game
GenericName[eo]=Ludo de saltadantaj pilkoj
GenericName[es]=Juego de pelotas que rebotan
GenericName[et]=Pallipõrgatamise mäng
GenericName[eu]=Pilotak boteak ematen jokoa
GenericName[fa]=بازی پرش توپ‌ها
GenericName[fi]=Pallopeli
GenericName[fr]=Jeu de balles rebondissantes
GenericName[ga]=Cluiche Liathróide Preabtha
GenericName[gl]=Xogo de bólas que botan
GenericName[hi]=उछलती गेंदों के खेल
GenericName[hne]=उछलती गेंदों वाले खेल
GenericName[hu]=Labdajáték
GenericName[id]=Permainan Memantulkan Bola
GenericName[it]=Gioco di rimbalzi di palline
GenericName[ja]=跳ねるボールのゲーム
GenericName[kk]=Доп қағу ойны
GenericName[km]=ល្បែង​បាល់​លោត
GenericName[ko]=튕기는 공 게임
GenericName[lv]=Atlēcošās bumbiņas spēle
GenericName[mr]=चेंडू उडविण्याचा खेळ
GenericName[nb]=Sprettballspill
GenericName[nds]=Speel mit springen Bäll
GenericName[nl]=Stuiterbalspel
GenericName[nn]=Sprettballspel
GenericName[pl]=Gra w odbijanie kul
GenericName[pt]=Jogo de Bolas aos Saltos
GenericName[pt_BR]=Jogo de bolas rebatidas
GenericName[ro]=Joc cu o minge săritoare
GenericName[ru]=Неуёмные шарики
GenericName[sk]=Hra s poskakujúcou loptou
GenericName[sl]=Igra odbijajočih se žogic
GenericName[sq]=Lojë me top që kërcen
GenericName[sr]=Игра одбијајућих лопти
GenericName[sr@ijekavian]=Игра одбијајућих лопти
GenericName[sr@ijekavianlatin]=Igra odbijajućih lopti
GenericName[sr@latin]=Igra odbijajućih lopti
GenericName[sv]=Bollstudsspel
GenericName[tr]=Top Zıplatma Oyunu
GenericName[ug]=توپنى سەكرىتىش ئويۇنى
GenericName[uk]=Гра з відбиття м’ячика
GenericName[x-test]=xxBall Bouncing Gamexx
GenericName[zh_CN]=弹球游戏
GenericName[zh_TW]=彈力球遊戲

Comment=Ball Bouncing Game
Comment[ca]=Un joc de pilotes que reboten
Comment[ca@valencia]=Un joc de pilotes que reboten
Comment[cs]=Hra s poskakujícími míčky
Comment[da]=Et spil med hoppende bolde
Comment[de]=Bälle einfangen
Comment[el]=Παιχνίδι αναπήδησης μπάλας
Comment[en_GB]=Ball Bouncing Game
Comment[es]=Juego de pelotas que rebotan
Comment[et]=Pallipõrgatamise mäng
Comment[fi]=Pallonpomputuspeli
Comment[fr]=Jeu de balles rebondissantes
Comment[gl]=Xogo de bólas que botan
Comment[hi]=उछलती गेंदों के खेल
Comment[hu]=Labdajáték
Comment[id]=Permainan Memantulkan Bola
Comment[it]=Gioco di rimbalzi di palline
Comment[ko]=튕기는 공 게임
Comment[nl]=Spel met stuiterende bal
Comment[nn]=Sprettballspel
Comment[pl]=Gra w odbijanie kul
Comment[pt]=Jogo de Bolas aos Saltos
Comment[pt_BR]=Jogo de bolas rebatidas
Comment[ru]=Неуёмные шарики
Comment[sk]=Hra s poskakujúcou loptou
Comment[sl]=Igra odbijajočih se žogic
Comment[sr]=Игра одбијајућих лопти
Comment[sr@ijekavian]=Игра одбијајућих лопти
Comment[sr@ijekavianlatin]=Igra odbijajućih lopti
Comment[sr@latin]=Igra odbijajućih lopti
Comment[sv]=Bollstudsspel
Comment[tr]=Top Zıplatma Oyunu
Comment[uk]=Гра з відбиття м’ячика
Comment[x-test]=xxBall Bouncing Gamexx
Comment[zh_CN]=弹球游戏
Comment[zh_TW]=彈力球遊戲

X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;ArcadeGame;
X-DBUS-ServiceName=org.kde.kbounce" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
