#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=kdenlive
SITE="https://kdenlive.org"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
kdenlive_url="https://download.kde.org/stable/kdenlive/"
kdenlive_ver=$(curl -Ls "$kdenlive_url" | tr '">< ' '\n' | grep -i "^[0-9].*[0-9]/$" | uniq)
kdenlive_apps=$(for a in $kdenlive_ver; do kdenlive_app=$(curl -Ls "$kdenlive_url$a"linux/ | tr '"><  ' '\n' | grep -i "x86_64.*appimage" | tail -1); [ -n "$kdenlive_app" ] && echo "$kdenlive_url$a"linux/"$kdenlive_app"; done)
version=$(echo "$kdenlive_apps" | tail -1)
wget "$version" || exit 1
# Keep this space in sync with other installation scripts
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
# Keep this space in sync with other installation scripts
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=kdenlive
SITE="https://kdenlive.org"
kdenlive_url="https://download.kde.org/stable/kdenlive/"
kdenlive_ver=$(curl -Ls "$kdenlive_url" | tr '">< ' '\n' | grep -i "^[0-9].*[0-9]/$" | uniq)
kdenlive_apps=$(for a in $kdenlive_ver; do kdenlive_app=$(curl -Ls "$kdenlive_url$a"linux/ | tr '"><  ' '\n' | grep -i "x86_64.*appimage" | tail -1); [ -n "$kdenlive_app" ] && echo "$kdenlive_url$a"linux/"$kdenlive_app"; done)
version0=$(cat "/opt/$APP/version")
version=$(echo "$kdenlive_apps" | tail -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv --backup=t ./tmp/*mage ./"$APP"
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHER & ICON
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./"$APP".desktop ]; then
		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
	fi
	if [ -L ./DirIcon ]; then
		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root

# ROLLBACK SCRIPT
cat >> /opt/"$APP"/"$APP"-rollback << 'EOF'
#!/usr/bin/env bash

APP=kdenlive
rm -f ./rollback-args* ./AM-rollback

# STABLE AND MORE RECENT VERSIONS
STABLE=$(curl -Ls https://download.kde.org/stable/kdenlive/ | grep -o "[0-9][0-9]\.[0-9][0-9]" | uniq | sort -nr)
for var in $STABLE; do
	curl -Ls "https://download.kde.org/stable/kdenlive/$var/linux/" \
	| tr '"' '\n' | grep -i "^kdenlive.*appimage$" | uniq | sort -nr >> "./rollback-args"
done

# ARCHIVED OLD RELEASES (THAT MAY NOT WORK)
ARCHIVED=$(curl -Ls https://download.kde.org/Attic/kdenlive/ | grep -o "[0-9][0-9]\.[0-9][0-9]" | uniq | sort -nr)
for var in $ARCHIVED; do
	curl -Ls "https://download.kde.org/Attic/kdenlive/$var/linux/" \
	| tr '"' '\n' | grep -i "^kdenlive.*appimage$" | uniq | sort -nr >> "./rollback-args"
done

# LET ROLLBACK KDENLIVE
echo "-----------------------------------------------------------------------"
echo "You have chosen to roll back $APP."
echo "Rollback will be done from https://kdenlive.org"
echo "-----------------------------------------------------------------------"
echo "Select a version (read carefully) or press CTRL+C to abort:"
echo "-----------------------------------------------------------------------"
select d in $(cat "./rollback-args"); do
	test -n "$d" && break
	echo ">>> Invalid Selection"
done

# PROCEEDE
rel=$(echo "$d" | cut -c 10- | cut -c -5)
if curl --output /dev/null --silent --head --fail "https://download.kde.org/stable/kdenlive/$rel/linux/$d" 1>/dev/null; then
	dl="https://download.kde.org/stable/kdenlive/$rel/linux/$d"
else
	dl="https://download.kde.org/Attic/kdenlive/$rel/linux/$d"
fi
cp ./AM-updater ./AM-rollback
sed -i 's/version0/#version0/g; s/appimageupdatetool -Or/#appimageupdatetool -Or/g;' ./AM-rollback
if wget --version | head -1 | grep -q ' 1.'; then
	sed -i "/wget /c\wget -q --no-verbose --show-progress --progress=bar \"$dl\"" ./AM-rollback
fi
./AM-rollback
echo "$dl" > ./version
rm -f ./rollback-args* ./AM-rollback
echo ""
echo "ROLLBACK SUCCESSFUL!"
exit
EOF
chmod a+x /opt/"$APP"/"$APP"-rollback
