#!/bin/sh

APP=kfourinline

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KFourInLine
Name[bs]=KFourInLine
Name[ca]=KFourInLine
Name[ca@valencia]=KFourInLine
Name[cs]=Čtyři v řadě
Name[da]=KFourInLine
Name[de]=Vier gewinnt
Name[el]=KFourInLine
Name[en_GB]=KFourInLine
Name[es]=KFourInLine
Name[et]=KFourInLine
Name[eu]=KFourInLine
Name[fa]=چهار-در-یک-خط
Name[fi]=KFourInLine
Name[fr]=KFourInLine
Name[ga]=KFourInLine
Name[gl]=KFourInLine
Name[hi]=के पंक्ति में चार
Name[hne]=केफोरइनलाइन
Name[hu]=Színes vonalak
Name[id]=KFourInLine
Name[it]=KFourInLine
Name[ja]=KFourInLine
Name[kk]=KFourInLine
Name[km]=KFourInLine
Name[ko]=KFourInLine
Name[lt]=KFourInLine
Name[lv]=KFourInLine
Name[mr]=के-फोर-इन-लाइन
Name[nb]=KFourInLine
Name[nds]=KFourInLine
Name[nl]=KFourInLine
Name[nn]=KFourInLine
Name[pl]=KCzteryWLinii
Name[pt]=KFourInLine
Name[pt_BR]=KFourInLine
Name[ro]=KPatruÎnLinie
Name[ru]=KFourInLine
Name[sk]=KFourInLine
Name[sl]=KFourInLine
Name[sq]=KFourInLine
Name[sr]=К‑четири‑у‑низу
Name[sr@ijekavian]=К‑четири‑у‑низу
Name[sr@ijekavianlatin]=K‑četiri‑u‑nizu
Name[sr@latin]=K‑četiri‑u‑nizu
Name[sv]=Fyra i rad
Name[tr]=KFourInLine
Name[ug]=KFourInLine
Name[uk]=Чотири-у-рядку
Name[wa]=KFourInLine
Name[x-test]=xxKFourInLinexx
Name[zh_CN]=KFourInLine
Name[zh_TW]=KFourInLine
GenericName=Four-in-a-row Board Game
GenericName[bs]=Četiri-u-nizu igra na ploči
GenericName[ca]=Joc de quatre en fila
GenericName[ca@valencia]=Joc de quatre en fila
GenericName[da]=Fire-på-række-brætspil
GenericName[de]=Vier-Gewinnt-Brettspiel
GenericName[el]=Επιτραπέζιο παιχνίδι Τέσσερα στη σειρά
GenericName[en_GB]=Four-in-a-row Board Game
GenericName[eo]=Gobanga bretludo
GenericName[es]=Juego de tablero de cuatro en raya
GenericName[et]=Neli ritta lauamäng
GenericName[eu]=Lauko artzain-jokoa
GenericName[fa]=بازی تخته چهار در یک سطر
GenericName[fi]=Neljän suora -lautapeli
GenericName[fr]=Jeu de plateau « Quatre-en-ligne »
GenericName[ga]=Cluiche Cláir ceithre-cinn-as-a-chéile
GenericName[gl]=Xogo de taboleiro «Catro en liña»
GenericName[hi]=बोर्ड में एक पंक्ति में चार का खेल
GenericName[hne]=बोर्ड मं एक लकीर मं चार वाले खेल
GenericName[hu]=Táblás játék
GenericName[id]=Permainan Papan Empat-dalam-sebaris
GenericName[it]=Quattro-in-fila, gioco da tavolo
GenericName[ja]=四目並べ
GenericName[km]=ល្បែង​ក្ដារ បួន​ក្នុង​មួយ​ជួរ
GenericName[ko]=한 줄에 네 개 보드 게임
GenericName[lv]=Četri-rindā galda spēle
GenericName[mr]=एका-ओळीत-चार बोर्ड खेळ
GenericName[nb]=Brettspill fire på rad
GenericName[nl]=Vier-op-een-rij bordspel
GenericName[nn]=Fire på rad
GenericName[pt]=Jogo de Tabuleiro Quatro-em-Linha
GenericName[pt_BR]=Jogo lógico quatro em linha
GenericName[ro]=Joc de table Patru-în-linie
GenericName[ru]=Четыре шарика в линию
GenericName[sl]=Namizna igra Štiri v vrsto
GenericName[sr]=Игра на табли „четири у низу“
GenericName[sr@ijekavian]=Игра на табли „четири у низу“
GenericName[sr@ijekavianlatin]=Igra na tabli „četiri u nizu“
GenericName[sr@latin]=Igra na tabli „četiri u nizu“
GenericName[sv]=Fyra-i-rad brädspel
GenericName[tr]=Bir-satırda-dört Tahta Oyunu
GenericName[ug]=بىر-قۇردا-تۆت تاختا ئويۇنى
GenericName[uk]=Настільна гра «Чотири-у-рядку»
GenericName[wa]=Djeu «cwate e roye»
GenericName[x-test]=xxFour-in-a-row Board Gamexx
GenericName[zh_CN]=四子连珠游戏
GenericName[zh_TW]=四子棋棋盤遊戲
Comment=Classic turn based game
Comment[ca]=Joc clàssic basat en torns
Comment[ca@valencia]=Joc clàssic basat en torns
Comment[cs]=Klasická tahová hra
Comment[da]=Klassisk tur-baseret spil
Comment[de]=Brettspiel für zwei Spieler, das auf dem Spiel „Vier Gewinnt“ basiert.
Comment[el]=Κλασικό παιχνίδι διαδοχής αντιπάλων
Comment[en_GB]=Classic turn based game
Comment[es]=Juego clásico basado en turnos
Comment[et]=Klassikaline käigupõhine mäng
Comment[fi]=Perinteinen vuoroperustainen peli
Comment[fr]=Jeu au tour par tour classique
Comment[gl]=Xogo clásico por quendas.
Comment[hi]= प्रतिष्ठित चाल अधारित खेल
Comment[id]=Permainan berdasarkan giliran yang klasik
Comment[it]=Classico gioco a turni
Comment[ko]=고전 턴제 게임
Comment[nl]=Klassiek beurtelings spel
Comment[nn]=Klassisk turbasert spel
Comment[pl]=Klasyczna gra turowa
Comment[pt]=Jogo clássico por turnos
Comment[pt_BR]=Jogo baseado em turnos clássico
Comment[ru]=Классическая пошаговая игра
Comment[sk]=Klasická ťahová hra
Comment[sl]=Klasična potezna igra
Comment[sr]=Класична игра на потезе
Comment[sr@ijekavian]=Класична игра на потезе
Comment[sr@ijekavianlatin]=Klasična igra na poteze
Comment[sr@latin]=Klasična igra na poteze
Comment[sv]=Klassiskt turbaserat spel
Comment[tr]=Klasik sıra tabanlı oyun
Comment[uk]=Класична покрокова гра
Comment[x-test]=xxClassic turn based gamexx
Comment[zh_CN]=经典的回合制游戏
Comment[zh_TW]=傳統輪流基礎遊戲
Exec=kfourinline
Icon=/opt/$APP/$APP.svg
Terminal=false
Type=Application
X-DocPath=kfourinline/index.html
Categories=Qt;KDE;Game;BoardGame;
X-DBUS-ServiceName=org.kde.kfourinline" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
