#!/bin/sh

APP=kmines

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KMines
Name[af]=Kmyne
Name[be]=Сапёр
Name[bn]=কে-মাইন্স
Name[br]=KMines
Name[bs]=KMines
Name[ca]=KMines
Name[ca@valencia]=KMines
Name[cs]=KMines
Name[cy]=KMines
Name[da]=KMines
Name[de]=KMines
Name[el]=KMines
Name[en_GB]=KMines
Name[eo]=KMines
Name[es]=KMines
Name[et]=KMines
Name[eu]=KMines
Name[fa]=مین‌یاب
Name[fi]=KMines
Name[fr]=KMines
Name[ga]=KMines
Name[gl]=KMines
Name[he]=KMines
Name[hne]=के-माइन्स
Name[hr]=KMines
Name[hu]=KMines
Name[id]=KMines
Name[is]=KMines
Name[it]=KMines
Name[ja]=KMines
Name[kk]=KMines
Name[km]=KMines
Name[ko]=KMines
Name[lt]=KMines
Name[lv]=KMines
Name[mk]=KMines
Name[ml]=കെമൈന്‍സ്
Name[mr]=के-माइन्स
Name[nb]=KMines
Name[nds]=KMines
Name[ne]=केडीई बारुद
Name[nl]=KMines
Name[nn]=KMinesveipar
Name[pa]=ਕੇ-ਸਰੁੰਗ
Name[pl]=KMiny
Name[pt]=KMines
Name[pt_BR]=KMines
Name[ro]=KMine
Name[ru]=KMines
Name[se]=KMines
Name[sk]=KMines
Name[sl]=KMines
Name[sq]=KMines
Name[sr]=К‑мине
Name[sr@ijekavian]=К‑мине
Name[sr@ijekavianlatin]=K‑mine
Name[sr@latin]=K‑mine
Name[sv]=Röja minor
Name[ta]=கேகன்னிவெடிகள்
Name[tg]=KСапёр
Name[tr]=KMines
Name[ug]=KMines
Name[uk]=Сапер
Name[vi]=KMines
Name[wa]=KMenes
Name[xh]=KMines
Name[x-test]=xxKMinesxx
Name[zh_CN]=KMines
Name[zh_TW]=KMines 踩地雷
Icon=/opt/$APP/$APP.svg
Exec=kmines -qwindowtitle %c
Type=Application
X-DocPath=kmines/index.html
GenericName=Minesweeper-like Game
GenericName[be]=Гульня ў сапёра
GenericName[bn]=মাইনসুইপার-জাতীয় খেলা
GenericName[br]=C'hoari doare Minesweeper
GenericName[bs]=Igra kao minolovac
GenericName[ca]=Joc a l'estil del dragamines
GenericName[ca@valencia]=Joc a l'estil del dragamines
GenericName[cs]=Hra s minovým polem
GenericName[cy]=Gêm tebyg i Minesweeper
GenericName[da]=Minestryger-lignende spil
GenericName[de]=„Minesweeper“-Spiel
GenericName[el]=Παιχνίδι παρόμοιο με το ναρκαλιευτή
GenericName[en_GB]=Minesweeper-like Game
GenericName[es]=Juego similar al Buscaminas
GenericName[et]=Miiniväljamäng
GenericName[eu]=Mina bilatzailearen antzeko jokoa
GenericName[fa]=بازی شبیه مین‌یاب
GenericName[fi]=Miinaharava-tyylinen peli
GenericName[fr]=Jeu de type « Démineur »
GenericName[ga]=Cluiche cosúil le Minesweeper
GenericName[gl]=Xogo como o busca minas
GenericName[he]=חיקוי שולה מוקשים
GenericName[hne]=माइनस्वीपर जइसन खेल
GenericName[hr]=Igra s poput Minesweepera
GenericName[hu]=Aknakereső
GenericName[id]=Permainan Seperti Minesweeper
GenericName[is]=Leikur sem líkist Minesweeper
GenericName[it]=Gioco simile a Mine
GenericName[ja]=地雷ゲーム
GenericName[km]=ល្បែង​ដូច Minesweeper
GenericName[ko]=지뢰찾기 게임
GenericName[lt]=Išminuotojo tipo žaidimas
GenericName[lv]=Minesweeper līdzīga spēle
GenericName[mk]=Игра слична на Minesweeper
GenericName[mr]=माइनस्वीपर सारखा खेळ
GenericName[nb]=Minesveiper-lignende spill
GenericName[nds]=Minesweeper-liek Speel
GenericName[ne]=बारुद हटाउने जस्तै खेल
GenericName[nl]=Mijnenveger-achtig spel
GenericName[nn]=Minesveipar-liknande spel
GenericName[pa]=ਸੁਰੰਗ ਹਟਾਓਣ ਵਰਗੀ ਖੇਡ
GenericName[pl]=Gra typu saper
GenericName[pt]=Jogo tipo Minas
GenericName[pt_BR]=Jogo semelhante ao Campo Minado
GenericName[ro]=Un joc ca Detectorul de mine
GenericName[ru]=Игра в сапёра
GenericName[sk]=Hra typu hľadanie mín
GenericName[sl]=Igra podobna Minolovcu
GenericName[sq]=Lojë si Minesweeper
GenericName[sr]=Игра налик на Миноловац
GenericName[sr@ijekavian]=Игра налик на Миноловац
GenericName[sr@ijekavianlatin]=Igra nalik na Minolovac
GenericName[sr@latin]=Igra nalik na Minolovac
GenericName[sv]=Minröjarliknande spel
GenericName[ta]=சுரங்கம்வெட்டும் விளையாட்டு
GenericName[tr]=Mayın Tarlası-benzeri Oyun
GenericName[ug]=مىنا تازىلاشقا ئوخشاش ئويۇن
GenericName[uk]=Гра в сапера
GenericName[wa]=On djeu di tchamp d' menes
GenericName[x-test]=xxMinesweeper-like Gamexx
GenericName[zh_CN]=扫雷游戏
GenericName[zh_TW]=類似踩地雷的遊戲
Comment=Minesweeper-like Game
Comment[ca]=Joc a l'estil del dragamines
Comment[ca@valencia]=Joc a l'estil del dragamines
Comment[cs]=Hra s minovým polem
Comment[da]=Minestryger-lignende spil
Comment[de]=„Minesweeper“-Spiel
Comment[el]=Παιχνίδι παρόμοιο με το ναρκαλιευτή
Comment[en_GB]=Minesweeper-like Game
Comment[es]=Juego similar al Buscaminas
Comment[et]=Miiniväljamäng
Comment[eu]=Mina bilatzailearen antzeko jokoa
Comment[fi]=Miinaharava-tyylinen peli
Comment[fr]=Jeu de type « Démineur »
Comment[gl]=Xogo como o busca minas
Comment[id]=Permainan Seperti Minesweeper
Comment[it]=Gioco simile a Mine
Comment[ko]=지뢰 찾기 같은 게임
Comment[nl]=Mijnenvegerachtig spel
Comment[nn]=Minesveipar-liknande spel
Comment[pl]=Gra typu saper
Comment[pt]=Jogo tipo Campo-Minado
Comment[pt_BR]=Jogo semelhante ao Campo Minado
Comment[ru]=Игра в сапёра
Comment[sk]=Hra typu hľadanie mín
Comment[sl]=Igra podobna Minolovcu
Comment[sr]=Игра налик на Миноловац
Comment[sr@ijekavian]=Игра налик на Миноловац
Comment[sr@ijekavianlatin]=Igra nalik na Minolovac
Comment[sr@latin]=Igra nalik na Minolovac
Comment[sv]=Minröjarliknande spel
Comment[tr]=Mayın tarlası benzeri Oyun
Comment[uk]=Гра у сапера
Comment[x-test]=xxMinesweeper-like Gamexx
Comment[zh_CN]=扫雷游戏
Comment[zh_TW]=類似踩地雷的遊戲
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.kmines" >> /usr/share/applications/AM-$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
