#!/bin/sh

APP=kolf

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
X-DocPath=kolf/index.html
Name=Kolf
Name[be]=Гольф
Name[bn]=কল্‌ফ
Name[br]=Kolf
Name[bs]=Kolf
Name[ca]=Kolf
Name[ca@valencia]=Kolf
Name[cs]=Kolf
Name[cy]=Kolf
Name[da]=Kolf
Name[de]=Kolf
Name[el]=Kolf
Name[en_GB]=Kolf
Name[eo]=Kolf
Name[es]=Kolf
Name[et]=Kolf
Name[eu]=Kolf
Name[fa]=کلف
Name[fi]=Kolf
Name[fr]=Kolf
Name[ga]=Kolf
Name[gl]=Kolf
Name[he]=Kolf
Name[hne]=कोल्फ
Name[hr]=Kolf
Name[hu]=Kolf
Name[is]=Kolf
Name[it]=Kolf
Name[ja]=Kolf
Name[kk]=Kolf
Name[km]=Kolf
Name[ko]=Kolf
Name[lt]=Kolf
Name[lv]=Kolf
Name[mk]=Kolf
Name[mr]=कोल्फ
Name[nb]=Kolf
Name[nds]=Kolf
Name[ne]=कोल्फ
Name[nl]=Kolf
Name[nn]=Kolf
Name[pa]=ਕੇ-ਗੋਲਫ਼
Name[pl]=Kolf
Name[pt]=Kolf
Name[pt_BR]=Kolf
Name[ro]=Kolf
Name[ru]=Kolf
Name[se]=Kolf
Name[sk]=Kolf
Name[sl]=Kolf
Name[sq]=Kolf
Name[sr]=Колф
Name[sr@ijekavian]=Колф
Name[sr@ijekavianlatin]=Kolf
Name[sr@latin]=Kolf
Name[sv]=Kolf
Name[ta]=கால்ஃப்
Name[te]=కొల్ఫ్
Name[tg]=Колф
Name[tr]=Kolf
Name[ug]=Kolf
Name[uk]=Kolf
Name[vi]=Kolf
Name[wa]=Kolf
Name[xh]=Kolf
Name[x-test]=xxKolfxx
Name[zh_CN]=Kolf
Name[zh_TW]=Kolf

Type=Application
Exec=kolf %U
Icon=/opt/$APP/$APP.svg
MimeType=application/x-kourse;application/x-kolf;

GenericName=Miniature Golf
GenericName[be]=Маленькі гольф
GenericName[bn]=ছোটখাটো গলফ
GenericName[bs]=Minijaturni golf
GenericName[ca]=Golf en miniatura
GenericName[ca@valencia]=Golf en miniatura
GenericName[cs]=Miniaturní golf
GenericName[cy]=Golff Bach
GenericName[da]=Minigolf
GenericName[de]=Minigolf
GenericName[el]=Μίνι γκολφ
GenericName[en_GB]=Miniature Golf
GenericName[eo]=Eta golfludo
GenericName[es]=Minigolf
GenericName[et]=Miniatuurne golf
GenericName[eu]=Golf txikia
GenericName[fa]=گلف مینیاتوری
GenericName[fi]=Ratagolf
GenericName[fr]=Golf miniature
GenericName[ga]=Mionghalf
GenericName[gl]=Golf en miniatura
GenericName[he]=מיני־גולף
GenericName[hne]=मिनिएचर गोल्फ
GenericName[hr]=Mini-golf
GenericName[hu]=Minigolf
GenericName[is]=Minigolf
GenericName[it]=Minigolf
GenericName[ja]=ミニチュアゴルフ
GenericName[kk]=Шағын гольф
GenericName[km]=ហ្គោល ខ្នាត​តូច
GenericName[ko]=모형 골프
GenericName[lt]=Miniatiūrinis golfas
GenericName[lv]=Miniatūrs golfs
GenericName[mk]=Минијатурен голф
GenericName[nb]=Minigolf
GenericName[nds]=Minigolf
GenericName[ne]=सानो गल्फ
GenericName[nl]=Miniatuurgolf
GenericName[nn]=Minigolf
GenericName[pa]=ਛੋਟੀ ਗੋਲਫ਼ ਭੇਜੋ
GenericName[pl]=Miniaturowy Golf
GenericName[pt]=Golfe em Miniatura
GenericName[pt_BR]=Mini-Golf
GenericName[ro]=Golf în miniatură
GenericName[ru]=Гольф в миниатюре
GenericName[se]=Minigolfa
GenericName[sk]=Miniatúrny golf
GenericName[sl]=Mini golf
GenericName[sq]=Golf në Miniaturë
GenericName[sr]=Минијатурни голф
GenericName[sr@ijekavian]=Минијатурни голф
GenericName[sr@ijekavianlatin]=Minijaturni golf
GenericName[sr@latin]=Minijaturni golf
GenericName[sv]=Minigolf
GenericName[ta]=சிறிய கால்ஃப்
GenericName[tg]=Колф дар шакли хурд
GenericName[tr]=Minyatür Golf
GenericName[ug]=كىچىك تىپتىكى گولف
GenericName[uk]=Мініатюрний гольф
GenericName[vi]=Miniature Golf
GenericName[wa]=Golf miniateure
GenericName[xh]=Igalufa encinci
GenericName[x-test]=xxMiniature Golfxx
GenericName[zh_CN]=迷你高尔夫
GenericName[zh_TW]=迷你高爾夫
Categories=Qt;KDE;Game;ArcadeGame;
X-DBUS-ServiceName=org.kde.kolf" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
