#!/bin/sh

APP=kollision

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Exec=kollision
Icon=/opt/$APP/$APP.svg
Type=Application
Name=Kollision
Name[bs]=Kollision
Name[ca]=Kollision
Name[ca@valencia]=Kollision
Name[cs]=Kollision
Name[da]=Kollision
Name[de]=Kollision
Name[el]=Kollision
Name[en_GB]=Kollision
Name[eo]=Kollision
Name[es]=Kollision
Name[et]=Kollision
Name[eu]=Kollision
Name[fi]=Kollision
Name[fr]=Kollision
Name[ga]=Kollision
Name[gl]=Kollision
Name[hi]=कोल्लिसन
Name[hne]=कोलिसन
Name[hu]=Kollision
Name[id]=Kollision
Name[it]=Kollision
Name[ja]=Kollision
Name[kk]=Kollision
Name[km]=Kollision
Name[ko]=Kollision
Name[lt]=Kollision
Name[lv]=Kollision
Name[mr]=कोलिजन
Name[nb]=Kollision
Name[nds]=Kollision
Name[nl]=Kollision
Name[nn]=Kollisjon
Name[pl]=Kolizja
Name[pt]=Kollision
Name[pt_BR]=Kollision
Name[ro]=Koliziune
Name[ru]=Kollision
Name[sk]=Kollision
Name[sl]=Kollision
Name[sr]=Колизија
Name[sr@ijekavian]=Колизија
Name[sr@ijekavianlatin]=Kolizija
Name[sr@latin]=Kolizija
Name[sv]=Kollision
Name[tr]=Kollision
Name[ug]=Kollision
Name[uk]=Kollision
Name[x-test]=xxKollisionxx
Name[zh_CN]=Kollision
Name[zh_TW]=Kollision
GenericName=A simple ball dodging game
GenericName[ca]=Un joc senzill d'esquivar una bola
GenericName[ca@valencia]=Un joc senzill d'esquivar una bola
GenericName[da]=Et enkelt undvigelsesspil med bolde
GenericName[de]=Ein einfaches Ausweich-Ballspiel
GenericName[el]=Ένα απλό παιχνίδι ελιγμών με μπάλες
GenericName[en_GB]=A simple ball dodging game
GenericName[es]=Un juego sencillo de esquivar pelotas
GenericName[et]=Lihtne pallitogimise mäng
GenericName[fi]=Yksinkertainen väistelypeli
GenericName[fr]=Un jeu simple d'évitement de balles
GenericName[gl]=Un xogo de bólas
GenericName[hi]=गेंद को चकमा देने वाला खेल
GenericName[id]=Sebuah permainan sederhana menghindari bola-bola
GenericName[it]=Un semplice gioco in cui devi schivare delle palle
GenericName[ko]=튀는 공 피하기 게임
GenericName[nn]=Enkelt spel der du skal unngå kollisjonar
GenericName[pl]=Gra w unikanie kul
GenericName[pt]=Um jogo simples de desvio de bolas
GenericName[pt_BR]=Um jogo simples: desvie das bolas
GenericName[ru]=Простая игра в уклонение от шариков
GenericName[sk]=Hra s vyhýbaním loptičiek
GenericName[sl]=Preprosta igra izmikanja žogicam
GenericName[sr]=Једноставна игра избегавања лопти
GenericName[sr@ijekavian]=Једноставна игра избјегавања лопти
GenericName[sr@ijekavianlatin]=Jednostavna igra izbjegavanja lopti
GenericName[sr@latin]=Jednostavna igra izbegavanja lopti
GenericName[sv]=Ett enkelt spel för att undvika bollar
GenericName[tr]=Basit bir toptan kaçma oyunu
GenericName[uk]=Проста гра з кулькою
GenericName[x-test]=xxA simple ball dodging gamexx
GenericName[zh_CN]=一个简单的躲避球游戏
GenericName[zh_TW]=簡單的閃躲球遊戲
Terminal=false
Categories=Qt;KDE;Game;ArcadeGame;
X-DocPath=kollision/index.html
X-DBUS-ServiceName=org.kde.kollision" >> /usr/share/applications/AM-$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
