#!/bin/sh

APP=kshisen

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimagetool/appimagetool
wget https://github.com/ivan-hc/AppMan/raw/main/applications/pkg2appimage/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: unstable
  sources:
    - deb http://ftp.us.debian.org/debian/ unstable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Exec=kshisen -qwindowtitle %c
Type=Application
X-DocPath=kshisen/index.html
Name=Shisen-Sho
Name[af]=Shisen-sho
Name[be]=Ші-сен-сёе
Name[bn]=শিসেন-শো
Name[br]=Shisen-Sho
Name[bs]=Shisen-Sho
Name[ca]=Shisen-Sho
Name[ca@valencia]=Shisen-Sho
Name[cs]=Šisen-Šo
Name[cy]=Shisen-Sho
Name[da]=Shisen-Sho
Name[de]=Shisen-Sho
Name[el]=Shisen-Sho
Name[en_GB]=Shisen-Sho
Name[eo]=Ŝisen-Ŝo
Name[es]=Shisen-Sho
Name[et]=Shisen-Sho
Name[eu]=Shisen-Sho
Name[fi]=Shisen-Sho
Name[fr]=Shisen-sho
Name[ga]=Shisen-Sho
Name[gl]=Shisen-Sho
Name[he]=שישן־שו
Name[hne]=साईसेन-सो
Name[hr]=Shisen-Sho
Name[hu]=Shisen-Sho
Name[id]=Shisen-Sho
Name[is]=Shisen-Sho
Name[it]=Shisen-Sho
Name[ja]=Shisen-Sho
Name[kk]=Сисен-сё
Name[km]=Shisen-Sho
Name[ko]=Shisen-Sho
Name[lt]=Shisen-Sho
Name[lv]=Shisen-Sho
Name[mk]=Shisen-Sho
Name[mr]=शाईसेन-शो
Name[nb]=Shisen-Sho
Name[nds]=Shisen-Sho
Name[ne]=सिसेन शो
Name[nl]=Shisen-Sho
Name[nn]=Shisen-Sho
Name[pa]=ਸ਼ਿਸੀਨ-ਸ਼ੋ
Name[pl]=Shisen-Sho
Name[pt]=Shisen-Sho
Name[pt_BR]=Shisen-Sho
Name[ro]=Shisen-Sho
Name[ru]=Shisen-Sho
Name[se]=Shisen-Sho
Name[sk]=Šisen-Šo
Name[sl]=Shisen-Sho
Name[sr]=Шисен‑шо
Name[sr@ijekavian]=Шисен‑шо
Name[sr@ijekavianlatin]=Šisen‑šo
Name[sr@latin]=Šisen‑šo
Name[sv]=Shisen-Sho
Name[ta]=ஷிசென்-ஷோ
Name[tg]=Шисен-Шо
Name[tr]=Shisen-Sho
Name[ug]=Shisen-Sho
Name[uk]=Шісен-шо
Name[vi]=Shisen-Sho
Name[wa]=Shisen-Sho
Name[xh]=Shisen-Sho
Name[x-test]=xxShisen-Shoxx
Name[zh_CN]=连连看
Name[zh_TW]=Shisen-Sho
GenericName=Shisen-Sho Mahjongg-like Tile Game
GenericName[be]=Варыянт маджонга Шысен-сё
GenericName[bn]=শিসেন-শো মাহজং-জাতীয় টালির খেলা
GenericName[br]=Ur c'hoari teol a seurt gant Shisen*Sho Mahjongg
GenericName[bs]=Shisen-Sho Mahjongg igra pločica
GenericName[ca]=Joc de mosaics Shisen-Sho a l'estil Mahjongg
GenericName[ca@valencia]=Joc de mosaics Shisen-Sho a l'estil Mahjongg
GenericName[cs]=Hra s dlaždicemi Šisen-Šo
GenericName[cy]=Gêm Deiliau Shisen-Sho sy'n debyg i Mahjongg
GenericName[da]=Shisen-Sho Mahjongg-lignende brikspil
GenericName[de]=Spiel mit Mahjongg-Spielsteinen
GenericName[el]=Παιχνίδι παρόμοιο με το Shisen-Sho Mahjongg
GenericName[en_GB]=Shisen-Sho Mahjongg-like Tile Game
GenericName[eo]=Ŝisen-Ŝo Mahjongg-simila kahel-ludo
GenericName[es]=Juego de fichas similar al Shisen-Sho Mahjongg
GenericName[et]=Mahjonggi moodi klotsimäng
GenericName[eu]=Shisen-Sho Mahjongg-en antzeko fitxa-jokoa
GenericName[fa]=بازی کاشی شبیه Shisen-Sho Mahjongg
GenericName[fi]=Shisen-Sho Mahjongg-tyylinen laattapeli
GenericName[fr]=Jeu de tuiles Shisen-Sho dans le style du Mahjongg
GenericName[ga]=Cluiche Tíleanna Shisen-Sho, cosúil le Mahjongg
GenericName[gl]=Xogo de fichas Shisen-so ao estilo do Mahjongg
GenericName[he]=Shisen Sho, חיקוי מה ג'ונג, משחק קלפים
GenericName[hne]=साइसेन-सो  महजोंग जइसन टाइल वाले खेल
GenericName[hr]=Shisen-Sho igra s pločicama poput Mahjongga
GenericName[hu]=Shisen-Sho Mahjongg-szerű kockajáték
GenericName[id]=Shisen-Sho Permainan Ubin Seperti Halnya Mahjongg
GenericName[is]=Shisen-Sho kubbaleikur líkur Mahjongg
GenericName[it]=Shisen-Sho, gioco di tessere simile a Mahjongg
GenericName[ja]=四川省マージャン牌ゲーム
GenericName[kk]=Маджонг секілді жапон ойны
GenericName[km]=ល្បែង​ក្បឿង​ដូច Shisen-Sho Mahjongg
GenericName[ko]=시센-쇼 마작과 같은 타일 게임
GenericName[lv]=Shisen-Sho Mahjongg līdzīga spēle
GenericName[mk]=Игра со плочки слична на Shisen-Sho Mahjongg
GenericName[mr]=शाईसेन-शो माहजोन्ग सारखा टाइल खेळ
GenericName[nb]=Shisen-Sho Mahjongg-lignende brikkespill
GenericName[nds]=Mahjongg-liek Speel
GenericName[ne]=सिसेन शो माहाजोङ्ग जस्तै टायल खेल
GenericName[nl]=Shisen-Sho Mahjongg-achtig stenenspel
GenericName[nn]=Shisen-Sho Mahjongg-liknande brikkespel
GenericName[pa]=ਸ਼ਿਸੀਨ-ਸ਼ੋ ਮਹਿਜ਼ੋਗ ਵਰਗੀ ਖੇਡ
GenericName[pl]=Gra typu Shisen-Sho Mahjongg
GenericName[pt]=Jogo de Peças Shisen-Sho, semelhante ao Mahjongg
GenericName[pt_BR]=Jogo de peças parecido com Shisen-Sho Mahjongg
GenericName[ru]=Вариант маджонга: Ши-сен-сё
GenericName[se]=Shisen-Sho Mahjongg-lágan bihttáspeallu
GenericName[sk]=Hra typu Shisen-Sho Mahjongg
GenericName[sl]=Igra s ploščicami Shisen-Sho, podobna Mahjonggu
GenericName[sr]=Игра с плочицама попут маџонга
GenericName[sr@ijekavian]=Игра с плочицама попут маџонга
GenericName[sr@ijekavianlatin]=Igra s pločicama poput madžonga
GenericName[sr@latin]=Igra s pločicama poput madžonga
GenericName[sv]=Shisen-Sho Mahjongg-liknande brickspel
GenericName[ta]=ஷிசெந்ஷோ மாஹ்ஜோங் போன்ற ஓடு விளையாட்டு
GenericName[tr]=Shisen-Sho Mahjongg Benzeri Döşeme Oyunu
GenericName[ug]=Shisen-Sho Mahjongg غا ئوخشاپ قالىدىغان كاھىش ئويۇنى
GenericName[uk]=Шісен-шо, схожа на маджонґ гра з плитками
GenericName[wa]=Djeu d' pîce do djinre di Mahjongg
GenericName[x-test]=xxShisen-Sho Mahjongg-like Tile Gamexx
GenericName[zh_CN]=类似连连看的麻将游戏
GenericName[zh_TW]=四川省麻將牌遊戲
Icon=/opt/$APP/$APP.svg
X-KDE-StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;BoardGame;" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
