#!/bin/sh

APP=ksquares

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O appimagetool
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous && mv pkg2appimage* pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=KSquares
Name[be]=KSquares
Name[bs]=KSquares
Name[ca]=KSquares
Name[ca@valencia]=KSquares
Name[cs]=KSquares
Name[da]=KSquares
Name[de]=KSquares
Name[el]=KSquares
Name[en_GB]=KSquares
Name[eo]=KSquares
Name[es]=KSquares
Name[et]=KSquares
Name[eu]=KSquares
Name[fa]=نقطه‌بازی
Name[fi]=KSquares
Name[fr]=KSquares
Name[ga]=KSquares
Name[gl]=KSquares
Name[hne]=के-स्कवेयर्स
Name[hu]=KSquares
Name[it]=KSquares
Name[ja]=KSquares
Name[kk]=KSquares
Name[km]=KSquares
Name[ko]=KSquares
Name[lt]=KSquares
Name[lv]=KSquares
Name[mr]=के-स्क्वेअर्स
Name[nb]=KSquares
Name[nds]=KSquares
Name[ne]=केडीई बर्ग
Name[nl]=KSquares
Name[nn]=Kvadrat
Name[pl]=Kwadraty
Name[pt]=KSquares
Name[pt_BR]=KSquares
Name[ro]=KPătrate
Name[ru]=KSquares
Name[sk]=KSquares
Name[sl]=KSquares
Name[sr]=К‑квадрати
Name[sr@ijekavian]=К‑квадрати
Name[sr@ijekavianlatin]=K‑kvadrati
Name[sr@latin]=K‑kvadrati
Name[sv]=Fyrkanter
Name[tr]=KSquares
Name[ug]=KSquares
Name[uk]=KSquares
Name[wa]=KCwårés
Name[x-test]=xxKSquaresxx
Name[zh_CN]=KSquares
Name[zh_TW]=KSquares 連方塊
Exec=ksquares -qwindowicon ksquares -qwindowtitle %c
Icon=/opt/$APP/$APP.svg
Type=Application
X-DocPath=ksquares/index.html
GenericName=Connect the dots to create squares
GenericName[bs]=Poveži tačke da napraviš kvadrat
GenericName[ca]=Connecteu els punts per a crear quadrats
GenericName[ca@valencia]=Connecteu els punts per a crear quadrats
GenericName[cs]=Spojte tečky a vytvořte čtverce
GenericName[da]=Forbind prikkerne for at danne kvadrater
GenericName[de]=Käsekästchen-Spiel
GenericName[el]=Συνδέστε τις τελείες για να σχηματίσετε τετράγωνα
GenericName[en_GB]=Connect the dots to create squares
GenericName[eo]=Konektu la punktojn por krei kvadratojn
GenericName[es]=Conecta los puntos para crear cuadrados
GenericName[et]=Punktikeste ühendamine ruutude loomiseks
GenericName[eu]=Konektatu puntuak karratuak sortzeko
GenericName[fa]=اتصال نقطه‌ها برای ایجاد مربعها
GenericName[fi]=Yhdistä pisteet muodostaaksesi neliöitä
GenericName[fr]=Relier les points pour créer des carrés
GenericName[ga]=Ceangail na poncanna chun cearnóga a chruthú
GenericName[gl]=Conecta os puntos creando cadrados
GenericName[hne]=वर्ग बनाए बर बिंदु मन ल जोड़व
GenericName[hu]=Négyzetet kell rajzolni a pontokkal
GenericName[it]=Unisci i puntini per creare dei quadrati
GenericName[ja]=点を結んで正方形を作るゲーム
GenericName[kk]=Нүклелерді біріктіріп шаршыларды құру
GenericName[km]=ភ្ជាប់​ទៅ​ចំណុច ដើម្បី​បង្កើត​រាង​ការេ
GenericName[ko]=점을 연결해서 사각형 만들기
GenericName[lv]=Savieno punktus, lai izveidotu kvadrātus
GenericName[mr]=चौरस बनविण्याकरिता बिंदू जोडा
GenericName[nb]=Tegn streker mellom prikkene for å lage kvadrater
GenericName[nds]=Pünkt verbinnen, so dat Quadraten dor bi rutkaamt
GenericName[ne]=बर्ग सिर्जना गर्न बिन्दुहरू जोड्नुहोस्
GenericName[nl]=Verbind de stippen om vierkanten te maken
GenericName[nn]=Teikn strekar mellom prikkar for å laga kvadrat
GenericName[pl]=Połącz kropki, żeby otrzymać kwadraty
GenericName[pt]=Ligue os pontos para criar quadrados
GenericName[pt_BR]=Conecte os pontos para criar quadrados
GenericName[ro]=Conectați punctele pentru a obține pătrate
GenericName[ru]=Соединяйте точки для создания квадрата
GenericName[sk]=Spojte bodky a vytvorte štvorce
GenericName[sl]=Povežite pikice, da ustvarite kvadrate
GenericName[sr]=Спајајте тачке и освајајте поља
GenericName[sr@ijekavian]=Спајајте тачке и освајајте поља
GenericName[sr@ijekavianlatin]=Spajajte tačke i osvajajte polja
GenericName[sr@latin]=Spajajte tačke i osvajajte polja
GenericName[sv]=Sammanbind punkter för att skapa fyrkanter
GenericName[tr]=Noktaları Birleştirerek Kare Yap
GenericName[ug]=چېكىتلەرنى تۇتاشتۇرۇپ كۋادرات ياشاش
GenericName[uk]=З'єднайте точки, щоб створити квадрати
GenericName[x-test]=xxConnect the dots to create squaresxx
GenericName[zh_CN]=连接点创建方形
GenericName[zh_TW]=將點連起來組成方塊
Comment=Connect the dots to create squares
Comment[ca]=Connecteu els punts per a crear quadrats
Comment[ca@valencia]=Connecteu els punts per a crear quadrats
Comment[cs]=Spojte tečky a vytvořte čtverce
Comment[da]=Forbind prikkerne for at danne kvadrater
Comment[de]=Käsekästchen-Spiel
Comment[el]=Συνδέστε τις τελείες για να σχηματίσετε τετράγωνα
Comment[en_GB]=Connect the dots to create squares
Comment[es]=Conecta los puntos para crear cuadrados
Comment[et]=Punktikeste ühendamine ruutude loomiseks
Comment[fi]=Yhdistä pisteet muodostaaksesi neliöitä
Comment[fr]=Relier les points pour créer des carrés
Comment[gl]=Conecta os puntos creando cadrados
Comment[it]=Unisci i puntini per creare dei quadrati
Comment[ko]=점을 연결해서 사각형 만들기
Comment[nl]=Verbind de stippen om vierkanten te maken
Comment[nn]=Teikn strekar mellom prikkar for å laga kvadrat
Comment[pl]=Połącz kropki, żeby otrzymać kwadraty
Comment[pt]=Ligue os pontos para criar quadrados
Comment[pt_BR]=Conecte os pontos para criar quadrados
Comment[ru]=Соединяйте точки для создания квадрата
Comment[sk]=Spojte bodky a vytvorte štvorce
Comment[sl]=Povežite pikice, da ustvarite kvadrate
Comment[sr]=Спајајте тачке и освајајте поља
Comment[sr@ijekavian]=Спајајте тачке и освајајте поља
Comment[sr@ijekavianlatin]=Spajajte tačke i osvajajte polja
Comment[sr@latin]=Spajajte tačke i osvajajte polja
Comment[sv]=Sammanbind punkterna för att skapa fyrkanter
Comment[tr]=Noktaları birleştirerek kare yap
Comment[uk]=З’єднайте точки, щоб створити квадрати
Comment[x-test]=xxConnect the dots to create squaresxx
Comment[zh_CN]=连接点创建方形
Comment[zh_TW]=將點連起來組成方塊
Terminal=false
Categories=Game;BoardGame;Qt;KDE;
X-DBUS-ServiceName=org.kde.ksquares" >> /usr/share/applications/AM-$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
