#!/bin/sh
set -u
APP=landrop
SITE="https://landrop.app"
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1
version=$(wget -qO- https://landrop.app | grep -oP '(?<=id="version-linux">)[^<]+' | head -n1)
wget "https://releases.landrop.app/LANDrop-latest-linux.AppImage" || exit 1
cd ..
mv ./tmp/* ./"$APP"
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=landrop
SITE="https://landrop.app"
version0=$(cat "/opt/$APP/version")
version=$(wget -qO- https://landrop.app | grep -oP '(?<=id="version-linux">)[^<]+' | head -n1)
[ -n "$version" ] || { echo "Error getting version"; exit 1; }
if [ "$version" != "$version0" ]; then
    mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
    notify-send "A new version of $APP is available, please wait"
    wget "https://releases.landrop.app/LANDrop-latest-linux.AppImage" || exit 1
    cd ..
    mv --backup=t ./tmp/* ./"$APP"
    chmod a+x ./"$APP" || exit 1
    echo "$version" > ./version
    rm -R -f ./*~old ./*.part ./tmp
    notify-send "$APP is updated!"
else
    echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do
    if [ -L ./"$APP".desktop ]; then
        LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
        ./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
    fi
    if [ -L ./DirIcon ]; then
        LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
        ./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
    fi
    [ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
    COUNT=$((COUNT + 1))
done
sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./"$APP".desktop
mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
rm -R -f ./squashfs-root
