#!/usr/bin/env bash

LIB=libfuse2
ARCH=$(uname -m)

# CREATE THE FOLDER
mkdir /opt/$LIB
cd /opt/$LIB

# ADD THE REMOVER
echo '#!/bin/sh
sudo rm -R -f /opt/'$LIB' /usr/local/lib/libfuse*' >> /opt/$LIB/remove
chmod a+x /opt/$LIB/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

function _debian_dl(){
	LIBFUSE2_DEB=$(wget -q http://ftp.debian.org/debian/pool/main/f/fuse/ -O - | grep -Po '(?<=href=")[^"]*' | sort | grep -v exp | grep amd64 | grep "libfuse2_" | tail -1)
	wget http://ftp.debian.org/debian/pool/main/f/fuse/"$LIBFUSE2_DEB"
	ar x ./*.deb
	tar fx ./data.tar.xz
	cd ..
	sudo mkdir -p /usr/local/lib
	sudo mv ./tmp/lib/*/libfuse* /usr/local/lib/
}

function _archlinux_dl(){
	wget https://archlinux.org/packages/extra/${ARCH}/fuse2/download && mv ./download ./$LIB.tar.zst
	tar fx ./*.tar.zst
	cd ..
	sudo mkdir -p /usr/local/lib
	sudo mv ./tmp/usr/lib/libfuse*2* /usr/local/lib/
}

_debian_dl

#_archlinux_dl

rm -R -f ./tmp
sudo ldconfig