#!/bin/sh

echo '

 This script will help you choose a version of Libreoffice using "AM".
 
 Libreoffice versions are classified according to functionality (STILL and
 FRESH) and the number of languages included (STANDARD and FULL):
 
 1) STILL-STANDARD is the Stable version with support for English (US and GB),
    Arabic, Chinese (Simplified and Traditional), French, German, Italian, 
    Japanese, Korean, Portuguese (Brazilian and Portugal), Russian, and Spanish,
    including manuals;
 
 2) STILL-FULL is the Stable version that includes all the languages supported
    by LibreOffice, including manuals;
 
 3) FRESH-STANDARD is the Testing version with support for English (US and GB),
    Arabic, Chinese (Simplified and Traditional), French, German, Italian, 
    Japanese, Korean, Portuguese (Brazilian and Portugal), Russian, and Spanish,
    including manuals;
 
 4) FRESH-FULL is the Testing version that includes all the languages supported
    by LibreOffice, including manuals;
 
 5) DAILY-STANDARD is the Unstable version with support for English (US and GB),
    Arabic, Chinese (Simplified and Traditional), French, German, Italian, 
    Japanese, Korean, Portuguese (Brazilian and Portugal), Russian, and Spanish.
    NOTE: Unlike all the other versions, THIS DOES NOT INCLUDE MANUALS;
 
 6) DAILY-STANDARD-HELP is the Unstable version (see 5) including manuals.

';
read -r -p " Which version of Libreoffice do you choose between 1, 2, 3, 4 and 5? " response
case "$response" in
    1) am -i libreoffice-still.standard;;
    2) am -i libreoffice-still.full;;
    3) am -i libreoffice-fresh.standard;;
    4) am -i libreoffice-fresh.full;;
    5) am -i libreoffice-daily.standard;;
    6) am -i libreoffice-daily.standard.help;;
    *) echo ""; echo " No valid argument was chosen: installation aborted! "; rm -f /opt/am/.cache/libreoffice; echo "";;
esac
