#!/bin/sh

APP=lskat

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimagetool/appimagetool
wget https://github.com/ivan-hc/AppMan/raw/main/applications/pkg2appimage/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: $APP
binpatch: true

ingredients:
  dist: unstable
  sources:
    - deb http://ftp.us.debian.org/debian/ unstable main contrib non-free" >> recipe.yml

./pkg2appimage ./recipe.yml;

ARCH=x86_64 ./appimagetool -n ./$APP/$APP.AppDir;

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
echo "[Desktop Entry]
Name=LSkat
Name[be]=LSkat
Name[bs]=LSkat
Name[ca]=LSkat
Name[ca@valencia]=LSkat
Name[cs]=Poručík skat
Name[da]=LSkat
Name[de]=LSkat
Name[el]=LSkat
Name[en_GB]=LSkat
Name[eo]=LSkat
Name[es]=LSkat
Name[et]=LSkat
Name[eu]=LSkat
Name[fi]=LSkat
Name[fr]=LSkat
Name[ga]=LSkat
Name[gl]=LSkat
Name[hne]=एलएस-कैट
Name[hr]=LSkat
Name[hu]=LSkat
Name[id]=LSkat
Name[is]=LSkat
Name[it]=LSkat
Name[ja]=LSkat
Name[kk]= 
Name[km]=LSkat
Name[ko]=LSkat
Name[lt]=LSkat
Name[lv]=LSkat
Name[mr]=एल-स्केट
Name[nb]=LSkat
Name[nds]=LSkat
Name[ne]=एल स्क्याट
Name[nl]=LSkat
Name[nn]=Løytnant Skat
Name[pl]=LSkat
Name[pt]=LSkat
Name[pt_BR]=LSkat
Name[ru]=LSkat
Name[sk]=LSkat
Name[sl]=LSkat
Name[sr]=П‑скат
Name[sr@ijekavian]=П‑скат
Name[sr@ijekavianlatin]=P‑skat
Name[sr@latin]=P‑skat
Name[sv]=Officersskat
Name[te]=ఎల్ స్కెట్
Name[tr]=LSkat
Name[ug]=LSkat
Name[uk]=LSkat
Name[wa]=LSkat
Name[x-test]=xxLSkatxx
Name[zh_CN]=LSkat
Name[zh_TW]=LSkat
GenericName=Classic German Card Game
GenericName[ca]=Joc de cartes alemany clàssic
GenericName[ca@valencia]=Joc de cartes alemany clàssic
GenericName[cs]=Klasická německá karetní hra
GenericName[da]=Klassisk tysk kortspil
GenericName[de]=Klassisches deutsches Kartenspiel
GenericName[el]=Κλασικό γερμανικό παιχνίδι καρτών
GenericName[en_GB]=Classic German Card Game
GenericName[es]=Clásico juego de cartas alemán
GenericName[et]=Klassikaline Saksa kaardimäng
GenericName[eu]=Karta-joko aleman klasikoa
GenericName[fi]=Perinteinen saksalainen korttipeli
GenericName[fr]=Jeu de cartes classique allemand.
GenericName[it]=Classico gioco di carte tedesco
GenericName[ko]=고전 독일식 카드 게임
GenericName[nl]=Klassiek Duits kaartspel
GenericName[nn]=Klassisk tysk kortspel
GenericName[pl]=Klasyczna niemiecka gra karciana
GenericName[pt]=Jogo Clássico de Cartas Alemão
GenericName[pt_BR]=Jogo de cartas alemão clássico
GenericName[sk]=Klaskická nemecká kartová hra
GenericName[sl]=Klasična nemška igra s kartami
GenericName[sv]=Klassiskt tyskt kortspel
GenericName[uk]=Класична німецька карткова гра
GenericName[x-test]=xxClassic German Card Gamexx
Exec=lskat
Icon=/opt/$APP/$APP.svg
Terminal=false
Type=Application
X-DocPath=lskat/index.html
Categories=Qt;KDE;Game;CardGame;
X-DBUS-ServiceName=org.kde.lskat" >> /usr/share/applications/$APP.desktop;

# ICON
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

echo "

 $APP is part of KDE Games, visit https://games.kde.org
  
";
