#!/bin/sh

APP=minecraft-launcher

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir tmp
cd ./tmp

wget https://launcher.mojang.com/download/Minecraft.tar.gz;
tar xf Minecraft.tar.gz
cd ..
mv ./tmp/*/* ./$APP
chmod a+x ./$APP
rm -R -f ./tmp
echo "latest" ./version

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
rm -f /usr/share/applications/AM-$APP.desktop 2> /dev/null
echo "[Desktop Entry]
Name=Minecraft Launcher
Comment=Game downloader and launcher for Minecraft
Exec=minecraft-launcher
Icon=/opt/$APP/$APP
Type=Application
Categories=Game;" >> /usr/share/applications/AM-$APP.desktop 2> /dev/null

# ICON
mkdir /opt/$APP/icons
wget https://user-images.githubusercontent.com/38465129/72480309-0dede180-37c5-11ea-9138-793b79713232.png -O ./icons/$APP 2> /dev/null

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 Minecraft Launcher is provided by https://www.minecraft.net
  
";
