#!/bin/sh

APP=minecraft-launcher

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir tmp
cd ./tmp

wget https://launcher.mojang.com/download/Minecraft.tar.gz;
tar xf Minecraft.tar.gz
cd ..;
mv ./tmp/$APP/$APP ./;
chmod a+x ./$APP

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=Minecraft Launcher
Comment=Game downloader and launcher for Minecraft
Exec=minecraft-launcher
Icon=/opt/$APP/$APP.svg
Type=Application
Categories=Game;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 Minecraft Launcher is provided by https://www.minecraft.net
  
";
