#!/bin/sh

APP=moonplayer

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/coslyk/moonplayer/releases/latest -O - | egrep '/.*/.*/.*x86_64.AppImage' -o);

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/coslyk/moonplayer/releases/latest' >> /opt/$APP/AM-updater

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
echo 'else' >> /opt/$APP/AM-updater
echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater

########################################################################################

function1='$(wget https://github.com/coslyk/moonplayer/releases/latest -O -'
function2="egrep '/.*/.*/.*x86_64.AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'

echo "  wget https://github.com/$function1 | $function2
  version=$function3" >> /opt/$APP/AM-updater

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /opt/$APP/AM-updater
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Categories=AudioVideo;Player;
Comment[zh_CN]=播放本地及网络视频
Comment=Play local or online videos
Exec=moonplayer %U
GenericName[zh_CN]=视频播放器
GenericName=Media Player
Icon=/opt/$APP/$APP.svg
MimeType=video/x-theora+ogg;video/x-ogm+ogg;video/x-msvideo;video/x-msvideo;video/x-ms-wmv;video/x-ms-asf;video/x-matroska;video/x-flv;video/vnd.rn-realvideo;video/quicktime;video/mpeg;video/mp4;audio/x-wav;audio/x-vorbis+ogg;audio/x-vorbis+ogg;audio/x-scpls;audio/x-ms-wma;audio/x-mpegurl;audio/x-mpegurl;audio/x-matroska;audio/x-adpcm;audio/vnd.rn-realaudio;audio/vnd.rn-realaudio;audio/mpeg;audio/mpeg;audio/mp4;audio/mp2;audio/ac3;application/xspf+xml;x-scheme-handler/moonplayer;x-scheme-handler/moonplayers;
Name[zh_CN]=MoonPlayer
Name=MoonPlayer
StartupNotify=true
StartupWMClass=MoonPlayer
Terminal=false
Type=Application
X-KDE-SubstituteUID=false" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " MoonPlayer is provided by https://coslyk.github.io/moonplayer.html ";
echo "";
