#!/bin/sh

echo ""
read -r -p " MPV is available as a fixed version (non-updatable), select one

 1) mpv-0.35 (requires LIBC 2.36+)
 2) mpv-0.32 (requires LIBC 2.31+)
 3) mpv-0.29 (requires LIBC 2.28+)

 What do you choose between 1, 2 and 3? " response
case "$response" in
    1) sudo am -i mpv-0.35;;

    2) sudo am -i mpv-0.32;;
    
    3) sudo am -i mpv-0.29;;

    *) echo ""; echo " No valid argument was chosen: installation aborted! "; rm -f /opt/am/.cache/mpv*; echo "";;
esac
