#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 
set -u
APP=mullvad-browser
SITE="mullvad/mullvad-browser"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
printf '\n%s' "rm -f /usr/share/applications/AM-$APP.desktop" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -oi 'https.*browser.*linux.*x86_64.*xz$' | head -1)
wget "$version" || exit 1
tar fx ./*tar* && rm -f ./*tar*
cd ..
mv ./tmp/*/* ./
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x "/opt/$APP/Browser/start-mullvad-browser" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/Browser/start-mullvad-browser" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
set -u
APP=mullvad-browser
SITE="mullvad/mullvad-browser"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -oi 'https.*browser.*linux.*x86_64.*xz$' | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	tar fx ./*tar* && rm -f ./*tar*
	cd ..
	mv --backup=t ./tmp/*/* ./
	chmod a+x "/opt/$APP/Browser/start-mullvad-browser" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
	exit 0
fi
echo "Update not needed!"
EOF
chmod a+x "/opt/$APP/AM-updater"

# Desktop
sed -i "s#Exec=.*#Exec=$APP %k#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g" ./*"$APP"*.desktop
mv ./Browser/browser/chrome/icons/default/default128.png ./icons/"$APP"
mv ./*"$APP"*.desktop /usr/share/applications/AM-"$APP".desktop
