#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=mullvad-browser
SITE="mullvad/mullvad-browser"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls  https://api.github.com/repos/mullvad/mullvad-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "download.*linux.*x86_64.*tar.xz$" | head -1)
wget "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z ./*/*.desktop
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.* ./*/*.desktop
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip ./*/*.desktop
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./mullvadbrowser.real || exit 1

# LINK TO PATH
ln -s "/opt/$APP/mullvadbrowser.real" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=mullvad-browser
SITE="mullvad/mullvad-browser"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls  https://api.github.com/repos/mullvad/mullvad-browser/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "download.*linux.*x86_64.*tar.xz$" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z ./*/*.desktop
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.* ./*/*.desktop
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip ./*/*.desktop
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x ./mullvadbrowser.real || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://portable-linux-apps.github.io/icons/mullvad-browser.png -O ./icons/"$APP" 2> /dev/null

# LAUNCHER
echo "[Desktop Entry]
Type=Application
Name=Mullvad Browser Setup
GenericName=Web Browser
Comment=Mullvad Browser  is +1 for privacy and −1 for mass surveillance
Categories=Network;WebBrowser;Security;
Exec=$APP
X-MullvadBrowser-ExecShell=/opt/$APP/start-mullvad-browser --detach
Icon=/opt/$APP/icons/$APP
StartupWMClass=Mullvad Browser Alpha" > /usr/local/share/applications/"$APP"-AM.desktop
