#!/bin/sh

APP=node
SITE="https://nodejs.org"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP
cd /usr/local/bin && find . -xtype l -exec rm {} \;" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(echo "https://nodejs.org/dist/latest/$(wget -q https://nodejs.org/dist/latest/ -O - | grep "linux-x64.tar.gz" | grep -o -P '(?<=href=").*(?=">node)')")
wget $version
echo "$version" >> /opt/$APP/version
tar fx ./*tar.gz
cd ..
mv ./tmp/node*linux-x64/* ./
rm -R -f ./tmp

# LINKS
ln -s /opt/$APP/bin/$APP /usr/local/bin/$APP
ln -s /opt/$APP/bin/npm /usr/local/bin/npm
ln -s /opt/$APP/bin/npx /usr/local/bin/npx
ln -s /opt/$APP/bin/corepack /usr/local/bin/corepak

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=node
version0=$(cat /opt/$APP/version)
version=$(echo "https://nodejs.org/dist/latest/$(wget -q https://nodejs.org/dist/latest/ -O - | grep "linux-x64.tar.gz" | grep -o -P '(?<=href=").*(?=">node)')")
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget $version
  tar fx ./*tar.gz
  cd ..
  mv --backup=t ./tmp/node*linux-x64/* ./
  rm -R -f ./tmp
  rm ./version
  echo $version >> ./version
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
  notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=NodeJS (Terminal)
Comment=A JavaScript runtime built on Chrome's V8 JavaScript engine.
Exec=exo-open --working-directory /opt/$APP/bin --launch TerminalEmulator
Icon=/opt/$APP/icons/$APP
Type=Application
Categories=Development;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir icons
wget https://nodejs.org/static/images/favicons/apple-touch-icon.png -O ./icons/$APP 2> /dev/null




