#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=node
SITE="https://nodejs.org"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
printf '\n%s' "cd /usr/local/bin && find . -xtype l -exec rm {} \;" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version="https://nodejs.org/dist/latest/$(curl -Ls https://nodejs.org/dist/latest/ | tr '"></ ' '\n' | grep -i "linux.*x64.*tar.gz$" | tail -1)"
wget "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./bin/"$APP" || exit 1

# LINK TO PATH
ln -s /opt/"$APP"/bin/"$APP" /usr/local/bin/"$APP"
ln -s /opt/"$APP"/bin/npm /usr/local/bin/npm
ln -s /opt/"$APP"/bin/npx /usr/local/bin/npx
ln -s /opt/"$APP"/bin/corepack /usr/local/bin/corepak

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=node
SITE="https://nodejs.org"
version0=$(cat "/opt/$APP/version")
version="https://nodejs.org/dist/latest/$(curl -Ls https://nodejs.org/dist/latest/ | tr '"></ ' '\n' | grep -i "linux.*x64.*tar.gz$" | tail -1)"
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x ./bin/"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://portable-linux-apps.github.io/icons/node.png -O ./icons/"$APP" 2> /dev/null

# LAUNCHER
echo "[Desktop Entry]
Name=NodeJS (Terminal)
Comment=A JavaScript runtime built on Chrome's V8 JavaScript engine.
Exec=exo-open --working-directory /opt/$APP/bin --launch TerminalEmulator
Icon=/opt/$APP/icons/$APP
Type=Application
Categories=Development;" > /usr/local/share/applications/"$APP"-AM.desktop
