#!/bin/sh

APP=ocenaudio
ICONURL="https://www.ocenaudio.com/imgs/logo.png"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd tmp
wget https://raw.githubusercontent.com/ivan-hc/$APP-appimage/main/$APP.sh
chmod a+x ./$APP.sh
./$APP.sh > /dev/null 2>&1
cd ..
version=$(wget -q https://www.ocenaudio.com/fileinfo/ocenaudio_mint32.deb -O - | grep Versão | cut -c 43- | rev | cut -c 5- | rev)
echo $version >> ./version
mv ./tmp/*AppImage ./$APP
rm -R -f ./tmp

#-------------------------------------

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=ocenaudio
version0=$(cat /opt/$APP/version)
version=$(wget -q https://www.ocenaudio.com/fileinfo/ocenaudio_mint32.deb -O - | grep Versão | cut -c 43- | rev | cut -c 5- | rev)
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://raw.githubusercontent.com/ivan-hc/ocenaudio-appimage/main/$APP.sh
  chmod a+x ./$APP.sh
  ./$APP.sh
  cd ..
  rm ./version
  echo $version >> ./version
  mv ./tmp/*AppImage ./$APP
  rm -R -f ./tmp
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=ocenaudio
Name[pt]=ocenaudio
Name[de]=ocenaudio
Name[ru]=ocenaudio
GenericName=Audio Editor
GenericName[pt]=Editor de Áudio
GenericName[de]=Audio Editor
GenericName[ru]=Звуковой редактор
Comment=Edit audio files
Comment[pt]=Edite arquivos de áudio
Comment[de]=Audio Dateien bearbeiten
Comment[ru]=Редактирование звуковых файлов

Icon=/opt/$APP/icons/$APP
Type=Application
Categories=AudioVideo;Audio;AudioVideoEditing;

Exec=ocenaudio %F
StartupNotify=false
Terminal=false
MimeType=application/ogg;audio/basic;audio/mpeg;audio/x-aiff;audio/x-mp3;audio/x-wav;application/x-ocenlink;x-scheme-handler/ocenaudio;
" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir /opt/$APP/icons
wget $ICONURL -O /opt/$APP/icons/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 Ocenaudio is provided by https://www.ocenaudio.com

"
