#!/bin/sh

mkdir /opt/ocenaudio
cd /opt/ocenaudio
mkdir tmp
cd tmp
wget https://www.ocenaudio.com/downloads/ocenaudio_mint64.deb
ar x ./*.deb
tar -xf ./*tar.xz
cd ..
mv ./tmp/opt/ocenaudio/* ./
cp ./tmp/usr/share/icons/hicolor/128x128/apps/ocenaudio.png ./
rm -R -f ./tmp

rm -R -f /usr/share/applications/ocenaudio.desktop
echo "[Desktop Entry]
Name=ocenaudio
Name[pt]=ocenaudio
Name[de]=ocenaudio
Name[ru]=ocenaudio
GenericName=Audio Editor
GenericName[pt]=Editor de Áudio
GenericName[de]=Audio Editor
GenericName[ru]=Звуковой редактор
Comment=Edit audio files
Comment[pt]=Edite arquivos de áudio
Comment[de]=Audio Dateien bearbeiten
Comment[ru]=Редактирование звуковых файлов

Icon=/opt/ocenaudio/ocenaudio.png
Type=Application
Categories=AudioVideo;Audio;AudioVideoEditing;

Exec=/opt/ocenaudio/bin/ocenaudio %F
StartupNotify=false
Terminal=false
MimeType=application/ogg;audio/basic;audio/mpeg;audio/x-aiff;audio/x-mp3;audio/x-wav;application/x-ocenlink;x-scheme-handler/ocenaudio;" >> //usr/share/applications/ocenaudio.desktop

ln -s /opt/ocenaudio/bin/ocenaudio /usr/local/bin/ocenaudio

echo '#!/bin/sh
rm -R -f /usr/share/applications/ocenaudio.desktop /opt/ocenaudio /usr/local/bin/ocenaudio' >> /opt/ocenaudio/remove
chmod a+x /opt/ocenaudio/remove

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/ocenaudio

echo ""
echo " OcenAudio Editor has been installed!"
echo ""
