#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=oh-my-git
SITE="https://ohmygit.org"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://raw.githubusercontent.com/ivan-hc/repology-versions/main/versions-list | grep "◆ $APP " | tr ' ' '\n' | tail -1)
wget "$(curl -qfsSL -X "POST" "https://blinry.itch.io/oh-my-git/file/$(curl -qfsSL "https://blinry.itch.io/oh-my-git" | grep -oP 'data-upload_id="\d+"(?=.*oh-my-git-linux\.zip)' | tr '"' '\n' | grep "^[0-9]")" | grep -o '"[^"]*cloudflarestorage[^"]*"' | grep -o 'https[^"]*' | tr -d '\\')" -O oh-my-git.zip || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./$APP || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=oh-my-git
SITE="https://ohmygit.org"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://raw.githubusercontent.com/ivan-hc/repology-versions/main/versions-list | grep "◆ $APP " | tr ' ' '\n' | tail -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$(curl -qfsSL -X "POST" "https://blinry.itch.io/oh-my-git/file/$(curl -qfsSL "https://blinry.itch.io/oh-my-git" | grep -oP 'data-upload_id="\d+"(?=.*oh-my-git-linux\.zip)' | tr '"' '\n' | grep "^[0-9]")" | grep -o '"[^"]*cloudflarestorage[^"]*"' | grep -o 'https[^"]*' | tr -d '\\')" -O oh-my-git.zip || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://ohmygit.org/assets/images/favicon.svg -O ./icons/"$APP" 2> /dev/null

# LAUNCHER
echo "[Desktop Entry]
Name=Oh My Git!
Exec=$APP
Icon=/opt/$APP/icons/$APP
Type=Application
Terminal=false
Categories=Game;" > /usr/local/share/applications/"$APP"-AM.desktop
