#!/bin/sh

APP=openarena

CATEGORIES="Game"
ICONURL="https://upload.wikimedia.org/wikipedia/commons/f/f0/Openarena-logo.svg"

URL=https://aur.archlinux.org/packages/openarena
COMMENT="A violent, sexy, multiplayer first person shooter based on the ioquake3 engine"
APPNAME=OpenArena

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ZIP ARCHIVE
mkdir tmp
cd ./tmp

version=$(wget -q https://aur.archlinux.org/packages/openarena -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep .zip | head -1)
wget $version
dir=$(ls . | rev | cut -c 5- | rev)
echo "$version" >> /opt/$APP/version

unzip -qq ./*.zip

cd ..
mv ./tmp/$dir/* ./
rm -R -f ./tmp

# LINK
cat >> /usr/local/games/$APP << 'EOF'
#!/bin/sh
APP=openarena
exec /opt/$APP/$APP.x86_64
EOF
chmod a+x /usr/local/games/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=openarena
version0=$(cat /opt/$APP/version)
url=https://aur.archlinux.org/packages/openarena
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  version=$(wget -q https://aur.archlinux.org/packages/openarena -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep .zip | head -1)
  wget $version
  dir=$(ls . | rev | cut -c 5- | rev)
  unzip -qq ./*.zip
  cd ..
  if test -f ./tmp/*.zip; then rm ./version
  fi
  echo $version >> ./version
  mv --backup=t ./tmp/$dir/* ./
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
  notify-send "$APP is updated!"
fi
EOF
sed -i s/FILENAMEEXTENTION/$FILENAMEEXTENTION/g /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=$APPNAME
Exec=$APP
Icon=/opt/$APP/icons/$APP
Type=Application
Terminal=false
Categories=$CATEGORIES;
Comment=$COMMENT" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir ./icons
wget $ICONURL -O /opt/$APP/icons/$APP




