#!/bin/sh

APP=photopea

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/spooknik/Photopea-Appimage/releases/download/1.2.1/Photopea_1.2.1_x86_64.AppImage;

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=Photopea
Comment=Photopea in AppImage
Exec=photopea
Terminal=false
Type=Application
Icon=/opt/$APP/$APP.svg
StartupWMClass=Photopea
X-AppImage-Version=1.2.0
Categories=Graphics;
X-AppImage-BuildId=1JjD14uwyf7zD0MXVDkhft0XRpx" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " Photopea is provided by https://github.com/spooknik ";
echo "";
