#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=kdegames
SITE="ivan-hc/KDE-games-suite-appimage"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-*-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/ivan-hc/KDE-games-suite-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
wget "$version" || exit 1
#wget "$version.zsync" 2> /dev/null # Comment out this line if you want to use zsync
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=kdegames
SITE="ivan-hc/KDE-games-suite-appimage"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/ivan-hc/KDE-games-suite-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ] || [ -e /opt/"$APP"/*.zsync ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	[ -e ../*.zsync ] || notify-send "A new version of $APP is available, please wait"
	[ -e ../*.zsync ] && wget "$version.zsync" 2>/dev/null || { wget "$version" || exit 1; }
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv ./tmp/*.zsync ./"$APP".zsync 2>/dev/null || mv --backup=t ./tmp/*mage ./"$APP"
	[ -e ./*.zsync ] && { zsync ./"$APP".zsync || notify-send -u critical "zsync failed to update $APP"; }
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# LAUNCHERS AND ICONS
./kdegames --appimage-extract ".junest/usr/share/icons/hicolor/128x128/apps/*" > /dev/null
./kdegames --appimage-extract ".junest/usr/share/applications/*" > /dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*bomber* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*bovo* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*granatier* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kajongg* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kapman* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*katomic* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kblackbox* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kblocks* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kbounce* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kbreakout* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kdiamond* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kfourinline* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kgoldrunner* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kigo* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*killbots* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kiriki* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kjumpingcube* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*klickety* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*klines* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kmahjongg* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kmines* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*knavalbattle* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*knetwalk* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*knights* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kolf* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kollision* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*konquest* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kpat* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kreversi* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kshisen* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*ksirk* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*ksnakeduel* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kspaceduel* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*ksquares* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*ksudoku* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*ktuberling* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*kubrick* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*lskat* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*palapeli* /opt/"$APP"/icons/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/icons/hicolor/128x128/apps/*picmi* /opt/"$APP"/icons/ 2>/dev/null
cd /opt/"$APP"/icons
for file in *.png; do mv -- "$file" "${file%%.png}"; done
cd ..

mkdir /opt/"$APP"/launchers
cp ./squashfs-root/.junest/usr/share/applications/*bomber* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*bovo* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*granatier* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kajongg* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kapman* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*katomic* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kblackbox* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kblocks* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kbounce* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kbreakout* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kdiamond* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kfourinline* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kgoldrunner* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kigo* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*killbots* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kiriki* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kjumpingcube* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*klickety* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*klines* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kmahjongg* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kmines* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*knavalbattle* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*knetwalk* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*knights* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kolf* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kollision* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*konquest* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kpat* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kreversi* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kshisen* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*ksirk* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*ksnakeduel* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kspaceduel* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*ksquares* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*ksudoku* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*ktuberling* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*kubrick* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*lskat* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*palapeli* /opt/"$APP"/launchers/ 2>/dev/null
cp ./squashfs-root/.junest/usr/share/applications/*picmi* /opt/"$APP"/launchers/ 2>/dev/null
cd /opt/"$APP"/launchers
for f in *; do mv "$f" "$APP-${f%.desktop}-AM.desktop"; done
sed -i "s#Exec=#Exec=/opt/kdegames/kdegames #g" /opt/"$APP"/launchers/*.desktop
sed -i "s#Icon=#Icon=/opt/kdegames/icons/#g" /opt/"$APP"/launchers/*.desktop
cp /opt/"$APP"/launchers/*.desktop /usr/local/share/applications/

rm -R -f /opt/"$APP"/launchers
rm -R -f /opt/"$APP"/squashfs-root
