#!/bin/sh

mkdir /opt/pkg2appimage
cd /opt/pkg2appimage

# Creating a script that removes all the files listed above
rm -R -f /opt/pkg2appimage/remove-pkg2appimage
echo '#!/bin/sh
rm -R -f /usr/bin/pkg2appimage /opt/pkg2appimage' >> /opt/pkg2appimage/remove
chmod a+x /opt/pkg2appimage/remove

mkdir tmp
cd tmp
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous
cd ..
mv ./tmp/*AppImage ./pkg2appimage
rmdir ./tmp
chmod a+x ./pkg2appimage

ln -s /opt/pkg2appimage/pkg2appimage /usr/bin/pkg2appimage

# Changing privileges in /opt/pkg2appimage to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/pkg2appimage

# Message
echo ""
echo " pkg2appimage has been installed!"
echo ""
