#!/bin/sh

APP=pkg2appimage

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
version=$(curl -s https://api.github.com/repos/AppImageCommunity/pkg2appimage/releases/latest | grep browser_download_url | cut -d '"' -f 4 | head -1)
wget $version
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
echo "appimage" >> /opt/$APP/version

cd ./tmp
wget https://github.com/ivan-hc/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
cd ..
mv ./tmp/appimageupdatetool-x86_64.AppImage ./updater
chmod a+x ./updater

rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM

echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo 'cd /opt/$APP
./updater -O ./$APP
chmod a+x /opt/$APP/$APP
rm -R -f /opt/$APP/*zs-old && rm -R -f /opt/$APP/*.part' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater




