#!/bin/sh

APP=platform-tools

mkdir /opt/$APP
cd /opt/$APP

echo '#!/bin/sh
rm -R -f /opt/platform-tools
cd /usr/local/bin && find . -xtype l -exec rm {} \;' >> /opt/$APP/remove;
chmod a+x /opt/$APP/remove;

mkdir tmp
cd tmp
wget https://dl.google.com/android/repository/$APP-latest-linux.zip
unzip -qq ./platform-tools-latest-linux.zip
cd ..
mv ./tmp/$APP/* ./
rm -R -f ./tmp

for f in /opt/$APP/*; do
	ln -s "$f" /usr/local/bin/"$(basename -- "$f")"
done

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP
# MESSAGE
echo "

  The full Android-SDK Platform Tools suite has been installed!
  
";
