#!/bin/sh

APP=play-2048

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/mgrojo/play_2048/releases/download/continuous/Play_2048-main-x86_64.AppImage;

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /urs/games/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=Play 2048
Exec=play-2048
Comment=Another 2048 game
Icon=/opt/$APP/$APP.svg
Type=Application
Categories=Game;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " Play 2048 is provided by https://github.com/mgrojo ";
echo "";
