#!/bin/sh

APP=proton

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp;
cd ./tmp;
wget https://github.com/ferion11/Proton_Appimage/releases/download/continuous-f11wine/proton-linux-x86-v5.11-f11-x86_64.AppImage
cd ..
mv ./tmp/*mage ./$APP
chmod a+x ./$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/bin/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

     Proton Wine AppImage is provided by 

  https://github.com/ferion11/Proton_Appimage
	
"
