#!/bin/sh

APP=pstube

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/prateekmedia/pstube/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)

cd ..
version=$(ls /opt/$APP/tmp)
echo $version >> /opt/$APP/version
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=pstube
version0=$(cat /opt/$APP/version)
version=$(curl -L -s https://github.com/prateekmedia/pstube/releases/latest | grep -E AppImage | head -1 | sed 's/^.*pstube-linux/pstube-linux/' | sed 's/\.AppImage.*/.AppImage/')
if [ "$version0" == "$version" ]; then
  echo "Update not needed, exit!"
else
  notify-send "A new version of $APP is available, please wait!"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://github.com/$(wget https://github.com/prateekmedia/pstube/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)
  cd ..
  rm -R -f /opt/$APP/version
  version=$(ls /opt/$APP/tmp)
  echo $version >> /opt/$APP/version
  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=PsTube
Comment=Watch and download videos without ads
Icon=/opt/$APP/pstube.png
Exec=pstube %u
StartupWMClass=pstube
Categories=Utility;Network;" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://raw.githubusercontent.com/prateekmedia/pstube/main/assets/pstube.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 PsTube is provided by https://github.com/prateekmedia/pstube
  
";
