#!/bin/sh

APP=qbittorrent-lite

# CREATING THE FOLDER
mkdir /opt/$APP
cd /opt/$APP;

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove
APP=qbittorrent-lite
mkdir tmp;
cd tmp;

# DOWNLOADING THE APPIMAGE
REPO=ivan-hc/qbittorrent-appimage
version=$(curl -s https://api.github.com/repos/$REPO/releases | grep browser_download_url | cut -d '"' -f 4 | head -1)
wget $version

cd ..;
mv ./tmp/*.AppImage ./$APP;
chmod a+x ./$APP

rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

echo "[Desktop Entry]
Categories=Network;FileTransfer;P2P;Qt;
Exec='$APP' %U
GenericName=BitTorrent client, unofficial AppImage built from the official PPA
Comment=Download and share files over BitTorrent
Icon=/opt/'$APP'/qbittorrent.svg
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
Name=qBittorrent Lite
Terminal=false
Type=Application
StartupNotify=false
StartupWMClass=qbittorrent
Keywords=bittorrent;torrent;magnet;download;p2p;" >> /usr/share/applications/AM-$APP.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/qbittorrent.svg;

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP
# MESSAGE
echo "

 qBittorrent Lite is built from https://launchpad.net/~qbittorrent-team
  
";
