#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=reaper
ICON=cockos-reaper
SITE="https://reaper.fm"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(echo "https://www.reaper.fm/$(curl -Ls https://www.reaper.fm/download.php | tr '">< ' '\n' | grep -i "x86_64.*tar.xz$" | head -1)")
wget "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
mv ./tmp/*/*/* ./
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./$APP || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=reaper
SITE="https://reaper.fm"
version0=$(cat "/opt/$APP/version")
version=$(echo "https://www.reaper.fm/$(curl -Ls https://www.reaper.fm/download.php | tr '">< ' '\n' | grep -i "x86_64.*tar.xz$" | head -1)")
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	mv --backup=t ./tmp/*/*/* ./
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://portable-linux-apps.github.io/icons/reaper.png -O ./icons/"$ICON" 2> /dev/null

# LAUNCHER
echo "[Desktop Entry]
Name=REAPER
Name[pt_BR]=REAPER
Exec=$APP
Icon=/opt/$APP/icons/$ICON
Type=Application
Terminal=false
Categories=AudioVideo;
Actions=NewProject;ShowAudioConfig;WhatsNew;License;
StartupWMClass=REAPER

[Desktop Action NewProject]
Name=REAPER (create new project)
Name[pt_BR]=REAPER (criar novo projeto)
Exec=$APP -new
Icon=/opt/$APP/icons/$ICON

[Desktop Action ShowAudioConfig]
Name=REAPER (show audio configuration on startup)
Name[pt_BR]=REAPER (mostrar configurações de áudio ao iniciar)
Exec=$APP -audiocfg
Icon=/opt/$APP/icons/$ICON

[Desktop Action WhatsNew]
Name=What's new
Name[pt_BR]=O que há de novo?
Exec=xdg-open /opt/$APP/whatsnew.txt
Icon=text-x-plain

[Desktop Action License]
Name=License and User Agreement
Name[pt_BR]=Licença e contrato de usuário
Exec=xdg-open /opt/$APP/EULA.txt
Icon=text-x-plain" > /usr/local/share/applications/"$APP"-AM.desktop
