#!/bin/sh

APP=redeclipse

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/games/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/redeclipse/deploy/releases/download/appimage_continuous_master/redeclipse-master-x86_64.AppImage;

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/games/$APP

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Red Eclipse
GenericName=First-person shooter game
Comment=First-person shooter with agile gameplay and built-in editor
Exec=redeclipse
TryExec=redeclipse
Icon=/opt/$APP/$APP.svg
Terminal=false
Categories=Game;ActionGame;
StartupNotify=true
Keywords=fps;action;multiplayer;play;arena;mapeditor;" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " Red Eclipse is provided by https://www.redeclipse.net ";
echo "";
