#!/bin/sh

APP=ruffle
REPO="ruffle-rs/ruffle"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

version=$(curl -Ls https://api.github.com/repos/$REPO/releases | jq '.' | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i "linux-x86_64.tar.gz" | cut -d '"' -f 4 | head -1)
wget $version
echo "$version" >> /opt/$APP/version
tar fx ./*tar*
cd ..
mv ./tmp/$APP ./$APP
rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=ruffle
REPO="ruffle-rs/ruffle"
version0=$(cat /opt/$APP/version)
version=$(curl -Ls https://api.github.com/repos/$REPO/releases | jq '.' | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i "linux-x86_64.tar.gz" | cut -d '"' -f 4 | head -1)
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send "A new version of $APP is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget $version
  tar fx ./*tar*
  cd ..
  mv ./tmp/$APP ./$APP
  rm ./version
  echo $version >> ./version
  rm -R -f ./tmp ./*~
  notify-send "$APP is updated!"
fi
EOF
chmod a+x /opt/$APP/AM-updater

# ICON
mkdir icons
wget https://raw.githubusercontent.com/ruffle-rs/ruffle/master/web/packages/extension/assets/images/icon128.png -O ./icons/$APP

# LAUNCHER
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Ruffle Flash emulator
Comment=An open source Flash Player emulator
Exec=$APP
Icon=/opt/$APP/icons/$APP
Terminal=false
Type=Application
Categories=AudioVideo;Video;" >> /usr/share/applications/AM-$APP.desktop




