#!/bin/sh

APP=smplayer

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE PROGRAM
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/smplayer-dev/smplayer/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
version=$(curl -L -s https://github.com/smplayer-dev/smplayer/releases | grep -E AppImage | head -1 | sed 's/^.*SMPlayer/SMPlayer/' | sed 's/\.AppImage.*/.AppImage/')
wget https://github.com/smplayer-dev/smplayer/releases/download/"$v"/$version
echo $version >> /opt/$APP/version
cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=smplayer
version0=$(cat /opt/$APP/version)
version=$(curl -L -s https://github.com/smplayer-dev/smplayer/releases | grep -E AppImage | head -1 | sed 's/^.*SMPlayer/SMPlayer/' | sed 's/\.AppImage.*/.AppImage/')
if [ "$version0" == "$version" ]; then
  echo "Update not needed, exit!"
else
  notify-send "A new version of $APP is available, please wait!"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  v=$(wget -q https://api.github.com/repos/smplayer-dev/smplayer/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
  wget https://github.com/smplayer-dev/smplayer/releases/download/"$v"/$version
  rm -R -f /opt/$APP/version
  echo $version >> /opt/$APP/version
  cd ..
  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Categories=Qt;AudioVideo;Player;Video;
Comment=A great MPlayer front-end
Exec=bash -c 'LD_PRELOAD=/lib/x86_64-linux-gnu/libgio-2.0.so.0 smplayer'
GenericName=Media Player
Icon=/opt/$APP/$APP.png
MimeType=audio/ac3;audio/mp4;audio/mpeg;audio/vnd.rn-realaudio;audio/vorbis;audio/x-adpcm;audio/x-matroska;audio/x-mp2;audio/x-mp3;audio/x-ms-wma;audio/x-vorbis;audio/x-wav;audio/mpegurl;audio/x-mpegurl;audio/x-pn-realaudio;audio/x-scpls;audio/aac;audio/flac;audio/ogg;video/avi;video/mp4;video/flv;video/mpeg;video/quicktime;video/vnd.rn-realvideo;video/x-matroska;video/x-ms-asf;video/x-msvideo;video/x-ms-wmv;video/x-ogm+ogg;video/x-theora;video/webm;
Name=SMPlayer
Type=Application
X-KDE-StartupNotify=false

# Translations
Comment[ar]=واجهة-طرفية ممتازة للمشغل MPlayer
GenericName[ar]=مشغل وسائط

Comment[bg]=Чудесната MPlayer обвивка.
GenericName[bg]=Медиен плейър
Name[bg]=SMPlayer
Icon[bg]=/opt/$APP/$APP.png

Comment[cs]=Skvělý front-end MPlayeru
GenericName[cs]=Přehrávač
Name[cs]=SMPlayer
Icon[cs]=/opt/$APP/$APP.png

Comment[da]=En fremragende MPlayer-brugerflade
GenericName[da]=Medieafspiller
Name[da]=SMPlayer
Icon[da]=/opt/$APP/$APP.png

Comment[de]=Eine tolle MPlayer-Vorderseite
GenericName[de]=Medienwiedergabe
Name[de]=SMPlayer
Icon[de]=/opt/$APP/$APP.png

Comment[el]=Ένα σπουδαίο περιβάλλον χρήστη για το MPlayer
GenericName[el]=Αναπαραγωγέας πολυμέσων
Name[el]=SMPlayer
Icon[el]=/opt/$APP/$APP.png

Comment[en_GB]=A great MPlayer front-end
GenericName[en_GB]=Media Player
Name[en_GB]=SMPlayer
Icon[en_GB]=/opt/$APP/$APP.png

Comment[es]=Un magnífico interfaz gráfico para el MPlayer
GenericName[es]=Reproductor multimedia
Name[es]=SMPlayer
Icon[es]=/opt/$APP/$APP.png

Comment[eu]=MPlayer aurrealde bikain bat
GenericName[eu]=Multimedia Irakurgailua
Name[eu]=SMPlayer
Icon[eu]=/opt/$APP/$APP.png

Comment[fa]=یک رابط کاربری عالی برای MPlayer
GenericName[fa]=پخش‌کننده رسانه
Name[fa]=SMPlayer
Icon[fa]=/opt/$APP/$APP.png

Comment[fr]=Une excellente interface pour MPlayer
GenericName[fr]=Lecteur média
Name[fr]=SMPlayer
Icon[fr]=/opt/$APP/$APP.png

Comment[gl]=Unha excelente interface para MPlayer
GenericName[gl]=Reprodutor multimedia
Name[gl]=SMPlayer
Icon[gl]=/opt/$APP/$APP.png

Comment[he]=מגשר חזיתי MPlayer נהדר
GenericName[he]=נגן מדיה

Comment[hr]=Odlično MPlayer grafičko sučelje
GenericName[hr]=Medijski reproduktor
Name[hr]=SMPlayer
Icon[hr]=/opt/$APP/$APP.png

Comment[id]=MPlayer luar biasa dengan antarmuka
GenericName[id]=Media Player
Name[id]=SMPlayer
Icon[id]=/opt/$APP/$APP.png

Comment[it]=Un grande front-end per MPlayer
GenericName[it]=Media Player
Name[it]=SMPlayer
Icon[it]=/opt/$APP/$APP.png

Comment[ja]=高性能 MPlayer フロントエンド
GenericName[ja]=メディア プレーヤー
Name[ja]=SMPlayer
Icon[ja]=/opt/$APP/$APP.png

Comment[ko]=뛰어난 MPlayer 프론트엔드
GenericName[ko]=미디어 재생기
Name[ko]=SMPlayer
Icon[ko]=/opt/$APP/$APP.png

Comment[lt]=Nuostabi MPlayer sąsaja
GenericName[lt]=Media grotuvas
Name[lt]=SMPlayer
Icon[lt]=/opt/$APP/$APP.png

Comment[sq_AL]=Nje front-end i mrekullueshem per MPlayer.
GenericName[sq_AL]=Media Player
Name[sq_AL]=SMPlayer
Icon[sq_AL]=/opt/$APP/$APP.png

Comment[nqo]=ߡߔߑߟߋߦߊ ߢߊߞߘߐߟߊ ߓߘߍߓߊ
GenericName[nqo]=ߞߟߋߞߟߋ  ߘߐߞߊߙߊ߲ߝߋ߲

Comment[nl]=Een geweldig MPlayer-front-end
GenericName[nl]=Mediaspeler
Name[nl]=SMPlayer
Icon[nl]=/opt/$APP/$APP.png

Comment[pl]=Świetna nakładka dla MPlayera
GenericName[pl]=Odtwarzacz mediów
Name[pl]=SMPlayer
Icon[pl]=/opt/$APP/$APP.png

Comment[pt]=Uma interface para o MPlayer
GenericName[pt]=Reprodutor multimédia
Name[pt]=SMPlayer
Icon[pt]=/opt/$APP/$APP.png

Comment[pt_BR]=Uma excelente interface gráfica para o MPlayer
GenericName[pt_BR]=Reprodutor de mídias
Name[pt_BR]=SMPlayer
Icon[pt_BR]=/opt/$APP/$APP.png

Comment[ru]=Отличная оболочка для MPlayer
GenericName[ru]=Проигрыватель мультимедиа
Name[ru]=SMPlayer
Icon[ru]=/opt/$APP/$APP.png

Comment[sk]=Skvelá nadstavba MPlayer-u
GenericName[sk]=Multimediálny prehrávač
Name[sk]=SMPlayer
Icon[sk]=/opt/$APP/$APP.png

Comment[sr]=Сјајно прочеље за МПлејер
GenericName[sr]=Медија плејер
Name[sr]=СМПлејер
Icon[sr]=/opt/$APP/$APP.png

Comment[sv]=En mäktig framände till MPlayer
GenericName[sv]=Media Spelare
Name[sv]=SMPlayer
Icon[sv]=/opt/$APP/$APP.png

Comment[th]=MPlayer front-end ที่ยอดเยี่ยม
GenericName[th]=เครื่องเล่นสื่อ
Name[th]=SMPlayer
Icon[th]=/opt/$APP/$APP.png

Comment[tr]=MPlayer harika bir ön uç
GenericName[tr]=Medya Oynatıcı
Name[tr]=SMPlayer
Icon[tr]=/opt/$APP/$APP.png

Comment[uk]=Відмінний інтерфейс MPlayer
GenericName[uk]=Медія-програвач
Name[uk]=SMPlayer
Icon[uk]=/opt/$APP/$APP.png

Comment[vi]=Giao diện tuyệt vời cho MPlayer/mpv

Comment[zh_CN]=强大的 MPlayer 前端
GenericName[zh_CN]=多媒体播放器
Name[zh_CN]=SMPlayer
Icon[zh_CN]=/opt/$APP/$APP.png

Comment[zh_TW]=一個優秀的 MPlayer 前端介面程式 
GenericName[zh_TW]=媒體播放器
Name[zh_TW]=SMPlayer
Icon[zh_TW]=/opt/$APP/$APP.png

Comment[ms_MY]=Merupakan bahagian-hadapan MPlayer yang hebat
GenericName[ms_MY]=Pemain Media
Name[ms_MY]=SMPlayer
Icon[ms_MY]=/opt/$APP/$APP.png

GenericName[km]=កម្មវិធី​ចាក់​មេឌា
Name[km]=SMPlayer
Icon[km]=/opt/$APP/$APP.png

Comment[nn_NO]=Eit fantastisk brukargrensesnitt for MPlayer
GenericName[nn_NO]=Mediaspelar
Name[nn_NO]=SMPlayer
Icon[nn_NO]=/opt/$APP/$APP.png
" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://www.smplayer.info/images/icons/smplayer_icon512.png -O $APP.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 SMPlayer is provided by https://www.smplayer.info
  
";
