#!/bin/sh

APP=sqlitebrowser

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget -r -A .AppImage -nd https://download.sqlitebrowser.org/;

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=DB Browser for SQLite
Comment=DB Browser for SQLite is a light GUI editor for SQLite databases
Comment[de]=DB Browser for SQLite ist ein GUI-Editor für SQLite-Datenbanken
Comment[fr]=Un éditeur graphique léger pour les bases de données SQLite
Comment[es]=«DB Browser for SQLite» es un editor gráfico de bases de datos SQLite
Exec=sqlitebrowser %f
Icon=/opt/$APP/$APP.svg
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=Development;Utility;Database;
MimeType=application/vnd.db4s-project+xml;application/sqlitebrowser;application/x-sqlitebrowser;application/vnd.sqlite3;application/geopackage+sqlite3;application/x-sqlite2;application/x-sqlite3;
X-AppImage-Version=v3.12.2" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " SQLite Browser is provided by https://sqlitebrowser.org ";
echo "";
