#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=sunvox
SITE="https://warmplace.ru/soft/sunvox/"
version=$(curl -s "$SITE" | grep -o "sunvox-[0-9]\+\.[0-9]\+\.[0-9]\+[a-z]*\.zip" | head -1 | sed 's/sunvox-\(.*\)\.zip/\1/')
[ -z "$version" ] && {
  echo "Error: Could not detect version from website"
  exit 1
}

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" >../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >>../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
# version=$(curl -Ls https://raw.githubusercontent.com/ivan-hc/repology-versions/main/versions-list | grep "◆ $APP " | tr ' ' '\n' | tail -1)
wget "https://warmplace.ru/soft/sunvox/sunvox-$version.zip" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* ] 2>/dev/null; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" >./version
chmod a+x ./$APP || exit 1

# LINK TO PATH
# SunVox provides all OS builds in one zip, we need to select the linux_x86_64 directory
ln -s "/opt/$APP/$APP/linux_x86_64/$APP" "/usr/local/bin/$APP"
ln -s "/opt/$APP/$APP/linux_x86_64/${APP}_opengl" "/usr/local/bin/${APP}_opengl"

# SCRIPT TO UPDATE THE PROGRAM
cat >>./AM-updater <<'EOF'
#!/bin/sh
set -u
APP=sunvox
SITE="https://warmplace.ru/soft/sunvox/"
version0=$(cat "/opt/$APP/version")
version=$(curl -s "$SITE" | grep -o "sunvox-[0-9]\+\.[0-9]\+\.[0-9]\+[a-z]*\.zip" | head -1 | sed 's/sunvox-\(.*\)\.zip/\1/')
# version=$(curl -Ls https://raw.githubusercontent.com/ivan-hc/repology-versions/main/versions-list | grep "◆ $APP " | tr ' ' '\n' | tail -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "https://warmplace.ru/soft/sunvox/sunvox-$version.zip" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://warmplace.ru/soft/sunvox/images/icon.png -O ./icons/"$APP" 2>/dev/null

# LAUNCHER
echo "[Desktop Entry]
Name=SunVox
Exec=$APP
Icon=/opt/$APP/icons/$APP
Type=Application
Terminal=false
Categories=Audio;" >/usr/local/share/applications/"$APP"-AM.desktop
