#!/bin/sh

APP=supertux2

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/SuperTux/supertux/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "APP=$APP" >> /usr/local/bin/$APP
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/SuperTux/supertux/releases/latest' >> /usr/local/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/local/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/local/bin/$APP
echo "  exec /opt/$APP/$APP" >> /usr/local/bin/$APP
echo 'else' >> /usr/local/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/local/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/local/bin/$APP

########################################################################################

function1='$(wget https://github.com/SuperTux/supertux/releases/latest -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'

echo "  wget https://github.com/$function1 | $function2
  version=$function3" >> /usr/local/bin/$APP

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /usr/local/bin/$APP
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
  exec /opt/$APP/$APP
fi" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Type=Application
Version=1.0
Name=SuperTux 2
Name[en]=SuperTux 2
GenericName=Platform Game
GenericName[en]=Platform Game
GenericName[ca]=Videojoc de Plataformes
GenericName[cs]=Plošinová hra
GenericName[da]=Platformspil
GenericName[de]=Jump ’n’ Run
GenericName[es]=Juego de Plataformas
GenericName[fr]=Jeu de Plate-forme
GenericName[hu]=Egy oldalnézeti játék
GenericName[it]=Videogioco a Piattaforme
GenericName[lt]=Platformos žaidimas
GenericName[nb]=Plattformspill
GenericName[nn]=Plattformspel
GenericName[nl]=Platformspel
GenericName[pt]=Jogo de Plataformas
GenericName[pt_BR]=Jogo de Plataforma
GenericName[ru]=Платформер
GenericName[fi]=Tasohyppely
GenericName[sv]=Plattformsspel
GenericName[tr]=Platform Oyunları
Comment=Play a classic 2D platform game
Comment[en]=Play a classic 2D platform game
Comment[de]=Ein klassisches Jump&Run Spiel
Comment[cs]=Plošinovka inspirovaná SuperMariem s tučňákem Tuxem v hlavní roli
Comment[fi]=Ohjaa pingviiniä perinteisessä tasohyppelyssä
Comment[lt]=Klasikinis 2D platformos žaidimas
Comment[nb]=Et klassisk todimensjonalt plattformspill.
Comment[nn]=Eit klassisk todimensjonalt plattformspel.
Comment[sv]=Ett klassiskt tvådimensionellt plattformsspel
Comment[pt]=Joga este clássico de plataformas 2D
Comment[pt_BR]=Encarne o pinguin Tux neste jogo inspirado em clássicos de Pular&Correr
Comment[hu]=Egy klasszikus 2D-s oldalnézeti játék
Icon=/opt/$APP/$APP.svg
Exec=supertux2
Terminal=false
StartupNotify=false
Categories=Game;ArcadeGame;
Keywords=game;arcade;platform;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " SuperTux is provided by https://www.supertux.org ";
echo "";
