#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 

set -u
APP=superfile
SITE="yorukot/superfile"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
echo "#!/bin/sh\nset -e\nrm -f /usr/local/bin/spf\nrm -R -f /opt/$APP" > "/opt/$APP/remove"
#echo "rm -f /usr/share/applications/AM-$APP.desktop" >> "/opt/$APP/remove"
chmod a+x "/opt/$APP/remove"

# DOWNLOAD AND PREPARE THE APP
# $version is also used for updates


version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*linux.*amd64.*tar.gz$' | head -1)
wget "$version" && echo "$version" > "/opt/$APP/version" || exit 1
tar fx ./*tar* || exit 1
cd ..
mv --backup=t ./tmp/*/*/* ./ && rm -R -f ./tmp || exit 1
chmod a+x "/opt/$APP/spf" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/spf" "/usr/local/bin/spf"

# SCRIPT TO UPDATE THE PROGRAM
cat >> "/opt/$APP/AM-updater" << 'EOF'
#!/bin/sh
set -u
APP=superfile
SITE="yorukot/superfile"
version0=$(cat /opt/$APP/version)
version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | jq '.' | sed 's/[()",{}]/ /g; s/ /\n/g' | grep -o 'https.*linux.*amd64.*tar.gz$' | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	notify-send "A new version of $APP is available, please wait"
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	wget "$version" || exit 1
	tar fx ./*tar* || exit 1
	cd ..
	mv --backup=t ./tmp/*/*/* ./ && rm -R -f ./tmp || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	chmod a+x "/opt/$APP/spf" || exit 1
	notify-send "$APP is updated!"
	exit 0
fi
echo "Update not needed!"
EOF
chmod a+x "/opt/$APP/AM-updater" || exit 1
