#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=sweethome3d
SITE="https://www.sweethome3d.com"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://www.sweethome3d.com/download.jsp | tr "'" '\n' | grep linux-x64.tgz | head -1)
wget "$version" -O "$APP.tgz" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tgz* ] && tar fx ./*tgz* && rm -f ./*tgz*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x "/opt/$APP/SweetHome3D" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/SweetHome3D" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=sweethome3d
SITE="https://www.sweethome3d.com"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://www.sweethome3d.com/download.jsp | tr "'" '\n' | grep linux-x64.tgz | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" -O "$APP.tgz" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tgz* ] && tar fx ./*tgz* && rm -f ./*tgz*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	if [ -d ./tmp/* 2>/dev/null ]; then mv --backup=t ./tmp/*/* ./; else mv --backup=t ./tmp/* ./"$APP" 2>/dev/null || mv --backup=t ./tmp/* ./; fi
	chmod a+x "/opt/$APP/SweetHome3D" || exit 1
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
cp ./*.png ./icons/"$APP"

# LAUNCHER & ICON
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=SweetHome3D
Exec=$APP
Icon=/opt/$APP/icons/$APP
Terminal=false
Type=Application
Categories=Utility;" >> /usr/local/share/applications/"$APP"-AM.desktop
