#!/bin/sh

APP=sweethome3d
SITE="https://www.sweethome3d.com"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

wget --user-agent="X11; Linux x86_64;" https://sourceforge.net/projects/sweethome3d/files/latest/download -O "linux-x64.tgz"
tar fx ./*.tgz
cd ..
mv ./tmp/*/* ./
rm -R -f ./tmp
echo "latest" ./version

# LINK
ln -s /opt/$APP/SweetHome3D /usr/local/bin/$APP

# ICON
mkdir ./icons
cp ./*.png ./icons/$APP

# LAUNCHER & ICON
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=SweetHome3D
Exec=$APP
Icon=/opt/$APP/icons/$APP
Terminal=false
Type=Application
Categories=Utility;" >> ./$APP.desktop /usr/share/applications/AM-$APP.desktop

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
 $APP is provided by $SITE
"
