#!/bin/sh

APP=telegram

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD
mkdir tmp
cd ./tmp

version=$(wget -q https://api.github.com/repos/telegramdesktop/tdesktop/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | egrep '/.*/.*/.*tar.xz' | head -1)
wget $version
echo "$version" >> /opt/$APP/version

tar fx ./*.tar.xz
rm ./*.tar.xz
cd ..
mv ./tmp/Telegram/Telegram* ./$APP
rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=telegram
version0=$(cat /opt/$APP/version)
version=$(wget -q https://api.github.com/repos/telegramdesktop/tdesktop/releases/latest -O - | grep -E browser_download_url | awk -F '[""]' '{print $4}' | egrep '/.*/.*/.*tar.xz' | head -1)
if [ $version = $version0 ]; then
  echo "Update not needed!"
else
  notify-send 'A new version of  is available, please wait'
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget $version
  cd ..
  if test -f ./tmp/*tar.xz; then rm ./version
  fi
  echo "$version" >> ./version
  tar fx ./tmp/*.tar.xz
  rm ./tmp/*.tar.xz
  mv ./tmp/* ./
  rm -R -f ./tmp
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Telegram
Comment=Official desktop version of Telegram messaging app
Exec=$APP -- %u
StartupWMClass=telegram-desktop
Icon=/opt/$APP/icons/$APP
Terminal=false
Type=Application
Categories=Network;
MimeType=application/x-xdg-protocol-tg;x-scheme-handler/tg;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir icons
wget https://web.telegram.org/k/assets/img/apple-touch-icon.png -O ./icons/$APP  2> /dev/null

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 Telegram is provided by https://desktop.telegram.org

"
