#!/bin/sh

APP=trans
SITE="soimort/translate-shell"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp
wget https://www.soimort.org/translate-shell/$APP
chmod a+x ./$APP
cd ..
mv ./tmp/* ./$APP
rm -R -f ./tmp
echo "latest" ./version

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/usr/bin/env bash
APP=trans
mkdir /opt/$APP/tmp
cd /opt/$APP/tmp
wget https://www.soimort.org/translate-shell/$APP
chmod a+x ./$APP
cd ..
mv ./tmp/* ./$APP
rm -R -f ./tmp
EOF
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP
