#!/bin/sh

APP=tutanota

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://mail.tutanota.com/desktop/tutanota-desktop-linux.AppImage

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=Tutanota Desktop
Exec=$APP --no-sandbox %U
Terminal=false
Type=Application
Icon=/opt/$APP/icon/$APP
StartupWMClass=tutanota-desktop
Comment=The desktop client for Tutanota, the secure e-mail service.
MimeType=x-scheme-handler/mailto;
Categories=Network;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir /opt/$APP/icon
wget https://tutanota.com/resources/favicon/logo-favicon.svg -O /opt/$APP/icon/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

 Tutanota is provided by https://tutanota.com

"
