#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=uad-ng
SITE="Universal-Debloater-Alliance/universal-android-debloater-next-generation" SITE2="pkgforge-dev/uad-ng-AppImage"
#VARIANT1="Official (Portable Package)" VARIANT2="AppImage"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP
read -r -p "
 Choose a package format:

 1. Official portable package.

    Source: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation

 2. Unofficial AppImage.

    Source: https://github.com/pkgforge-dev/uad-ng-AppImage

 Which version you choose (type a number and press ENTER)?" response
RELEASE=""

if echo "$response" | grep -q "^1"; then
	RELEASE="PORTABLE"
	version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | sed 's/[()",{} ]/\n/g' | grep -oi 'https.*uad.*noself.*linux.*zip$' | head -1)
	wget "$version" || exit 1
	[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	cd ..
	mv ./tmp/*/uad-ng-noselfupdate-linux ./"$APP" 2>/dev/null || mv ./tmp/uad-ng-noselfupdate-linux ./"$APP" 2>/dev/null || mv ./tmp/uad-ng-noselfupdate-linux ./"$APP"
elif echo "$response" | grep -q "^2"; then
	RELEASE="APPIMAGE"
	version=$(curl -Ls https://api.github.com/repos/pkgforge-dev/uad-ng-AppImage/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
	wget "$version" || exit 1
	cd ..
	mv ./tmp/*mage ./"$APP"
fi
[ -z "$RELEASE" ] && exit 0
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

if [ "$RELEASE" = APPIMAGE ]; then
	# SCRIPT TO UPDATE THE PROGRAM
	cat <<-'HEREDOC' >> ./AM-updater
	#!/bin/sh
	set -u
	APP=uad-ng
	SITE="pkgforge-dev/uad-ng-AppImage"
	version0=$(cat "/opt/$APP/version")
	version=$(curl -Ls https://api.github.com/repos/pkgforge-dev/uad-ng-AppImage/releases/latest | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
	[ -n "$version" ] || { echo "Error getting link"; exit 1; }
	if command -v appimageupdatetool >/dev/null 2>&1; then
	   cd "/opt/$APP" || exit 1
	   appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
	fi
	if [ "$version" != "$version0" ]; then
	   mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	   notify-send "A new version of $APP is available, please wait"
	   wget "$version" || exit 1
	   # Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	   cd ..
	   mv --backup=t ./tmp/*mage ./"$APP"
	   chmod a+x ./"$APP" || exit 1
	   echo "$version" > ./version
	   rm -R -f ./*zs-old ./*.part ./tmp ./*~
	   notify-send "$APP is updated!"
	else
	   echo "Update not needed!"
	fi
	HEREDOC
	chmod a+x ./AM-updater || exit 1

	# LAUNCHER & ICON
	./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
	./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
	COUNT=0
	while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
		if [ -L ./"$APP".desktop ]; then
			LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||' 2>/dev/null)"
			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
		fi
		if [ -L ./DirIcon ]; then
			LINKPATH="$(readlink ./DirIcon | sed 's|^\./||' 2>/dev/null)"
			./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
		fi
		[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
		COUNT=$((COUNT + 1))
	done
	sed -i "s#Exec=[^ ]*#Exec=$APP#g; s#Icon=.*#Icon=/opt/$APP/icons/$APP#g; s# --no-sandbox##g" ./"$APP".desktop
	mv ./"$APP".desktop /usr/local/share/applications/"$APP"-AM.desktop && mv ./DirIcon ./icons/"$APP" 1>/dev/null
	rm -R -f ./squashfs-root
else
	# SCRIPT TO UPDATE THE PROGRAM
	cat <<-'HEREDOC' >> ./AM-updater
	#!/bin/sh
	set -u
	APP=uad-ng
	SITE="Universal-Debloater-Alliance/universal-android-debloater-next-generation"
	version0=$(cat "/opt/$APP/version")
	version=$(curl -Ls https://api.github.com/repos/"$SITE"/releases | sed 's/[()",{} ]/\n/g' | grep -oi 'https.*uad.*noself.*linux.*zip$' | head -1)
	[ -n "$version" ] || { echo "Error getting link"; exit 1; }
	if [ "$version" != "$version0" ]; then
	   mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	   notify-send "A new version of $APP is available, please wait"
	   wget "$version" || exit 1
	   [ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
	   [ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
	   [ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
	   cd ..
	   mv ./tmp/*/uad-ng-noselfupdate-linux ./"$APP" 2>/dev/null || mv ./tmp/uad-ng-noselfupdate-linux ./"$APP" 2>/dev/null || mv ./tmp/uad-ng-noselfupdate-linux ./"$APP"
	   chmod a+x ./"$APP" || exit 1
	   echo "$version" > ./version
	   rm -R -f ./tmp ./*~
	   notify-send "$APP is updated!"
	else
	   echo "Update not needed!"
	fi
	HEREDOC
	chmod a+x ./AM-updater || exit 1

	# ICON
	mkdir -p icons
	curl -s -Lo ./icons/"$APP" https://portable-linux-apps.github.io/icons/"$APP".png

	# LAUNCHER
	rm -f /usr/local/share/applications/"$APP"-AM.desktop
	cat <<-HEREDOC >> /usr/local/share/applications/"$APP"-AM.desktop
	[Desktop Entry]
	StartupWMClass=uad-ng
	Name=Universal Android Debloater Next Generation
	Exec=uad-ng
	Comment=Tool for debloating Android
	Type=Application
	Categories=Utility
	Icon=/opt/$APP/icons/$APP
	HEREDOC
fi
