#!/bin/sh

APP=vidcutter

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/ozmartian/vidcutter/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/ozmartian/vidcutter/releases/download/$v/VidCutter-$v-x86_64.AppImage;

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://api.github.com/repos/ozmartian/vidcutter/releases/latest' >> /opt/$APP/AM-updater

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater
echo 'else' >> /opt/$APP/AM-updater
echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater

########################################################################################

function1='$(wget -q https://api.github.com/repos/ozmartian/vidcutter/releases/latest -O -'
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget https://github.com/ozmartian/vidcutter/releases/download/$v/VidCutter-$v-x86_64.AppImage'

echo "  v=$function1 | $function2
  $function4
  version=$function3" >> /opt/$APP/AM-updater

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$version" >> ./version' >> /opt/$APP/AM-updater
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=VidCutter
GenericName=Media Cutter + Joiner
X-GNOME-FullName=VidCutter
Comment=the simplest + fastest video cutter & joiner
Exec=vidcutter %f
Terminal=false
Type=Application
Icon=/opt/$APP/$APP.svg
Categories=Qt;KDE;Video;AudioVideo;AudioVideoEditing;
Keywords=editing;video;audio;ffmpeg;qt;python;pyqt;mpv;
MimeType=application/x-vidcutter;video/x-msvideo;video/x-ms-wmv;video/x-matroska-3d;video/x-matroska;video/x-flv;video/webm;video/quicktime;video/mpeg;video/mp4;video/3gpp2;video/3gpp;video/mp2t;
StartupNotify=true" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/.icons/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " VidCutter is provided by https://github.com/ozmartian/vidcutter";
echo "";
