#!/bin/sh

echo ""
echo " Vivaldi browser is provided by https://vivaldi.com"
echo ""
echo " 1) Vivaldi Stable, the public release (RECOMMENDED)"
echo ""
echo " 2) Vivaldi Snapshot, the testing version (may be a bit unstable)"
echo ""
read -r -p " What do you choose between 1 and 2? " response
case "$response" in
    1) rm /opt/am/.cache/vivaldi && sudo am install vivaldi-stable;;
    2) rm /opt/am/.cache/vivaldi && sudo am install vivaldi-snapshot;;
    *) echo ""; echo " No valid argument was chosen: installation aborted! "; rm -f /opt/am/.cache/vivaldi; echo "";;
esac
