#!/bin/sh

APP=vscodium

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/VSCodium/vscodium/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/VSCodium/vscodium/releases/download/$v/VSCodium-linux-x64-$v.tar.gz

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

tar fx ./*.tar.gz
rm ./*.tar.gz
cd ..
mv ./tmp/* ./
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "APP=$APP" >> /usr/local/bin/$APP
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/VSCodium/vscodium/releases/latest' >> /usr/local/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/local/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/local/bin/$APP
echo "  exec /opt/$APP/codium" >> /usr/local/bin/$APP
echo 'else' >> /usr/local/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/local/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/local/bin/$APP

########################################################################################

function1='$(wget -q https://api.github.com/repos/VSCodium/vscodium/releases/latest -O -'
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget https://github.com/VSCodium/vscodium/releases/download/$v/VSCodium-linux-x64-$v.tar.gz'

echo "  v=$function1 | $function2
  $function4
  version=$function3" >> /usr/local/bin/$APP

########################################################################################

echo '  cd ..
  if test -f ./tmp/*tar.gz; then rm ./version
  fi
  echo "$version" >> ./version' >> /usr/local/bin/$APP
echo "  tar fx ./tmp/*.tar.gz
  rm ./tmp/*.tar.gz
  mv ./tmp/* ./
  rmdir ./tmp
  exec /opt/$APP/codium
fi" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=vscodium --unity-launch %F
Icon=/opt/$APP/$APP.svg
Type=Application
StartupNotify=false
StartupWMClass=VSCodium
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-codium-workspace;
Actions=new-empty-window;
Keywords=vscode;

X-AppImage-Version=1.59.1-1629418630.glibc2.17

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=vscodium --new-window %F
Icon=/opt/$APP/$APP.svg" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " VSCodium is provided by https://vscodium.com ";
echo "";
