#!/bin/sh

APP=vscodium

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/VSCodium/vscodium/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/VSCodium/vscodium/releases/download/$v/VSCodium-linux-x64-$v.tar.gz

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

tar fx ./*.tar.gz
rm ./*.tar.gz
cd ..
mv ./tmp/* ./
rmdir ./tmp

# LINK
ln -s /opt/$APP/codium /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=vscodium
version0=$(cat /opt/$APP/version)

url=https://github.com/VSCodium/vscodium/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!".
else
  notify-send 'A new version of vscodium is available, please wait'
  mkdir /opt/vscodium/tmp
  cd /opt/vscodium/tmp
  v=$(wget -q https://api.github.com/repos/VSCodium/vscodium/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
  wget https://github.com/VSCodium/vscodium/releases/download/$v/VSCodium-linux-x64-$v.tar.gz
  version=$(ls /opt/$APP/tmp)
  cd ..
  if test -f ./tmp/*tar.gz; then rm ./version
  fi
  echo "$version" >> ./version
  tar fx ./tmp/*.tar.gz
  rm ./tmp/*.tar.gz
  mv ./tmp/* ./
  rmdir ./tmp
fi
EOF
chmod a+x ./AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=vscodium --unity-launch %F
Icon=/opt/$APP/icons/$APP
Type=Application
StartupNotify=false
StartupWMClass=VSCodium
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-codium-workspace;
Actions=new-empty-window;
Keywords=vscode;

X-AppImage-Version=1.59.1-1629418630.glibc2.17

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=vscodium --new-window %F
Icon=/opt/$APP/icons/$APP" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir icons
wget https://raw.githubusercontent.com/VSCodium/vscodium/master/src/stable/resources/linux/code.png -O ./icons/$APP

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo " VSCodium is provided by https://vscodium.com ";
echo "";
