#!/bin/sh

APP=webcamoid
URL=https://github.com/webcamoid/webcamoid/releases/latest

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp
APP=webcamoid
URL=https://github.com/webcamoid/webcamoid/releases/latest
wget https://github.com/$(wget $URL -O - | egrep '/.*/.*/.*AppImage' -o)

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM
function1='$(wget '$URL' -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'
echo '#!/bin/sh
APP='$APP'
version0=$(cat /opt/$APP/version)
url='$URL'
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!"
else
  notify-send "A new version of '$APP' is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://github.com/'$function1' | '$function2'
  version='$function3'
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo $version >> ./version
  mv --backup=t ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=Webcamoid
GenericName=Webcam Capture Software
GenericName[ca]=Programari de Captura de Càmera web
GenericName[de]=Webcam-Capture-Software
GenericName[el]=κάμερα συλλαμβάνει το λογισμικό
GenericName[es]=Programa para Captura de la Webcam
GenericName[fr]=Logiciel de Capture Webcam
GenericName[gl]=Programa de Captura de Webcam
GenericName[it]=Webcam Capture Software
GenericName[ja]=ウェブカメラのキャプチャソフトウェア
GenericName[ko]=웹캠 캡처 소프트웨어
GenericName[pl]=Oprogramowanie do przechwytywania z kamery internetowej
GenericName[pt]=Software de Captura de Webcam
GenericName[ru]=Программа для захвата веб-камеры
GenericName[zh_CN]=摄像头捕捉软件
GenericName[zh_TW]=攝像頭捕捉軟件
Comment=Take photos and record videos with your webcam
Comment[ca]=Fer fotos i gravar vídeos amb la seva webcam
Comment[de]=Nehme Fotos und Videos mit deiner Webcam auf
Comment[el]=Τραβήξτε φωτογραφίες και εγγραφή βίντεο με την κάμερα σας
Comment[es]=Tome fotos y grabe videos con su camara web
Comment[fr]=Prenez des photos et enregistrer des vidéos avec votre webcam
Comment[gl]=Facer fotos e gravar vídeos coa súa cámara web
Comment[it]=Scatta foto e registrare video con la tua webcam
Comment[ja]=ウェブカメラで写真や記録ビデオを撮影
Comment[ko]=웹캠으로 사진과 기록 비디오를 촬영
Comment[pl]=Rób zdjęcia i nagrywaj wideo z kamery internetowej
Comment[pt]=Tirar fotos e gravar vídeos com sua webcam
Comment[ru]=Снимайте фотографии и записывайте видео с веб-камеры
Comment[zh_CN]=拍摄照片和录制视频与您的摄像头
Comment[zh_TW]=拍攝照片和錄製視頻與您的攝像頭
Exec=webcamoid
Icon=/opt/webcamoid/webcamoid.png
Terminal=false
Type=Application
Categories=AudioVideo;Player;Qt;
StartupNotify=true" >> /usr/share/applications/AM-$APP.desktop

# ICON
wget https://webcamoid.github.io/theme/images/icons/webcamoid.png

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo '

   Webcamoid is provided by https://webcamoid.github.io

'
