#!/bin/sh

APP=wget

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

wget2 -q https://github.com/ivan-hc/AM/raw/main/tools/x86_64/$APP
cd ..
mv ./tmp/$APP ./$APP
chmod a+x /opt/$APP/$APP
echo "1.21.4" >> ./version
rmdir ./tmp

# LINK
echo '#!/bin/sh
APP=wget
/opt/$APP/$APP --no-check-certificate "$@"' >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP
