#!/bin/sh

APP=whatsapp-for-linux

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/eneshecan/whatsapp-for-linux/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/eneshecan/whatsapp-for-linux/releases/download/$v/whatsapp-for-linux-latest-x86_64.AppImage

echo "$v" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "APP=$APP" >> /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://api.github.com/repos/eneshecan/whatsapp-for-linux/releases/latest' >> /usr/local/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/local/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/local/bin/$APP
echo "  exec /opt/$APP/$APP" >> /usr/local/bin/$APP
echo 'else' >> /usr/local/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/local/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/local/bin/$APP

########################################################################################

function1='$(wget -q https://api.github.com/repos/eneshecan/whatsapp-for-linux/releases/latest -O -'
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget https://github.com/eneshecan/whatsapp-for-linux/releases/download/$v/whatsapp-for-linux-latest-x86_64.AppImage'

echo "  v=$function1 | $function2
  $function4
  version=$function3" >> /usr/local/bin/$APP

########################################################################################

echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo "$v" >> ./version' >> /usr/local/bin/$APP
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
  exec /opt/$APP/$APP
fi" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Type=Application
Encoding=UTF-8
Version=1.0
Name=WhatsApp for Linux
GenericName=Unofficial WhatsApp client
Comment=An unofficial WhatsApp desktop application for linux
Exec=whatsapp-for-linux
Icon=/opt/$APP/$APP.svg
Categories=GTK;GNOME;Network;
Keywords=chat;im;messaging;messenger;sms;whatsapp;whatsapp-desktop;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "
       This version of whatsapp-for-linux comes from
       
      https://github.com/eneshecan/whatsapp-for-linux
      ";
