#!/bin/sh

APP=whatsapp-nativefier

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/frealgagu/archlinux.whatsapp-nativefier/releases/download/$v/whatsapp-nativefier-$v-x86_64.pkg.tar.zst;

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/wa-version

tar xf ./*.tar.zst;
rm ./*.tar.zst;
cd ..
mv ./tmp/opt/$APP/* ./
rm -R -f /opt/$APP/tmp

# LINK
ln -s /opt/$APP/WhatsApp /usr/local/bin/$APP 2> /dev/null

# SCRIPT TO UPDATE THE PROGRAM
cat >> /opt/$APP/AM-updater << 'EOF'
#!/bin/sh
APP=whatsapp-nativefier
version0=$(cat /opt/$APP/wa-version)

url=https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!".
else
  notify-send 'A new version of whatsapp-nativefier is available, please wait'
  mkdir /opt/whatsapp-nativefier/tmp
  cd /opt/whatsapp-nativefier/tmp
  v=$(wget -q https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
  wget https://github.com/frealgagu/archlinux.whatsapp-nativefier/releases/download/$v/whatsapp-nativefier-$v-x86_64.pkg.tar.zst;
  version=$(ls /opt/$APP/tmp)
  cd ..
  if test -f ./tmp/*tar.zst; then rm ./wa-version
  fi
  echo "$version" >> ./wa-version
  tar xf ./*.tar.zst
  rm ./tmp/*.tar.zst
  mv ./tmp/opt/whatsapp-nativefier/* ./
  rm -R -f /opt/whatsapp-nativefier/tmp
  notify-send whatsapp-nativefier is updated!
fi
EOF
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/AM-$APP.desktop
echo "[Desktop Entry]
Name=WhatsApp
Comment=WhatsApp desktop built with nativefier (electron)
Exec=whatsapp-nativefier
Icon=/opt/$APP/icons/$APP
Encoding=UTF-8
StartupWMClass=whatsapp-nativefier-d40211
Terminal=false
StartupNotify=true
Type=Application
Categories=Network;Chat;InstantMessaging;Application;" >> /usr/share/applications/AM-$APP.desktop

# ICON
mkdir icons
wget https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg -O ./icons/$APP 2> /dev/null

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo "         WhatsApp Nativefier is provided by";
echo "";
echo "https://github.com/frealgagu/archlinux.whatsapp-nativefier";
echo "";
