#!/bin/sh

APP=whatsapp-nativefier

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/frealgagu/archlinux.whatsapp-nativefier/releases/download/$v/whatsapp-nativefier-$v-x86_64.pkg.tar.zst;

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/wa-version

tar xf ./*.tar.zst;
rm ./*.tar.zst;
cd ..
mv ./tmp/opt/$APP/* ./
rm -R -f ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM
echo '#!/bin/sh' >> /usr/local/bin/$APP
echo "APP=$APP" >> /usr/local/bin/$APP
echo "cd /opt/$APP" /usr/local/bin/$APP
echo 'version0=$(cat /opt/$APP/wa-version)

url=https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest' >> /usr/local/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/local/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/local/bin/$APP
echo "  exec /opt/$APP/WhatsApp" >> /usr/local/bin/$APP
echo 'else' >> /usr/local/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/local/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/local/bin/$APP

########################################################################################

function1='$(wget -q https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest -O -'
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget https://github.com/frealgagu/archlinux.whatsapp-nativefier/releases/download/$v/whatsapp-nativefier-$v-x86_64.pkg.tar.zst;'

echo "  v=$function1 | $function2
  $function4
  version=$function3" >> /usr/local/bin/$APP

########################################################################################

echo '  cd ..
  if test -f ./tmp/*tar.zst; then rm ./wa-version
  fi
  echo "$version" >> ./wa-version' >> /usr/local/bin/$APP
echo "  tar xf ./*.tar.zst
  rm ./tmp/*.tar.zst
  mv ./tmp/opt/$APP/* ./
  rm -R -f ./tmp
  exec /opt/$APP/WhatsApp
fi" >> /usr/local/bin/$APP
chmod a+x /usr/local/bin/$APP

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Name=WhatsApp
Comment=WhatsApp desktop built with nativefier (electron)
Exec=whatsapp-nativefier
Icon=/opt/$APP/$APP.svg
Encoding=UTF-8
StartupWMClass=whatsapp-nativefier-d40211
Terminal=false
StartupNotify=true
Type=Application
Categories=Network;Chat;InstantMessaging;Application;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "";
echo "         WhatsApp Nativefier is provided by";
echo "";
echo "https://github.com/frealgagu/archlinux.whatsapp-nativefier";
echo "";
