#!/bin/sh

# AM INSTALL SCRIPT VERSION 3. 
set -u
APP=windows95
SITE="felixrieseberg/windows95"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/felixrieseberg/windows95/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "amd64.deb" | head -1)
wget "$version" || exit 1
ar x *.deb
tar xf data.tar.xz
cd ..
mv --backup=t ./tmp/usr/lib/windows95/* ./
rm -R -f ./tmp || exit 1
echo "$version" > ./version

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=windows95
SITE="felixrieseberg/windows95"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/felixrieseberg/windows95/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | grep -i "amd64.deb" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	ar x *.deb
	tar xf data.tar.xz
	cd ..
	mv --backup=t ./tmp/usr/lib/windows95/* ./
	echo "$version" > ./version
	rm -R -f ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICON
mkdir -p icons
wget https://raw.githubusercontent.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/main/icons/windows95.png -O ./icons/"$APP" 2> /dev/null

# LAUNCHER
echo "[Desktop Entry]
Name=windows95
Comment=Windows 95, in an app. I'm sorry.
GenericName=windows95
Exec=windows95 %U
Icon=/opt/$APP/icons/$APP
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;" > /usr/local/share/applications/"$APP"-AM.desktop
