#!/bin/sh

APP=wine32

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/pawitp/wine-appimage/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
echo "$v" >> /opt/$APP/version
wget https://github.com/pawitp/wine-appimage/releases/download/$v/wine

cd ..
mv ./tmp/wine ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM

val1='"$1"'
val2='"$@"'

echo '#!/bin/sh' >> /usr/bin/$APP
echo "APP=$APP" >> /usr/bin/$APP

echo 'version0=$(cat /opt/$APP/version)
url=https://api.github.com/repos/pawitp/wine-appimage/releases/latest' >> /usr/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/bin/$APP

echo "  case "$val1" in
  $APP) exec /opt/$APP/$APP ;;
  *) exec /opt/$APP/$APP "$val2" ;;
esac" >> /usr/bin/$APP

echo 'else' >> /usr/bin/$APP

echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/bin/$APP

function1='$(wget -q https://api.github.com/repos/pawitp/wine-appimage/releases/latest -O -'
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"
function3='$(ls /opt/$APP/tmp)'
function4='wget WGET'

echo "  v=$function1 | $function2" >> /usr/bin/$APP
echo '  wget https://github.com/pawitp/wine-appimage/releases/download/$v/wine
  cd ..
  if test -f ./tmp/wine; then rm ./version
  fi
  echo "$v" >> ./version' >> /usr/bin/$APP
echo "  mv ./tmp/wine ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
  case "$val1" in
  $APP) exec /opt/$APP/$APP ;;
  *) exec /opt/$APP/$APP "$val2" ;;
esac
fi" >> /usr/bin/$APP
chmod a+x /usr/bin/$APP

ln -s /usr/bin/$APP /opt/$APP/wine

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

     Wine32 Stable AppImage is provided by
 
    https://github.com/pawitp/wine-appimage 

"
