#!/bin/sh

# Creating a dedicated folder for wine-staging
mkdir /opt/wine-staging
cd /opt/wine-staging
mkdir tmp
cd ./tmp

# Downloading the AppImage
wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-staging
cd ..
mv ./tmp/wine*AppImage ./wine-staging
chmod a+x ./wine-staging
rmdir ./tmp

ln -s /opt/wine-staging/wine-staging /usr/bin/wine
ln -s /opt/wine-staging/wine-staging /usr/bin/wineserver

# Creating an updater script
rm -R -f /opt/wine-staging/wine-update
echo '#!/bin/sh
version=$(exec /opt/wine-staging/wine-staging --version  | grep -Eo "[0-9]+([.][0-9]+)?")
url="https://github.com/mmtrt/WINE_AppImage/releases/download/continuous-staging/wine-staging_$version-x86_64.AppImage"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
else
  mkdir /opt/wine-staging/tmp
  cd /opt/wine-staging/tmp
  wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-staging
  cd ..
  mv ./tmp/wine*AppImage ./wine-staging
  chmod a+x ./wine-staging
  rmdir ./tmp
fi' >> /opt/wine-staging/wine-update
chmod a+x /opt/wine-staging/wine-update

# Creating a script that removes all the files listed above
rm -R -f /opt/wine-staging/remove
echo '#!/bin/sh
currentuser=$(who | awk '{print $1}')
rm -R -f /usr/bin/wine /usr/bin/wineserver /home/$currentuser/.config/autostart/wine-staging-update.desktop /opt/wine-staging' >> /opt/wine-staging/remove
chmod a+x /opt/wine-staging/remove


# Creating the "about" file
rm -R -f /opt/wine-staging/about
echo "
 WINE - Compatibility layer to run MS Windows apps and games on GNU/Linux.
 
 This version is for both x86 and x64 MS Windows programs.
 
 USAGE: wine winecfg (this will launch WINE Config)
        wine <program>.exe (to launch a Windows program)
 
 SITE: https://www.winehq.org
 SOURCE: https://github.com/mmtrt/WINE_AppImage" >> /opt/wine-staging/about
 
# Changing privileges in /opt/wine-staging to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/wine-staging

# Creating a process for "wine-update"
mkdir /home/$currentuser/.config/autostart
rm -R -f /home/$currentuser/.config/autostart/wine-update.desktop
echo "[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=wine-update
Comment=Automatic update of WINE
Exec=/opt/wine-staging/wine-update
OnlyShowIn=XFCE;
RunHook=0
StartupNotify=true
Terminal=false
Hidden=false" >> /home/$currentuser/.config/autostart/wine-update.desktop
chown -R $currentuser /home/$currentuser/.config/autostart

echo "
 WINE - Compatibility layer to run MS Windows apps and games on GNU/Linux.
 
 This version is for both x86 and x64 MS Windows programs.
 
 USAGE: wine winecfg (this will launch WINE Config)
        wine <program>.exe (to launch a Windows program)
 
 SITE: https://www.winehq.org
 
 SOURCE: https://github.com/mmtrt/WINE_AppImage
 "
