#!/bin/sh

APP=wine-devel

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /opt/$APP /usr/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-devel

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# SCRIPT TO LAUNCH AND UPDATE THE PROGRAM

val1='"$1"'
val2='"$@"'

echo '#!/bin/sh' >> /usr/bin/$APP
echo "APP=$APP" >> /usr/bin/$APP
echo 'version0=$(cat /opt/$APP/version)

url=https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-devel' >> /usr/bin/$APP

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /usr/bin/$APP
echo '  echo "Update not needed!".'  >> /usr/bin/$APP
echo "  case "$val1" in
  $APP) exec /opt/$APP/$APP ;;
  *) exec /opt/$APP/$APP "$val2" ;;
esac" >> /usr/bin/$APP
echo 'else' >> /usr/bin/$APP
echo "  notify-send 'A new version of $APP is available, please wait'" >> /usr/bin/$APP
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /usr/bin/$APP
echo "  wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-devel" >> /usr/bin/$APP
echo '  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  version=$(ls /opt/$APP/tmp)
  echo "$version" >> ./version' >> /usr/bin/$APP
echo "  mv ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
  case "$val1" in
  $APP) exec /opt/$APP/$APP ;;
  *) exec /opt/$APP/$APP "$val2" ;;
esac
fi" >> /usr/bin/$APP
chmod a+x /usr/bin/$APP

ln -s /usr/bin/$APP /opt/$APP/wine

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE

echo "
                                WINE
 
    Compatibility layer to run MS Windows apps and games on GNU/Linux.

       This version is for both x86 and x64 MS Windows programs.
 
                   SITE: https://www.winehq.org
 
           SOURCE: https://github.com/mmtrt/WINE_AppImage

 "
