#!/bin/sh

echo ""
echo " Wine AppImage is provided by https://github.com/mmtrt/WINE_AppImage"
echo ""
echo " Please choose only one version of WINE:"
echo ""
echo " 1) Wine Stable, the current stable wine version (recommended)"
echo ""
echo " 2) Wine Staging, the most recent testing wine version (for testers)"
echo ""
echo " 3) Wine Devel, used to provide development headers (for developers)"
echo ""
read -r -p " What do you choose between 1, 2 and 3? " response
case "$response" in
    1) rm /opt/am/.cache/wine && sudo am install wine-stable;;
    2) rm /opt/am/.cache/wine && sudo am install wine-staging;;
    3) rm /opt/am/.cache/wine && sudo am install wine-devel;;
    *) echo ""; echo " No valid argument was chosen: installation aborted! "; rm -f /opt/am/.cache/wine; echo "";;
esac
