#!/bin/sh

APP=wine32

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

v=$(wget -q https://api.github.com/repos/pawitp/wine-appimage/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
echo "$v" >> /opt/$APP/version
wget https://github.com/pawitp/wine-appimage/releases/download/$v/wine

cd ..
mv ./tmp/wine ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/bin/$APP

# SCRIPT TO UPDATE THE PROGRAM

echo '#!/bin/sh' >> /opt/$APP/AM-updater
echo "APP=$APP" >> /opt/$APP/AM-updater

echo 'version0=$(cat /opt/$APP/version)
url=https://api.github.com/repos/pawitp/wine-appimage/releases/latest' >> /opt/$APP/AM-updater

echo 'if curl -L -s $url | grep -ioF "$version0"; then' >> /opt/$APP/AM-updater
echo '  echo "Update not needed!".'  >> /opt/$APP/AM-updater

echo 'else' >> /opt/$APP/AM-updater

echo "  notify-send 'A new version of $APP is available, please wait'" >> /opt/$APP/AM-updater
echo "  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp" >> /opt/$APP/AM-updater

function1='$(wget -q https://api.github.com/repos/pawitp/wine-appimage/releases/latest -O -'
part0='{print $4}'
part1='[""]'
function2="grep -E tag_name | awk -F '$part1' '$part0')"

echo "  v=$function1 | $function2" >> /opt/$APP/AM-updater
echo '  wget https://github.com/pawitp/wine-appimage/releases/download/$v/wine
  cd ..
  if test -f ./tmp/wine; then rm ./version
  fi
  echo "$v" >> ./version' >> /opt/$APP/AM-updater
echo "  mv ./tmp/wine ./$APP
  chmod a+x /opt/$APP/$APP
  rmdir ./tmp
fi" >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo "

     Wine32 Stable AppImage is provided by
 
    https://github.com/pawitp/wine-appimage 

"
