#!/bin/sh

# Creating a dedicated folder for wine-devel
mkdir /opt/wine-devel
cd /opt/wine-devel

# Creating a script that removes all the files listed
rm -R -f /opt/wine-devel/remove
echo '#!/bin/sh
rm -R -f /opt/wine-devel /usr/bin/wine-devel' >> /opt/wine-devel/remove
chmod a+x /opt/wine-devel/remove

mkdir tmp
cd ./tmp

# Downloading the AppImage
wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-devel
cd ..
mv ./tmp/wine*AppImage ./wine-devel
chmod a+x ./wine-devel
rmdir ./tmp

echo '#!/bin/sh
version=$(exec /opt/wine-devel/wine-devel --version  | grep -Eo "[0-9]+([.][0-9]+)?")
url="https://github.com/mmtrt/WINE_AppImage/releases/download/continuous-devel/wine-devel_$version-x86_64.AppImage"
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "Update not needed, exit!"
  case "$1" in
  	wine-devel) exec /opt/wine-devel/wine-devel ;;
  	*) exec /opt/wine-devel/wine-devel "$@" ;;
  esac
else
  notify-send "A new version of Wine is available, please wait!"
  mkdir /opt/wine-devel/tmp
  cd /opt/wine-devel/tmp
  wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-devel
  cd ..
  mv ./tmp/wine*AppImage ./wine-devel
  chmod a+x ./wine-devel
  rmdir ./tmp
  case "$1" in
  	wine-devel) exec /opt/wine-devel/wine-devel ;;
  	*) exec /opt/wine-devel/wine-devel "$@" ;;
  esac
fi' >> /usr/bin/wine-devel
chmod a+x /usr/bin/wine-devel

ln -s /usr/bin/wine-devel /opt/wine-devel/wine

# Changing privileges in /opt/wine-devel to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/wine-devel

echo "
                                WINE
 
    Compatibility layer to run MS Windows apps and games on GNU/Linux.
 
       This version is for both x86 and x64 MS Windows programs.
 
                   SITE: https://www.winehq.org
 
           SOURCE: https://github.com/mmtrt/WINE_AppImage
 "
