#!/bin/sh

# AM INSTALL SCRIPT VERSION 3.5
set -u
APP=wps-office
SITE="ivan-hc/WPS-Office-appimage"

# CREATE DIRECTORIES AND ADD REMOVER
[ -n "$APP" ] && mkdir -p "/opt/$APP/tmp" "/opt/$APP/icons" && cd "/opt/$APP/tmp" || exit 1
printf "#!/bin/sh\nset -e\nrm -f /usr/local/bin/$APP\nrm -R -f /opt/$APP" > ../remove
printf '\n%s' "rm -f /usr/local/share/applications/$APP*-AM.desktop" >> ../remove
chmod a+x ../remove || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -Ls https://api.github.com/repos/ivan-hc/WPS-Office-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
wget "$version" || exit 1
# Keep this space in sync with other installation scripts
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
cd ..
mv ./tmp/*mage ./"$APP"
# Keep this space in sync with other installation scripts
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

# LINK TO PATH
ln -s "/opt/$APP/$APP" "/usr/local/bin/$APP"

# SCRIPT TO UPDATE THE PROGRAM
cat >> ./AM-updater << 'EOF'
#!/bin/sh
set -u
APP=wps-office
SITE="ivan-hc/WPS-Office-appimage"
version0=$(cat "/opt/$APP/version")
version=$(curl -Ls https://api.github.com/repos/ivan-hc/WPS-Office-appimage/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
if command -v appimageupdatetool >/dev/null 2>&1; then
	cd "/opt/$APP" || exit 1
	appimageupdatetool -Or ./"$APP" && chmod a+x ./"$APP" && echo "$version" > ./version && exit 0
fi
if [ "$version" != "$version0" ]; then
	mkdir "/opt/$APP/tmp" && cd "/opt/$APP/tmp" || exit 1
	notify-send "A new version of $APP is available, please wait"
	wget "$version" || exit 1
	# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
	cd ..
	mv --backup=t ./tmp/*mage ./"$APP"
	chmod a+x ./"$APP" || exit 1
	echo "$version" > ./version
	rm -R -f ./*zs-old ./*.part ./tmp ./*~
	notify-send "$APP is updated!"
else
	echo "Update not needed!"
fi
EOF
chmod a+x ./AM-updater || exit 1

# ICONS
./"$APP" --appimage-extract usr/share/icons/hicolor/128x128/apps/*.png 1>/dev/null && mv ./squashfs-root/usr/share/icons/hicolor/128x128/apps/*.png ./icons/
for file in ./icons/*.png; do
    mv -- "$file" "${file%%.png}"
done


# LAUNCHERS
./"$APP" --appimage-extract opt/kingsoft/wps-office/desktops/*.desktop 1>/dev/null && mv ./squashfs-root/op*/kingsoft/wps-office/desktops/*.desktop ./
for f in *.desktop ; do mv "$f" "$APP-${f%.desktop}-AM.desktop"; done
sed -i "s#Icon=#Icon=/opt/$APP/icons/#g" ./*-AM.desktop
sed -i "s#/usr/bin/##g" ./*-AM.desktop
sed -i "s#Exec=#Exec=$APP #g" ./*-AM.desktop
sed -i 's/wps-office wps %F/wps-office %F/g' ./*prometheus-AM.desktop
sed -i "s/WPS [0-9]*/WPS OFFICE/g" ./*prometheus-AM.desktop

mv ./*-AM.desktop /usr/local/share/applications/
rm -R -f ./squashfs-root
