#!/bin/sh

APP=xournal++
URL=https://github.com/xournalpp/xournalpp/releases/latest

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/$APP.desktop /opt/$APP /usr/local/bin/xournalpp" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE APPIMAGE
mkdir tmp
cd ./tmp

wget https://github.com/$(wget https://github.com/xournalpp/xournalpp/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)

version=$(ls /opt/$APP/tmp)
echo "$version" >> /opt/$APP/version

cd ..
mv ./tmp/*mage ./$APP
chmod a+x /opt/$APP/$APP
rmdir ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/xournalpp

# SCRIPT TO UPDATE THE PROGRAM
function1='$(wget '$URL' -O -'
function2="egrep '/.*/.*/.*AppImage' -o)"
function3='$(ls /opt/$APP/tmp)'
echo '#!/bin/sh
APP='$APP'
version0=$(cat /opt/$APP/version)
url='$URL'
if curl -L -s $url | grep -ioF "$version0"; then
  echo "Update not needed!"
else
  notify-send "A new version of '$APP' is available, please wait"
  mkdir /opt/$APP/tmp
  cd /opt/$APP/tmp
  wget https://github.com/'$function1' | '$function2'
  version='$function3'
  cd ..
  if test -f ./tmp/*mage; then rm ./version
  fi
  echo $version >> ./version
  mv --backup=t ./tmp/*mage ./$APP
  chmod a+x /opt/$APP/$APP
  rm -R -f ./tmp ./*~
fi' >> /opt/$APP/AM-updater
chmod a+x /opt/$APP/AM-updater

# LAUNCHER
rm /usr/share/applications/$APP.desktop
echo "[Desktop Entry]
Type=Application

Name=Xournal++
Comment=Take handwritten notes
Keywords=Tablet;Wacom;Pen Input;PDF Annotation;Markup
Name[fr]=Xournal++
Comment[fr]=Prise de notes manuscrites
Name[ca]=Xournal++
Comment[ca]=Preneu notes a mà
Name[cs]=Xournal++
Comment[cs]=Dělejte si rukou psané poznámky
Name[de]=Xournal++
Comment[de]=Handnotizen erstellen
Name[pl]=Xournal++
Comment[pl]=Notatki odręczne
Name[zh_CN]=Xournal++
Comment[zh_CN]=手写注释工具，可为PDF文件添加各种元素的注释标记
Name[ru]=Xournal++
Comment[ru]=Делайте рукописные заметки

Exec=xournalpp %f
StartupWMClass=xournalpp
Terminal=false
StartupNotify=true
MimeType=application/x-xoj;application/x-xojpp;application/x-xopp;application/x-xopt;application/pdf;
Icon=/opt/$APP/$APP.ico
Categories=Office;GNOME;GTK;" >> /usr/share/applications/$APP.desktop

# ICON
wget https://xournalpp.github.io/img/favicon.ico -O $APP.ico

# CHANGE THE PERMISSIONS
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/$APP

# MESSAGE
echo '

  Xournal++ is provided by https://xournalpp.github.io

'
