#!/bin/sh

APP=zotero
SITE="https://www.zotero.org"

# CREATE THE FOLDER
mkdir /opt/$APP
cd /opt/$APP

# ADD THE REMOVER
echo '#!/bin/sh' >> /opt/$APP/remove
echo "rm -R -f /usr/share/applications/AM-$APP.desktop /opt/$APP /usr/local/bin/$APP" >> /opt/$APP/remove
chmod a+x /opt/$APP/remove

# DOWNLOAD THE ARCHIVE
mkdir tmp
cd ./tmp

wget "https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64" --trust-server-names
echo "$version" >> /opt/$APP/version
cd ..
tar fx ./tmp/*.tar.bz2 -C ./tmp/ && mv ./tmp/*/* .
rm -R -f ./tmp

# LINK
ln -s /opt/$APP/$APP /usr/local/bin/$APP

# LAUNCHER & ICON
echo "[Desktop Entry]
Name=Zotero
Exec=$APP
Icon=/opt/$APP/chrome/icons/default/default256.png
Type=Application
Terminal=false
Categories=Office;
MimeType=text/plain;x-scheme-handler/zotero;application/x-research-info-systems;text/x-research-info-systems;text/ris;application/x-endnote-refer;application/x-inst-for-Scientific-info;application/mods+xml;application/rdf+xml;application/x-bibtex;text/x-bibtex;application/marc;application/vnd.citationstyles.style+xml
X-GNOME-SingleWindow=true" >> /usr/share/applications/AM-$APP.desktop




