#!/bin/sh
HERE=$(dirname "$(readlink -f "$0")")
if [ -z "$1" ] && [ ! -t 1 ]; then
    if command -v am >/dev/null 2>&1 && [ -e /opt/am/APP-MANAGER ]; then
        AM_EXEC_CMD="am -h"
    elif command -v appman >/dev/null 2>&1; then
        AM_EXEC_CMD="appman -h"
    else
        AM_EXEC_CMD="$HERE/AM-INSTALLER"
    fi
    for TERM_CMD in x-terminal-emulator\ -e gnome-terminal\ -- konsole\ -e xfce4-terminal\ -e mate-terminal\ -e lxterminal\ -e terminator\ -e urxvt\ -e xterm\ -e; do
        if command -v "$(echo "$TERM_CMD" | cut -d' ' -f1)" >/dev/null 2>&1; then
            exec $TERM_CMD sh -c "$AM_EXEC_CMD; printf '\nPress CTRL+C to close this window...\n'; sleep 1h"
        fi
    done
else
    if [ "$1" = "setup" ] && ! command -v am >/dev/null 2>&1 && ! command -v appman >/dev/null 2>&1 && [ ! -e /opt/am/APP-MANAGER ]; then
        exec "$HERE/AM-INSTALLER"
    else
        exec "$HERE/APP-MANAGER" "$@"
    fi
fi
