#!/usr/bin/env bash

# THIS IS A SCRIPT i USE TO CREATE AND UPDATE THE APPLICATION LIST ON https://portable-linux-apps.github.io/
# ONCE CREATED, THE PAGE WILL APPEAR LIKE THIS: https://portable-linux-apps.github.io/apps.html
# FIRST OF ALL, WE NEED TO CREATE A FILE CONTAINING ALL THE ARGUMENTS THAT THIS SCRIPT MUST READ
AMREPO="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
arch="x86_64"
echo "" >> args
wget -q $AMREPO/programs/$arch-apps && echo -e "$(cat ./$arch-apps | awk -v FS="(◆ | : )" '{print $2}')" >> args
echo STOP >> args
ARGS=$(sed '1d' ./args)

# THIS IS THE WORKFLOW
for arg in $ARGS; do
	for var in $arg; do
	if [ $arg == STOP ]; then
		exit
	else
	case $arg in
	*) for var in $arg;
		do
		description=$(cat $arch-apps | grep "◆ $arg :" | echo $(grep -oP "$arg : \K.*"))
		echo "-----------------" >> apps.md
		echo "## ◆ [*$arg*](apps/$arg.md)" >> apps.md
		echo " ***$description***" >> apps.md
		echo "" >> apps.md
		echo "-----------------" >> apps.md
		sleep 0.2
		done
	esac
	fi
done
done