#!/bin/sh

mkdir /opt/firefox-dev
cd /opt/firefox-dev
mkdir tmp;
cd ./tmp;
wget "https://download.mozilla.org/?product=firefox-devedition-latest&os=linux&lang=en-US" --trust-server-names
tar fx firefox-*.tar.bz2
cd ..
mv ./tmp/firefox/* ./
rm -R ./tmp

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/firefox-dev

ln -s /opt/firefox-dev/firefox /usr/local/bin/firefox-dev

rm -R -f /usr/share/applications/firefox-dev.desktop
echo "[Desktop Entry]
Name=Firefox Developer Edition
Comment=Web Browser
Exec=/opt/firefox-dev/firefox %u
Terminal=false
Type=Application
Icon=/opt/firefox-dev/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Actions=Private;

[Desktop Action Private]
Exec=/opt/firefox-dev/firefox --private-window %u
Name=Open in private mode"  >> /usr/share/applications/firefox-dev.desktop

echo "#!/bin/sh
rm -R -f /opt/firefox-dev /usr/share/applications/firefox-dev.desktop /usr/local/bin/firefox-dev" >> /opt/firefox-dev/remove
chmod a+x /opt/firefox-dev/remove

echo "";
echo " Firefox Developer Edition has been installed! ";
echo "";
