#!/bin/sh

mkdir /opt/appimage
cd /opt/appimage
mkdir tmp
cd tmp
wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
cd ..
mv ./tmp/*AppImage ./appimagetool
rmdir ./tmp
chmod a+x ./appimagetool
ln -s /opt/appimage/appimagetool /usr/bin/appimagetool

# Creating a script that removes all the files listed above
echo '#!/bin/sh
rm -R /usr/bin/appimagetool /opt/appimage/appimagetool /opt/appimage/about-appimagetool /opt/eya/remove/appimagetool /opt/eya/programs/appimagetool' >> /opt/eya/remove/appimagetool
chmod a+x /opt/want/remove/appimagetool

# Creating an about file
echo "
 Appimagetool is used to generate an AppImage from an existing AppDir.
 
 SITE: https://github.com/AppImage/AppImageKit" >> /opt/appimage/about-appimagetool

# Changing privileges in /opt/appimage to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimage

# Message
echo ""
echo " AppImageTool has been installed!"
echo ""
