#!/bin/sh

mkdir /opt/appimagetool
cd /opt/appimagetool
mkdir tmp
cd tmp
wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
cd ..
mv ./tmp/*AppImage ./appimagetool
rmdir ./tmp
chmod a+x ./appimagetool
ln -s /opt/appimagetool/appimagetool /usr/bin/appimagetool

# Creating a script that removes all the files listed above
rm /opt/appimagetool/remove-appimagetool
echo '#!/bin/sh
rm -R /usr/bin/appimagetool /opt/appimagetool/appimagetool /opt/appimagetool/about-appimagetool /opt/appimagetool/remove-appimagetool /opt/eya/programs/appimagetool' >> /opt/appimagetool/remove-appimagetool
chmod a+x /opt/appimagetool/remove-appimagetool

# Creating an about file
rm /opt/appimagetool/about-appimagetool
echo "
 Appimagetool is used to generate an AppImage from an existing AppDir.
 
 SITE: https://github.com/AppImage/AppImageKit" >> /opt/appimagetool/about-appimagetool

# Changing privileges in /opt/appimagetool to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimagetool

# Message
echo ""
echo " AppImageTool has been installed!"
echo ""
