#!/bin/sh

mkdir /opt/firefox
cd /opt/firefox
mkdir tmp;
cd ./tmp;
wget "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" --trust-server-names
tar fx firefox-*.tar.bz2
cd ..
mv ./tmp/firefox/* ./
rm -R ./tmp

currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/firefox

ln -s /opt/firefox/firefox /usr/local/bin/firefox

rm /usr/share/applications/firefox-stable.desktop
echo "[Desktop Entry]
Name=Firefox
Comment=Web Browser
Exec=/opt/firefox/firefox %u
Terminal=false
Type=Application
Icon=/opt/firefox/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Actions=Private;

[Desktop Action Private]
Exec=/opt/firefox/firefox --private-window %u
Name=Open in private mode"  >> /usr/share/applications/firefox-stable.desktop

echo "#!/bin/sh
rm -R /opt/firefox /usr/share/applications/firefox-stable.desktop /usr/local/bin/firefox /opt/app/programs/firefox" >> /opt/firefox/remove
chmod a+x /opt/firefox/remove

echo "";
echo " Firefox Stable has been installed! ";
echo "";
