#!/bin/sh

mkdir /opt/appimage
cd /opt/appimage
mkdir tmp
cd tmp
wget -r -A .AppImage -nd https://github.com/AppImage/pkg2appimage/releases/tag/continuous
cd ..
mv ./tmp/*AppImage ./pkg2appimage
rmdir ./tmp
chmod a+x ./pkg2appimage
ln -s /opt/appimage/pkg2appimage /usr/bin/pkg2appimage

# Creating a script that removes all the files listed above
rm /opt/eya/remove/pkg2appimage
echo '#!/bin/sh
rm -R /usr/bin/pkg2appimage /opt/appimage/pkg2appimage /opt/appimage/about-pkg2appimage /opt/appimage/remove-pkg2appimage /opt/eya/programs/pkg2appimage' >> /opt/appimage/remove-pkg2appimage
chmod a+x /opt/appimage/remove-pkg2appimage

# Creating an about file
rm /opt/appimage/about-pkg2appimage
echo "
 Utility to convert .yml recipes to AppDir
 
 SITE: https://github.com/AppImage/pkg2appimage" >> /opt/appimage/about-pkg2appimage

# Changing privileges in /opt/appimage to allow automatic updates
currentuser=$(who | awk '{print $1}')
chown -R $currentuser /opt/appimage

# Message
echo ""
echo " pkg2appimage has been installed!"
echo ""
