name: "Check archived and obsolete sources"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-files:
    name: "Run sync"
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/kazam0180/am-ci-tools:80d6340a
    outputs:
      message: ${{ steps.commit_message.outputs.message }}
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v7

      - name: "Get commit message"
        id: commit_message
        run: |
          git config --global --add safe.directory /__w/AM/AM
          COMMIT_MESSAGE="Update list of archived and obsolete sources"
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: "Run test"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          am-source-checker --api-base="https://api.github.com/graphql" -c 2 -b 35

      - name: "Push to Source"
        run: |
          git config --global user.name "web-flow"
          git config --global user.email "noreply@github.com"
          git add programs/archived-apps programs/obsolete-apps
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -a -m "${{ steps.commit_message.outputs.message }}"
            git push && echo "Sync to Source succeeded" >> $GITHUB_STEP_SUMMARY
          fi
