name: "Lint Shellcheck 🐚"

on:
  pull_request:
    branches: '**'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: gcc
          severity: error
