name: "trigger"

on:
  repository_dispatch:
    types: [trigger]

  workflow_dispatch:
    inputs:
      input_amcheck:
        description: "Check variables in 250 apps"
        required: true
        default: false
        type: boolean
      input_lister:
        description: "Sync AppImages listing"
        required: true
        default: false
        type: boolean
      input_apps:
        description: "Test random 💯"
        required: true
        default: false
        type: boolean
      input_test:
        description: "Clean main"
        required: true
        default: false
        type: boolean

jobs:
  check-variables:
    name: "trigger 250 dispatch"
    if: github.event.inputs.input_amcheck == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger 250 dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: check
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: "Set name"
        run: |
          RUN_NAME="trigger 250 dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  lister-sync:
    name: "trigger Lister dispatch"
    if: github.event.inputs.input_lister == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger Lister dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: lister
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: "Set name"
        run: |
          RUN_NAME="trigger Lister dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  test-apps:
    name: "trigger 💯 dispatch"
    if: github.event.inputs.input_apps == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger 💯 dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: apps
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: "Set name"
        run: |
          RUN_NAME="trigger 💯 dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  main-clean:
    name: "trigger Clean dispatch"
    if: github.event.inputs.input_test == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger Clean dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: clean
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: "Set name"
        run: |
          RUN_NAME="trigger Clean dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  rename:
    runs-on: ubuntu-22.04
    steps:
      - name: "Rename"
        run: |
          echo "${{ env.RUN_NAME }}"
          echo "#TODO"
          #curl -X PATCH -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          #-H "Accept: application/vnd.github.v3+json" \
          #https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          #-d "{\"name\": \"running: ${{ env.RUN_NAME }}\"}"
